### ISSUE TITLE
[Device Support Request] Moes Zigbee Dimmer Module MS-105Z

### ISSUE THREAD

**Issue by thechad0351** [zigpy/zha-device-handlers#1011]
Hello, 
When trying to add these zigbee dimmer modules via ZHA it does not add any entities, only the device. 
Are you able to assist with support for this device/entities?

{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_la2c2uo9",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}

Thanks in advance,
Chad.

**Comment by thechad0351** [comment]
Thanks for the reply.
I'm only just starting out with home assistant, so not quite sure what to
do with setting up quirks.
How long until the next update for when these will be supported natively in
ZHA?

Cheers,
Craig

**Comment by MattWestb** [comment]
Its merged in to the beta of next HA so you can waiting some week and its being released and shall working out of the box with your device :-)))

**Comment by thechad0351** [comment]
Thank you.

**Comment by thechad0351** [comment]
Hi,

I Updated to the new version of Home Assistant today and the devices are
still not being recognized.
Was the device support added as planned?
Moes MS-105Z 1 Gang Dimmer Module

Cheers,
Craig.

**Comment by javicalle** [comment]
`_TZE200_la2c2uo9` must be supported in HA 2022.02

Can the issue be closed?
