### ISSUE TITLE
[BUG] Third Reality switch state is inverted

### ISSUE THREAD

**Issue by Josephtsessions** [zigpy/zha-device-handlers#1014]
**Describe the bug**
I have multiple second and third gen third reality switches.

The third gen switches (model 3RSS009Z) work fine and show no quirks in the interface.

The second gen switches (model 3RSS008Z) show `Quirk: zhaquirks.thirdreality.switch.Switch` and work but the state is inverted. When I turn it off, the light turns on, and vice versa. Note that I'm talking about the actual high or low position of the nub on the back of the switch, so I know this isn't electrical or related to the wiring of the house.

I would have expected the quirk to take care of the correct state. 

**To Reproduce**
1) Link a 2nd gen third reality switch and turn it on or off.
2) Observe that the switch is the opposite of what you saw in the lovelace UI. On makes the switch turn off and vice versa.

**Expected behavior**
Turning the switch on turns it on and turning it off turns it off.

**Screenshots**

**Additional context**
I'm using home assistant and am new, so it may be user error. If you have any resources for me I'd appreciate the lead.

These same 2nd gen switches were inverted in smartthings when I used it a few weeks ago without zigpy/zha, so this is familiar to me.

Zigbee Device Signature for 2nd gen (inverted/bugged/quirked) switch:

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4659, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0002",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0019"
      ],
      "out_clusters": [
        "0x0001"
      ]
    }
  },
  "manufacturer": "Third Reality, Inc",
  "model": "3RSS008Z",
  "class": "zhaquirks.thirdreality.switch.Switch"
}
```

Zigbee Device Signature for 3rd gen (working) switch:

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4659, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0000",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0006"
      ],
      "out_clusters": [
        "0x0006",
        "0x0019"
      ]
    }
  },
  "manufacturer": "Third Reality, Inc",
  "model": "3RSS009Z",
  "class": "zigpy.device.Device"
}
```

**Comment by dmulcahey** [comment]
this is the hardware... hold the button for 20 seconds I think... I accidentally tripped this once when I was resetting one. Let me see if I can find the docs.

**Comment by dmulcahey** [comment]
https://fccid.io/2AOCT-3RSS007Z/User-Manual/User-manual-3721369

![Screen Shot 2021-08-30 at 9 39 36 AM](https://user-images.githubusercontent.com/1335687/131348338-2c9c07b4-f7f1-4e06-b26f-d30f254449fb.png)

**Comment by Josephtsessions** [comment]
Hey, you're right!!!! Can't believe I didn't know this. RTFM I guess.

Thanks a ton!
