### ISSUE TITLE
[Device Support Request] Decoupled mode for Xioami Aqara wall switch (lumi ctrl_neutral)

### ISSUE THREAD

**Issue by alceasan** [zigpy/zha-device-handlers#1063]
After 0.0.62 version bump into new HomeAssistant I tried using the switch in decoupled mode. I made the changes in the cluster configuration (BasicClusterDecoupled -> decoupled_mode_left & decoupled_mode_right), using value 254 for decoupled.

This worked, and now I'm receiving zha_event in HomeAssistant any time a button is pushed, but I'm not able to distinguish left from right button from the event data:

Left button:
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:15:8d:00:03:5a:39:cb",
        "unique_id": "00:15:8d:00:03:5a:39:cb:4:0x0006",
        "device_id": "cb97e9c30a5411eb83b8d70661890843",
        "endpoint_id": 4,
        "cluster_id": 6,
        "command": "attribute_updated",
        "args": {
            "attribute_id": 0,
            "attribute_name": "on_off",
            "value": 0
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-10-07T13:48:49.133884+00:00",
    "context": {
        "id": "7c59476337bdfa17d778fbc430a16900",
        "parent_id": null,
        "user_id": null
    }
}
```

Right button:
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:15:8d:00:03:5a:39:cb",
        "unique_id": "00:15:8d:00:03:5a:39:cb:4:0x0006",
        "device_id": "cb97e9c30a5411eb83b8d70661890843",
        "endpoint_id": 4,
        "cluster_id": 6,
        "command": "attribute_updated",
        "args": {
            "attribute_id": 0,
            "attribute_name": "on_off",
            "value": 0
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-10-07T13:48:50.917194+00:00",
    "context": {
        "id": "21ba5824a248f7fae8784e95841b01f0",
        "parent_id": null,
        "user_id": null
    }
}
```

How could I identify one button from another, to create an automation?

**Comment by javicalle** [comment]
Have you tried to add an automation from the device view?
Or from the automations view selecting as trigger the device?
![image](https://user-images.githubusercontent.com/31999997/139581802-4fb058fc-49e6-427f-a5d6-d7ec75a36159.png)

if I'm not mistaken, you should see several options listed like `"button_N" [Short|Double] press`

**Comment by javicalle** [comment]
I just realized that the device is of type `ctrl_neutral` and not the `ctrl_ln` I was checking.
`ctrl_neutral` currently has no events implemented for the second button. The PR #761 is stale and does not look like it is going to advance.

If you have availability to do tests (with local quirks), I can try to implement the quirks for the second button.

**Comment by caesar1987sk** [comment]
Im trying to change aqara wall switch h1 EU - lumi.switch.n2aeu1 to decoupled mode. @alceasan how did you do that? were you able to integrate this switch to hassio in decoupled mode?

**Comment by alceasan** [comment]
No, I integrated it in normal mode. I don't think you can join the switch in decoupled mode because the device resets on joining a new zigbee network and goes back to coupled mode.

After joining to the zigbee network, I changed to decoupled mode using clusters:
![image](https://user-images.githubusercontent.com/3265883/145577852-db221877-4123-468c-9d03-745bfcffea18.png)

**Comment by caesar1987sk** [comment]
i was wondering, because of that reset  after pairing.
I dont have clusters ff22 and ff23 in list of cluster for my switch, so also this needs to be added for lumi.switch.n2aeu1
