### ISSUE TITLE
[BUG] Yooksmart blinds reporting position backwards after 8/25 custom quirk 

### ISSUE THREAD

**Issue by HEAT16** [zigpy/zha-device-handlers#1069]
**Describe the bug**
After the custom quirk was added on 8/24 my Yooksmart blinds which were previously working correctly started reporting their positions backwards. Additionally, after adding and removing them from HA in an attempt to fix them, now they no longer report any position other than 0 or 100. This appears to be related to the firmware version as I am on version 0x11006780 and they worked fine before the custom quirk. I did try modifying the quirk to disable it as suggested here (https://github.com/zigpy/zha-device-handlers/pull/971#issuecomment-938174298). Doing so does reverse the percentages to 100 fully open and 0 fully closed, however the in-between percentages still do not report. 

Additionally, sending a close or open command with any % will just result in the blinds either fully opening or fully closing, it will never stop at the intended percentage. 

**To Reproduce**
1. Pair blinds with HA
2. Open or close the blinds and observe them report 0% when fully open and immediately jump to 100% as they start to close

**Expected behavior**
The blinds used to display 0% when fully closed and increment by 1% when opening all the way up to completely open @ 100%

**Screenshots**

**Additional context**
Device Signature:
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4169, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.0: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0202",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0020",
        "0x0102"
      ],
      "out_clusters": [
        "0x0003",
        "0x0019"
      ]
    }
  },
  "manufacturer": "yooksmart",
  "model": "D10110",
  "class": "D10110blinds.D10110Blinds"
}

**Comment by HEAT16** [comment]
Any chance we could get some eyes on this? My blinds have been busted for 3 months. I can help test and provide any logs or additional info necessary; I just really want to get my blinds working normally again.

**Comment by oripaamoni** [comment]
Same issue here. Seem like this was a issue in deCONZ too but they fixed it over there. Maybe I should try deCONZ instead of ZHA
