### ISSUE TITLE
[Device Support Request] Tesla Smart Thermostatic Valve _TZE200_husqqvux TS0601

### ISSUE THREAD

**Issue by ad1k4h** [zigpy/zha-device-handlers#1072]
**Is your feature request related to a problem? Please describe.**

I'm trying to add _TZE200_husqqvux TS0601 (Tesla Smart Thermostatic Valve) and cant see any functions like Climate entity. (No entities at all) - I Tried to write in the files by hand, but not seems to work.

**Describe the solution you'd like**
Plug and Play support

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**

{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_husqqvux",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}

**Additional context**

**Comment by ad1k4h** [comment]
I having this![image](https://user-images.githubusercontent.com/53319400/137506898-5b754cc5-9bf0-4c47-9d35-618cfdb15a47.jpeg)

**Comment by MattWestb** [comment]
Its merged to the dev now so more then likely is being in the next release of HA :-))

**Comment by radorado31** [comment]
> Its merged to the dev now so more then likely is being in the next release of HA :-))

Hello Matt. Please how do i know if i already have this update in my HA? what actually needs to be updated... the Core and with this the ZHA integration is also automatically updated?
Sorry for that basic question, i just dont know whats the flow and how things work in this area. Thats why i would rather wait for official update then trying to use "quirks" which might be complicated for me

thank you

**Comment by MattWestb** [comment]
The PR is merged in to ZHA dev and is also merged in HA 2021-11 beta and is being released  as GA (General Availability) on 3 of November.

So i think is easiest waiting some more days and installing the GA instead and not trying out the beta if you is not having very cold in your home then is beta for you ;-))

**Comment by radorado31** [comment]
Great, thanks for the good news Matt , i will wait few more days....
Just for my understanding of the flow - so if I update the HA (i guess the "core" ?) ,this will always automatically upgrade my integrations, including ZHA? Or how to know which version of ZHA am I running?
I already did try some google search by my self to get the answer how things work, but no luck :/

Thank you for answering my rookie questions :)

**Comment by MattWestb** [comment]
Correct !!

HA is Home Assistant Core and the [release notes](https://rc.home-assistant.io/blog/2021/10/27/release-202111/) is shoeing the "Bumped" version of ZHA in it (use F3 for seartching for ZHA and you is finding it if expanding all changes, the same for the GA release).

Then you can clicking on the issue link to the ZHA bump and there you gave the release note for ZHA.

The same for ZHA quirks and you can look wot is included in the Reese.
https://github.com/zigpy/zha-device-handlers/releases/tag/0.0.63

**Comment by radorado31** [comment]
cool, I appreciate this comprehensive info, finally got some picture how it works in background...was already afraid that i will need to update the FW on my zigbee usb dongle and re-pair all devices, but thankfully not :)
thank you and have a nice day (y)

**Comment by radorado31** [comment]
Hello All

I confirm that after latest release of HA, the TZE200 is added into ZHA together with current temperature & target temperature.
However the problem with not reading current temperature persists. Was anybody able to make it work?
I have found out that it at least always report the current temperature at the moment me when device is added to ZHA. But after that it just show the same temp

**Comment by ress23** [comment]
> Hello All
> 
> I confirm that after latest release of HA, the TZE200 is added into ZHA together with current temperature & target temperature. However the problem with not reading current temperature persists. Was anybody able to make it work? I have found out that it at least always report the current temperature at the moment me when device is added to ZHA. But after that it just show the same temp

I have the same issue with my Moes TV01. 

Would you mind testing one thing? If you set a temp offset (on the TRV, press and hold Menu button, then select offset), is the current temp updated in HA? This is the only way I've been able to get data from the TRV to HA.

**Comment by JosefKrieglstein** [comment]
Hi,
Yes you're right, when I adjust offset, TRV send new current temperature value. But it should be same periodic like target temperature value. Current state: "current temperature" and "heating" values are not updated, "current temperature" value is updated periodically.
BR Josef

**Comment by ress23** [comment]
Right, exact same issue as me and @radorado31 then.

Seems like zhaquirks.tuya.ts0601_trv.ZonnsmartTV01_ZG is causing the problem.

**Comment by mirecekd** [comment]
check my answer and simple PR here: 

https://community.home-assistant.io/t/moes-tv01-trv-temp-sensor-issues/356903/4

> I confirm that after latest release of HA, the TZE200 is added into ZHA together with current temperature & target temperature. However the problem with not reading current temperature persists. Was anybody able to make it work? I have found out that it at least always report the current temperature at the moment me when device is added to ZHA. But after that it just show the same temp
