### ISSUE TITLE
King Of Fans MR101Z update

### ISSUE THREAD

**Issue by flyize** [zigpy/zha-device-handlers#1092]
**Is your feature request related to a problem? Please describe.**
This quirk could use an update to fully match the new fan percentages. The device has four fan modes. The fourth mode (max fan speed) is set with the preset_mode of 'on'. It also supports a 'breeze' mode using the preset_mode of 'smart'.

**Describe the solution you'd like**
The quirk to easily, and obviously, support all fan modes 1-4 and breeze.

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
This one https://github.com/zigpy/zha-device-handlers/blob/b12ebc37790af34253fce4a0c549d05a8ffb995c/zhaquirks/kof/kof_mr101z.py

**Additional context**
I made a fan template here to bridge the gap, but a real implementation would be awesome.
https://community.home-assistant.io/t/king-of-fans-mr101z-missing-max-setting/267131

This was also discussed here:
https://github.com/zigpy/zigpy/issues/628

**Comment by chrismdann** [comment]
Is anyone going to address this?

**Comment by d0u8l3m** [comment]
Wondering if the template is the only solution to this or if this can be fixed. Thank you!

**Comment by Hedda** [comment]
FYI, check out this pull request that @tronikos just submitted for ZHA in Home Assistant core  -> https://github.com/home-assistant/core/pull/101859
