### ISSUE TITLE
[Device Support Request] WZ5 Zigbee 5 in 1 LED Controller  _TZE200_fcooykb4

### ISSUE THREAD

**Issue by tbornon** [zigpy/zha-device-handlers#1095]
Hi,

I'm requesting your help for supporting a Zigbee device I bought : https://www.aliexpress.com/item/1005002003150030.html

**Is your feature request related to a problem? Please describe.**
I tried connecting the led dimmer with Home Assistant. The connection went well however I can't control it from my dashboard.
I then tried modifying ts0601_dimmer.py so that my controller can be recognized. It partly worked. Now I can switch on/off my LEDs but I can't control the brightness.

**Describe the solution you'd like**
I would like to be able to control the brightness of the LEDs strips. It would be awesome if it was possible to control each LEDs' strip brightness individually but that isn't a requirement

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
```json 
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_fcooykb4",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

**Additional context**

I hope I gave enough informations. If I can do anything, I would be glad to help

**Comment by gabrielbergeron** [comment]
I too would greatly appreciate if it was supported in ZHA as I have one laying around that I want to install. I found the pr that was made for Zigbee2Mqtt if that helps in the parsing. https://github.com/Koenkk/zigbee-herdsman-converters/pull/3620/files
