### ISSUE TITLE
TS011F Plug RMS-Current wrong value

### ISSUE THREAD

**Issue by miit86** [zigpy/zha-device-handlers#1108]
**Is your feature request related to a problem? Please describe.**

This looks OK, a bit off but cheap plugs. 
 ```
electrical_measurement
193 W
 electrical_measurement rms_current
1,141 A
```
This is not OK.
```
Electrical_measurement
62 W
Electrical_measurement rms_current
433 A
```

**Describe the solution you'd like**
Divide RMS-Current by 1000 (I Guess)

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. 
Signature is OKE

**Additional context**
Can't find any Attributes for RMS-Current Divide
But Maybe this is not the way to go.

**Comment by PonyOny** [comment]
This is still reporting invalid values with latest HAS (2022.2.5) Current & Voltage
![image](https://user-images.githubusercontent.com/17080292/153382537-0f7502e5-195e-44ec-bf39-5da565c6deb9.png)

Current:
![image](https://user-images.githubusercontent.com/17080292/153382916-b6cf7f74-5a5a-4272-9c6a-5d45a81c9e78.png)

Voltage:
![image](https://user-images.githubusercontent.com/17080292/153383069-74ca5535-b9e3-4e0f-9900-c0529aadc4c5.png)

**Comment by dentra** [comment]
Same here but for TZ3000_gjnozsaz.
