### ISSUE TITLE
error in line 91 

### ISSUE THREAD

**Issue by pervolianinen** [zigpy/zha-device-handlers#1119]
https://github.com/zigpy/zha-device-handlers/blob/02aeb2910f2fce12aa0499ab0b8184d39f8b7cf3/zhaquirks/tuya/ts0601_trv.py#L91

no need operation division to 10 in line 91, becauser after it not correct set temperature

**Comment by MattWestb** [comment]
Can you pleas explaining !
My TRVs is being sett OK and is reporting back to ZHA OK.

**Comment by pervolianinen** [comment]
When i set 30 degrees on moes _TZE200_b6wax7g0 by using it buttons, i get 3 degrees in card thermostat in hpmeassistent. 35 - 3.5 und so on. When i set minimum in component thermostat in home assistent moes opens for full.

**Comment by pervolianinen** [comment]
![Screenshot_2021-11-01-22-34-35-051_io homeassistant companion android](https://user-images.githubusercontent.com/74545183/139730807-d89960a5-ba61-49b1-a244-caffadb8eb40.jpg)
![IMG_20211101_223421](https://user-images.githubusercontent.com/74545183/139730816-66224a49-d5ab-4b1a-8212-d75b80d38e77.jpg)

**Comment by MattWestb** [comment]
Your devicse is **NOT** one SITERWELL its one BRT-100 Made of BecaSmart and its one know problem and was using https://github.com/zigpy/zha-device-handlers/blob/02aeb2910f2fce12aa0499ab0b8184d39f8b7cf3/zhaquirks/tuya/ts0601_trv.py#L1047
but one user have making one fixed type for it https://github.com/zigpy/zha-device-handlers/pull/1082 so it shall working in dev / HA beta and shall being in HA 2012.11 GA

For more info of tuya TRVs https://github.com/zigpy/zigpy/discussions/653#discussioncomment-314395

**Comment by MattWestb** [comment]
You can downloading the updated quirk https://github.com/zigpy/zha-device-handlers/blob/02aeb2910f2fce12aa0499ab0b8184d39f8b7cf3/zhaquirks/tuya/ts0601_trv.py and configuring local quirk in ZHA https://github.com/zigpy/zha-device-handlers/discussions/693#discussioncomment-857274 and putting it in the local  quirk folder and restarting HA and it shall working OK or waiting some days for the new HA release.

**Comment by pervolianinen** [comment]
> You can downloading the updated quirk https://github.com/zigpy/zha-device-handlers/blob/02aeb2910f2fce12aa0499ab0b8184d39f8b7cf3/zhaquirks/tuya/ts0601_trv.py and configuring local quirk in ZHA [#693 (comment)](https://github.com/zigpy/zha-device-handlers/discussions/693#discussioncomment-857274) and putting it in the local quirk folder and restarting HA and it shall working OK or waiting some days for the new HA release.

Thanks!
