### ISSUE TITLE
[BUG] XIAOMI light sensor does not show battery level

### ISSUE THREAD

**Issue by Lampyridae1984** [zigpy/zha-device-handlers#1132]
I moved from Deconz to ZHA and now I no longer have a battery sensor for the XIAOMI light sensor (lumi.sen_ill.mgl01). Tried to re-add and reconfigure it several times, but nothing seems to help.
![Screenshot 2021-11-08 024128](https://user-images.githubusercontent.com/75570119/140671610-6f48200e-32c6-41b5-9aad-0053d57b2a1a.jpg)

**Comment by Adminiuga** [comment]
This is fixed in current ha core dev. Will be in next bug fix release.
