### ISSUE TITLE
[Device Support Request] LivingWise LVS-SC7 (also known as Orvibo T10S7)

### ISSUE THREAD

**Issue by jfrancais** [zigpy/zha-device-handlers#1185]
**Is your feature request related to a problem? Please describe.**

Events aren't captured when pressing buttons on this paired device.  Here are the log entries I see for each button press.
[0xb1d0:1:0x0017] Unknown cluster-specific command 8
[0xb1d0:1:0x0017] ZCL request 0x0008: b'\x01\x00\x00'
[0xb1d0:1:0x0017] Unknown cluster-specific command 8
[0xb1d0:1:0x0017] ZCL request 0x0008: b'\x02\x00\x00'
[0xb1d0:1:0x0017] Unknown cluster-specific command 8
[0xb1d0:1:0x0017] ZCL request 0x0008: b'\x03\x00\x00'
[0xb1d0:1:0x0017] Unknown cluster-specific command 8
[0xb1d0:1:0x0017] ZCL request 0x0008: b'\x04\x00\x00'
[0xb1d0:1:0x0017] Unknown cluster-specific command 8
[0xb1d0:1:0x0017] ZCL request 0x0008: b'\x05\x00\x00'
[0xb1d0:1:0x0017] Unknown cluster-specific command 8
[0xb1d0:1:0x0017] ZCL request 0x0008: b'\x06\x00\x00'
[0xb1d0:1:0x0017] Unknown cluster-specific command 8
[0xb1d0:1:0x0017] ZCL request 0x0008: b'\x07\x00\x00'

**Describe the solution you'd like**
Would like the device to expose the following actions:
#Action (enum)
Triggered action (e.g. a button click). Value can be found in the published state on the action property. It's not possible to read (/get) or write (/set) this value. The possible values are: button_1_click, button_1_hold, button_1_release, button_2_click, button_2_hold, button_2_release, button_3_click, button_3_hold, button_3_release, button_4_click, button_4_hold, button_4_release, button_5_click, button_5_hold, button_5_release, button_6_click, button_6_hold, button_6_release, button_7_click, button_7_hold, button_7_release.

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=0, maximum_buffer_size=80, maximum_incoming_transfer_size=160, server_mask=0, maximum_outgoing_transfer_size=160, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x000c",
      "in_clusters": [
        "0x0000",
        "0x0005"
      ],
      "out_clusters": [
        "0x0000",
        "0x0005",
        "0x0017"
      ]
    }
  },
  "manufacturer": "欧瑞博",
  "model": "75d430d66c164c26ac8601c05932dc94",
  "class": "zigpy.device.Device"
}

**Additional context**
In using home assistant zha, this pairs but events don't get captured.  As such device can't be used.

This device does seem to be supported in zigbee2mqtt but not zha
https://www.zigbee2mqtt.io/devices/LVS-SC7.html

**Comment by jfrancais** [comment]
Might be some more useful information in here as well, same device:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2639

**Comment by jfrancais** [comment]
Also may have useful information, same device:
https://github.com/bradlee-s/det-SmartThings/blob/master/Orvibo%207%20Button%20Scene%20Controller.groovy

**Comment by jfrancais** [comment]
Still on the hunt for this

**Comment by jfrancais** [comment]
Still an issue

**Comment by jfrancais** [comment]
Still looking for this to be resolved.  Anyone?

**Comment by dominic195** [comment]
would also like to know if a solution was found
