### ISSUE TITLE
[BUG] Wrong "current" for Tuya plug TS0121 (BlitzWolf SHP13, _TZ3000_g5xawfcq)

### ISSUE THREAD

**Issue by avbor** [zigpy/zha-device-handlers#1220]
**Describe the bug**
Wrong current (A) sensor for Tuya plug TS0121 (BlitzWolf SHP13, _TZ3000_g5xawfcq).
It's impossible to get 220 V 11 A and 1 W at the same time =)
It seems to me that the multiplier is lost somewhere...

**Screenshots**
![image](https://user-images.githubusercontent.com/32452033/146580846-8338fdfc-6288-46d7-b09e-2d851ed35f1e.png)

**Comment by smiba** [comment]
This should be fixed, but as a workaround you can manually refresh the ac_current_divisor cluster attribute to fix this:

https://github.com/home-assistant/core/issues/61564#issuecomment-993299627

**Comment by avbor** [comment]
> This should be fixed, but as a workaround you can manually refresh the ac_current_divisor cluster attribute to fix this:
> 
> [home-assistant/core#61564 (comment)](https://github.com/home-assistant/core/issues/61564#issuecomment-993299627)

Thanks! a completely unobvious action, I tried to reconfigure many times, but it did not help, but the cluster polling helped.
