### ISSUE TITLE
[BUG] Failed to call service cover/stop_cover. '>' not supported between instances of 'NoneType' and 'int

### ISSUE THREAD

**Issue by thedead** [zigpy/zha-device-handlers#1223]
**Describe the bug**
After adding the blinds to HA, if I press up, the blinds go up, and if I press stop, they stop but I get this error: Failed to call service cover/stop_cover. '>' not supported between instances of 'NoneType' and 'int

Now, I can only go down, I can't go up again.

The state also does not change to stopped and is stuck in the last used state

**To Reproduce**
1. Open the entity in HA
2. Click on up or down
3. Click stop
4. Error appears on the bottom

**Expected behavior**
I would expect both up and down to be available once I stop and no error message

**Screenshots**
`Failed to call service cover/stop_cover. '>' not supported between instances of 'NoneType' and 'int`

**Additional context**
Add any other context about the problem here. Please include full debug logs as well as the device signature.

`1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0202",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0102",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_5sbebbzs",
  "model": "TS0601",
  "class": "zhaquirks.tuya.ts0601_cover.TuyaMoesCover0601"
}
`

**Comment by jonnylangefeld** [comment]
I just ran into the same thing after upgrading to home assistant version `2022.9.4`...
Maybe it's just happening after an upgrade, if it doesn't have `self._current_position` yet?
