### ISSUE TITLE
[Device Support Request] How to get battery voltage reading from DYI sensor

### ISSUE THREAD

**Issue by glcos** [zigpy/zha-device-handlers#1283]
I have made a DIY sensor based on a CC2652P module and PTVO firmware. The quirk I made works fine but I would like to add a battery voltage reading in volts as a separate entity. The reading is provided on an AnalogInput cluster as present_value

`[0x959f:2:0x000c] Attribute report received: present_value=3.299999952316284`

Unfortunately I'm not able to create an entity with that value.
Any idea is welcome

**Comment by slashbv** [comment]
were you able to find a solution for this ?
