### ISSUE TITLE
[Device Support Request] TS0121 _TZ3000_8nkb7mof still gives incorrect readings

### ISSUE THREAD

**Issue by ali1234** [zigpy/zha-device-handlers#1299]
This device pairs and all functions work, but it gives incorrect current and power summation readings. The current is wrong by a factor of 1000 and the power is wrong by a factor of 100. Recent patches [1](https://github.com/zigpy/zha-device-handlers/pull/1131), [2](https://github.com/zigpy/zha-device-handlers/pull/1062) claim to resolve this issue for TS0121, but are not applied to this device for some reason - presumably because its signature is slightly different from what the quirk expects (see below).

With zhaquirks-0.0.65, after deleting and re-pairing the device:

![image](https://user-images.githubusercontent.com/651970/150607995-b8021f48-2040-4a67-a6d6-76edbf1a3768.png)

Signature:

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x010a",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0702",
        "0x0b04",
        "0xe000",
        "0xe001"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZ3000_8nkb7mof",
  "model": "TS0121",
  "class": "zigpy.device.Device"
}
```
I suspect the problem is "device_type": "0x010a". This translates to zha.DeviceType.ON_OFF_PLUG_IN_UNIT but the quirk expects this field to be zha.DeviceType.SMART_PLUG which has value 81.

All in_clusters listed in the TS0121 quirk are present. In addition the standard Identify cluster and two Tuya specific clusters are also present. The extra clusters are not shown in hass.

**Comment by Adminiuga** [comment]
do you have "admin console access" to your HASS OS to try https://raw.githubusercontent.com/Adminiuga/zha-device-handlers/ac/ts0121/zhaquirks/tuya/ts0121_plug.py
