### ISSUE TITLE
[BUG] Develco Heat Alarm HESZB-120

### ISSUE THREAD

**Issue by SuperBigB** [zigpy/zha-device-handlers#1327]
The device does not report battery status.
The device does not implemented as a IAS Zone ZigBee end point. (or it is not working correctly)

I think there's a lot of features not implemented, but I'm willing to test this device utill it's fully fuctional.

Technical manual localted here: [heszb-120-technical-manual-heat-alarm.pdf](https://www.develcoproducts.com/media/1708/heszb-120-technical-manual-heat-alarm.pdf)

Device dignature:
```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.NONE: 0>, manufacturer_code=4117, maximum_buffer_size=80, maximum_incoming_transfer_size=80, server_mask=0, maximum_outgoing_transfer_size=80, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 49353,
      "device_type": "0x0001",
      "in_clusters": [
        "0x0003",
        "0x0005",
        "0x0006"
      ],
      "out_clusters": []
    },
    "35": {
      "profile_id": 260,
      "device_type": "0x0402",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x000f",
        "0x0020",
        "0x0500",
        "0x0502"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "38": {
      "profile_id": 260,
      "device_type": "0x0302",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0402"
      ],
      "out_clusters": [
        "0x0003"
      ]
    }
  },
  "manufacturer": "Develco Products A/S",
  "model": "HESZB-120",
  "class": "zigpy.device.Device"
}
```

[heszb-120-technical-manual-heat-alarm.pdf](https://github.com/zigpy/zha-device-handlers/files/7998361/heszb-120-technical-manual-heat-alarm.pdf)
![HESZB-120](https://user-images.githubusercontent.com/96742527/152432196-f22f9c31-1e78-40d5-b233-a6c8bbd6e172.jpg)
![Bilde_2022-02-03_223225](https://user-images.githubusercontent.com/96742527/152432420-0a15f187-6b59-42c9-8642-eaba0bdc4444.png)

#1022

**Comment by ark-** [comment]
For me it connects in HA, displays all the settings such as temperature, binary sensor and ias_zone. However none of these update values past their first initial state when pairing.

I found a full data sheet for the clusters here: https://www.develcoproducts.com/media/1708/heszb-120-technical-manual-heat-alarm.pdf

The temperature sensor part for example should be reporting at least every 5 minutes so clearly something is wrong.

Any advice on what logs I could share to help diagnose this issue?
