### ISSUE TITLE
[BUG]without MultistateInputmCluster, AQARA Switch aq3  (WXKG12LM)  recognized as lumi.sensor_swit  

### ISSUE THREAD

**Issue by freeskyflying** [zigpy/zha-device-handlers#1342]
**Describe the bug**
My Xiaomi AQARA Switch aq3  (WXKG12LM) ,recognized as lumi.sensor_swit.

only two entity available:
1.device_temperature
2.battery
but there is no  MultistateInput so i could use the switch

**Expected behavior**
with the entity MultistateInput so ha could use the swith

**Additional context**
HA os 7.4

**Comment by dmulcahey** [comment]
Remotes fire events. Subscribe to zha_event
