### ISSUE TITLE
Osram A19 tunable white device shows color picker in HA

### ISSUE THREAD

**Issue by tube0013** [zigpy/zha-device-handlers#135]
This is a white tunable bulb only, it should not show the color wheel - can this be addressed in this quirk?

<img width="827" alt="Screen Shot 2019-08-20 at 2 19 45 PM" src="https://user-images.githubusercontent.com/11084412/63373269-9c188580-c355-11e9-91b7-735c7452aaa7.png">

**Comment by TheJulianJES** [comment]
This should be fixed by: https://github.com/zigpy/zha-device-handlers/pull/488
The mismatching of other bulbs with the "OSRAM A19 tunable white quirk" should be fixed by: https://github.com/zigpy/zha-device-handlers/pull/543

I think the issue can be closed.
