### ISSUE TITLE
[Device Support Request] AVATTO Tuya Thermostat ME81AH 

### ISSUE THREAD

**Issue by conorm125** [zigpy/zha-device-handlers#1390]
**Is your feature request related to a problem? Please describe.**
The thermostat device connects to ZHA as a router device but it does not expose any entities. I would expect it to expose atleast current temperature and temperature set point.

**Describe the solution you'd like**
Support to be added to view and control the entities via ZHA.

**Device signature**
`{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_ye5jkfsb",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}`

**Additional context**
- This following issue on Z2M provides some solutions to get the device to work with Z2M https://github.com/Koenkk/zigbee2mqtt/discussions/9024.
- This is the device on Ali Express https://www.aliexpress.com/item/1005002960679997.html.
- Also thed device is refered to as ME81AH in the manual.

**Comment by MattWestb** [comment]
https://github.com/zigpy/zha-device-handlers/issues/1109
