### ISSUE TITLE
Add wiki and create a page with details for each device that is currently supported

### ISSUE THREAD

**Issue by dmulcahey** [zigpy/zha-device-handlers#14]

**Comment by macros0** [comment]
Tell me, do you need to install ZHA Device Handlers on your own, or is this functionality supplied with the HA core?
If individual actions are required from the user, where are they described?
Something like this: copy something to the config directory ...

**Comment by dmulcahey** [comment]
The user doesn’t have to do anything

**Comment by macros0** [comment]
Thank you, please explain more for my understanding. How to see which Pull requests are already on my system and which are not yet? There are no tags for hassio versions.

**Comment by Hedda** [comment]
As for the original issue, suggest copying existing device wiki pages from Zigbee2mqtt docs, or?

- https://www.zigbee2mqtt.io/information/supported_devices.html

- https://github.com/Koenkk/zigbee2mqtt.io
  - https://github.com/Koenkk/zigbee2mqtt.io/tree/master/docs/devices

blakadder also have a device database which might contain additional description for each device:

- https://zigbee.blakadder.com/
- https://github.com/blakadder/zigbee/

deCONZ also has a remark/issues comment on devices that they had problems with in their wiki too:

- https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices
