### ISSUE TITLE
[BUG / Device Support Request] Smart Air House keeper TS0601 _TZE200_dwcarsat v2

### ISSUE THREAD

**Issue by JoryHogeveen** [zigpy/zha-device-handlers#1406]
See https://github.com/zigpy/zha-device-handlers/issues/1313 for technical info

The current implementation isn't 100%.
It assumes it's the same as the `_TZE200_ryfmq5rl` and `_TZE200_yvx5lh6k` devices but it isn't.

The `_TZE200_dwcarsat` actually has six sensors.

- **Temperature** - 0-60 °C
- **Humidity** - 0-95%
- **CO2** - 0-1000 ppm
- **Formaldehyde** / CHOH (CH2O) - 0-10.00 mg/m3
- **PM2.5** - 0-1000 ug/m3
- **VOC** - 0-99.9 ppm

Most of the above are visible, however, incorrect:

- **VOC**
Shows a value of 0 constantly measured by `µg/m³` which should be the PM2.5 measurement.

- **CO2**
Currently shows a value between 0 and 10 measured by `ppm` which doesn't really match any "normal" situation. Not sure what this value should stand for. It might be the VOC

- **Formaldehyde / CHOH (CH2O)**
Currently shows a value of 350-400 measured by `ppm` which would be deadly and definitely not a normal situation.
It looks like this might be the value that is meant for CO2.

- **PM2.5** Not shown at all.

**Comment by JoryHogeveen** [comment]
More info on the MQTT implementation here: https://github.com/Koenkk/zigbee-herdsman-converters/pull/3745/files

**Comment by budcalloway** [comment]
Hi Jory,
I have the same concerns with this exact same device :)

**Comment by ajpalm** [comment]
Can confirm under ZHA I'm seeing similar issues with the TZE200_dwcarsat TS0601 device not showing all the sensors and the data being mismatched.

**Comment by JoryHogeveen** [comment]
@LittleFox94 Thanks for this, if even the 5 sensor model is showing inaccurate then I assume the whole integration for all smart air models is incorrect.

@MattWestb Do you have more information on how the sensor params are linked to the actual HA params? Besides the values being reported, was it tested that the values we're linked correctly?

**Comment by LittleFox94** [comment]
I just noticed the values don't even change a lot after having the window open for half an hour

The original values in the comment above were before letting fresh air in after the night (bedroom+home office), only difference is formaldehyde now being at 368ppm - but Hass history suggests the 378ppm in the comment above were a typo (it shows constant 368ppm)

This could be the sensor of course, but might also point at a problem in the integration

**Comment by JoryHogeveen** [comment]
Hi @LittleFox94 
A Formaldehype  value above 100 would be deadly ;). The exposure limit is 8 hours for 0.75 ppm and 15 minutes for 2 ppm (on the workfloor).

Your Formaldehype value probably stands for CO2 which is a normal "daily" value. Hence opening a window won't change it very much.

**Comment by LittleFox94** [comment]
Yep, I'm aware that formaldehyde value being true would mean I'm dead ^^'

But shouldn't CO2 change when opening the window, by letting CO2 out? I thought it concentrates in rooms from .. breathing it out?

**Comment by JoryHogeveen** [comment]
Hi @LittleFox94 
If your usual value is around 350 then it means your house is "breathing naturally" so that's a good sign :)
Of course this would depend on the isolation of your house and the room size but just from breathing this difference wouldn't be very large and very local in your room.

**Comment by MattWestb** [comment]
@JoryHogeveen I think all magic is being made in the INIT https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/air/__init__.py and i also think the DPs from some  one that is having tuya integration and have looking in tuya dev for getting the information what its function liked to the device but its not 110% sure is correct.

**Comment by JoryHogeveen** [comment]
@MattWestb Yep looks like it's handled there.
Also looks like this is an issue that is also happening at Zigbee2MQTT: https://github.com/Koenkk/zigbee2mqtt/issues/11033

**Comment by MattWestb** [comment]
We have founding that many tuya device need some "tuya magic" being casting on them then joining (first was TS004F) but we have not getting it implanted in ZHA but HB and Z2M have getting it working and we need reading and writing attributes very early (or kicking the device so it rejoining) then the device is paring for getting it working. 
Then we can getting it working in quirks we can fixing nearly 10 bad devices and perhaps i can helping in this case 2 but we cant testing it for the moment.

Bad things is missing endpoints (2 devices), Not reporting attributes and having connecting problems / stooping committing or falling in sleep or cant  getting time synced.

**Comment by LittleFox94** [comment]
just for completeness, my sensor doesn't seem to actually send any updated data - it's not shown as connected in ZigBee visualization and all data is last updated "Yesterday" and right now there is a lot of Isopropanol in the air it should probably pick up as VOC ^^'

**Comment by stephenjamieson** [comment]
Can confirm that I'm having the same issues with this device. watching

**Comment by JoryHogeveen** [comment]
Maybe related error logs:

`Logger: zigpy.zcl
Source: /usr/local/lib/python3.9/site-packages/zhaquirks/tuya/__init__.py:1295
First occurred: 6:09:32 PM (2 occurrences)
Last logged: 6:09:36 PM

[0x4093:1:0xef00] No 'handle_set_data_response' tuya handler found for [TuyaCommand(status=0, tsn=1, dp=20, data=TuyaData(dp_type=<TuyaDPType.VALUE: 2>, function=0, raw=b'\x00\x00\x00\x00', *payload=0))]
[0x4093:1:0xef00] No 'handle_set_data_response' tuya handler found for [TuyaCommand(status=0, tsn=3, dp=20, data=TuyaData(dp_type=<TuyaDPType.VALUE: 2>, function=0, raw=b'\x00\x00\x00\x00', *payload=0))]`

**Comment by buddy31130** [comment]
I have to add that this device is sending a huge amount of messages everyday. About 15,000-20,000 entries for some sensors and linkquality each day. Is it normal ?

**Comment by maxperron** [comment]
I just bought this device and have the same issues as described above. Is there any unofficial quirk we can download?

**Comment by sj3fk3** [comment]
Seeing the same issues.. Deadly Formaldehyde Concentration (about 300 ppm) and strange CO2 levels (either around 8 or 40.000)? Temp and Hum seem ok, no PM2.5 and VOC also looks kinda okish.

**Comment by Sesshoumaru-sama** [comment]
I also died of Formaldehyde several times over, if the value would be correct and PM2.5 is missing.
Fix would be greatly appreciated.

**Comment by AssetBurned** [comment]
Isn't this a pretty similar unit compared to the _TZE200_yvx5lh6k in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4990 ?

Also to link the topics https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5733

**Comment by arohl** [comment]
> Can confirm under ZHA I'm seeing similar issues with the TZE200_dwcarsat TS0601 device not showing all the sensors and the data being mismatched.

I have the same model and only see one sensor - Voc_level - any idea why I can't even see temperature and humidity?

**Comment by gudvinr** [comment]
So, I have this sensor too and also didn't have anything other than VOC right after it is paired.

Other sensors appeared only after HA restart and CO₂/HCHO sensors are swapped. PM2.5 is missing as well.

**Comment by chaples55** [comment]
I have several of these TZE200_dwcarsat TS0601 and can confirm the behavior that several others have reported. Would love to see these supported! For the time being, I have them integrated via Tuya, though even that isn't perfect since the temperature units use a weird ° character that isn't recognized. Here's how that shows up:
![Screenshot_2022-07-29-20-18-00-90_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/33135543/181862668-28f079e6-58c2-4a88-b64f-0ed3a461a6b1.jpg)

**Comment by chaples55** [comment]
Just updated HA Core from 6.6 to 8.0 and the temperature reading shows up correctly in °F now via the Tuya integration.

**Comment by arohl** [comment]
> Just updated HA Core from 6.6 to 8.0 and the temperature reading shows up correctly in °F now via the Tuya integration.

@chaples55 Doing it via the Tuya integration means you need a Tuya hub? Looks like it works in zigbee2mqtt but not ZHA.

**Comment by chaples55** [comment]
Yeah, I'm still using 5 of these things via a Tuya hub. I have a 6th one connected via ZHA to keep tabs on whether it is fully supported yet, but unfortunately that still is not the case. 

I have a second ZigBee dongle coming soon so I can use both z2m and ZHA and ditch the Tuya hub entirely.

**Comment by arohl** [comment]
@chaples55 My SkyConnect arrived on Friday so I guess I can use my old dongle to run z2m - why didn't I think of that :-)

**Comment by marinswk** [comment]
Having the same exact issues with the same model and ZHA with Skyconnect on homeassistant OS.
Mismatched sensors values and missing pm2.5 sensor report.
Any update here? any way to fix it? :)

**Comment by n00b001** [comment]
I'm also having this exact same issue

**Comment by jdopson0624** [comment]
Same issue here...

**Comment by fhaust** [comment]
It's a bit strange ... the sensors come up after a home assistant restart.
But CO2 and CH2O (Formaldehyde) seems to be switched? (But even then the
CH20 level is higher than safe standard).

Am Do., 16. Feb. 2023 um 21:51 Uhr schrieb Jason Dopson <
***@***.***>:

**Comment by gudvinr** [comment]
Don't bother to make it make sense. HCHO and CO2 values are artificial and just calculated from VOC sensor data inside box.

**Comment by fhaust** [comment]
@gudvinr Is that so? So the "4 in 1" and "6 in 1" sensors are basically the same, just with some more code?

**Comment by Walmtech** [comment]
Well nothing suprise me with these cheap sensors. I took a look inside and can confirm in my 6in1 there are only 3 sensors.

![PXL_20230217_200805988](https://user-images.githubusercontent.com/35749327/219786646-aa815388-7c69-44e9-a496-f420bc997912.jpg)

**Comment by Walmtech** [comment]
That MP501sensor for VOC only has 4 levels of output not very useful really

![image](https://user-images.githubusercontent.com/35749327/219787887-d2067154-68c4-46e1-b0f3-53d6717449cc.png)

**Comment by chaples55** [comment]
Can confirm that the HCHO, CO2, and VOC values are complete garbage. Bought some proper sensors from Airthings and the values are completely different. The CO2 level on the Airthings reads 2-3x higher and actually changes in response to room occupancy and ventilation, unlike these cheap multi-sensors.

**Comment by tobixen** [comment]
Bought a heap of cheap tuya airsensors a while ago - _TZE200_yvx5lh6k - using ZHA and they are only reporting VOC (varying between 20 and 50 micrgram / cubic metre.

The layout looks different from what's posted above, but I can recognize the MP501 gas sensor, the AHT20 temperature/humidity sensor and I also have that ZT3L-chip.

Even just the information from the humidity/temperature sensor would be useful for me.

**Comment by pwnorbitals** [comment]
Bump ! Thank you :)

**Comment by shaman007** [comment]
> Bought a heap of cheap tuya airsensors a while ago - _TZE200_yvx5lh6k - using ZHA and they are only reporting VOC (varying between 20 and 50 micrgram / cubic metre.
> 
> The layout looks different from what's posted above, but I can recognize the MP501 gas sensor, the AHT20 temperature/humidity sensor and I also have that ZT3L-chip (EDIT: that's the zigbee interface).
> 
> Even just the information from the humidity/temperature sensor would be useful for me.

Same thing for me.

**Comment by schwaboy** [comment]
Using ZHA and I only see the VOCs. I bought this primarily for the CO2. How can we get this to show up using ZHA?
