### ISSUE TITLE
[Improvement] Provide version number through code

### ISSUE THREAD

**Issue by mdeweerd** [zigpy/zha-device-handlers#1423]
Most of the projects in the zigpy univers have a __version__ set in the module.

I can't find this for zha-device-handlers.

My goal was to add this to event data in [zha-toolkit](/mdeweerd/zha-toolkit) so that it's easier and more reliable to determine which version of a quirk is actually used.

**Comment by dmulcahey** [comment]
I agree. I also think we should move this lib to CalVer. Semantic versioning doesn't really fit the purpose of this library.

**Comment by mdeweerd** [comment]
I agree that CalVer is more appropriate - not so much because of the purpose but because it's linked to frequently updated SW (that uses the same numbering system).
