### ISSUE TITLE
Quirky tripper door sensor battery not reporting

### ISSUE THREAD

**Issue by cbarth3** [zigpy/zha-device-handlers#1440]
I am creating this new issue as this was the last post I could find about this. I can see voltage info but the entity shows as unkown as previously stated. I am running HA 2022.3.1 and just installed ZHA yesterday. 

I can confirm, the latest version of HA, just added the Quirky tripper door sensor and seeing this:
![image](https://user-images.githubusercontent.com/6178252/110219106-32a28e00-7e8b-11eb-868b-00b3e5179828.png)

_Originally posted by @42ism in https://github.com/zigpy/zha-device-handlers/issues/33#issuecomment-792041390_

**Comment by MattWestb** [comment]
You need making one quirk and adding this in the replacement:
https://github.com/zigpy/zha-device-handlers/blob/039a31f1ca15821e800bdb347eb47fdb02455f31/zhaquirks/__init__.py#L188.
of the `PowerConfiguration` cluster then the system shall calculating the battery from the voltage,

**Comment by MattWestb** [comment]
Its looks some device from the same manufacture have implanting on fix in one other quirk:
https://github.com/zigpy/zha-device-handlers/blob/039a31f1ca15821e800bdb347eb47fdb02455f31/zhaquirks/sercomm/szwtd02n.py#L21-L25

**Comment by cbarth3** [comment]
Thanks for info. Not sure how I can implement that into my home assistant.

**Comment by javicalle** [comment]
Probably just adding the MODEL to the existing quirk would do the job:
```python
class SZWTD02N(CustomDevice):
    """Custom device representing Sercomm SZ-WTD02N flood sensor."""

    signature = {
        #  <SimpleDescriptor endpoint=1 profile=260 device_type=1026
        #  device_version=0
        #  input_clusters=[0, 1, 3, 1280, 32, 2821]
        #  output_clusters=[3, 25]>
        MODELS_INFO: [
            (SERCOMM, "SZ-WTD02N_SF"),
            (SERCOMM, "Tripper"),
        ],
```

You need to edit the `szwtd02n.py` file in your installation or copy in a local quirks path:

There are some guides here:
* https://github.com/zigpy/zha-device-handlers/discussions/693
