### ISSUE TITLE
[BUG] 0.0.68 broke zha 

### ISSUE THREAD

**Issue by smarthomelawyer** [zigpy/zha-device-handlers#1449]
0.0.68 broke zha

Installed via custom deeps deployment add-on. Rebooted HA core. ZHA failed to start. Screenshot of errors below. Reverting back to 0.0.67 fixed the issue. 

![image](https://user-images.githubusercontent.com/74792554/160928878-ba95fb52-1dae-4391-b846-4ccf9e790345.jpeg)

![image](https://user-images.githubusercontent.com/74792554/160928902-ea716aa9-a548-4d6f-88e8-8d37aa24316f.jpeg)

**Comment by dmulcahey** [comment]
It needs the HA beta and the new version of Zigpy
