### ISSUE TITLE
[Device support request] Parkside PSBZS A1  frost alert

### ISSUE THREAD

**Issue by SzymonZy** [zigpy/zha-device-handlers#1452]
**Is your feature request related to a problem? Please describe.**
At the moment Parkside PSBZS A1  has no reset on frost alert in ZHA. If temp fall below 5 deg device is locked and you have to remove batteries to make it work again.

**Describe the solution you'd like**
Have additional entity on which you can call reset of frost alert. 

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen.**
Details of sniffed traffic can be found on zigbee2mqtt github issues discussion: 
https://github.com/Koenkk/zigbee2mqtt/issues/7695
current id in ZHA:
`{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0000",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_htnnfasr",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}`

**Additional context**
Current integration is not complete and not suitable for productive usage in real life.

**Comment by rforro** [comment]
It has been worked on see https://github.com/zigpy/zha-device-handlers/issues/933#issuecomment-1127249857
