### ISSUE TITLE
ZHA Device Handlers releases not using semantic versioning correctly?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zha-device-handlers#1456]
Maybe my misunderstanding but think zha-quirks releases are not using semantic versioning correctly for "MINOR" and "PATCH"?

https://github.com/zigpy/zha-device-handlers/releases

Believe "MINOR" releases of zha-device-handlers like example version 0.0.68 should instead have used ex. 0.68.0 as its versioning?

Following that logic, the new 0.0.69 which was a "PATCH" release should instead have been released as ex. 0.68.1 as its versioning?

That is, many open source projects use semantic versioning schemes commonly impart these meanings on individual sequences:

MAJOR.MINOR.PATCH (example: 0.68.1 release version)

Btw, some other zigpy projects like the zigpy project do use MAJOR.MINOR.PATCH -> https://github.com/zigpy/zigpy/releases at least looking at the latest zigpy releases as examples -> [zigpy 0.44.0 release.](https://github.com/zigpy/zigpy/releases/tag/0.44.0) (MINOR) compared to [zigpy 0.44.1 release](https://github.com/zigpy/zigpy/releases/tag/0.44.1) (PATCH).

As such, most ZHA Device Handlers releases should probably instead use a versioning schema that change "MINOR" in the middle.

### Summary

Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards compatible manner, and
3. PATCH version when you make backwards compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

https://semver.org

https://en.wikipedia.org/wiki/Software_versioning#Semantic_versioning

Examples of semantic versioning three-part version number from wikipedia:

![image](https://user-images.githubusercontent.com/6320001/161235616-da46f8b4-d655-4afc-ab29-16ae0dee6efe.png)

![image](https://user-images.githubusercontent.com/6320001/161235887-58aeb87e-eb93-4a93-8713-77d1d5acd51b.png)

**Comment by dmulcahey** [comment]
We’re going to switch to calver for quirks as it’s more appropriate. Just haven’t had the time to do it yet.
