### ISSUE TITLE
[BUG] Aqara Vibration Sensor zha_send_event strength not available in HA

### ISSUE THREAD

**Issue by switschel** [zigpy/zha-device-handlers#1488]
**Describe the bug**
I’m using 2 Aqara Vibrations Sensors with ZHA and Home Assistant 2022.4.2. Coordinator is a sonoff zigbee 3.0 usb dongle plus which is working fine so far.

My issue is that I want to work with the Vibration Strength. So I created the following entry in my configuration.yaml in HA:
```
template:
- trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "00:15:8d:00:07:c7:d1:d3"
      endpoint_id: 1
      command: "vibration_strength"
  sensor:
  - name: Briefkasten Vibration Strength
    state: "{{ trigger.event.data.args[0]['strength'] }}"
    unit_of_measurement: "%"
    attributes:
      last_update: "{{ now() }}"
```
The Problem is that this Event is never received and the Sensor value is always unavailable.
If I trigger the sensor (shaking) I see the following entry in my logs:
```
Logger: zigpy.util
Source: /usr/local/lib/python3.9/site-packages/zigpy/util.py:51
First occurred: 15:38:58 (23 occurrences)
Last logged: 18:08:39

* Error calling listener.zha_send_event: Unexpected zha_send_event 'vibration_strength' argument: ({'strength': 83},)
* Error calling listener.zha_send_event: Unexpected zha_send_event 'vibration_strength' argument: ({'strength': 5},)
* Error calling listener.zha_send_event: Unexpected zha_send_event 'vibration_strength' argument: ({'strength': 4},)
* Error calling listener.zha_send_event: Unexpected zha_send_event 'vibration_strength' argument: ({'strength': 10},)
* Error calling listener.zha_send_event: Unexpected zha_send_event 'vibration_strength' argument: ({'strength': 16},)
```
So I thought to change the event from “zha_event” to “zha_send_event” but also no success. Also if I subscribe for these events in developer tools in HA I don’t get any entry but the default events like “tilt”, “onOff” but not “vibration_strength”.

It seems to me there is an issue with zha / zigpy not forwarding the zha_send_event accordingly.

**Expected behavior**
The zha_event vibrations_strength with the strength arguement is available in HA and can be used to map data to a sensor or to be used in automation.

**Comment by dmulcahey** [comment]
This will be fixed in .3
