### ISSUE TITLE
[Device Support Request] ZBMini-L delayed response after minutes of pairing. Workaround found on Zigbee2MQTT

### ISSUE THREAD

**Issue by pulento** [zigpy/zha-device-handlers#1519]
**Context**

ZBMini-L is Zigbee 3.0 switch which does not need neutral line for power. It seems to work fine at the beginning but after minutes ZBMini-L switch is paired it shows a delayed response that seems to get worse with time.

**To Reproduce**
1. Pair the ZBMini-L with ZHA
2. It responds fast at the beginning
3. Wait 30 minutes or more
4. Switch it ON/OFF and note the delay
5. It gets workse with time

**Expected behavior**
No delay. But it seems to be a workaround for this behavior since it was fixed in Z2M on this commit:

https://github.com/Koenkk/zigbee-herdsman-converters/commit/ac7a095463c8b4dec3d6a6b34eb1e221a0f37d90

Bug was reported here:

https://github.com/Koenkk/zigbee2mqtt/issues/11676

**Device Signature**

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4742, maximum_buffer_size=80, maximum_incoming_transfer_size=160, server_mask=11264, maximum_outgoing_transfer_size=160, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0002",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0007",
        "0x0020",
        "0xfc57",
        "0xfca0"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "SONOFF",
  "model": "ZBMINI-L",
  "class": "zigpy.device.Device"
}
```

TIA

**Comment by hevili** [comment]
also experiencing this issue

**Comment by MattWestb** [comment]
Very likely is not one problem with the host system more the device not working as intended.
Read little of the problem our Z2M friends is having and all reclamations of devices they have doing to SonOff.
https://github.com/Koenkk/zigbee2mqtt/issues/10282

**Comment by Hedda** [comment]
If the Zigbee2MQTT developers could implement a workaround for this slow delay problem in a Zigbee converter for zigbee-herdsman-converters then maybe it is also possible to do the same in a ZHA Device Handlers quirk for the ZHA integration too?

https://github.com/Koenkk/zigbee2mqtt/issues/11676

Sound as if as a workaround they chose to unbind genPollCtrl to prevent the device from sending checkin message which causes Sonoff Zigbee End-Devices poll slower about 1-hour after powering the device?

https://github.com/Koenkk/zigbee-herdsman-converters/commit/ac7a095463c8b4dec3d6a6b34eb1e221a0f37d90

**Comment by Hedda** [comment]
> Very likely is not one problem with the host system more the device not working as intended.

ITead SONOFF Product Manager @Daniel-zhan-itead confirmed that their SONOFF engineer analyses found that the root cause for Sonoff ZBMINI-L delays and slow response in Home Assistant is a firmware issue, but hope problem can be worked around in application.

"**_Our engineer analyzes the reason for this may be: After ZBMINI-L joins HA, HA will configure the Check-in message of the device. When HA receives the Check-in message from the device, it will modify the wake-up time of the device to 6S, which will cause the device to receive the control command delay. And our check-in period is 1 hour, so the control delay problem will occur after one hour. Is it possible for HA to handle polling time for ZBMINI-L especially?_**"

For reference; the Sonoff ZBMINI-L is a Zigbee End Device, (not a Zigbee Router ). Still, the product is a switch with a relay so it needs to respond quickly to control commands sent by the Zigbee application.

**Comment by MattWestb** [comment]
One Zigbee 3 end device shall supporting pull control for not loosing messages the host system like sending it with out pulling its parent in short intervals all the time but doing check in to the host system..

Fast pull shall timing out if the hoist is not sending one fast pull stop that ZHA is sending but its looks the device is not being Zigbee compatible and / or not tested of the manufacture.

Its looks like TI have implanting many nice buts in the SDK and the companies need learning how to working then around or getting TI fixing then. 

Disabling chicken is not recommend but if the manufacture cant fixing the bug i think its the last resort for getting the device working or returning them to the seller (at least EU it shall being no problem if the seller cant fixing the device working OK) and perhaps some manufactures is learning how to do working devices and not only selling components in one plastic box with firmware that is not working.

**Comment by caroku** [comment]
I have the same problem, my ZBMINI-L shows a delayed response after 1 hour, then appears offline the next day. I am from Chile and i bought the product from aliexpress, and returning to China is not an option. Great customer service. Hope you can help us.

**Comment by DieserKirsche** [comment]
Expierencing exactly same problem with HA, ConBee II and ZHA integration. After initial setting up everthing works fine and later some wiered behavior of ZBMINI-L switch. All other devices (in same automation) work as expected.
ZBMINI-L as itself is perfect device for my purpose, as long as this issue will / can be fixed with my setup (HA, ConBee II and ZHA).

**Comment by pulento** [comment]
Strangely I changed my coordinator to a Sonoff Dongle USB 3.0 from a ZBBridge and I've no experiencing big delays.

But what I'm having now is randoms turn off of the ZBMini-L not random turn on just random turn off on all of my 4 switches. I noted that other people reported the same problem on iTead page.

**Comment by Daniel-zhan-itead** [comment]
We will optimize the firmware to fix the delay issue of ZBMINI-L running on ZHA and release the OTA update image for you.
The firmware is under testing, once the test is completed, it will be published.

**Comment by dmulcahey** [comment]
> We will optimize the firmware to fix the delay issue of ZBMINI-L running on ZHA and release the OTA update image for you.
> The firmware is under testing, once the test is completed, it will be published.

Is the issue caused by something we are doing?

**Comment by Daniel-zhan-itead** [comment]
> > We will optimize the firmware to fix the delay issue of ZBMINI-L running on ZHA and release the OTA update image for you.
> > The firmware is under testing, once the test is completed, it will be published.
> 
> Is the issue caused by something we are doing?

After ZBMINI-L is added to ZHA, ZHA will enable the device poll control cluster function, and then the device interval of sleep & wake-up will be set to 6 seconds as default,  We will disable the poll control function in the device firmware so the interval will be kept at 500ms as default.

**Comment by jds11111** [comment]
> > > We will optimize the firmware to fix the delay issue of ZBMINI-L running on ZHA and release the OTA update image for you.
> > > The firmware is under testing, once the test is completed, it will be published.
> > 
> > 
> > Is the issue caused by something we are doing?
> 
> After ZBMINI-L is added to ZHA, ZHA will enable the device poll control cluster function, and then the device interval of sleep & wake-up will be set to 6 seconds as default, We will disable the poll control function in the device firmware so the interval will be kept at 500ms as default.

Will this also fix the random shutdowns?

**Comment by DieserKirsche** [comment]
> Expierencing exactly same problem with HA, ConBee II and ZHA integration. After initial setting up everthing works fine and later some strange behavior of ZBMINI-L switch. All other devices (in same automation) work as expected. ZBMINI-L as itself is perfect device for my purpose, as long as this issue will / can be fixed with my setup (HA, ConBee II and ZHA).

I had the same problem with the random turn off, not very often, sometimes after half an hour and sometimes immediatly after turning on (10s).

**Comment by dmulcahey** [comment]
> > > We will optimize the firmware to fix the delay issue of ZBMINI-L running on ZHA and release the OTA update image for you.
> > > The firmware is under testing, once the test is completed, it will be published.
> > 
> > 
> > Is the issue caused by something we are doing?
> 
> After ZBMINI-L is added to ZHA, ZHA will enable the device poll control cluster function, and then the device interval of sleep & wake-up will be set to 6 seconds as default, We will disable the poll control function in the device firmware so the interval will be kept at 500ms as default.

Why Is this cluster even part of this device. This is really meant for battery powered devices that may need to accept configuration commands from an application so that they don't go to sleep while they are in the middle of being configured no? seems odd to me that this cluster is on a mains powered relay.

**Comment by pulento** [comment]
Maybe powering without Neutral hasn't much power either. If not why iTead didn't implemented it as Router devices ?

**Comment by Hedda** [comment]
> Why Is this cluster even part of this device? This is really meant for battery powered end devices
> 
> > Maybe powering without Neutral hasn't much power either. If not why iTead didn't implemented it as Router devices ?

IIRC believe someone in Home Assistant community forum posted a link 
reference to a technical article that explained why power to non-neutral devices is unreliable/unstable or should at least not be assumed to be guaranteed, and therefore they should at least not be Zigbee Router devices.

https://github.com/Koenkk/zigbee2mqtt/issues/11676

**Comment by Daniel-zhan-itead** [comment]
> > > > We will optimize the firmware to fix the delay issue of ZBMINI-L running on ZHA and release the OTA update image for you.
> > > > The firmware is under testing, once the test is completed, it will be published.
> > > 
> > > 
> > > Is the issue caused by something we are doing?
> > 
> > 
> > After ZBMINI-L is added to ZHA, ZHA will enable the device poll control cluster function, and then the device interval of sleep & wake-up will be set to 6 seconds as default, We will disable the poll control function in the device firmware so the interval will be kept at 500ms as default.
> 
> Will this also fix the random shutdowns?

Yup, this random shutdown issue will also be fixed together, Pls wait for the new firmware release. Thanks for your understanding

**Comment by pulento** [comment]
Great news 👍 

Now we have to figure how to apply OTA on these with HA

**Comment by MattWestb** [comment]
Im having one tuya `TS110F _TZ3000_92chsky7` its one dual dimmer switch  without neutral that works great and is one router device so its depends of the hardware implementation and its no need having external capacitor for making it working stable.
If getting one OTA files from Sonoff / itead its only configure local OTA in HA and putting the file in the folder and restarting HA https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates if the original firmware have implanting working OTA function.

Also if its shall being one end device (not real sleeper) is better deleting the poll control cluster then making some crazy half implanting then its need pulling its parent very oft for not getting delay then sending commands to it. If it shall being one sleeper it shall having working pull control as one Zigbee 3 device for not loosing commands sent to it like all battery powered remotes is doing (that is Zigbee certificated).

Or the best is fixing the bug in the TI SDK or in the code made of the manufacture as shall being done before releasing the product if it was good tested.

**Comment by Hedda** [comment]
> Now we have to figure how to apply OTA on these with HA

@Daniel-zhan-itead FYI, if you can add images to a public repo then Itead Sonoff OTA provider for it could be added to zigpy:

https://github.com/zigpy/zigpy/blob/dev/README.md#zigbee-device-ota-updates

https://github.com/zigpy/zigpy/tree/dev/zigpy/ota

https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates

Once your OTA provider is in zigpy then OTA support in Home Assistant's ZHA can be extended to support Itead Sonoff devices:

https://www.home-assistant.io/integrations/zha#ota-firmware-updates

PS: That will by the way also be similar for Zigbee2MQTT which will need a new OTA provider for zigbee-herdsman-converters:

https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/lib/ota

https://www.zigbee2mqtt.io/guide/usage/ota_updates.html

**Comment by DieserKirsche** [comment]
> > > > > We will optimize the firmware to fix the delay issue of ZBMINI-L running on ZHA and release the OTA update image for you.
> > > > > The firmware is under testing, once the test is completed, it will be published.
> > > > 
> > > > 
> > > > Is the issue caused by something we are doing?
> > > 
> > > 
> > > After ZBMINI-L is added to ZHA, ZHA will enable the device poll control cluster function, and then the device interval of sleep & wake-up will be set to 6 seconds as default, We will disable the poll control function in the device firmware so the interval will be kept at 500ms as default.
> > 
> > 
> > Will this also fix the random shutdowns?
> 
> Yup, this random shutdown issue will also be fixed together, Pls wait for the new firmware release. Thanks for your understanding


Do you have any updates about the timeschedule or much better a pre-release? Otherwise I have to refund my devices today.

**Comment by Daniel-zhan-itead** [comment]
We have raised the pull request for the OTA update image on github https://github.com/Koenkk/zigbee-OTA/pulls.
Once it is approved, you can download the image and update the ZBMINI-L devices.

**Comment by MattWestb** [comment]
Use https://github.com/Koenkk/zigbee-OTA/blob/a26ec426d0c744f63e6ee534bcee7875434d1008/images/Sonoff/zbmini-l_v1.1.1.ota and clicking on download and putting the file in your OTA folder you have reconfigured in Z/HA and restart HA and it shall being possible updating the device firmware.
Configuring and triggering OTA updated is in in the wiki https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates.

**Comment by dmulcahey** [comment]
> We have raised the pull request for the OTA update image on github https://github.com/Koenkk/zigbee-OTA/pulls.
> Once it is approved, you can download the image and update the ZBMINI-L devices.

Do you have release notes for the firmware?

**Comment by pulento** [comment]
OTA is aborting on my case:

```
2022-05-20 09:34:16 DEBUG (MainThread) [zigpy.zcl] [0xF9E4:1:0x0019] OTA query_next_image handler for 'SONOFF ZBMINI-L': field_control=0, manufacture_id=4742, image_type=1, current_file_version=4101, hardware_version=None, model=ZBMINI-L

2022-05-20 09:34:16 DEBUG (MainThread) [zigpy.zcl] [0xF9E4:1:0x0019] OTA image version: 4353, size: 131086. Update needed: True

2022-05-20 09:35:12 DEBUG (MainThread) [zigpy.zcl] [0xF9E4:1:0x0019] OTA upgrade_end handler for 'SONOFF ZBMINI-L': status=Status.ABORT, manufacturer_id=4742, image_type=1, file_version=4353

2022-05-20 09:35:16 DEBUG (MainThread) [zigpy.zcl] [0xF9E4:1:0x0019] OTA query_next_image handler for 'SONOFF ZBMINI-L': field_control=0, manufacture_id=4742, image_type=1, current_file_version=4101, hardware_version=None, model=ZBMINI-L
```

**Comment by m2r57700** [comment]
Hi
First time I tried an OTA from ZHA and finally seems ok.

Previous Firmware: 0x00001004
Now : Firmware: 0x00001101

FYI

I used the following commands 

![image](https://user-images.githubusercontent.com/97808872/169560030-512add79-e42e-46fd-a64d-63a8174df535.png)

**Comment by pulento** [comment]
> Hi First time I tried an OTA from ZHA and finally seems ok.
> 
> Previous Firmware: 0x00001004 Now : Firmware: 0x00001101
> 
> ![image](https://user-images.githubusercontent.com/97808872/169560616-ec2c5a1d-9777-4559-9785-357e7d8943cf.png)
> 
> FYI
> 
> I used the following commands
> 
> ![image](https://user-images.githubusercontent.com/97808872/169561760-538b3d98-d09f-4da7-af38-8b6448a275fa.png)
> 
> I hope response delay will disappear.

My fault. I needed to upgrade latest HA, surely had mixed dependencies.

Now I see OTA file being uploaded. Will report if the firmware fixed the problems.

**Comment by m2r57700** [comment]
I did the update 21h ago and device seems working without response delay.

**Comment by jds11111** [comment]
For anyone seeking more details on accomplishing the OTA flash, I found this link the most helpful (also mentioned by Hedda): [https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates](https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates).  It worked fine for me, and took several minutes.

**Comment by Daniel-zhan-itead** [comment]
> > We have raised the pull request for the OTA update image on github https://github.com/Koenkk/zigbee-OTA/pulls.
> > Once it is approved, you can download the image and update the ZBMINI-L devices.
> 
> Do you have release notes for the firmware?

Feature: Added Poll Control Cluster private attribute poll control 0xFF00 enable/disable configuration, the default Poll Control Cluster initial configuration is disabled
Bugfix: Random shutdown issue

**Comment by Hedda** [comment]
> We have raised the pull request for the OTA update image on github https://github.com/Koenkk/zigbee-OTA/pulls.
> Once it is approved, you can download the image and update the ZBMINI-L devices.

@Daniel-zhan-itead Great to see you uploading OTA files (thanks!), however, can you please consider creating a new separate dedicated repository called "Sonoff_Zigbee_OTA" or similar under ITead's own official organization on GitHub and use that as your primary publishing location for all officially released Zigbee OTA files for Sonoff branded Zigbee devices?

https://github.com/itead

(That would for example be https://github.com/itead/Sonoff_Zigbee_OTA or someting like that).

Preferably also copying the concept of `index.json` with metadata on all files like Koenkk repository has to make scripting easier:

https://github.com/Koenkk/zigbee-OTA/blob/master/index.json

And of course `README.md` file which among other things could contain some basic information on how to update those:

https://github.com/Koenkk/zigbee-OTA/blob/master/README.md

Perhaps also as keeping some kind of `CHANGELOG.md` with changelog release history for each device firmware version:

https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/CHANGELOG.md

For ex. `zbmini-l_v1.1.1_release_notes.md` and so on with release notes for each version released + compounded changelog.

That way it will be a single trusted and official primary source of official Zigbee OTA files released by ITead.

**Comment by jds11111** [comment]
> > > We have raised the pull request for the OTA update image on github https://github.com/Koenkk/zigbee-OTA/pulls.
> > > Once it is approved, you can download the image and update the ZBMINI-L devices.
> > 
> > 
> > Do you have release notes for the firmware?
> 
> Feature: Added Poll Control Cluster private attribute 0xFF00 (enable/disable configuration), the default Poll Control Cluster initial configuration is disabled Bugfix: Random shutdown issue

The random shutdown issue is not fixed by this firmware for my device.

**Comment by DieserKirsche** [comment]
My device seeems to work properly since firmware update 4 days ago.

**Comment by jds11111** [comment]
With this firmware, I got two random shutdowns this morning:
![image](https://user-images.githubusercontent.com/15203860/170046963-09b150cb-8a16-46fb-bdd6-89ba3f5e6856.png)
![image](https://user-images.githubusercontent.com/15203860/170047157-f8a638bf-2938-4a1e-91d6-6fd3eba20b25.png)

(timezone is central US) This is the latest, no?

**Comment by pulento** [comment]
That meas that last time the device was seen on the network. Not the last time it went off.

**Comment by jds11111** [comment]
Of course. I witnessed it shut off twice.

**Comment by pulento** [comment]
> Of course. I witnessed it shut off twice.

Can you post the history to see if just "Turn off" which will mean bug still there.

In my case I haven't see a random shut off yet.

**Comment by jds11111** [comment]
Sure.  The last two here appear to be just random.  OTOH, I found an odd automation that might be causing problems. I have disabled it to see what happens.
![image](https://user-images.githubusercontent.com/15203860/170284309-e49602b3-6993-4266-a64b-8f284773daff.png)

**Comment by dtalens** [comment]
I have same issue with random shut off. In my case, device turns on or off for a second and returns to previous state. Issue occurs approximately 1 or 2 every 30 minutes. It has same behavior whether it is off or on.

**Comment by langejos** [comment]
I managed to upgrade to version 1.1.1 but it still is not working more than maybe half a day. Giving up for now.

**Comment by mbarcia** [comment]
Glad to see a new firmware has been provided to deal with these issues, thanks to the maintainers for that!

I've 4 of these ZBMINI-L installed, and one of them is exhibiting the bug described here (random turn on and off behaviour). I've followed this thread and managed to install the new firmware OTA, but unfortunately it didn't fix the bug, as you can see in the screen capture below:

<img width="1018" alt="Screenshot 2022-07-30 at 12 43 25" src="https://user-images.githubusercontent.com/6518569/181909456-fb68b1b5-9e12-484a-b92b-975908ff418f.png">

Is there anything else required to make this work? Thanks,
--mariano

**Comment by dtalens** [comment]
Same behaviour with last firmware 1.1.1. There seems to be more random shutdowns when I turn light on from home assistant switch.

**Comment by maxime1992** [comment]
Not sure if I witness the same issue or not but my light just went absolutely insane:

![image](https://user-images.githubusercontent.com/4950209/209484071-fe63782a-863b-42e8-81f2-2ec3b9b45aa4.png)

When this happen the only outcome for me is rebooting all my docker compose stack (including HA and Z2M) until it happens again.

**Comment by myref** [comment]
I have the same behaviour

**Comment by caroku** [comment]
I gave up, my zbmini-l is in a drawer.
