### ISSUE TITLE
TZ3000_bfn1w0mm quirk required

### ISSUE THREAD

**Issue by ssm84** [zigpy/zha-device-handlers#1545]
This tuya plug (20A) connects to ZHA but does not show the metering
please can someone help??

`{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=0, maximum_buffer_size=80, maximum_incoming_transfer_size=80, server_mask=10752, maximum_outgoing_transfer_size=80, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006"
      ],
      "out_clusters": [
        "0x0003",
        "0x0006",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZ3000_bfn1w0mm",
  "model": "TS011F",
  "class": "zigpy.device.Device"
}`
![zha quirk](https://user-images.githubusercontent.com/76822199/166559012-2c569aeb-cf3d-45c9-934c-754e182e1a95.png)

**Comment by javicalle** [comment]
According to this, device is not exposing power metering:
* https://github.com/Koenkk/zigbee2mqtt/issues/10604

Do you have any evidence that it does report power metering?
