### ISSUE TITLE
[Device Support Request]

### ISSUE THREAD

**Issue by elektrinis** [zigpy/zha-device-handlers#1590]
**Is your feature request related to a problem? Please describe.**
There is a new presence detector available, which should solve many automation problems. However it is not supported on zha yet.

**Describe the solution you'd like**
Support for new device

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_ztc6ggyl",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

</details>

**Additional context**
https://www.aliexpress.com/item/1005004170513399.html

**Comment by Hedda** [comment]
Nice! This "Tuya Zigbee Human Presence Detector" and other microwave/millimeter wave motion sensors from Tuya for smart human body presence a.k.a. occupancy and vacancy detection (product models: MIR-HE200-ZB, MYQ-ZHFD02, MSA050-Z1, MSA042D-Z1, MSA035-Z1, and MYQ-ZHFD01) are listed for global worldwide sale (unlike competing [Aqara FP1](https://github.com/zigpy/zha-device-handlers/issues/1533) product):

https://expo.tuya.com/product/952001

https://expo.tuya.com/product/1031059

https://expo.tuya.com/product/842246

https://expo.tuya.com/product/902056

https://expo.tuya.com/product/804011

https://expo.tuya.com/product/1031058
