### ISSUE TITLE
[BUG] aqara cube knock on faces 2, 3, 5, 6 report wrong activated face

### ISSUE THREAD

**Issue by mouth4war** [zigpy/zha-device-handlers#1629]
**Describe the bug**
Doing a double knock on faces 2, 3, 5 and 6 reports incorrect values for activated face:

Below example is for active face 2:

    "command": "knock",
    "args": {
        "value": 513,
        "description": "aqara logo facing user rotated 90 degrees left",
        "activated_face": 5

**To Reproduce**
1. Enable event listening. 
2. Flip the cube and knock on each face (1-6), check events.
3. Faces 1 and 4 work fine but knocking on faces 2, 3, 5, 6 generates incorrect activated_face values.

**Expected behavior**
Testing results for knock events: 6 and 3 are interchanged so are 2 and 5. 1 and 4 are reporting correctly.

**Screenshots**

<details>

<summary>Device signature</summary>

```yaml
Paste the device signature here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
Paste the diagnostic information here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

**Additional context**

**Comment by TheJulianJES** [comment]
Relevant PR that also contains some discussion: https://github.com/zigpy/zha-device-handlers/pull/1972

**Comment by alfa43** [comment]
Hi, so i got a new Aquqra Cube t1 pro and i got the same issue. How do i resolve this? How do i implement this fix?
