### ISSUE TITLE
[BUG] Wrong commands Hue Dimmer Switch 324131137411(EU) RWL021

### ISSUE THREAD

**Issue by Homergy** [zigpy/zha-device-handlers#1633]
**Describe the bug**
Wrong commands are received when pressing the buttons on the Hue Dimmer RWL021 Model Nr:324131137411 in ZHA.
I have 2 old Hue dimmers they are up to date and both have the exact same behavior.

Same issue as was posted here [https://github.com/zigpy/zha-device-handlers/issues/878](url) but since that ticket is closed I believe it would be a good idea to make a new post. 

If I read it correctly the changes to fix this were later pulled? [https://github.com/zigpy/zha-device-handlers/pull/884](url)
Can I possibly manually integrate them? (I'm very new to this)

**To Reproduce**
1. Add Hue Dimmer RWL021 324131137411 to ZHA
2. Go to Developer Tools --> Events --> Listen to events --> "zha_event"
3. See that the commands are not what they are supposed to be, only 3 commands "on" , "off_with_effect", "step"
4. Automations and blueprints don't work due to wrong commands

**Expected behavior**
Recieve the new updated commands when pressing a button:
 ''on_short_release''--> 'button_1_single_press'
 ''on_hold'' --> 'button_1_long_press'
 ''on_double_press'' --> 'button_1_double_press'
 ''up_short_release''--> 'button_2_single_press'
 ''up_hold'' --> 'button_2_long_press'
 ''up_double_press'' --> 'button_2_double_press'
 ''down_short_release'' --> 'button_3_single_press'
 ''down_hold'' --> 'button_3_long_press'
 ''down_double_press'' --> 'button_3_double_press'
 ''off_short_release'' --> 'button_4_single_press'
 ''off_hold'' --> 'button_4_long_press'
 ''off_double_press'' --> 'button_4_double_press'

**Screenshots**
A possible solution would be to reconfigure the device, unfortunately this doesn't work:
![image](https://user-images.githubusercontent.com/96831316/175804598-e6152be1-a857-456b-b3a0-4a146cca928e.png)

<details>
<summary>Device signature</summary>

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4107, maximum_buffer_size=89, maximum_incoming_transfer_size=63, server_mask=0, maximum_outgoing_transfer_size=63, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 49246,
      "device_type": "0x0830",
      "in_clusters": [
        "0x0000"
      ],
      "out_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x000c",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x000f",
        "0xfc00"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "Philips",
  "model": "RWL021",
  "class": "zhaquirks.philips.rwlfirstgen.PhilipsRWLFirstGen"
}
```

</details>

<details>
<summary>"zha_event" log for each button (from top to bottom)</summary>

```
Event 175 fired 10:01 PM:
{
"event_type": "zha_event",
"data": {
"device_ieee": "00:17:88:01:03:e4:dd:c1",
"unique_id": "00:17:88:01:03:e4:dd:c1:1:0x0006",
"device_id": "ab82eaeb54a49351f8df4fc6ca23dfed",
"endpoint_id": 1,
"cluster_id": 6,
"command": "on",
"args": [],
"params": {}
},
"origin": "LOCAL",
"time_fired": "2022-06-25T20:01:26.119088+00:00",
"context": {
"id": "01G6E78WK79G8AX3FN6JACWWD7",
"parent_id": null,
"user_id": null
}
}
Event 174 fired 10:01 PM:
{
"event_type": "zha_event",
"data": {
"device_ieee": "00:17:88:01:03:e4:dd:c1",
"unique_id": "00:17:88:01:03:e4:dd:c1:1:0x0008",
"device_id": "ab82eaeb54a49351f8df4fc6ca23dfed",
"endpoint_id": 1,
"cluster_id": 8,
"command": "step",
"args": [
0,
30,
9
],
"params": {
"step_mode": 0,
"step_size": 30,
"transition_time": 9,
"options_mask": null,
"options_override": null
}
},
"origin": "LOCAL",
"time_fired": "2022-06-25T20:01:25.536097+00:00",
"context": {
"id": "01G6E78W106CA4PDN8JBXQ4YC8",
"parent_id": null,
"user_id": null
}
}
Event 173 fired 10:01 PM:
{
"event_type": "zha_event",
"data": {
"device_ieee": "00:17:88:01:03:e4:dd:c1",
"unique_id": "00:17:88:01:03:e4:dd:c1:1:0x0008",
"device_id": "ab82eaeb54a49351f8df4fc6ca23dfed",
"endpoint_id": 1,
"cluster_id": 8,
"command": "step",
"args": [
1,
30,
9
],
"params": {
"step_mode": 1,
"step_size": 30,
"transition_time": 9,
"options_mask": null,
"options_override": null
}
},
"origin": "LOCAL",
"time_fired": "2022-06-25T20:01:24.896536+00:00",
"context": {
"id": "01G6E78VD0KS6ARXP2A6FWYPJA",
"parent_id": null,
"user_id": null
}
}
Event 172 fired 10:01 PM:
{
"event_type": "zha_event",
"data": {
"device_ieee": "00:17:88:01:03:e4:dd:c1",
"unique_id": "00:17:88:01:03:e4:dd:c1:1:0x0006",
"device_id": "ab82eaeb54a49351f8df4fc6ca23dfed",
"endpoint_id": 1,
"cluster_id": 6,
"command": "off_with_effect",
"args": [
0,
0
],
"params": {
"effect_id": 0,
"effect_variant": 0
}
},
"origin": "LOCAL",
"time_fired": "2022-06-25T20:01:23.887488+00:00",
"context": {
"id": "01G6E78TDF14Z5EQ8TMXZW0EDE",
"parent_id": null,
"user_id": null
}
}
```

</details>

**Comment by MrCamby** [comment]
Same for me

**Comment by Homergy** [comment]
@TheJulianJES as requested a new topic and tagged you.

**Comment by TheJulianJES** [comment]
> If I read it correctly the changes to fix this were later pulled? [https://github.com/zigpy/zha-device-handlers/pull/884](url)
> Can I possibly manually integrate them? (I'm very new to this)

The changes were pulled into Home Assistant (meaning they're already included in Home Assistant).

I have the same exact dimmer (same signature) and it's working just fine for me here and the quirk is correctly applying for your dimmer. So it's a different issue than the older one.

You could try to re-pair your dimmer to Home Assistant again or pressing a button on the dimmer during reconfiguring.

**Comment by Homergy** [comment]
@TheJulianJES You're a hero!!!
How could the solution be so simple... I adapted blueprint, paired and re-paired,... while all I had to do was press a button during reconfiguring... a bit ashamed I did not know that was a trick.

I have 2 dimmers tried removing it from HA, re-pairing to Hue check for upgrades (which there were none) and repairing it back to ZHA. Both still had the issue.
Pressing a button while reconfiguring did do the trick!
Still got an error but it works:
![image](https://user-images.githubusercontent.com/96831316/175829142-ff2a6e22-c51c-427f-a9e4-e2154506263f.png)

The strange (or normal?) thing is that it now sends 3 commands while pressing the on button:
<details>
<summary>"zha_event" log for just one on press button</summary>
```
Event 40 fired 8:33 PM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:03:e4:dd:c1",
        "unique_id": "00:17:88:01:03:e4:dd:c1:2:0xfc00",
        "device_id": "ab82eaeb54a49351f8df4fc6ca23dfed",
        "endpoint_id": 2,
        "cluster_id": 64512,
        "command": "on_press",
        "args": {
            "button": "on",
            "press_type": "press",
            "command_id": 0,
            "args": [
                1,
                3145728,
                0,
                33,
                0,
                0
            ]
        },
        "params": {}
    },
    "origin": "LOCAL",
    "time_fired": "2022-06-26T18:33:39.012458+00:00",
    "context": {
        "id": "01G6GMMVY4TX301RGYCC786HWH",
        "parent_id": null,
        "user_id": null
    }
}
Event 39 fired 8:33 PM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:03:e4:dd:c1",
        "unique_id": "00:17:88:01:03:e4:dd:c1:2:0xfc00",
        "device_id": "ab82eaeb54a49351f8df4fc6ca23dfed",
        "endpoint_id": 2,
        "cluster_id": 64512,
        "command": "on_short_release",
        "args": {
            "button": "on",
            "press_type": "short_release",
            "command_id": 0,
            "args": [
                1,
                3145728,
                2,
                33,
                0,
                0
            ]
        },
        "params": {}
    },
    "origin": "LOCAL",
    "time_fired": "2022-06-26T18:33:38.801927+00:00",
    "context": {
        "id": "01G6GMMVQH886Q152YTX2WDVKT",
        "parent_id": null,
        "user_id": null
    }
}
Event 38 fired 8:33 PM:
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:17:88:01:03:e4:dd:c1",
        "unique_id": "00:17:88:01:03:e4:dd:c1:1:0x0006",
        "device_id": "ab82eaeb54a49351f8df4fc6ca23dfed",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "on",
        "args": [],
        "params": {}
    },
    "origin": "LOCAL",
    "time_fired": "2022-06-26T18:33:38.730748+00:00",
    "context": {
        "id": "01G6GMMVNAHB6173VP5MX6S2F4",
        "parent_id": null,
        "user_id": null
    }
}
```
</details>
However it works fine now thx for the quick support!

**Comment by MrCamby** [comment]
For me it does still not work.
I tried reconfiguring it multiple times now, but it does not work for me.

![grafik](https://user-images.githubusercontent.com/15329731/175830432-cb67fd33-fb33-4597-94ef-c3df9d7c5f18.png)

**Comment by dmulcahey** [comment]
> For me it does still not work. I tried reconfiguring it multiple times now, but it does not work for me.
> 
> ![grafik](https://user-images.githubusercontent.com/15329731/175830432-cb67fd33-fb33-4597-94ef-c3df9d7c5f18.png)

Are you pressing a button on the remote to keep it awake while reconfigure is running?

**Comment by MrCamby** [comment]
Yes, I pressed every button (one after another, aswell as only one button) with a delay of maybe a second between each click.

**Comment by ljorg** [comment]
This is an issue again in 2026.2.1. When I add a Hue Dimmer RWL021 it has the wrong commands. When I press the buttons I get these events in in order from top to bottom:

On event was fired

Step event was fired with parameters: {'step_mode': <StepMode.Up: 0>, 'step_size': 30, 'transition_time': 9, 'options_mask': None, 'options_override': None} with arguments: [<StepMode.Up: 0>, 30, 9]

Step event was fired with parameters: {'step_mode': <StepMode.Down: 1>, 'step_size': 30, 'transition_time': 9, 'options_mask': None, 'options_override': None} with arguments: [<StepMode.Down: 1>, 30, 9]

Terrasse kontakt Off With Effect event was fired with parameters: {'effect_id': <OffEffectIdentifier.Delayed_All_Off: 0>, 'effect_variant': 0} with arguments: [<OffEffectIdentifier.Delayed_All_Off: 0>, 0]

I have tried reconfiguring while pressing buttons, resetting, moving it to hue hub (where it works fine) and move it back to HA. Nothing helps. It was working fine until it dropped off the network a couple of days ago.

I thought the switch might be bad, so I bought a new V2. Exactly the same issue on that one.
