### ISSUE TITLE
Tuya (Moes) _TZ3000_hhiodade switch with N is seen as end-device

### ISSUE THREAD

**Issue by JoryHogeveen** [zigpy/zha-device-handlers#1640]
**Describe the bug**

To be fair, this could be a Tuya issue.
This device can be installed with and without the N wire.

Device type: TS0011 - _TZ3000_hhiodade

When the N wire is connected I assumed it would register as a Router, is this assumption correct?

This is a Moes device: https://aliexpress.ru/item/1005002061439926.html

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0xe000",
        "0xe001"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZ3000_hhiodade",
  "model": "TS0011",
  "class": "zhaquirks.tuya.ts001x.Tuya_Single_No_N"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
Paste the diagnostic information here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

**Additional context**

**Comment by MattWestb** [comment]
The device signature / node description is saying `is_end_device=True` and very likely its not being changes if connecting with neutral.
You can trying deleting the device and re adding it after on minute and see is its reporting its self as one router but i think tuya have not putting so much good engineering in there firmware for doing that.

Changing it on the ZHA side is not helping then end device is normally not having one complete Zigbee stack and dont have the router function implanted (normally = the SDK is working so and customer can adding / changing things but its not easy = costing €).

**Comment by JoryHogeveen** [comment]
HI @MattWestb 
Thanks for your quick reply.
Could it be that this is yet again some strange Tuya setting issue, similar to that of the 4 button remotes (TS004F)?

**Comment by JoryHogeveen** [comment]
Hi @MattWestb 
Tested it a few times without luck and finally got reply from Moes. This device simply isn't a router at all, they only support the N wire for an unknown reason to me. Perhaps so you can use bulbs that use less than 0.5 watts.
Closing issue since there won't be a fix for this!
