### ISSUE TITLE
[Device Support Request] OWON Technology Inc. PC321,need more information to be display

### ISSUE THREAD

**Issue by adi90x** [zigpy/zha-device-handlers#1657]
Hello,

Reoppening #977
At the moment zha will only report one consumption while 3 are available.

Is it possible to do something ?
Signature of the device is available in #977
And manfucaturer doc is available there : https://github.com/froggyfly/pc321-zigbee/blob/main/PC321zigbee.docx

@froggyfly : Did you find another solution ?

Regards

**Comment by fergalish** [comment]
Hi, I'm trying to install one of these OWON 3-phase/triple single phase power meters. It's adds to ZHA with no problem, but the only sensors I'm seeing are instantaneous power and total energy consumed, each a sum of the three physical input sensors.

I'm still learning HA & ZHA, so I have no idea how to edit a device signature etc.

Curious to know if there's a way to proceed.

Thanks.

**Comment by udivankin** [comment]
Seems to be implemented in z2m

BUT

there's two different PC321 zigbee clamp meters - PC321-Z and PC321-Z-TY (Tuya), which are according to @Koenkk two completely different devices.

Here's the long thread PC321-Z
https://github.com/Koenkk/zigbee2mqtt/issues/9525

And here is for PC321-Z-TY (Tuya)
https://github.com/Koenkk/zigbee2mqtt/issues/14790

**Comment by exelsis423** [comment]
Hello,
I reopen this request.
I have this equipment too the OWON PC321 Z.

After having searched a lot, I tried to write a quirk. The first way I tried was following the documentation with using the metering cluster. This the quirk:
`import zigpy.types as t

from zigpy.profiles import zha
from zigpy.quirks import CustomCluster, CustomDevice
from zigpy.zcl.foundation import ZCLAttributeDef, ZCLCommandDef
from zigpy.zcl.clusters.general import (
    Basic,
    Identify,
    )
from zigpy.zcl.clusters.smartenergy import (
    Metering, 
    )
from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
    SKIP_CONFIGURATION,
    )
    
from zhaquirks import LocalDataCluster



class OwonSimpleMetering(CustomCluster):
    cluster_id = 0x0702
    name = "Owon Simple Metering dbl"
    ep_attribute = "electrical_measurement" 

    attributes: dict[int, ZCLAttributeDef] = {
        0x0000: ZCLAttributeDef("current_summ_delivered", type=t.uint48_t, access="r", mandatory=True),
        0x0017: ZCLAttributeDef("Inlet_temperature", type=t.uint24_t, access="r", mandatory=True),
        0x0200: ZCLAttributeDef("Status", type=t.bitmap8, access="r", mandatory=True),
        0x0300: ZCLAttributeDef("unit_of_measure", type=t.enum8, access="r", mandatory=True),
        0x0301: ZCLAttributeDef("multiplier", type=t.uint24_t, access="r", mandatory=True),
        0x0302: ZCLAttributeDef("divisor", type=t.uint24_t, access="r", mandatory=True),
        0x0303: ZCLAttributeDef("summation_formatting", type=t.bitmap8, access="r", mandatory=True),
        0x0304: ZCLAttributeDef("demand_formatting", type=t.bitmap8, access="r", mandatory=True),
        0x0306: ZCLAttributeDef("metering_device_type", type=t.bitmap8, access="r", mandatory=True),
        0x0400: ZCLAttributeDef("Instantaneous_Demand", type=t.uint24_t, access="rw", mandatory=True),
        0x1000: ZCLAttributeDef("report_map", type=t.bitmap8, access="rw", mandatory=True, is_manufacturer_specific=True),
        0x2000: ZCLAttributeDef("L1_phase_power", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x2001: ZCLAttributeDef("L2_phase_power", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x2002: ZCLAttributeDef("L3_phase_power", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x2100: ZCLAttributeDef("L1_phase_reactive_power", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x2101: ZCLAttributeDef("L2_phase_reactive_power", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x2102: ZCLAttributeDef("L3_phase_reactive_power", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x2103: ZCLAttributeDef("reactive_power_summation_of_the_3_phases", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x3000: ZCLAttributeDef("L1_phase_voltage", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x3001: ZCLAttributeDef("L2_phase_voltage", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x3002: ZCLAttributeDef("L3_phase_voltage", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x3100: ZCLAttributeDef("L1_phase_current", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x3101: ZCLAttributeDef("L2_phase_current", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x3102: ZCLAttributeDef("L3_phase_current", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x3103: ZCLAttributeDef("current_summation_of_the_3_phases", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x3104: ZCLAttributeDef("leakage_current", type=t.uint24_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x4000: ZCLAttributeDef("L1_phase_energy_consumption", type=t.uint48_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x4001: ZCLAttributeDef("L2_phase_energy_consumption", type=t.uint48_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x4002: ZCLAttributeDef("L3_phase_energy_consumption", type=t.uint48_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x4100: ZCLAttributeDef("L1_phase_reactive_energy_consumption", type=t.uint48_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x4101: ZCLAttributeDef("L2_phase_reactive_energy_consumption", type=t.uint48_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x4102: ZCLAttributeDef("L3_phase_reactive_energy_consumption", type=t.uint48_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x4103: ZCLAttributeDef("reactive_energy_summation_of_the_3_phases", type=t.uint48_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x5000: ZCLAttributeDef("the_latest_historical_record_time", type=t.uint32_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x5001: ZCLAttributeDef("the_oldest_historical_recorded_time", type=t.uint32_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x5002: ZCLAttributeDef("set_minimum_cycle_for_report", type=t.uint32_t, access="rw", mandatory=True, is_manufacturer_specific=True),
        0x5003: ZCLAttributeDef("set_maximum_cycle_for_report", type=t.uint32_t, access="rw", mandatory=True, is_manufacturer_specific=True),
        0x5004: ZCLAttributeDef("sent_historical_record_state", type=t.uint8_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x5005: ZCLAttributeDef("frequency", type=t.uint8_t, access="r", mandatory=True, is_manufacturer_specific=True),
        0x5006: ZCLAttributeDef("the_accumulative_threshold_of_energy", type=t.uint8_t, access="rw", mandatory=True, is_manufacturer_specific=True),
        0x5007: ZCLAttributeDef("report_mode", type=t.uint8_t, access="rw", mandatory=True, is_manufacturer_specific=True),
        0x5008: ZCLAttributeDef("Set_Z_percent_change_in_power", type=t.uint8_t, access="rw", mandatory=True, is_manufacturer_specific=True),
    } 


    server_commands: dict[int, ZCLCommandDef] = {
        0x20: ZCLCommandDef("get_history_record", {}, is_manufacturer_specific=True),
        0x21: ZCLCommandDef("stop_sending_historical_record", {}, is_manufacturer_specific=True),
    }
    
    client_commands: dict[int, ZCLCommandDef] = {
        0x20: ZCLCommandDef("sent_historical_record", {}, is_manufacturer_specific=True),
    }
    


class OwonClearMetering(CustomCluster):
    cluster_id = 0xFFE0
    ep_attribute = "clear_metering"

    attributes: dict[int, ZCLAttributeDef] = {}
    
    server_commands: dict[int, ZCLCommandDef] = {
        0x00: ZCLCommandDef("clear_measurement_data", {}, is_manufacturer_specific=True),
    }
    client_commands: dict[int, ZCLCommandDef] = {}
    

""" New Device Owon PC321 """

class Owon(CustomDevice):
    
    signature = {
        #MODELS_INFO: [("Owon", "PC321")],
        ENDPOINTS: {
            # <SimpleDescriptor endpoint=1 profile=260 device_type=13
            # device_version=1
            # input_clusters=[0, 3, 1794]
            # output_clusters=[3]>
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.CONSUMPTION_AWARENESS_DEVICE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Metering.cluster_id,
                    ],
                OUTPUT_CLUSTERS: [Identify.cluster_id],
            },
        },
        "manufacturer": "OWON Technology Inc.",
    }
    replacement = {
        #SKIP_CONFIGURATION: True,
        ENDPOINTS: {
            # <SimpleDescriptor endpoint=1 profile=260 device_type=0x0053
            # device_version=1
            # input_clusters=[0, 3, 1794, 83]
            # output_clusters=[3]>
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.METER_INTERFACE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    OwonPowerMeasurement,
                    OwonClearMetering,
                ],
                OUTPUT_CLUSTERS: [Identify.cluster_id],
            },
        },
    }`

This quirk works, but when the device is discovered by ZHA, there's no entity.

I ask for help on a french forum, and I get adviced to try to pass the replacement trough ElectricalMeasurement.
I wrote a new quirk (simplier for the moment, there're not all attributes but it's for testing).
Regarding the documentation, it's possible to have different measurement types:
`class ElectricalMeasurementClusterHandler(ClusterHandler):
    """Cluster handler that polls active power level."""

    CLUSTER_HANDLER_NAME = CLUSTER_HANDLER_ELECTRICAL_MEASUREMENT

    class MeasurementType(enum.IntFlag):
        """Measurement types."""

        ACTIVE_MEASUREMENT = 1
        REACTIVE_MEASUREMENT = 2
        APPARENT_MEASUREMENT = 4
        PHASE_A_MEASUREMENT = 8
        PHASE_B_MEASUREMENT = 16
        PHASE_C_MEASUREMENT = 32
        DC_MEASUREMENT = 64
        HARMONICS_MEASUREMENT = 128
        POWER_QUALITY_MEASUREMENT = 256
`

I wrote this quirk:
`import zigpy.types as t

from zigpy.profiles import zha
from zigpy.quirks import CustomCluster, CustomDevice
from zigpy.zcl.foundation import ZCLAttributeDef, ZCLCommandDef
from zigpy.zcl.clusters.general import (
    Basic,
    Identify,
    )
from zigpy.zcl.clusters.smartenergy import (
    Metering, 
    )
from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
    SKIP_CONFIGURATION,
    )
    
from zigpy.zcl.clusters.homeautomation import ElectricalMeasurement
from zhaquirks import LocalDataCluster




class OwonPowerMeasurement(LocalDataCluster, ElectricalMeasurement):
    """Custom class for power, voltage and current measurement."""

    cluster_id = 0x0702

    POWER_ONE_ID = 0x2000
    POWER_TWO_ID = 0x2001
    POWER_THREE_ID = 0x2002

    MULTIPLIER = 0x0301
    DIVISOR = 0x0302
    _CONSTANT_ATTRIBUTES = {MULTIPLIER: 1, DIVISOR: 1000}



    ep_attribute = "electrical_measurement"
    attributes = {
        0x0000: ("current_summ_delivered", t.uint48_t, True),
        0x2000: ("L1_phase_power", t.uint24_t, True),
        0x2001: ("L2_phase_power", t.uint24_t, True),
        0x2002: ("L3_phase_power", t.uint24_t, True),
        0x0400: ("Instantaneous_Demand", t.uint24_t, True),
    }

    server_commands: dict[int, ZCLCommandDef] = {
        0x20: ZCLCommandDef("get_history_record", {}, is_manufacturer_specific=True),
        0x21: ZCLCommandDef("stop_sending_historical_record", {}, is_manufacturer_specific=True),
    }
    
    client_commands: dict[int, ZCLCommandDef] = {
        0x20: ZCLCommandDef("sent_historical_record", {}, is_manufacturer_specific=True),
    }
    


class OwonClearMetering(CustomCluster):
    cluster_id = 0xFFE0
    ep_attribute = "clear_metering"

    attributes: dict[int, ZCLAttributeDef] = {}
    
    server_commands: dict[int, ZCLCommandDef] = {
        0x00: ZCLCommandDef("clear_measurement_data", {}, is_manufacturer_specific=True),
    }
    client_commands: dict[int, ZCLCommandDef] = {}
    

""" New Device Owon PC321 """

class Owon(CustomDevice):
    
    signature = {
        #MODELS_INFO: [("Owon", "PC321")],
        ENDPOINTS: {
            # <SimpleDescriptor endpoint=1 profile=260 device_type=13
            # device_version=1
            # input_clusters=[0, 3, 1794]
            # output_clusters=[3]>
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.CONSUMPTION_AWARENESS_DEVICE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Metering.cluster_id,
                    ],
                OUTPUT_CLUSTERS: [Identify.cluster_id],
            },
        },
        "manufacturer": "OWON Technology Inc.",
    }
    replacement = {
        #SKIP_CONFIGURATION: True,
        ENDPOINTS: {
            # <SimpleDescriptor endpoint=1 profile=260 device_type=83
            # device_version=1
            # input_clusters=[0, 3, 1794, 65504]
            # output_clusters=[3]>
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.METER_INTERFACE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    OwonPowerMeasurement,
                    OwonClearMetering,
                ],
                OUTPUT_CLUSTERS: [Identify.cluster_id],
            },
        },
    }`

With this new quirk, I can read attributes as the first one, but I still don't have any entity. I block on this point, I cannot pass the good parameter to have for example PHASE_A_MEASUREMENT.
If someone could help on this point to try to finalize the quirk, I could share it.

Thanks

**Comment by exelsis423** [comment]
Sorry for the presentation, I used quote but all isn't taken completely for each example...

**Comment by udivankin** [comment]
any idea when it makes its way to hass update? and what are the steps to make it work in case it was already configured with only 3 entities?

**Comment by fergalish** [comment]
> Hi, I found a way to write a quirk, but it's doesn't descover entitier. So it's needed to create sensors, and an automation to have these sensors updated (mine is every minute).
> 
> Here is the code, code for sensors and automation is in comments at the end

Thanks for this. I implemented these, removed the PC321, restarted HA, and it is working as described.

**Comment by KPI33** [comment]
Never integrated?

**Comment by zoic21** [comment]
Hello,

For information I create an quirks v2 : 

```
"""Quirk for Owon PC321"""

from zigpy.quirks import CustomCluster
from zigpy.quirks.v2 import EntityPlatform, EntityType, QuirkBuilder, SensorDeviceClass, SensorStateClass
import zigpy.types as t
from zigpy.zcl.clusters.smartenergy import Metering
from zigpy.quirks.v2.homeassistant import (
    UnitOfApparentPower,
    UnitOfElectricCurrent,
    UnitOfPower,
    UnitOfEnergy,
    UnitOfElectricPotential,
)


class OwonPC321MeteringCluster(CustomCluster, Metering):
    """OwonPC321MeteringCluster cluster."""

    cluster_id = 0x0702
    name = "OwonPC321Metering"
    ep_attribute = "smartenergy_metering"

    attributes = Metering.attributes.copy()
    attributes.update(
        {
        0x2000: ("phase_1_power", t.uint24_t, True),
        0x2001: ("phase_2_power", t.uint24_t, True),
        0x2002: ("phase_3_power", t.uint24_t, True),
        0x2100: ("phase_1_reactive_power", t.uint24_t, True),
        0x2101: ("phase_2_reactive_power", t.uint24_t, True),
        0x2102: ("phase_3_reactive_power", t.uint24_t, True),
        0x2103: ("reactive_power_summation_of_the_3_phases", t.uint24_t, True),
        0x3000: ("phase_1_voltage", t.uint24_t, True),
        0x3001: ("phase_2_voltage", t.uint24_t, True),
        0x3002: ("phase_3_voltage", t.uint24_t, True),
        0x3100: ("phase_1_current", t.uint24_t, True),
        0x3101: ("phase_2_current", t.uint24_t, True),
        0x3102: ("phase_3_current", t.uint24_t, True),
        0x3103: ("current_summation_of_the_3_phases", t.uint24_t, True),
        0x3104: ("leakage_current", t.uint24_t, True),
        0x4000: ("phase_1_energy_consumption", t.uint48_t, True),
        0x4001: ("phase_2_energy_consumption", t.uint48_t, True),
        0x4002: ("phase_3_energy_consumption", t.uint48_t, True),
        0x4100: ("phase_1_reactive_energy_consumption", t.uint48_t, True),
        0x4101: ("phase_2_reactive_energy_consumption", t.uint48_t, True),
        0x4102: ("phase_3_reactive_energy_consumption", t.uint48_t, True),
        0x4103: ("reactive_energy_summation_of_the_3_phases", t.uint48_t, True),
        }
    )

(
    QuirkBuilder("OWON Technology Inc.", "PC321")
    .replaces(OwonPC321MeteringCluster)
    .sensor(
        "phase_1_power",
        OwonPC321MeteringCluster.cluster_id,
        unit=UnitOfPower.WATT,
        translation_key="active_power_phase_1",
        fallback_name="Active power phase 1",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_2_power",
        OwonPC321MeteringCluster.cluster_id,
        unit=UnitOfPower.WATT,
        translation_key="active_power_phase_2",
        fallback_name="Active power phase 2",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_3_power",
        OwonPC321MeteringCluster.cluster_id,
        unit=UnitOfPower.WATT,
        translation_key="active_power_phase_3",
        fallback_name="Active power phase 3",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_1_current",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="current_phase_1",
        unit=UnitOfElectricCurrent.AMPERE,
        fallback_name="Current phase 1",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_2_current",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="current_phase_2",
        unit=UnitOfElectricCurrent.AMPERE,
        fallback_name="Current phase 2",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_3_current",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="current_phase_3",
        unit=UnitOfElectricCurrent.AMPERE,
        fallback_name="Current phase 3",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_1_energy_consumption",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="energy_consumption_1",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        fallback_name="Energy consumption 1",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        divisor=1000,
    )
    .sensor(
        "phase_2_energy_consumption",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="energy_consumption_2",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        fallback_name="Energy consumption 2",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        divisor=1000,
    )
    .sensor(
        "phase_3_energy_consumption",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="energy_consumption_3",
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        fallback_name="Energy consumption 3",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        divisor=1000,
    )
    .sensor(
        "phase_1_voltage",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="voltage_1",
        unit=UnitOfElectricPotential.VOLT  ,
        fallback_name="Voltage 1",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        divisor=10,
    )
    .sensor(
        "phase_2_voltage",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="voltage_2",
        unit=UnitOfElectricPotential.VOLT,
        fallback_name="Voltage 2",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        divisor=10,
    )
    .sensor(
        "phase_3_voltage",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="voltage_3",
        unit=UnitOfElectricPotential.VOLT  ,
        fallback_name="Voltage 3",
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        divisor=10,
    )
    .sensor(
        "phase_1_reactive_power",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="reactive_power_1",
        unit=UnitOfPower.WATT,
        fallback_name="Reactive power 1",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_2_reactive_power",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="reactive_power_2",
        unit=UnitOfPower.WATT,
        fallback_name="Reactive power 2",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_3_reactive_power",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="reactive_power_3",
        unit=UnitOfPower.WATT,
        fallback_name="Reactive power 3",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "reactive_power_summation_of_the_3_phases",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="reactive_power_summation",
        unit=UnitOfPower.WATT,
        fallback_name="Reactive power summation",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "leakage_current",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="leakage_current",
        unit=UnitOfElectricCurrent.AMPERE,
        fallback_name="Leakage current",
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_1_reactive_energy_consumption",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="reactive_energy_consumption_1",
        unit=UnitOfPower.WATT,
        fallback_name="Reactive energy consumption 1",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_2_reactive_energy_consumption",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="reactive_energy_consumption_2",
        unit=UnitOfPower.WATT,
        fallback_name="Reactive energy consumption 2",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "phase_3_reactive_energy_consumption",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="reactive_energy_consumption_3",
        unit=UnitOfPower.WATT,
        fallback_name="Reactive energy consumption 3",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .sensor(
        "reactive_energy_summation_of_the_3_phases",
        OwonPC321MeteringCluster.cluster_id,
        translation_key="reactive_energy_consumption_summation",
        unit=UnitOfPower.WATT,
        fallback_name="Reactive energy consumption summation",
        device_class=SensorDeviceClass.REACTIVE_POWER,
        state_class=SensorStateClass.MEASUREMENT,
    )
    .add_to_registry()
)
```

With this v2 it's not needed anymore to have automation or template all entity are automatically create and update.

**Comment by BartGysens** [comment]
Working - confirmed
Please add to integration.
Thank you.

**Comment by zoic21** [comment]
Hello,
Thanks for return I make a PR #4120
