### ISSUE TITLE
[BUG] TS0201 Reporting Humidity off by factor of 10

### ISSUE THREAD

**Issue by romain1206** [zigpy/zha-device-handlers#1684]
hello,

Connected a Tuya TS0201 and watch reporting. 
Temperature is correct, Humidity displays 47.3% (on screen) but reports 4.73 via ZHA

**Comment by javicalle** [comment]
Please, fill the new bug template with the relevant info. At least, the device's signature and a vendor URL to identify the device.

Thanks in advance.

**Comment by javicalle** [comment]
Maybe duplicate of #1667

**Comment by dmulcahey** [comment]
Please do as instructed by @javicalle
