### ISSUE TITLE
[Device Support Request] Do quirks / support for devices start automatically?

### ISSUE THREAD

**Issue by jase31** [zigpy/zha-device-handlers#1703]
[Device Support Request] Do quirks / support for devices start automatically?

I have a TS0601 TRV valve that is not support by ZHA - but I think should be with quirks? How do I get it working?

**Comment by MattWestb** [comment]
Look in the  tuya TRV matrix and if you device is one clone of one supported ones you can adding your device in the quirk and testing if its working OK.

https://github.com/zigpy/zigpy/discussions/653#discussioncomment-314395

**Comment by dmulcahey** [comment]
Do as @MattWestb suggests above and either open a PR if it works or if you are uncomfortable with that you can open a device support requests with all of the necessary data.
