### ISSUE TITLE
[Device Support Request] Aqara LUMI.weather

### ISSUE THREAD

**Issue by paulstimpson** [zigpy/zha-device-handlers#1765]
**Is your feature request related to a problem? Please describe.**
I have purchased an Aqara temperature/humidity/pressure sensor. Home Assistant says it has paired and configured it successfully. Its entities exist and can be used. The attributes update immediately when paired but then don't continue to update. The device appears in the visualization but doesn't have any connections and after a short time it becomes unavailable and falls off the mesh. Pressing the button on the device while it's connected causes it to update in HA. I've tried adding it directly to the coordinator and via two different model Ikea bulbs as repeaters, the result is identical.

I bought 3 devices, unpacked another and its sensors seem to go unavailable at different times. I also tried changing the battery in the first sensor even though the level of the factory battery was showing 74% and this hasn't changed the behaviour

**Describe the solution you'd like**
The device should pair then its values automatically update periodically in HA, like my Sonoff temperature sensors do.

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4151, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=0, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0302",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0402",
        "0x0403",
        "0x0405",
        "0xffff"
      ],
      "out_clusters": [
        "0x0000",
        "0x0004",
        "0xffff"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.weather",
  "class": "zhaquirks.xiaomi.aqara.weather.Weather2"
}

</details>

<details>
<!-- Diagnostic information can be acquired by clicking on the "Download Diagnostics" button in the device settings view -->
<summary>Diagnostic information</summary>

```yaml
Paste the diagnostic information here.
Don't remove the extra line breaks outside the ``` marks.
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.9.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.15.67",
    "supervisor": "2022.08.6",
    "host_os": "Home Assistant OS 9.0",
    "docker_version": "20.10.17",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "nodered": {
      "version": "1.0.7",
      "requirements": []
    },
    "hacs": {
      "version": "1.24.5",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.33.1",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.79",
      "zigpy-deconz==0.18.1",
      "zigpy==0.50.3",
      "zigpy-xbee==0.15.0",
      "zigpy-zigate==0.9.2",
      "zigpy-znp==0.8.2"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 36502,
    "manufacturer": "LUMI",
    "model": "lumi.weather",
    "name": "LUMI lumi.weather",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.xiaomi.aqara.weather.Weather2",
    "manufacturer_code": 4151,
    "power_source": "Battery or Unknown",
    "lqi": 145,
    "rssi": null,
    "last_seen": "2022-09-17T15:59:59",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4151, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=0, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0302",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0402",
            "0x0403",
            "0x0405",
            "0xffff"
          ],
          "out_clusters": [
            "0x0000",
            "0x0004",
            "0xffff"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "button.lumi_lumi_weather_identifybutton",
        "name": "LUMI lumi.weather"
      },
      {
        "entity_id": "sensor.lumi_lumi_weather_battery",
        "name": "LUMI lumi.weather"
      },
      {
        "entity_id": "sensor.lumi_lumi_weather_pressure",
        "name": "LUMI lumi.weather"
      },
      {
        "entity_id": "sensor.lumi_lumi_weather_temperature",
        "name": "LUMI lumi.weather"
      },
      {
        "entity_id": "sensor.lumi_lumi_weather_humidity",
        "name": "LUMI lumi.weather"
      }
    ],
    "neighbors": [],
    "endpoint_names": [
      {
        "name": "TEMPERATURE_SENSOR"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "0a5a6f46d6ffbb18a2ac04415bcc8eab",
    "area_id": "bedroom",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "TEMPERATURE_SENSOR",
          "id": 770
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0001": {
                "attribute_name": "app_version",
                "value": 5
              },
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "LUMI"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "lumi.weather"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 30.2
              },
              "0x0021": {
                "attribute_name": "battery_percentage_remaining",
                "value": 146
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0402": {
            "endpoint_attribute": "temperature",
            "attributes": {
              "0x0000": {
                "attribute_name": "measured_value",
                "value": 2322
              }
            },
            "unsupported_attributes": {}
          },
          "0x0403": {
            "endpoint_attribute": "pressure",
            "attributes": {
              "0x0000": {
                "attribute_name": "measured_value",
                "value": 1013.77
              }
            },
            "unsupported_attributes": {}
          },
          "0x0405": {
            "endpoint_attribute": "humidity",
            "attributes": {
              "0x0000": {
                "attribute_name": "measured_value",
                "value": 6227
              }
            },
            "unsupported_attributes": {}
          },
          "0xffff": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xffff": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```
LUMI lumi.weather Identifybutton became unavailable
5:06:14 PM - Yesterday
LUMI lumi.weather Zha Event was fired
5:06:14 PM - Yesterday

</details>

**Additional context**

**Comment by MattWestb** [comment]
I have one IKEA CWS1 600 Lm (first gen) and its working very good with my Aqara weather on  the balcony for 3 years.
Most of my lumi weather is connected thru IKEA 2 gen devises like the outlet and is working well.

I have some 3 gen IKEA lights and they is having not so good radio performance  as first and 2 gen devices (Silabs have putting the TX power down in the module) and some is the antenna very bad places (up side down and is shielded of the metal in the socket) and can being tricky getting good radio performance.

How hi / low is your LIQ on the link between the routers and also the link the end device is having to its parent ?

My production network is one device having 96 i LIQ and all the other is having 116 or higher and is normally very stable only my Philips HUE motion sensors is "jumping around".

**Comment by monsieurhannes** [comment]
I also have problems with my aqara "weather" sensor `lumi.weather`, having the sensor just 1m from a `TRADFRI bulb E27 WW 806lm by IKEA of Sweden`  and another one roughly 1m from **6** `TRADFRIbulbE14WScandleopal470lm` - though that's through a wooden floor up to the attic.
They work just fine when I connect them. But after a couple of status updates they become unresponsive.
My network looks like this, I'd say it's not too crowded, but who knows what the limit is... I use a ConBee II and the two circles on the left are the aqara sensors.
![image](https://user-images.githubusercontent.com/20651440/198384281-12aa4778-f42a-437e-90ce-3cbeb43e204b.png)

I have one aqara TVOC sensor which has no problem staying connected.

**Comment by dmulcahey** [comment]
These work fine when the parents don't drop them. This is a widely known issue w/ older aquaria devices and there is nothing that any integration can do to prevent this. This is purely caused by the mix of devices you have on your network. See this discussion for more details: https://community.smartthings.com/t/original-aqara-xiaomi-zigbee-sensors-contact-temp-motion-button-outlet-leak-etc/113253

**Comment by monsieurhannes** [comment]
Thanks for the reply. I’ll try to hard-bind them to the coordinator so they don’t lose connection 👍
