### ISSUE TITLE
[Device Support Request] Support EVOLVEO Heat M30v2 TRV

### ISSUE THREAD

**Issue by zbeky** [zigpy/zha-device-handlers#1798]
**Is your feature request related to a problem? Please describe.**
Hello, I have bought a new set of EVOLVEO Heat M30v2 TRVs - https://eshop.evolveo.com/evolveo-heat-m30--smart-thermostatic-radiator-valve-2/
They look like rebrand of MOES HY368-ZB. They are currently not supported by ZHA due to different `manufacturer_code` `_TZE200_8whxpsiw`

**Describe the solution you'd like**
I've added its manufacturer_code to the ts0601_trv.py quirk to class MoesHY368_Type1 and after re-pairing it started to show its  entities in HA.
To be able to select presets in HA I had to also update ZHA/climate.py by adding the TRVs manufacturer_code to match MoesThermostat class.

This is tested as fully working. Unfortunately I have little to no experience with Git so I'm a bit afraid to do the PR myself. Would someone be so kind and helped me with it please? Thanks in advance.

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0301",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0201",
        "0x0204",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_8whxpsiw",
  "model": "TS0601",
  "class": "ts0601_trv.MoesHY368_Type1"
}
```

</details>

**Additional context**

**Comment by MattWestb** [comment]
Start with clicking on the editing symbol in the git on the file you like editing.
GIT is doing one copy in yoor git that you can doing all the changes you like.
Then you is finished do one pull request from you git and git is making one PR in the "original" git.

Start with the quirk its easier and then its OK make the pull in ZHA that is more tricky then its have more test and things.

If you getting problems asking and we is helping you.

I adding the new CN-Hysen HY368-ZB clone TRV in our tuya TRV matrix and suppoeted.
