### ISSUE TITLE
Cannot control a Zigbee device when network is down

### ISSUE THREAD

**Issue by andrekosak** [zigpy/zha-device-handlers#1923]
**Describe the bug**
Given hardware: a raspberry Pi with RaspBee II adapter configured with ZHA, Home Assistant 2022.11.2 installed on it.
Script that worked before: Turn off an outlet connected to the network router, wait 2 seconds, turn on the outlet.
Problem: The outlet goes off but never goes on.

**Additional context**
It worked well in one on previous HA releases (at leas in 2022.9.X)

**Comment by puddly** [comment]
ZHA has no dependency on the internet. Can you capture a debug log? https://www.home-assistant.io/integrations/zha/#debug-logging
