### ISSUE TITLE
Aqara Lumi EU smart plug in ZHA power consumption always zero

### ISSUE THREAD

**Issue by Zandstrom** [zigpy/zha-device-handlers#1994]
The plug it self is working ON/OFF and i see the values for power consumption, but its always zero. Ive read that the “custom quirk” is now included with Home Assistant Core 2022.10.5 (and later) but i have version 2022.12.0 and it still always show zero, like this.

![image](https://user-images.githubusercontent.com/32096337/206376269-394f8523-4c9b-48f5-b3b5-f38dc76f5957.png)

If i try to reconfigure it says everything is working.
![image](https://user-images.githubusercontent.com/32096337/206376519-cea28d07-0c59-4383-a602-17e7db83e64e.png)

The signature looks like this 
`{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4447, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0002",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0009",
        "0x0702",
        "0x0b04",
        "0xfcc0"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "21": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x000c"
      ],
      "out_clusters": []
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.plug.maeu01",
  "class": "zhaquirks.xiaomi.aqara.plug_eu.PlugMAEU01"
}`

Am i missing something? What i can read on the forums this should already be fixed? 
@TheJulianJES

**Comment by TheJulianJES** [comment]
What Zigbee coordinator are you using?
You need to update firmware on Conbee/Raspbee coordinators and on Z-Stack coordinators to a somewhat recent version and then re-pair the plug.

**Comment by Zandstrom** [comment]
> What Zigbee coordinator are you using? You need to update firmware on Conbee/Raspbee coordinators and on Z-Stack coordinators to a somewhat recent version and then re-pair the plug.

Im using a Sonoff Zigbee 3.0 USB Dongle Plus. Can you point me in the right directions on how to check and update the firmware?

**Comment by IvanVojtko** [comment]
I have the same issue, same HA version 2022.12.0 and same Lumi plug firmware version. Tried to repair multiple times, can control the plug but all values are 0.
