### ISSUE TITLE
Add support for ecozy smart thermostat valves

### ISSUE THREAD

**Issue by nerdosity** [zigpy/zha-device-handlers#200]
Hi, I have got 3 of them. How can I help with support?Those were supported in zigbee2mqtt:

https://www.zigbee2mqtt.io/devices/1TST-EU.html
https://github.com/Koenkk/zigbee-herdsman-converters/tree/master/converters

**Comment by dmulcahey** [comment]
Climate still isn’t in ZHA yet. Should be soonish... hopefully...

**Comment by Hedda** [comment]
FYI, Adminiuga has now submitted a pull request for "ZHA Climate" (beta) with thermostats support.
