### ISSUE TITLE
Is IKEA TRADFRI transformer 30w supported?

### ISSUE THREAD

**Issue by nerdosity** [zigpy/zha-device-handlers#201]
Hi, I am desperately trying to pair an IKEA 30w power supply.
Zigate with latest firmware, latest home assistant.
It was working (ON/OFF / DIM) when I was using Zigate lib, but I prefer to start migrating toward ZHA.
Now it's not pairing anymore.
I tried at least 20 times, I have paired more distant devices without hassle, but this one is not pairing at all.
It's just my problem? Can I provide some log? Regards.

**Comment by Adminiuga** [comment]
This should belong to https://github.com/doudz/zigpy-zigate move this issue there and provide debug logs
