### ISSUE TITLE
Wrong IKEA Tradfri E14 WS Opal 400lm configuration

### ISSUE THREAD

**Issue by nerdosity** [zigpy/zha-device-handlers#202]
The variable supported_features after pairing the light is set as 51 (RGB picker, dimmable, tunable white).
Should be 43 (dimmable, tunable white).

With 43 is good as seen in next image.
![image](https://user-images.githubusercontent.com/26657281/69825049-26eb0500-120e-11ea-9b5d-50782e23e1ff.png)

**Comment by dmulcahey** [comment]
There isn’t a quirk for this which would mean the bulb is reporting this on its own.

**Comment by nerdosity** [comment]
Well then should be very similar to this one, right?
https://github.com/dmulcahey/zha-device-handlers/blob/dev/zhaquirks/osram/a19twhite.py

**Comment by dmulcahey** [comment]
Not following what you mean?

**Comment by nerdosity** [comment]
Ok sorry I'm not expert, I just searched for a simple tunable white bulb, I thought it would be a good starting point for me to try. 
I would like to help, I have access to a CC2531 flashable with sniffer firmware, a zigate and tons of ZigBee devices (battery powered and mains).
Please let me know what I can provide.

**Comment by dmulcahey** [comment]
Remove and re-join it with zha and paste the content of the add devices screen logs in a code block here. Then I’ll help you make a quirk.

**Comment by dmulcahey** [comment]
We’ll probably have to do something like this: https://github.com/dmulcahey/zha-device-handlers/pull/182/files to override the value the bulb returns.
