### ISSUE TITLE
tuya naming of Switch MCU command cluster

### ISSUE THREAD

**Issue by MattWestb** [zigpy/zha-device-handlers#2070]
I dont like the naming of this cluster class:
https://github.com/zigpy/zha-device-handlers/blob/22968954cacaff4fc2b00e02ca1bd5622f637393/zhaquirks/tuya/mcu/__init__.py#L464
Its being used of tuya MCU switches that is sending DP commands instead of ZCL commands / attributes.
Its coming more devices that is using it and also some hybrid devices that is using ZCL cluster plus this function for setting some tuya things.

Adding this cluster in quirks is very strange then the naming is not logical for my.
I think better renaming it to "tuyaMCUSwitchManufCluster" or somthing likely that and taking the  brand name "MOES" and better describing the function.

Then the class is linked in more then 6 levels and all is having test its over my limited code knowledge i cant doing the changes without braking test and other linked code.

@javicalle I think i need help if doing the changes and also feedback for doing it right and also the coding.

Its not one high priority thing but longer waiting doing "housekeeping" its being more problematic doing the changes.

Thanks in advance.

**Comment by javicalle** [comment]
I'm trying to clear up my backlog tasks. Give me some time and ping me again to review it.
