### ISSUE TITLE
[BUG] OSRAM Switch-LIGHTIFY sends broadcast and turns on/off all devices

### ISSUE THREAD

**Issue by floriandotorg** [zigpy/zha-device-handlers#2076]
**Describe the bug**
The OSRAM Switch-LIGHTIFY sends a broadcast messages to all ZigBee devices to turn them on/off when pressing the arrow down or up button.

**To Reproduce**
1. Connect OSRAM Switch-LIGHTIFY to ZHA 
(https://zigbee.blakadder.com/OSRAM_AC0251x00NJ.html)
3. Not setting up any automations
4. Press up or down arrow button
5. All ZigBee switches/lights etc. turn on or off

**Expected behavior**
Nothing happens because no automations are set up.

**Additional context**
The problem is further described here: https://github.com/zigpy/zha-device-handlers/issues/324

It appears that the switch is factory configured to send ZigBee broadcast messages. Only when using it with the OSRAM app, it can be reconfigured to not do so.

zigbee2mqtt has apparently fixed this by reconfiguring the switch on initial connect:
https://github.com/Koenkk/zigbee2mqtt/issues/962

It would be spectacular if someone could implant that fix into ZHA cause the switch is unusable and outright dangerous in some scenarios like this.

Thank you very much for the great work ❤️
Florian

**Comment by TheJulianJES** [comment]
Like mentioned in the other issue, please fill-out the issue template.

Diagnostic information and the device signature are still missing. Diagnostic information can be downloaded by clicking the "Download Diagnostics" button on the device config page of the OSRAM switch (three small dots).
There, you'll also find the device signature under "Manage Zigbee device" -> "Device signature" tab

**Comment by floriandotorg** [comment]
Hey Julian, thanks for your reply! Which issue template? I filled out the template for bugs.

Anyway, please find attached the device signature:

```JSON
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4364, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=0, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0810",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0020",
        "0x1000",
        "0xfd00"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0019",
        "0x0300",
        "0x1000"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0810",
      "in_clusters": [
        "0x0000",
        "0x1000",
        "0xfd00"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0300",
        "0x1000"
      ]
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x0810",
      "in_clusters": [
        "0x0000",
        "0x1000",
        "0xfd00"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0300",
        "0x1000"
      ]
    }
  },
  "manufacturer": "OSRAM",
  "model": "Lightify Switch Mini",
  "class": "zhaquirks.osram.switchmini.OsramSwitchMini"
}
``` 

And the diagnostic information:

```JSON
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.1.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "5.15.76-v8",
    "supervisor": "2022.12.1",
    "host_os": "Home Assistant OS 9.4",
    "docker_version": "20.10.19",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {},
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "config_flow": true,
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "requirements": [
      "bellows==0.34.5",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.90",
      "zigpy-deconz==0.19.2",
      "zigpy==0.52.3",
      "zigpy-xbee==0.16.2",
      "zigpy-zigate==0.10.3",
      "zigpy-znp==0.9.2"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "dependencies": [
      "file_upload"
    ],
    "after_dependencies": [
      "onboarding",
      "usb",
      "zeroconf"
    ],
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 49194,
    "manufacturer": "OSRAM",
    "model": "Lightify Switch Mini",
    "name": "OSRAM Lightify Switch Mini",
    "quirk_applied": true,
    "quirk_class": "zhaquirks.osram.switchmini.OsramSwitchMini",
    "manufacturer_code": 4364,
    "power_source": "Battery or Unknown",
    "lqi": 48,
    "rssi": null,
    "last_seen": "2023-01-09T11:02:41",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4364, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=0, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0810",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0020",
            "0x1000",
            "0xfd00"
          ],
          "out_clusters": [
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x0019",
            "0x0300",
            "0x1000"
          ]
        },
        "2": {
          "profile_id": 260,
          "device_type": "0x0810",
          "in_clusters": [
            "0x0000",
            "0x1000",
            "0xfd00"
          ],
          "out_clusters": [
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x0300",
            "0x1000"
          ]
        },
        "3": {
          "profile_id": 260,
          "device_type": "0x0810",
          "in_clusters": [
            "0x0000",
            "0x1000",
            "0xfd00"
          ],
          "out_clusters": [
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x0300",
            "0x1000"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "sensor.osram_lightify_switch_mini_battery",
        "name": "OSRAM Lightify Switch Mini"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "COLOR_SCENE_CONTROLLER"
      },
      {
        "name": "COLOR_SCENE_CONTROLLER"
      },
      {
        "name": "COLOR_SCENE_CONTROLLER"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "6e6f4367637293d5dab241a5bd99552c",
    "area_id": "wohnzimmer",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "COLOR_SCENE_CONTROLLER",
          "id": 2064
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "OSRAM"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "Lightify Switch Mini"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 31
              }
            },
            "unsupported_attributes": {
              "0x0021": {
                "attribute_name": "battery_percentage_remaining"
              },
              "0x0033": {
                "attribute_name": "battery_quantity"
              },
              "0x0031": {
                "attribute_name": "battery_size"
              }
            }
          },
          "0x0020": {
            "endpoint_attribute": "poll_control",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xfd00": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0300": {
            "endpoint_attribute": "light_color",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "2": {
        "device_type": {
          "name": "COLOR_SCENE_CONTROLLER",
          "id": 2064
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xfd00": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0300": {
            "endpoint_attribute": "light_color",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "3": {
        "device_type": {
          "name": "COLOR_SCENE_CONTROLLER",
          "id": 2064
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xfd00": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0300": {
            "endpoint_attribute": "light_color",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

If you need any other information, please let me know :-)

**Comment by MattWestb** [comment]
Your Zigbee controller is one light controlling device that sending light commands to devices / groups that is bond to it.
If you have not putting your lights in one new group is it very likely that they is suing the `Default Lightlink Group` with Group Id: `0x0000`.
And your controller (and most lights) is using that as default if you not have changing the binding of it.
You can making one new group and putting all you light in and deleting them after after adding them to group `0x0000`.
Or you can deleting the binding of your light controller and binding it to one new group or the coordinator (its depends what the device can do group or device binding). If not have bond the controller its not sending any command to the coordinator so you need finding how to do it right.

**Comment by TheJulianJES** [comment]
> Which issue template? I filled out the template for bugs.

All good now. (The issue template asks for diagnostic information and the signature)

From what MattWestb wrote, try the following:

Go to the device page -> three dots -> Manage Zigbee device (same place where you grabbed the signature)
Select the "Bindings" tab at the top. Then you have two things to try:
1. Select your Zigbee coordinator in the first dropdown menu and click unbind. Directly after having pressed unbind, press some buttons on the remote to make sure it wakes up. (You can repeat this a couple of times to be sure the remote received the command) (then see if the issue is resolved)
2. Select the name of your 0x0000 group. It should be "Default LightLink Group" or "No name group 0x0000".
Then, select all checkboxes and click "unbind group". Press some buttons on the remote directly after that (you can also repeat this multiple times). (see if this resolves the issue)

**Comment by floriandotorg** [comment]
Hey @MattWestb and @TheJulianJES, thank you both so much for your support, I appreciated it!

I tried both:

1. The unbind button just shows the loading spinner forever. I tried ~20 times. I moved close to the Zigbee stick, I pressed buttons before and/or after, but same, it just loads forever. The problem is still there.
<img width="589" alt="CleanShot 2023-01-09 at 17 09 34@2x" src="https://user-images.githubusercontent.com/6143734/211354287-b53bec22-a4aa-460c-a464-786f669d6bf1.png">
2. The group (in fact no groups) are in the dropdown:
![CleanShot 2023-01-09 at 17 10 10@2x](https://user-images.githubusercontent.com/6143734/211355089-b345c478-56d5-4c2d-bb41-3003b4c38cdb.png)
I also looked under Configure > Groups, but same here no groups found, also no default group:
<img width="619" alt="CleanShot 2023-01-09 at 17 10 24@2x" src="https://user-images.githubusercontent.com/6143734/211354486-ebd34bec-8ecb-4351-a367-9ae8e431c6a9.png">

**Comment by MattWestb** [comment]
If i remember right is spooky with the binding of this remotes and its looks you cant getting it unbound.

Then trying the Zigbee groups way.
First make one new group for your devices (then is normally having 0x0000 as factory and is not sett in ZHA so you dont see it) and adding then to the new group.
From the` Manage Zigbee Device` (as you was doing the binding) select the group cluster (0X0004) and then command remove (0x0003) for the device and "issue zigbee command".
You can also trying remove all but then you need adding  the new group or you is not getting any status from the device in ZHA.

**Comment by floriandotorg** [comment]
Hey @MattWestb, thank you so much for your explanation!

So, I've added a group and added all devices:
![CleanShot 2023-01-09 at 19 45 46](https://user-images.githubusercontent.com/6143734/211384230-4724036f-5da0-473b-9539-e67fa5a84cae.png)

Next, I tried to remove one of the switches from the default group:
![CleanShot 2023-01-09 at 19 46 34](https://user-images.githubusercontent.com/6143734/211384341-baecfffe-61cc-46b4-a226-1ebb754a59cb.png)

But I got an error: `Failed to issue cluster command with status: 0x0000`
![CleanShot 2023-01-09 at 19 44 13](https://user-images.githubusercontent.com/6143734/211384411-5f230ee2-6b1c-4c05-be84-516270200ee8.png)

I then used remove_all and that worked. Then I tried to use add:
![CleanShot 2023-01-09 at 19 47 44](https://user-images.githubusercontent.com/6143734/211384596-7b96b1f7-a82a-4640-bbff-97b01768e84a.png)

But it also failed: `Failed to issue cluster command with status: 0x0002`

Now I indeed get no status from the switch in ZHA anymore 😬
(also attempted to remove the switch from the Default group and add it again in ZHA, but no change)

Oh, and also the switch is still switching this switch ..

Any way to solve this? Guess this is what you call a cluster bug!

And again thanks for the help, I really appreciate it.

**Comment by MattWestb** [comment]
I dont have OSRAM devices then they is not my taste then it come to function (or luck / crappy one).

Zigbee lights is normally controlled by groups and you can adding and deleting them by cluster commands.

Zigbee light controllers (your remote) shall being bonded to one group and sending command to it.

Many controllers have strange behaviors like must deleting binding before adding then dont have enough space for adding the coordinator (Philips HUE).
Also tuya is adding groups to remotes as lights (not binding) = very wrong.

I cant helping you fixing it then i dont knowing the device bu you can trying different combinations and you is very likely fixing it with little try and error.

Also search in community forum then i remember it was some strange with  the OSRAMs remotes but i cant remember where i have reading it.
If cant fixing the switch then you must "move" all lights to one new group and deleting the group `0x0000` in them so they not listening to it.

Z2M is not having any binding in there device wiki or it so very likely it cant being bonded to one custom group.

**Comment by floriandotorg** [comment]
Thanks for all the help @MattWestb. I had to give up in the end, learning: no OSRAM ;)

**Comment by MattWestb** [comment]
My feeling is that they have used old hardware with week radio and many hard and software bugs so i have kept away from them and is not having so many strange problem also trying getting real Zigbee 3 devices that can using the network futures like end device can keeping contact with there parents better.

Hope your future Zigbee adventure is working well !!

**Comment by 1doubleDD1** [comment]
This is probably too late for anyone here, but...
Today I encountered this problem as I switched from deConz to ZHA. So my Osram switches started "misbehaving" meaning turning random devices on or off when button is pressed. I solved it by first deleting the default group (as also suggested in one of the previous posts), then deleting the device from ZHA, then resetting the device, and re-adding to ZHA. Now pressing buttons doesn't trigger anything, and I use zha_event connected to each button for triggering what I want.
Maybe it will help someone down the line, if anyone still uses Osram. :)

**Comment by aaronegger** [comment]
@1doubleDD1 Sadly this has not fixed it for me.. I removed every group, not only the default group, but i even before zha shows the dialog with "Interview" the switch turns on/off all devices. All i can do is to send the switches back to amazon..

**Comment by 1doubleDD1** [comment]
@aaronegger  Did you try also unbinding from the "Manage Zigbee device" menu? I did it several times in a row; unbinding, deleting group, deleting the device from ZHA, then resetting the device; then back from the start.

I have a couple of Osram switches; yes, they are quite fiddly to initially set up, but afterwards I've had absolutely no issues with them whatsoever. Unfortunately might have to play with them again as I'm rethinking migration to ZHA, deConz was so much more stabile.

**Comment by aaronegger** [comment]
@1doubleDD1 I did that. It finally worked. But for testing purposes i tried the function to bind it directly to a device.
Not the group, but a device, as i suspected it will bind to any device not only groups. Binding the switch to a single device worked, but unbinding did not work. Therefore i think the whole product is faulty and bad designed and therefore not reliable usable.
I will try one more time to get them working reliably and if i don't find any solution i will send them back. Very sad as they had the perfect size i needed. I need a narrow button to attach them to a hose of an vaccum cleaner (with 3d printed holders) and there is nothing except loratap that offers such devices.
The Osram device was perfect, als it has a dustproof design.

**Comment by 1doubleDD1** [comment]
@aaronegger Not sure that I completely follow your last message, but why do you need it to be binded to a device? Once it's behaving properly, meaning it's not switching off all devices, I use it via events in automations, and it works perfectly. Each of their buttons typically has 3 events per "pressing position" (?): short click, long press, and release after long press. You can check produced events in the Events tab of Developer options.

Example of my trigger in one automation (not sure which one you use):
ZHA

```typescript
platform: event
event_type: zha_event
event_data:
  unique_id: 00:0d:6f:00:0d:9f:62:ec:1:0x0006
``` 

DECONZ:

```typescript
platform: event
event_type: deconz_event
event_data:
  id: switch_name
  event: 1002
```

**Comment by aaronegger** [comment]
@1doubleDD1 No i don't need i bound to a specific device. I just wanted to test if i would be able to unbind the switch, if it for example binds itself.

I think i will never bind any device to any device, as i want to be able to control what happens on an event and not let the device decide what button will do.

I only have some trust issues. I don't trust the switch to work properly in the future.

**Comment by 1doubleDD1** [comment]
@aaronegger I can only speak from my experience. I have 3 Osram switches, for about 6+years now. They were initially used in Osram system, then HA+deConz, and now HA+ZHA. Once properly paired and unbined, I've never had any issues with them. They are even still on their original batteries, not that it means much. I'm perfectly happy with them, their size and functionality.
