### ISSUE TITLE
[BUG] TS0502A _TZ3000_oh7jddmx changes brightness not color temp

### ISSUE THREAD

**Issue by erazorv** [zigpy/zha-device-handlers#2087]
Hello all,
when I change the color temperature it always changes the brightness and not from warm white to cool white. 

TS0502A
_TZ3000_oh7jddmx

zigbee2mqtt: 1.29.1

**Comment by MattWestb** [comment]
As its looks like you is using Z2M and not ZHA i think its better putting the issue in this git https://github.com/Koenkk/zigbee2mqtt.

**Comment by erazorv** [comment]
upps sorry
