### ISSUE TITLE
[Device Support Request] TS0601 _TZE200_qyflbnbj Tuya outdoor temperature and humidity sensor

### ISSUE THREAD

**Issue by m0nty81** [zigpy/zha-device-handlers#2113]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Sensor connection

<details>

<summary>Device signature</summary>

```yaml
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_qyflbnbj",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
Paste the diagnostic information here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>
<summary>Additional logs</summary>

```
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00u\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00v\x02\x02\x00\x04\x00\x00\x00Z'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00w\x03\x04\x00\x01\x02'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00x\x04\x02\x00\x04\x00\x00\x00Z'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00y\x01\x02\x00\x04\x00\x00\x00\x00'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00z\x02\x02\x00\x04\x00\x00\x00Z'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00{\x03\x04\x00\x01\x02'
[0xC241:1:0xef00] Unknown cluster command 1 b'\x00|\x04\x02\x00\x04\x00\x00\x00Z'
[0xC241:1:0xef00] Unknown cluster command 36 b'\x0c\x1b'
```

</details>

**Additional context**

**Comment by javicalle** [comment]
More info from the device will be helpfull (vendor link, device capabilities, ...)

According to Z2M this device can be added to the `TuyaTempHumiditySensor` quirk.
Enable the local quirk folder and copy the current `ts0601_sensor.py` file:
* https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601_sensor.py

Edit the file and add your device at the `TuyaTempHumiditySensor` class:
```python
class TuyaTempHumiditySensor(CustomDevice):
    """Custom device representing tuya temp and humidity sensor with e-ink screen."""

    # RelativeHumidity multiplier
    RH_MULTIPLIER = 10

    signature = {
        # <SimpleDescriptor endpoint=1, profile=260, device_type=81
        # device_version=1
        # input_clusters=[4, 5, 61184, 0]
        # output_clusters=[25, 10]>
        MODELS_INFO: [
            ("_TZE200_bjawzodf", "TS0601"),
            ("_TZE200_qyflbnbj", "TS0601"),
        ],

```

Save changes, restart HA and re pair the device.

**Comment by m0nty81** [comment]
Works perfect for me!
Without reconnection.
Thank you so much.

Aubess/Tuya zigbee temperature/hummidity meter with external wired outdoor sensor
Bought here: https://aliexpress.ru/item/1005004212085690.html?spm=a2g2w.orderdetail.0.0.42eb4aa63PnaIl&sku_id=12000028396389027&gatewayAdapt=glo2rus
![IMG_6973](https://user-images.githubusercontent.com/13285846/213427419-45dce533-4302-460d-9b04-aa1a4c4de407.jpg)
<img width="1012" alt="Снимок экрана 2023-01-19 в 14 16 14" src="https://user-images.githubusercontent.com/13285846/213428889-bf5f25c2-e856-4e1a-9a4c-97dccc4d8c94.png">

**Comment by javicalle** [comment]
Do you mind to create the PR for your device?
You can edit the file right from the web browser and follow the indications.

Thanks in advance.

**Comment by javicalle** [comment]
> But i change RH_MULTIPLIER = 10 to RH_MULTIPLIER = 100

If it is the case, then put your device in the `TuyaTempHumiditySensorVar03` class. Just as you have done in the other class.

**Comment by m0nty81** [comment]
> Just one step more: When you go to your github fork you will see a banner offering to create a PR for your change.
> 
> Push the banner and fill the form. That's all.

i hope i did it
PR: https://github.com/zigpy/zha-device-handlers/pull/2118
but not all checks passed...

**Comment by MattWestb** [comment]
Black is not happy and need one small fix.
https://github.com/zigpy/zha-device-handlers/pull/2118#issuecomment-1398091663

**Comment by javicalle** [comment]
I'm sorry that finally you can't finish the PR.
I really appreciate your efforts.

**Comment by m0nty81** [comment]
Problems with negative values of temperature ((
<img width="573" alt="Снимок экрана 2023-01-21 в 15 40 15" src="https://user-images.githubusercontent.com/13285846/213867245-7619b02d-bd25-4cae-87b0-5b7a846cc6aa.png">
<img width="1409" alt="Снимок экрана 2023-01-21 в 15 38 57" src="https://user-images.githubusercontent.com/13285846/213867250-f0b86973-c046-4de5-b2bb-a9e4d515e1bd.png">

**Comment by javicalle** [comment]
Ummm, I believe that has been already reported but I don't remember how it was fixed (or if it was fixed).
Please enable debug logging and attach some reading of the negative values.

**Comment by javicalle** [comment]
Already discussed in #1976

We're going to need a little help here.

The current quirk is mapping the DP1 value to the `TuyaTemperatureMeasurement` with a `lambda x: x * 10` converter:
https://github.com/zigpy/zha-device-handlers/blob/a16c153131afffdcdcae711e1695575d8267d703/zhaquirks/tuya/ts0601_sensor.py#L47-L52

The `TuyaTemperatureMeasurement` is just a 'local' wrapper for the `TemperatureMeasurement` cluster:
https://github.com/zigpy/zha-device-handlers/blob/a16c153131afffdcdcae711e1695575d8267d703/zhaquirks/tuya/ts0601_sensor.py#L23-L25

From what I can see, the `measured_value` is a 16bits signed value (and is what we need):
https://github.com/zigpy/zigpy/blob/297a2b0f364fe7a31de3b4966d70d1a67d432358/zigpy/zcl/clusters/measurement.py#L72-L81

At this point I can go any further. I can't see how the quirk is broking the values or how to fix it.

**Comment by javicalle** [comment]
@m0nty81 can you check what values are show in HA if you disables the quirk?
I want to check if the problem is in the quirk manipulation.

**Comment by TheJulianJES** [comment]
Huh, a 16 bit signed integer shouldn't even go near ``42949672660``.
At the moment, zigpy does not check if the value is valid for the specified data type when writing "fake attributes" to a cluster. (A conversion is tried when reading the attribute through the clusters UI though)

From a quick glance, it seems like the issue could be here (**unsigned** 32 bit integer (and I guess the deserialization fails for negative values causing an overflow)):
https://github.com/zigpy/zha-device-handlers/blob/a16c153131afffdcdcae711e1695575d8267d703/zhaquirks/tuya/__init__.py#L190-L191

cc @puddly (not important but maybe worth reading this)
It seems to be a similar thing with the "non-rounded values" of the Aqara plug quirk recently.

However, as I see it here, the quirk provides way too big of a value (overflowed int due to deserializing as a unsigned 32 bit int) for the specified data type (signed 16 bit int), but then it also looks like that reading the value through the clusters UI doesn't "cap" the value to the max value for the appropriate data type (seen in the picture) but perhaps this is expected if the conversion fails?

**Comment by m0nty81** [comment]
> @m0nty81 can you check what values are show in HA if you disables the quirk? I want to check if the problem is in the quirk manipulation.

Cluster settings crashes and i can't read the temperature value when i turned off quirk (cluster 0x0402, attr 0x0000)

quirk on:
<img width="569" alt="Снимок экрана 2023-01-21 в 22 39 44" src="https://user-images.githubusercontent.com/13285846/213884368-c514e62d-cc83-4972-9c5f-d5d69a62ea96.png">

quirk off:
<img width="569" alt="Снимок экрана 2023-01-21 в 22 35 46" src="https://user-images.githubusercontent.com/13285846/213884379-adc5d2a0-eb10-4463-8e19-ae9e10fc940f.png">

**Comment by javicalle** [comment]
> Cluster settings crashes and i can't read the temperature value when i turned off quirk (cluster 0x0402, attr 0x0000)

Of course 🤦🏻‍♂️ 
No quirk, no temp

**Comment by MattWestb** [comment]
Enable more debug and look how the package received looks and encoding it.
Can bin done with the last quirk active so can see what is doing.

**Comment by javicalle** [comment]
@m0nty81 please enable the debug logs (with the quirk enabled 😅) and attach a few value readings.
I want to use the raw data to made some tests.

**Comment by m0nty81** [comment]
> @m0nty81 please enable the debug logs (with the quirk enabled 😅) and attach a few value readings. I want to use the raw data to made some tests.

it seems that problems start from line 63
[home-assistant_zha_2023-01-22T08-45-31.031Z.log](https://github.com/zigpy/zha-device-handlers/files/10474029/home-assistant_zha_2023-01-22T08-45-31.031Z.log)

**Comment by javicalle** [comment]
Ok, it seems to be a question of negative value representation. Any expert in the room?
I'm going to check if there's a 'two's complement' type in zigpy and then figure out a way to fix the issue.
I don't know if it is an issue just for these devices or generic for the MCU Tuya devices.

**Comment by javicalle** [comment]
Ok, I think I have something.
In my tests it seems that I have fixed it, but it may be based on erroneous data.
At least the current tests don't fail after the change, but that doesn't guarantee that there are no other problems.

I have updated that part:
https://github.com/zigpy/zha-device-handlers/blob/a16c153131afffdcdcae711e1695575d8267d703/zhaquirks/tuya/__init__.py#L209-L213

The updated code is this:
```python
    @payload.setter
    def payload(self, value):
        """Set payload accordingly to data point type."""
        if self.dp_type == TuyaDPType.VALUE:
            self.raw = t.int32s_be(value).serialize()
```

To test the changes, you have to copy the current `__init__.py` and the `ts0601_sensor.py` files.
At the `ts0601_sensor.py` the `from zhaquirks.tuya import` must be replaced like:
```python
from custom_zha_quirks import TuyaLocalCluster, TuyaPowerConfigurationCluster2AAA
```

@Shulyaka, sorry to ping to you directly. Do you mind to take a look at the proposed change?

**Comment by MattWestb** [comment]
Or editing **the** line in the INIT in the HA container but do one copy of the original before start editing and dont need changing all imports in the quirk.
Fast guide editing files in the HA container https://github.com/zigpy/zha-device-handlers/discussions/693#discussion-1237451

**Comment by Shulyaka** [comment]
> @Shulyaka, sorry to ping to you directly. Do you mind to take a look at the proposed change?

So you are changing the unsigned type to signed? I think you are right.

One issue though. We need to bump the minimal zigpy version to 0.53. Currently in setup.py it is 0.52, but t.int32s_be was only introduced in 0.53

**Comment by m0nty81** [comment]
> 

Copy modified __init__.py and ts0601_sensor.py to /config/custom_zha_quirks/ or __init__.py to /usr/local/lib/python3.10/site-packages/zigpy/zcl/ (i see this path in the logs) ?

**Comment by javicalle** [comment]
Both files to the `/config/custom_zha_quirks/` folder.

**Comment by m0nty81** [comment]
> Both files to the `/config/custom_zha_quirks/` folder.

Without changes (
Wrong value again.
But confuses another path in log `/usr/local/lib/python3.10/site-packages/zigpy/zcl/__init__.py`
[home-assistant_zha_2023-01-23T14-22-19.201Z.log](https://github.com/zigpy/zha-device-handlers/files/10480596/home-assistant_zha_2023-01-23T14-22-19.201Z.log)

**Comment by javicalle** [comment]
No, there is no need to modify the `zcl/__init__.py` file.
There are 2 more references to `uint32_t_be` in the file (lines 180 and 191). Replace it with `t.int32s_be`

https://github.com/zigpy/zha-device-handlers/blob/a16c153131afffdcdcae711e1695575d8267d703/zhaquirks/tuya/__init__.py#L176-L191

Save changes, delete any `__pycache__` folder in your local quirk folder and restart HA.

**Comment by javicalle** [comment]
> But now it doesn't work `TS0201`.

What isn't working? Any related logs?
`TS0201` is not a MCU device, so didn't must be affected by the modifications.

Any error in HA startup?

**Comment by javicalle** [comment]
Ummmm, there must be other imports to modify... (all the mcu)
Let me check

**Comment by javicalle** [comment]
I have managed to get a test working with a testing frame and getting the expected value:
```python

def test_tuya_negative_value():
    """Test tuya "Value" datatype."""

    data = b"\x02\x00\x04\xff\xff\xff\xf8"
    extra = b"extra data"

    r, rest = TuyaData.deserialize(data + extra)
    assert rest == extra

    assert r.dp_type == 2
    assert r.raw == b"\xff\xff\xff\xf8"
    assert r.payload == -8
```

I have get it just replacing all the `t.uint32_t_be` for `t.int32s_be` in the `tuya/__init__.py` file.

The problem is that the required change has broken many of the existing tests, but IMHO there is something wrong with the tests.

This part is not clear to me and I may be wrong, but from what I have been able to understand from the data formats, the following values cannot be correct temperature values (correct=normal positive temperature values):
```
ZCL_TUYA_EHEAT_TEMPERATURE = b"\tp\x02\x00\x02\x18\x02\x00\x04\xff\xff\xff\xe3"
ZCL_TUYA_EHEAT_TARGET_TEMP = b"\t3\x01\x03\x05\x10\x02\x00\x04\xff\xff\xff\xe3"
```

This values complains in the tests:
```
        if not cls.min_value <= n <= cls.max_value:
>           raise ValueError(
                f"{int(n)} is not an {'un' if not cls._signed else ''}signed"
                f" {cls._bits} bit integer"
            )
E           ValueError: 429496726900 is not an signed 16 bit integer
```

```
>       assert thermostat_listener.attribute_updates[0][1] == 1790
E       assert 42949672670 == 1790
```


From here I have the doubt if it is an error, if the problem is that the value in the log messages is formatted 'badly' due to the implementation or the device actually formats the data in this way.

The problem is that I have no way to check if the new implementation doesn't break anything.

**Comment by Shulyaka** [comment]
According to the ZCL specs, the value for the LocalTemperature Attribute of Thermostat should be in range of -27315 (0x954d) to 32767, and 429496726900 is clearly outside that range.

The issue with negative values in ZCL_TUYA_EHEAT_TEMPERATURE fixture is completely different. It is because in MoesBHTManufCluster the attributes for MOESBHT_TARGET_TEMP_ATTR and MOESBHT_TEMPERATURE_ATTR use unsigned types.
https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601_electric_heating.py#L40
If you change t.uint32_t to t.int32s then it will work:
```
class MoesBHTManufCluster(TuyaManufClusterAttributes):
    """Manufacturer Specific Cluster of some electric heating thermostats."""

    attributes = {
        MOESBHT_TARGET_TEMP_ATTR: ("target_temperature", t.int32s, True),
        MOESBHT_TEMPERATURE_ATTR: ("temperature", t.int32s, True),
        MOESBHT_SCHEDULE_MODE_ATTR: ("schedule_mode", t.uint8_t, True),
        MOESBHT_MANUAL_MODE_ATTR: ("manual_mode", t.uint8_t, True),
        MOESBHT_ENABLED_ATTR: ("enabled", t.uint8_t, True),
        MOESBHT_RUNNING_MODE_ATTR: ("running_mode", t.uint8_t, True),
        MOESBHT_CHILD_LOCK_ATTR: ("child_lock", t.uint8_t, True),
    }
```

**Comment by Shulyaka** [comment]
@javicalle I think you uncovered a completely new issue which no one reported before because the quirk is usually used for the heater devices in houses which don't often experience negative temperatures :)

Are there any other tests failing?

**Comment by javicalle** [comment]
> I don't think this test is related to `TuyaTempHumiditySensorVar03`.

No, it isn't.
The point here is that the current MCU implementation don't support signed values (as detected in `TuyaTempHumiditySensorVar03`).
To fix it, I have replaced the implementation with `int32s_be` types.
But that change have broken several tests.

I don't think that there are diferents MCU implementations.

So I focus in the failling tests and the related test data seems extrange to me.


> Are there any other tests failing?

Yes, a few:
```
========================================================================================== short test summary info ==========================================================================================
FAILED tests/test_tuya.py::test_tuya_receive_attribute[TuyaTestDevice] - assert 4294967267 == 179
FAILED tests/test_tuya.py::test_siren_state_report[TuyaSiren] - assert 42949672670 == 1790
FAILED tests/test_tuya.py::test_zonnsmart_state_report[ZonnsmartTV01_ZG] - assert 42949672670 == 2110
FAILED tests/test_tuya.py::test_valve_state_report[SiterwellGS361_Type1] - assert 42949672670 == 1790
FAILED tests/test_tuya.py::test_moes[MoesHY368_Type1] - assert 42949672670 == 1790
FAILED tests/test_tuya.py::test_eheating_state_report[MoesBHT] - assert -290 == 1790
FAILED tests/test_tuya.py::test_eheat_send_attribute[MoesBHT] - AssertionError: expected call not found.
```

**Comment by javicalle** [comment]
All related to:

```
ZCL_TUYA_ATTRIBUTE_617_TO_179 = b"\tp\x02\x00\x02i\x02\x00\x04\xff\xff\xff\xe3"
ZCL_TUYA_SIREN_TEMPERATURE = ZCL_TUYA_ATTRIBUTE_617_TO_179
ZCL_TUYA_VALVE_ZONNSMART_TEMPERATURE = (
    b"\tp\x01\x00\x02\x18\x02\x00\x04\xff\xff\xff\xe3"
)
ZCL_TUYA_VALVE_ZONNSMART_TARGET_TEMP = (
    b"\t3\x01\x03\x05\x10\x02\x00\x04\xff\xff\xff\xe3"
)
ZCL_TUYA_VALVE_ZONNSMART_HOLIDAY_TEMP = (
    b"\t3\x01\x03\x05\x20\x02\x00\x04\xff\xff\xff\xe3"
)
ZCL_TUYA_VALVE_TEMPERATURE = b"\tp\x02\x00\x02\x03\x02\x00\x04\xff\xff\xff\xe3"
ZCL_TUYA_EHEAT_TEMPERATURE = b"\tp\x02\x00\x02\x18\x02\x00\x04\xff\xff\xff\xe3"
ZCL_TUYA_EHEAT_TARGET_TEMP = b"\t3\x01\x03\x05\x10\x02\x00\x04\xff\xff\xff\xe3"
```

All these `\x04\xff\xff\xff\xe3` seems extrange to be a 'normal' temperature. But I can be totally wrong in that matter.

**Comment by javicalle** [comment]
These are the 'updated' tests data to make it pass:
```
ZCL_TUYA_ATTRIBUTE_617_TO_179 = b"\tp\x02\x00\x02i\x02\x00\x04\x00\x00\x00\xb3"
ZCL_TUYA_VALVE_TEMPERATURE = b"\tp\x02\x00\x02\x03\x02\x00\x04\x00\x00\x00\xb3"
ZCL_TUYA_VALVE_ZONNSMART_TEMPERATURE = (
    b"\tp\x01\x00\x02\x18\x02\x00\x04\x00\x00\x00\xd3"
)
ZCL_TUYA_VALVE_ZONNSMART_TARGET_TEMP = (
    b"\t3\x01\x03\x05\x10\x02\x00\x04\x00\x00\x00\xcd"
)
ZCL_TUYA_VALVE_ZONNSMART_HOLIDAY_TEMP = (
    b"\t3\x01\x03\x05\x20\x02\x00\x04\x00\x00\x00\xaa"
)
ZCL_TUYA_EHEAT_TEMPERATURE = b"\tp\x02\x00\x02\x18\x02\x00\x04\x00\x00\x00\xb3"
ZCL_TUYA_EHEAT_TARGET_TEMP = b"\t3\x01\x03\x05\x10\x02\x00\x04\x00\x00\x00\x15"
```

Looking at the expected tests values (right equals side):
```
test_tuya_receive_attribute[TuyaTestDevice] - assert 4294967267 == 179
test_siren_state_report[TuyaSiren] - assert 42949672670 == 1790
test_zonnsmart_state_report[ZonnsmartTV01_ZG] - assert 42949672670 == 2110
test_valve_state_report[SiterwellGS361_Type1] - assert 42949672670 == 1790
test_moes[MoesHY368_Type1] - assert 42949672670 == 1790
test_eheating_state_report[MoesBHT] - assert -290 == 1790
test_eheat_send_attribute[MoesBHT] - AssertionError: expected call not found.
```
I can't understand how is possible to get it work with the previous values were all the data tests ended with `\x04\xff\xff\xff\xe3`

**Comment by Shulyaka** [comment]
I don't understand.
Aren't "\x04\x00\x00\x00\xb3" the current values? Not updated?

Also, if I just just change `t.uint32_t_be` into `t.int32s_be` it does not break any test.

**Comment by Shulyaka** [comment]
Check out draft here: #2175

**Comment by javicalle** [comment]
> Aren't "\x04\x00\x00\x00\xb3" the current values? Not updated?

Are the values that I need to replace to make happy the tests.



> if I just just change `t.uint32_t_be` into `t.int32s_be` it does not break any test.

🤔 
I have replaced it in 2 places:
```python
    @property
    def payload(
        self,
    ) -> Union[
        t.int32s_be,
        t.Bool,
        t.CharacterString,
        t.enum8,
        t.bitmap8,
        t.bitmap16,
        t.bitmap32,
        t.LVBytes,
    ]:
        """Payload accordingly to data point type."""
        if self.dp_type == TuyaDPType.VALUE:
            return t.int32s_be.deserialize(self.raw)[0]
        elif self.dp_type == TuyaDPType.BOOL:
            return t.Bool.deserialize(self.raw)[0]
```
and 
```python
    @payload.setter
    def payload(self, value):
        """Set payload accordingly to data point type."""
        if self.dp_type == TuyaDPType.VALUE:
            self.raw = t.int32s_be(value).serialize()
        elif self.dp_type == TuyaDPType.BOOL:
            self.raw = t.Bool(value).serialize()
```

That have fixed my 2 local tests:
```python
def test_negative_types():
    """Test tuya "Value" datatype."""

    raw = b"\xff\xff\xff\xe3"  # int32s.deserialize -469762049
    typed = t.int32s_be.deserialize(raw)

    assert typed[0] == -29
    

def test_tuya_negative_value():
    """Test tuya "Value" datatype."""

    data = b"\x02\x00\x04\xff\xff\xff\xf8"
    extra = b"extra data"

    r, rest = TuyaData.deserialize(data + extra)
    assert rest == extra

    assert r.dp_type == 2
    assert r.raw == b"\xff\xff\xff\xf8"
    assert r.payload == -8
```

But I also need to change all the commented data tests to pass all the tuya tests.

**Comment by javicalle** [comment]
Ummmm, I don't see the `tests/test_tuya.py` in the tests...
All my errors are in that file.

**Comment by Shulyaka** [comment]
The tests are failing for a completely different reason: the cluster attributes that are supposed to hold the temperature, are of unsigned type. Please see an example here: #2176

**Comment by javicalle** [comment]
Ahhhh, I see. 
Let me check.

**Comment by javicalle** [comment]
Wow, searching for 'temp' in the quirks it seems to be a few ones:
* https://github.com/zigpy/zha-device-handlers/blob/98b2c61e36052671f20119ca754a04f599b5ed92/zhaquirks/tuya/ts0201.py#L34-L44
* https://github.com/zigpy/zha-device-handlers/blob/98b2c61e36052671f20119ca754a04f599b5ed92/zhaquirks/tuya/ts0601_haozee.py#L99
* https://github.com/zigpy/zha-device-handlers/blob/98b2c61e36052671f20119ca754a04f599b5ed92/zhaquirks/tuya/ts0601_trv_sas.py#L76

(and most of the TRV temps)

**Comment by Shulyaka** [comment]
Yes, there are a lot

**Comment by javicalle** [comment]
Forget all my comments related to the `\x04\xff\xff\xff\xe3` values. It seems that there are only in my local environment 🤦🏻‍♂️ 

I'm going to start from scratch again.

**Comment by Shulyaka** [comment]
Wouldn't #2175 be enough for this issue?

**Comment by javicalle** [comment]
> Wouldn't #2175 be enough for this issue?

Yes, I believe that is the good one.
I have PR you for a test.

**Comment by javicalle** [comment]
@m0nty81 just to be sure: your device has been already added to an existing quirk, isn't it?
I have focused on the negative values problem and now I can't recall if the device has been already fixed.

**Comment by Shulyaka** [comment]
I can see `_TZE200_qyflbnbj` in `TuyaTempHumiditySensorVar03`

**Comment by Shulyaka** [comment]
See #2117

**Comment by javicalle** [comment]
Check all the changes from:

https://github.com/zigpy/zha-device-handlers/pull/2175/files

**Comment by EugeneTM** [comment]
What is the correct way to fix negative temps for `_TZE200_qyflbnbj` now?

I don't see any python classes in https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601_sensor.py

**Comment by EugeneTM** [comment]
For now, in Quirks.V2 the `TS0601 _TZE200_qyflbnbj` has wrong attribution:

```
TuyaQuirkBuilder("_TZE200_a8sdabtg", "TS0601")  # Variant without screen, round
    .applies_to("_TZE200_qoy0ekbd", "TS0601")
    .applies_to("_TZE200_znbl8dj5", "TS0601")
    .applies_to("_TZE200_qyflbnbj", "TS0601")
```

Yet it is a round version with a screen.

Also for now a wrong quirk is used: `zigpy.quirks.v2.CustomDeviceV2`. Resulting negative temp values are now around 65535, so it seems this is a uint/int issue.
