### ISSUE TITLE
[Device Support Request] 0/1-10V Zigbee + RF + Push Dimmer ( Model #: L1 (WZ) )

### ISSUE THREAD

**Issue by skorpioskorpio** [zigpy/zha-device-handlers#2191]
Device pairs without issue and has some functionality, however it displays as a device that has color capabilities (which it does not, it's just a dimmer), and for dimming to take effect it needs to be followed by a off-on event (which will populate the "Off Brightness" attribute and use that as its "on" state, OR changing to a different "color" in the color wheel (that shouldn't be there) will also trigger a newly set brightness to take effect. Under some conditions a transition to full brightness will occur as expected (but not always) though transitions down to a lesser brightness only ever happen in conjunction with another event as described above. 

DataSheet: [L1(WZ).pdf](https://github.com/zigpy/zha-device-handlers/files/10723786/L1.WZ.pdf)

Signature:
[TS0501B Signature.json.txt](https://github.com/zigpy/zha-device-handlers/files/10724098/TS0501B.Signature.json.txt)

Diagnostics:
[zha-319602e28f45a4a98f0003122c91b90b-_TZB210_rkgngb5o TS0501B-071522b60e7e5018e7bc7cb56bf73a0c.json.txt](https://github.com/zigpy/zha-device-handlers/files/10724077/zha-319602e28f45a4a98f0003122c91b90b-_TZB210_rkgngb5o.TS0501B-071522b60e7e5018e7bc7cb56bf73a0c.json.txt)

**Comment by javicalle** [comment]
The NO color capabilities in `TS0501B` devices has been already fixed.

You would need enable the local quirk folder in your installation. There is a good guide to configure it:
* https://github.com/zigpy/zha-device-handlers/discussions/693#discussioncomment-857274

Once configured, copy in your `custom_zha_quirks` folder the current `ts0501bs.py` file:
* https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0501bs.py

Edit the file content adding your device like this:
```python
    signature = {
        MODELS_INFO: [
            ("_TZ3210_9q49basr", "TS0501B"),
            ("_TZ3210_4zinq6io", "TS0501B"),
            ("_TZ3210_e5t9bfdv", "TS0501B"),
            ("_TZB210_rkgngb5o", "TS0501B"),
        ],
        .../...
```

Save changes, restart HA and repair your device.


To analize the dimming behavior it would be necessary some logs from your device.
Enable the debug logs and attach the behavior from:
* dimming from HA
* dimming from the device

Any information from the actions performed (ie: dimming from 0 to half brightness, switching off, etc)  will help us to analize what can be happening.
