### ISSUE TITLE
[Device Support Request] Missing backlight mode entity in ZHA for _TZ3000_hhiodade

### ISSUE THREAD

**Issue by cayote64** [zigpy/zha-device-handlers#2204]
The problem
On the 1 gang Moes TS0011 switches there is no option to change the backlight status which on the 1 gang switches are all the opposite of what they should be, i.e go out when light off so you cant see the switch in the dark.

The 2 gang Moes switches ( TS0601 ) display an entity : *.backlight_mode and power on state in the configuration tab in ZHA.

Can the same configurations not be added to the 1 gang TS0011 switches so we can swap the LED status so they react in the correct way ? 

I'm new to HA so not sure if ZHA has files missing or is it not a ZHA error ?

I have been asked to include the signitures or each.

TS0011 1 gang with no backlight feature : 

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZ3000_hhiodade",
  "model": "TS0011",
  "class": "zhaquirks.tuya.ts001x.TuyaSingleNoNeutralSwitch_2"
}
```

TS0601 with fully working features : 

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0006",
        "0xef00"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0006"
      ],
      "out_clusters": []
    }
  },
  "manufacturer": "_TZE200_g1ib5ldv",
  "model": "TS0601",
  "class": "zhaquirks.tuya.ts0601_switch.TuyaDoubleSwitchTO"
}
```

![1 gang](https://user-images.githubusercontent.com/124784526/219853319-ded3ba39-5d76-47ec-b6b9-5e53558ee406.png)

![2 gang](https://user-images.githubusercontent.com/124784526/219853324-3c8fbb6f-2baf-4bdc-a39a-956e677751b5.jpg)

**Comment by javicalle** [comment]
In the `TS0011` devices the backlight behavior can be set from the device view -> Admin zigbee device:
![image](https://user-images.githubusercontent.com/31999997/219900188-c7b222ce-2e20-4562-9615-f9f2e881b938.png)

Select the `TuyaZBOnOffAttributeCluster` cluster and the `backlight_mode` attribute to get and set the value.

As the attribute is already there, the UI part must be addressed in HA.

**Comment by javicalle** [comment]
BTW, some Moes devices accepts different `backlight_mode` values:
* https://github.com/zigpy/zha-device-handlers/blob/8122e9283589f4fff585e4cf03892bf87587e345/zhaquirks/tuya/mcu/__init__.py#L70-L77

**Comment by cayote64** [comment]
Thank you

**Comment by javicalle** [comment]
@cayote64 have you be able to fix the behavior? can the issue be closed?

**Comment by cayote64** [comment]
Yes all the switches changed to the correct status.

Many thanks, case closed 😀

**Comment by TheJulianJES** [comment]
We could also leave this open until the proper entities are added in ZHA/HA Core (even though it's technically a HA issue and not a quirks issue), but it's a bit easier to keep track of the issues here.

I think this should/would be fixed if we match quirk names instead of manufacturer names for Tuya devices?

**Comment by javicalle** [comment]
> I think this should/would be fixed if we match quirk names instead of manufacturer names for Tuya devices?

I think that would be a clear candidate to be implemented 😉

**Comment by dr3amr** [comment]
Been looking for this for ages...would be verry nice to be added to ui. The switch supports other functions also.

**Comment by GerardUmbert** [comment]
> e and power on state in the configuration tab in ZHA.
> 
> Can the same configurations not be added to the 1 gang TS0011 switches so we can swap the LED status so they react in the correct way ?
> 
> I'm new to HA so not sure if ZHA has files missing or is it not a ZHA error ?
> 
> I have been asked to include the signitures or each.

And what are we supposed to write there if we want it disabled all the time?

**Comment by dr3amr** [comment]
@GerardUmbert it is mentioned above, write "0x00" (off) in the Value field and click on "Write attribute". You should now be able to see that the light is always off.
