### ISSUE TITLE
LED GU5.3 reflectors Gledopto Model GL-S-004P with Zigbee ZHA. 

### ISSUE THREAD

**Issue by muensterandi** [zigpy/zha-device-handlers#2245]
I would like to use LED GU5.3 reflectors Gledopto Model GL-S-004P with Zigbee ZHA. 
I bought the reflectors from Gledopto Model GL-S-004P. Unfortunately, I found out too late that this model is not supported with ZHA.  Zigbee ID: GL-S-004Z 

However, the model of the same manufacturer Gledopto Model GL-S-004Z is supported with ZHA. 

Is it possible that my model GL-S-004P will be supported with ZHA soon? 
This would help me a lot because I have other devices with ZHA and I don't want to have a second gataway with Zigbee2.
Gataway with Zigbee2MQTT only for my 4 reflectors.

about a positive message I would be very happyGerman

Translated with www.DeepL.com/Translator (free version)

**Comment by TheJulianJES** [comment]
Huh, why do you think that device is not supported? Does something not work?

**Comment by muensterandi** [comment]
when trying to pair the reflectors under ZHA, they were found but the setup could not be started.

ZHA support is also not listed on the Zigbee Devicee website. 

https://zigbee.blakadder.com/Gledopto_GL-S-004P.html
[](https://zigbee.blakadder.com/Gledopto_GL-S-004P.html)

Zigbee ID: GL-S-004P 

Model GL-S-004Z shows support for ZHA. 
Zigbee ID: GL-S-004Z 

If my model Zigbee ID: GL-S-004P will be supported with ZHA soon, I would be very happy. 

Kind regards from muensterandi

**Comment by muensterandi** [comment]
Thank you very much for the tip. I will try again the days. 

But when the setup did not work I had found at Zigbee Devicee the differences of the two models on the website.

https://zigbee.blakadder.com/Gledopto_GL-S-004P.html
[](https://zigbee.blakadder.com/Gledopto_GL-S-004P.html)
Zigbee ID: GL-S-004P 

https://zigbee.blakadder.com/Gledopto_GL-S-004Z.htm
[](https://zigbee.blakadder.com/Gledopto_GL-S-004Z.html)
Zigbee ID: GL-S-004Z 

Maybe I will have better luck on the next try.

Thanks for the hint.

Kind regards from muensterandi
