### ISSUE TITLE
[BUG] IKEA Styrbar not using v2 quirk after OTA

### ISSUE THREAD

**Issue by jpmiller25** [zigpy/zha-device-handlers#2335]
IKEA styrbar remote still using V1 quirk after update to 2.4.5 firmware. Not sure how to get it to use the updated quirk. Currently long hold up and down is not working when using the awesome-ha blueprint for styrbar remote. I suspect the updated quirk will help it work right. Clicking reconfigure fails. 

**To Reproduce**
Updated styrbar firmware from 1.0.024 to 2.4.5 using guide here:
https://community.home-assistant.io/t/ikea-styrbar-force-ota-if-on-v1-0-024/528715

** had to repair styrbar to zigbee without deleting it first in order to force the ota update. Service call to image_notify did not work. **

Update successfully ran and shows firmware 0x02040005 under device info, but quirk shows zhaquirks.ikea.fourbtnremote.IkeaTradfriRemoteV1

Unsure if related, but clicking reconfigure fails. 

**Expected behavior**
Automatically use proper quirk for firmware version installed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5355449/231424901-b1c8658c-4a9e-4dd8-9d79-c37f78360e07.png)

```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0820",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0x1000",
        "0xfc57"
      ],
      "out_clusters": [
        "0x0003",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0019",
        "0x1000"
      ]
    }
  },
  "manufacturer": "IKEA of Sweden",
  "model": "Remote Control N2",
  "class": "zhaquirks.ikea.fourbtnremote.IkeaTradfriRemoteV1"
}
```

**Comment by TheJulianJES** [comment]
Hmm, since the quirk is based on the signature, you'll need to re-pair the device.
It's possible that you might even need to remove it first before pairing again.

But try to allow joins in HA again (Add Device), then reset the remote and let it join again.
It _should_ pick up the v2 quirk then.

It's currently a limitation of how zigpy works. It doesn't re-interview the device after an OTA updgrade.

**Comment by MattWestb** [comment]
The v2.4.5 firmware is doing function upgrade of the device and is adding one extra cluster.
ZHA is only reading the hardware then paring one device new so you need deleting it waiting one minute and then adding it new and it shall loading the V2 quirk OK.
If not restart HA so its reading the new device info from the database.

**Comment by MattWestb** [comment]
The signature of 24.5 firmware:
```
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0820",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0x1000",
        "0xfc57",
        "0xfc7c"
      ],
      "out_clusters": [
        "0x0003",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0019",
        "0x1000"
      ]
    }
  },
  "manufacturer": "IKEA of Sweden",
  "model": "Remote Control N2",
  "class": "zhaquirks.ikea.fourbtnremote.IkeaTradfriRemoteV2"
}
```

**Comment by jpmiller25** [comment]
Ok, thank you for such a quick response!  I'll remove and repair and let you know.

**Comment by UsefulVid** [comment]
@jpmiller25 How did you solve it? Afer a repairing it still shows V1 on my side:
![image](https://github.com/zigpy/zha-device-handlers/assets/39967070/8a2142b6-83a8-48df-ba70-8b37edf72bd8)
I have 2 styrbar controllers which both use v1

**Comment by jpmiller25** [comment]
@UsefulVid I don't remember but I'll have to look back into this, I currently have one running on v2 and another running on v1 lol. I'll update if I figure it out.

**Comment by UsefulVid** [comment]
perhaps @TheJulianJES may help out?
