### ISSUE TITLE
[BUG] ikea pir sensor e1745 on_time 1800 change attribute

### ISSUE THREAD

**Issue by antoweb** [zigpy/zha-device-handlers#2342]
**Describe the bug**
How to change attribute of ikea motion sensor model e1745 to less delay even the default 1800. I would to set it to 30 secs.

**To Reproduce**

**Expected behavior**

**Screenshots**

<details>

<summary>Device signature</summary>

```yaml
Paste the device signature here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>

<summary>Diagnostic information</summary>

```yaml
Paste the diagnostic information here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

<details>
<summary>Additional logs</summary>

```
Paste any additional debug logs here.
Don't remove the extra line breaks outside the ``` marks.
```

</details>

**Additional context**

**Comment by MattWestb** [comment]
IKEA motion sensors is having fixed col down in the firmware then they is made for controlling light directly so its not possible if you not cocking on new firmware for it.

**Comment by antoweb** [comment]
How to cooking with new firmware?

**Comment by MattWestb** [comment]
https://github.com/SiliconLabs/gecko_sdk
