### ISSUE TITLE
[Device Support Request] Aqara P1 - MCCGQ13LM

### ISSUE THREAD

**Issue by fabiobrolo** [zigpy/zha-device-handlers#2349]
Is it possible to include the Aqara P1 door and window sensor in ZHA?
The device is added, however the sensors and binary sensors are not getting updates.
It´s code is MCCGQ13LM and it is supported in Z2M according to https://www.zigbee2mqtt.io/devices/MCCGQ13LM.html
I´m using ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus with firmware Z-Stack_3.x.0 coordinator 20230410
![image](https://user-images.githubusercontent.com/91396121/233644860-5f8d5abd-9038-49c8-878c-b0ca0c4026c4.png)

  `  "data": {
    "ieee": "**REDACTED**",
    "nwk": 5163,
    "manufacturer": "LUMI",
    "model": "lumi.magnet.ac01",
    "name": "LUMI lumi.magnet.ac01",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4447,
    "power_source": "Battery or Unknown",
    "lqi": 83,
    "rssi": null,
    "last_seen": "2023-04-21T10:01:20",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4447, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": 260,
          "device_type": "0x0402",
          "in_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0500"
          ],
          "out_clusters": [
            "0x0019"
          ]
        }
      }
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "binary_sensor.lumi_lumi_magnet_ac01_iaszone",
        "name": "LUMI lumi.magnet.ac01"
      },
      {
        "entity_id": "button.lumi_lumi_magnet_ac01_identify",
        "name": "LUMI lumi.magnet.ac01"
      },
      {
        "entity_id": "sensor.lumi_lumi_magnet_ac01_battery",
        "name": "LUMI lumi.magnet.ac01"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "IAS_ZONE"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "deba85ed2e3a96ecb0cba18dc75b02a5",
    "area_id": null,
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "IAS_ZONE",
          "id": 1026
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0001": {
                "attribute_name": "app_version",
                "value": 24
              },
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "LUMI"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "lumi.magnet.ac01"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0500": {
            "endpoint_attribute": "ias_zone",
            "attributes": {
              "0x0000": {
                "attribute_name": "zone_state",
                "value": 1
              },
              "0x0001": {
                "attribute_name": "zone_type",
                "value": 21
              },
              "0x0002": {
                "attribute_name": "zone_status",
                "value": 32
              },
              "0x0010": {
                "attribute_name": "cie_addr",
                "value": [
                  6,
                  161,
                  198,
                  36,
                  0,
                  75,
                  18,
                  0
                ]
              }
            },
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 33
              },
              "0x0031": {
                "attribute_name": "battery_size",
                "value": 7
              },
              "0x0033": {
                "attribute_name": "battery_quantity",
                "value": 1
              }
            },
            "unsupported_attributes": {
              "0x0021": {
                "attribute_name": "battery_percentage_remaining"
              }
            }
          }
        },
        "out_clusters": {
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }`

**Comment by heroclix** [comment]
Same issue here, were you able to get it to work?

**Comment by PabloGux** [comment]
Same issue here! Aqara P1 contact sensor (lumi.magnet.ac01) pairs with ZHA but the binary_sensor does not get updated nor it have battery information. Please add support in ZHA for this.

**Comment by TheJulianJES** [comment]
Another issue: 
- https://github.com/zigpy/zha-device-handlers/issues/2349

Subscribe to both threads. I've ordered a T1 sensor that might be very similar to this P1 sensor, so it's possible that I can provide a custom test quirk in the next few days.
