### ISSUE TITLE
[Device Support Request] LS82-Tuya" curtain motor (cover).

### ISSUE THREAD

**Issue by DavoudTaghawiNejadWSP** [zigpy/zha-device-handlers#2391]
### Problem description

I am trying to add a quirk for the "LS82-Tuya" curtain motor (cover). This is a zigbee device that looks exactly as other tuya curtain motors.

### Solution description

 I was able to build the signature, so that it is recognized. It shows up as a cover device. And it correctly reflects the position (open/closed). However, when I push the open stop or close button nothing happens. There is also no error message in the logs.
I am at loss how to trouble shoot this device. The current quirk attempt is below.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature
    
          {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0051",
          "input_clusters": [
            "0x0000",
            "0x0004",
            "0x0005",
            "0xef00"
          ],
          "output_clusters": [
            "0x000a",
            "0x0019"
          ]
        },
        "242": {
          "profile_id": "0xa1e0",
          "device_type": "0x0061",
          "input_clusters": [],
          "output_clusters": [
            "0x0021"
          ]
        }
      },
      "manufacturer": "_TZE200_xu4a5rhj",
      "model": "TS0601",
      "class": "zigpy.device.Device"
    }
   
### Diagnostic information

        {
      "home_assistant": {
        "installation_type": "Home Assistant Supervised",
        "version": "2023.5.2",
        "dev": false,
        "hassio": true,
        "virtualenv": false,
        "python_version": "3.10.11",
        "docker": true,
        "arch": "aarch64",
        "timezone": "Asia/Dubai",
        "os_name": "Linux",
        "os_version": "5.15.84-v8+",
        "supervisor": "2023.04.1",
        "host_os": "Debian GNU/Linux 11 (bullseye)",
        "docker_version": "20.10.23",
        "chassis": "",
        "run_as_root": true
      },
      "custom_components": {
        "average": {
          "version": "2.3.0",
          "requirements": []
        },
        "localtuya": {
          "version": "5.0.0",
          "requirements": []
        },
        "zha_toolkit": {
          "version": "v0.8.37",
          "requirements": [
            "packaging>=20.8",
            "pytz"
          ]
        },
        "hacs": {
          "version": "1.31.0",
          "requirements": [
            "aiogithubapi>=22.10.1"
          ]
        },
        "climate_template": {
          "version": "0.6.1",
          "requirements": []
        },
        "pyscript": {
          "version": "1.3.3",
          "requirements": [
            "croniter==1.3.4",
            "watchdog==2.1.6"
          ]
        }
      },
      "integration_manifest": {
        "domain": "zha",
        "name": "Zigbee Home Automation",
        "after_dependencies": [
          "onboarding",
          "usb"
        ],
        "codeowners": [
          "@dmulcahey",
          "@adminiuga",
          "@puddly"
        ],
        "config_flow": true,
        "dependencies": [
          "file_upload"
        ],
        "documentation": "https://www.home-assistant.io/integrations/zha",
        "iot_class": "local_polling",
        "loggers": [
          "aiosqlite",
          "bellows",
          "crccheck",
          "pure_pcapy3",
          "zhaquirks",
          "zigpy",
          "zigpy_deconz",
          "zigpy_xbee",
          "zigpy_zigate",
          "zigpy_znp"
        ],
        "requirements": [
          "bellows==0.35.2",
          "pyserial==3.5",
          "pyserial-asyncio==0.6",
          "zha-quirks==0.0.99",
          "zigpy-deconz==0.21.0",
          "zigpy==0.55.0",
          "zigpy-xbee==0.18.0",
          "zigpy-zigate==0.11.0",
          "zigpy-znp==0.11.1"
        ],
        "usb": [
          {
            "vid": "10C4",
            "pid": "EA60",
            "description": "*2652*",
            "known_devices": [
              "slae.sh cc2652rb stick"
            ]
          },
          {
            "vid": "1A86",
            "pid": "55D4",
            "description": "*sonoff*plus*",
            "known_devices": [
              "sonoff zigbee dongle plus v2"
            ]
          },
          {
            "vid": "10C4",
            "pid": "EA60",
            "description": "*sonoff*plus*",
            "known_devices": [
              "sonoff zigbee dongle plus"
            ]
          },
          {
            "vid": "10C4",
            "pid": "EA60",
            "description": "*tubeszb*",
            "known_devices": [
              "TubesZB Coordinator"
            ]
          },
          {
            "vid": "1A86",
            "pid": "7523",
            "description": "*tubeszb*",
            "known_devices": [
              "TubesZB Coordinator"
            ]
          },
          {
            "vid": "1A86",
            "pid": "7523",
            "description": "*zigstar*",
            "known_devices": [
              "ZigStar Coordinators"
            ]
          },
          {
            "vid": "1CF1",
            "pid": "0030",
            "description": "*conbee*",
            "known_devices": [
              "Conbee II"
            ]
          },
          {
            "vid": "10C4",
            "pid": "8A2A",
            "description": "*zigbee*",
            "known_devices": [
              "Nortek HUSBZB-1"
            ]
          },
          {
            "vid": "0403",
            "pid": "6015",
            "description": "*zigate*",
            "known_devices": [
              "ZiGate+"
            ]
          },
          {
            "vid": "10C4",
            "pid": "EA60",
            "description": "*zigate*",
            "known_devices": [
              "ZiGate"
            ]
          },
          {
            "vid": "10C4",
            "pid": "8B34",
            "description": "*bv 2010/10*",
            "known_devices": [
              "Bitron Video AV2010/10"
            ]
          }
        ],
        "zeroconf": [
          {
            "type": "_esphomelib._tcp.local.",
            "name": "tube*"
          },
          {
            "type": "_zigate-zigbee-gateway._tcp.local.",
            "name": "*zigate*"
          },
          {
            "type": "_zigstar_gw._tcp.local.",
            "name": "*zigstar*"
          },
          {
            "type": "_slzb-06._tcp.local.",
            "name": "slzb-06*"
          }
        ],
        "is_built_in": true
      },
      "data": {
        "ieee": "**REDACTED**",
        "nwk": 56025,
        "manufacturer": "_TZE200_xu4a5rhj",
        "model": "TS0601",
        "name": "_TZE200_xu4a5rhj TS0601",
        "quirk_applied": false,
        "quirk_class": "zigpy.device.Device",
        "manufacturer_code": 4417,
        "power_source": "Mains",
        "lqi": 63,
        "rssi": null,
        "last_seen": "2023-05-12T20:27:23",
        "available": true,
        "device_type": "Router",
        "signature": {
          "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
          "endpoints": {
            "1": {
              "profile_id": "0x0104",
              "device_type": "0x0051",
              "input_clusters": [
                "0x0000",
                "0x0004",
                "0x0005",
                "0xef00"
              ],
              "output_clusters": [
                "0x000a",
                "0x0019"
              ]
            },
            "242": {
              "profile_id": "0xa1e0",
              "device_type": "0x0061",
              "input_clusters": [],
              "output_clusters": [
                "0x0021"
              ]
            }
          },
          "manufacturer": "_TZE200_xu4a5rhj",
          "model": "TS0601"
        },
        "active_coordinator": false,
        "entities": [],
        "neighbors": [],
        "routes": [],
        "endpoint_names": [
          {
            "name": "SMART_PLUG"
          },
          {
            "name": "unknown 97 device_type of 0xa1e0 profile id"
          }
        ],
        "user_given_name": "Office: Curtains",
        "device_reg_id": "d61adacb75ee5175d052064fcc3e4d97",
        "area_id": "office",
        "cluster_details": {
          "1": {
            "device_type": {
              "name": "SMART_PLUG",
              "id": 81
            },
            "profile_id": 260,
            "in_clusters": {
              "0x0004": {
                "endpoint_attribute": "groups",
                "attributes": {},
                "unsupported_attributes": {}
              },
              "0x0005": {
                "endpoint_attribute": "scenes",
                "attributes": {},
                "unsupported_attributes": {}
              },
              "0xef00": {
                "endpoint_attribute": null,
                "attributes": {},
                "unsupported_attributes": {}
              },
              "0x0000": {
                "endpoint_attribute": "basic",
                "attributes": {
                  "0x0000": {
                    "attribute_name": "zcl_version",
                    "value": 3
                  },
                  "0x0001": {
                    "attribute_name": "app_version",
                    "value": 70
                  },
                  "0x0004": {
                    "attribute_name": "manufacturer",
                    "value": "_TZE200_xu4a5rhj"
                  },
                  "0x0005": {
                    "attribute_name": "model",
                    "value": "TS0601"
                  },
                  "0x0007": {
                    "attribute_name": "power_source",
                    "value": 1
                  },
                  "0xfffe": {
                    "attribute_name": "attr_reporting_status",
                    "value": 0
                  }
                },
                "unsupported_attributes": {}
              }
            },
            "out_clusters": {
              "0x0019": {
                "endpoint_attribute": "ota",
                "attributes": {},
                "unsupported_attributes": {}
              },
              "0x000a": {
                "endpoint_attribute": "time",
                "attributes": {},
                "unsupported_attributes": {}
              }
            }
          },
          "242": {
            "device_type": {
              "name": "unknown",
              "id": 97
            },
            "profile_id": 41440,
            "in_clusters": {},
            "out_clusters": {
              "0x0021": {
                "endpoint_attribute": "green_power",
                "attributes": {},
                "unsupported_attributes": {}
              }
            }
          }
        }
      }
    }

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

    class LS82TuyaCover(TuyaWindowCover):
        """Tuya blind controller device."""
        signature = {
            # "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4098,
            #                    maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264,
            #                    maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
            # "endpoints": {
            # "1": { "profile_id": 260, "device_type": "0x0051", "in_clusters": [ "0x0000", "0x0004","0x0005","0xef00"], "out_clusters": ["0x000a","0x0019"] }
            # },
            # "manufacturer": "_TZE200_xu4a5rhj",
            # "model": "TS0601",
            # "class": "zigpy.device.Device"
            MODELS_INFO: [("_TZE200_xu4a5rhj", "TS0601")],
            ENDPOINTS: {
                1: {
                    PROFILE_ID: zha.PROFILE_ID,
                    DEVICE_TYPE: zha.DeviceType.SMART_PLUG,
                    INPUT_CLUSTERS: [
                        Basic.cluster_id,
                        Groups.cluster_id,
                        Scenes.cluster_id,
                        TuyaManufCluster.cluster_id,
                    ],
                    OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
                },
                242: {
                    PROFILE_ID: 41440,
                    DEVICE_TYPE: 0x0061,
                    INPUT_CLUSTERS: [],
                    OUTPUT_CLUSTERS: [0x0021
                        ]
                }
            },
        }
    
        replacement = {
            ENDPOINTS: {
                1: {
                    DEVICE_TYPE: zha.DeviceType.WINDOW_COVERING_DEVICE,
                    INPUT_CLUSTERS: [
                        Basic.cluster_id,
                        Groups.cluster_id,
                        Scenes.cluster_id,
                        TuyaManufacturerWindowCover,
                        TuyaWindowCoverControl,
                    ],
                    OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
                },
                242: {
                    DEVICE_TYPE: 0x0061,
                    INPUT_CLUSTERS: [],
                    OUTPUT_CLUSTERS: [0x0021
                        ]
                }
            }
        }

### Additional information

I am very willing to support the development as much as I can.

**Comment by javicalle** [comment]
Have you tried to to re-pair your device after the new quirk is added?
If not, remove the device from HA, wait a couple of minutes and pair it again.

If already done or not working, enable the debug logs and attach the events from operating the cover and the (not working) from HA.
