### ISSUE TITLE
[Device Support Request] Curtain Motor (Tuya, Zigbee) C-Type (3 Button) _TZE200_cpbo62rn

### ISSUE THREAD

**Issue by ivannemitko** [zigpy/zha-device-handlers#2442]
### Problem description

I bought new Roller Blind Cover here:
https://www.aliexpress.com/item/1005002954586484.html?spm=a2g0o.order_list.order_list_main.34.25771802eEeu0j

It has been successfully connected to Home Assistant, but there are no controls to control it.

### Solution description

I'd like to have ability at least to set min/max limits and open/close curtain

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

### Additional information

I found topic in zigbee2mqtt with some information for this device: https://github.com/Koenkk/zigbee2mqtt/issues/17436

**Comment by mitchellsanders** [comment]
I think I've bricked mine. I have two of these, they were working fine, now one is having issues.

I'm hoping I can get the device working in Home Assistant. Right now I've added it to the smart things app and can't seem to delete the up and down position - the wheel only moves for a split second before stopping when attempting to relearn via the smart things app.

**Comment by i8nemo** [comment]
these aren't that new, Im surprised no quirk exists for _TZE200_cpbo62rn TS0601

**Comment by gabstrusi** [comment]
I've got the same unit. Any update??

**Comment by joshdaffern** [comment]
I also have this device and am looking for a quirk to handle it

**Comment by salos1982** [comment]
Me too. I bought this device and could not do anything with it

**Comment by 1liminal1** [comment]
Did this even go anywhere?

**Comment by lucasfirl** [comment]
https://gist.github.com/lucasfirl/3403fb85a8804e55a81d63901663251b

**Comment by AnaRuxandra** [comment]
It drives me nuts, I forgot how to set it in calibration mode. Now it one moves one sec up or down and stops. Did anyone find the solution, please?
