### ISSUE TITLE
[BUG] TS0601 by _TZE200_gubdgai2 (Bead Curtain Motor)

### ISSUE THREAD

**Issue by choportrend** [zigpy/zha-device-handlers#2456]
### Bug description

Hi, I currently have the bead curtain rollers from Tuya. They're labelled as TS0601 by TZE200_gubdgai2. I searched for this specific device on here and found a few threads, but I'm still lost on what to do with mine. 

I'm very new to home assistant and ZHA as well, so please forgive me if this is coming from a very uninformed place. the problem is the following:

I managed to pair this device with ZHA and it shows up. It's loaded up as a cover but none of the buttons work. The open button is even grayed out! I looked under Zigbee info and it shows the following:

IEEE: 04:0d:84:ff:fe:ca:3f:79
Nwk: 0x6b7e
Device Type: EndDevice
LQI: 105
RSSI: Unknown
Last Seen: 2023-07-03T22:15:57
Power Source: Battery or Unknown
Quirk: zhaquirks.tuya.ts0601_cover.TuyaMoesCover0601

I understand that quirks are drivers that should make this device work, is that correct? I've also found an older thread that states this particular model has been "added': https://github.com/zigpy/zha-device-handlers/pull/1009

Still, I'm encountering problems with the device - unable to control it in any way. Is there anything else I need to do to enable quirks in my config.yaml file? Any step I'm missing? Any help is appreciated!

### Steps to reproduce

<img width="674" alt="image" src="https://github.com/zigpy/zha-device-handlers/assets/137311929/01d47adb-02a9-4009-9435-3f6c71f7e4e4">

### Expected behavior

Cover template should work

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0202",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0102",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_gubdgai2",
  "model": "TS0601",
  "class": "zhaquirks.tuya.ts0601_cover.TuyaMoesCover0601"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by javicalle** [comment]
Do you have any physical device to open/close the curtain? a wall switch or a remote?
Have you tried to set a position? (clicking on the device name and using the position bar)

If already checked, enable the debug logs and interact with the device (push buttons and use the bar), then attach the logs.

**Comment by Jobsa** [comment]
@choportrend -- I had the same issue.  Solution was to add this device via Tuya cloud to set the upper and lower limits of the blind travel.  I then reconnected the devices directly via ZHA and they worked.  Only downside is that the battery level is not coming across via ZHA.
