### ISSUE TITLE
[Device Support Request] 2023 Aqara Light Sensor T1 Brightness Sensor

### ISSUE THREAD

**Issue by Anto79-ops** [zigpy/zha-device-handlers#2462]
### Problem description

Hi, purchased a few of these sensors (manufactured April 2023):

2023 Aqara Light Sensor T1 Brightness Sensor on Aqara Global Store on AliExpress:
https://www.aliexpress.com/item/1005005012531138.html
Touted as 2023 with model number is GZCGQ11LM

The device pairs and works correctly (with SkyConnect)

However, a couple of features may be missing:
1. No battery level entity
2. Detection period (as reported by Z2M user that this device can support)

(See screenshot section)

### Solution description

possible update the library driver for create a quirk?

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

ZHA:
![image](https://github.com/zigpy/zha-device-handlers/assets/79593761/3d5b5215-8213-4077-aefb-71e4518e74e0)

Z2M:
![image](https://github.com/zigpy/zha-device-handlers/assets/79593761/5974acd7-4a5c-47cc-9c69-347c888cf16a)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.MainsPowered|AllocateAddress: 132>, manufacturer_code=4718, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=True, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0106",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0400"
      ],
      "output_clusters": [
        "0x0003"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.sen_ill.agl01"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.7.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Edmonton",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.07.1",
    "host_os": "Home Assistant OS 10.3",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "nest_protect": {
      "version": "0.3.12",
      "requirements": []
    },
    "spook": {
      "version": "0.14.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "hass_agent": {
      "version": "2022.11.9",
      "requirements": []
    },
    "dyson_local": {
      "version": "0.22.1",
      "requirements": [
        "libdyson-neon==1.0.2"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "after_dependencies": [
      "onboarding",
      "usb"
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "config_flow": true,
    "dependencies": [
      "file_upload"
    ],
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "requirements": [
      "bellows==0.35.8",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.101",
      "zigpy-deconz==0.21.0",
      "zigpy==0.56.1",
      "zigpy-xbee==0.18.1",
      "zigpy-zigate==0.11.0",
      "zigpy-znp==0.11.2"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 4973,
    "manufacturer": "LUMI",
    "model": "lumi.sen_ill.agl01",
    "name": "LUMI lumi.sen_ill.agl01",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4718,
    "power_source": "Mains",
    "lqi": 120,
    "rssi": -70,
    "last_seen": "2023-07-07T12:43:19",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.MainsPowered|AllocateAddress: 132>, manufacturer_code=4718, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=True, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0106",
          "input_clusters": [
            "0x0000",
            "0x0001",
            "0x0003",
            "0x0400"
          ],
          "output_clusters": [
            "0x0003"
          ]
        }
      },
      "manufacturer": "LUMI",
      "model": "lumi.sen_ill.agl01"
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "button.lumi_lumi_sen_ill_agl01_identify",
        "name": "LUMI lumi.sen_ill.agl01"
      },
      {
        "entity_id": "sensor.lumi_lumi_sen_ill_agl01_illuminance",
        "name": "LUMI lumi.sen_ill.agl01"
      },
      {
        "entity_id": "sensor.lumi_lumi_sen_ill_agl01_rssi",
        "name": "LUMI lumi.sen_ill.agl01"
      },
      {
        "entity_id": "sensor.lumi_lumi_sen_ill_agl01_lqi",
        "name": "LUMI lumi.sen_ill.agl01"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "LIGHT_SENSOR"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "4af9c66c77f298fff514ff0407f47e2b",
    "area_id": "kitchen",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "LIGHT_SENSOR",
          "id": 262
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0001": {
                "attribute_name": "app_version",
                "value": 27
              },
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "LUMI"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "lumi.sen_ill.agl01"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0400": {
            "endpoint_attribute": "illuminance",
            "attributes": {
              "0x0000": {
                "attribute_name": "measured_value",
                "value": 33786
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0001": {
            "endpoint_attribute": "power",
            "attributes": {
              "0x0033": {
                "attribute_name": "battery_quantity",
                "value": 1
              },
              "0x0031": {
                "attribute_name": "battery_size",
                "value": 7
              },
              "0x0020": {
                "attribute_name": "battery_voltage",
                "value": 32
              }
            },
            "unsupported_attributes": {
              "0x0021": {
                "attribute_name": "battery_percentage_remaining"
              }
            }
          }
        },
        "out_clusters": {
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

**Comment by TheJulianJES** [comment]
You need to attach the device signature or device diagnostic information.
EDIT: Now also in original post.

**Comment by Anto79-ops** [comment]
ah, yes how did I forget that. Sorry about that. Here's the diagnostic information (file download)

[zha-35e4f47bd1aec2897f2fa1af0eeb1329-LUMI lumi.sen_ill.agl01-4af9c66c77f298fff514ff0407f47e2b.json.txt](https://github.com/zigpy/zha-device-handlers/files/11985011/zha-35e4f47bd1aec2897f2fa1af0eeb1329-LUMI.lumi.sen_ill.agl01-4af9c66c77f298fff514ff0407f47e2b.json.txt)

**Comment by asucrews** [comment]
Z2M Page & code block if that helps.  Onces this is added i should be able to run ZHA :)

 https://www.zigbee2mqtt.io/devices/GZCGQ11LM.html

`    {
        zigbeeModel: ['lumi.sen_ill.agl01'],
        model: 'GZCGQ11LM',
        vendor: 'Xiaomi',
        description: 'Aqara T1 light intensity sensor',
        fromZigbee: [fz.battery, fz.illuminance, fz.aqara_opple],
        toZigbee: [tz.GZCGQ11LM_detection_period],
        meta: {battery: {voltageToPercentage: '3V_2850_3000'}},
        exposes: [e.battery(), e.battery_voltage(), e.illuminance(), e.illuminance_lux(),
            e.numeric('detection_period', exposes.access.ALL).withValueMin(1).withValueMax(59).withUnit('s')
                .withDescription('Time interval in seconds to report after light changes')],
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await device.getEndpoint(1).write('aqaraOpple', {'mode': 1}, {manufacturerCode: 0x115f, disableResponse: true});
            await endpoint.read('aqaraOpple', [0x0000], {manufacturerCode: 0x115f});
        },
        ota: ota.zigbeeOTA,
    },`

**Comment by TheJulianJES** [comment]
@Anto79-ops Can you check what the device reports for "Power Source"? (See screenshots in https://github.com/zigpy/zha-device-handlers/issues/1473)

**Comment by Anto79-ops** [comment]
@TheJulianJES 
![Screenshot_20230801_154041_Home Assistant.jpg](https://github.com/zigpy/zha-device-handlers/assets/79593761/15e23fe1-47a1-4693-9784-a81e779749c0)

**Comment by TheJulianJES** [comment]
Thanks. Please download and install this file as a custom quirk: https://raw.githubusercontent.com/zigpy/zha-device-handlers/98bd5229c6f233f27d8960b1021707fc50e9f962/zhaquirks/xiaomi/aqara/illumination.py  -> SAVE using your browser / CTRL + S or CMD + S in most cases).

Instructions for installing: https://github.com/zigpy/zha-device-handlers/discussions/693#discussioncomment-857274

(For that, you just have to create the `custom_zha_quirks` folder in your `/config` directory and add the zha config section to your `configuration.yaml`, then drop the downloaded file in that folder and restart Home Assistant.
If everything works correctly, the sensor should/might work now.

Let me know if that custom quirk works correctly, so we can get it merged into ZHA (so you can remove that custom quirk and it'll keep on working).

**Comment by Anto79-ops** [comment]
Sounds good. I will report back in a few hours.

Cheers!

**Comment by TheJulianJES** [comment]
Note: It should only change the "power source" to "battery" and actually show the battery entity.

If that works, I'll also look at adding the update interval attribute.

**Comment by TheJulianJES** [comment]
Here's a quirk with the added detection interval: https://raw.githubusercontent.com/zigpy/zha-device-handlers/5ef2d80955f1ba205bcebb3e3c73891d8371adfc/zhaquirks/xiaomi/aqara/illumination.py

Apparently you can set it from 1 to 59 (in seconds).

Do note that you'll have to set it on the `OppleCluster` using:
-  "Manage Zigbee device -> clusters" -> select `OppleCluster`
- -> select `detection_interval` -> click "Read Zigbee attribute" to read current interval

It'll display in the first text field.
To set a new interval, change the value in the first text field (and always leave the lower text field empty!), then click "Write Zigbee attribute".

Let me know if this works (and if the battery entity works).

**Comment by Anto79-ops** [comment]
Perfect!

I will try the quirk with interval reporting out.

By the way I don't need to delete or re-pair the device correct?

**Comment by TheJulianJES** [comment]
Yeah, you shouldn't need to re-pair it. It should pick up the quirk (if everything is working) and display it under "Power Source" (and that should change from "Mains" to "Battery or Unknown").

When reading/writing the detection interval, you might have to wake up the device by pressing the button on it.

**Comment by Anto79-ops** [comment]
Hey! it worked exacty as you said it would.

the battery entity is showing up now, albeit it shows unknown, I know eventually that will report a %

![image](https://github.com/zigpy/zha-device-handlers/assets/79593761/b5db6fda-804b-4788-8796-077e71bcae93)

But the attribute is reporting correctly battery voltage, size etc so I know that will eventually report a %

![image](https://github.com/zigpy/zha-device-handlers/assets/79593761/132519e4-e273-4d3f-bf7e-fa9e67161396)

Now as for the reporting interval, the default was 5

![image](https://github.com/zigpy/zha-device-handlers/assets/79593761/8351b7b9-76a5-42ea-a7b4-35a9e9e6a791)

but I changed it to 59 seconds. Here the screen shot after I re-read the the value after waking it up again

![image](https://github.com/zigpy/zha-device-handlers/assets/79593761/b7674360-fb81-4c6e-a9b4-bdceacdd3f50)

to make sure it is obeying the interval, I watch the light value and indeed it reported every 1 minute

Woo hoo! now, less clutter on my ZHA network.

Thank again @TheJulianJES

**Comment by Anto79-ops** [comment]
and as expected....the battery % came after about 20 minutes

:)
![image](https://github.com/zigpy/zha-device-handlers/assets/79593761/f3868403-b1d6-4366-bb1d-88dad1e1ef26)

**Comment by TheJulianJES** [comment]
Awesome! The quirk won't make it in time for 2023.8.0 (we just pushed a new version some hours ago).

Expect it to be officially available in 2023.9.0.
For now, you can keep using your custom quirk, but you should remove it for future versions which include the quirk (to not cause any issues in the future).

**Comment by Anto79-ops** [comment]
That sounds great!

I often join the beta core, so I'll make sure to remove it before I do the beta update but also I'll keep out for ZHA core updates too.

Thanks all for the help.

**Comment by TheJulianJES** [comment]
It won't break instantly, even if the quirk is merged. The custom quirk will take precedence over the integrated one though.
And if something major ever changes in the libraries, that custom quirk *could break*.

**Comment by dikkeleo2** [comment]
Thank you very much, indeed this solves the problem. Actually this is the second topic, I've played around with the suggestions and quirk's in the previous topic but I never got it to function. This worked in an instance.

Thanks

**Comment by kristofferR** [comment]
I can't get my lumi.sen_ill.agl01 to work in ZHA, either with this quirk or not. It connects easily to my HA Skyconnect ZHA setup, but then it just reports 3 576 021 lx constantly and I can't read/write anything from the clusters.

**Comment by kristofferR** [comment]
Turns out that it is VERY easy to pair the Aqara T1 sensor halfway, leaving it broken. After pairing it and deleting it like 5 times, it finally paired properly and it works fine now.
