### ISSUE TITLE
[Device Support Request] GLEDOPTO GL-SD-003P

### ISSUE THREAD

**Issue by twitch86** [zigpy/zha-device-handlers#2471]
### Problem description

Device is found and added without problems. 
On & Off works fine. But when changing dimming status it not working properly and it returns errors 

light/turn_on. unknown error_ 

### Solution description

Maybe the quirk can be corrected? It was in the list of new added devices of z2mqtt in july.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by TheJulianJES** [comment]
Can you check the logs for any errors? (and post the entire error here?)
