### ISSUE TITLE
[Device Support Request] Aqara Smart Radiator Thermostat E1

### ISSUE THREAD

**Issue by dtisch** [zigpy/zha-device-handlers#2472]
### Problem description

Hi, I just purchased an Aqara Smart Radiator Thermostat E1 from Amazon. Works fine except battery information is not available in Home Assitant.

### Solution description

Is it possible tu have battery information in Home Assitant ?

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

![Screenshot_20230713_183854](https://github.com/zigpy/zha-device-handlers/assets/10739686/1f3b1e25-2391-4720-9993-1bbc70772e20)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4447, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0301",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x000a",
        "0x0201",
        "0xfcc0"
      ],
      "output_clusters": [
        "0x0003",
        "0x0019",
        "0x0201",
        "0xfcc0"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.airrtc.agl001",
  "class": "zhaquirks.xiaomi.aqara.thermostat_agl001.AGL001"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

Can't download diagnotics. It's the only zigbee device of my home that ends up with an error 500 when I try to download the diagnostics.

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by Mar1usW3** [comment]
for me it is working fine. Battery takke some time to reflect in HA

**Comment by dtisch** [comment]
How long should it take to appear in HA ? It's been 5 days and for the moment nothing changed. Battey level is still marked as "unknown". Other Aqara devices (Cube, temperature sensors) that I own display battey info as soon as they are connected, so I'm still suspecting it doesn't work well with this Radiator Thermostat...

**Comment by Mar1usW3** [comment]
only a few hours

**Comment by Inoguitar** [comment]
Did you get your battery status to show in the end? I've just installed some of these and having the same problem

**Comment by TheJulianJES** [comment]
Battery information should work now. What HA version are you running?
If you still have that issue in a couple of hours, I'd recommend creating a new issue. Make sure to fill-out the issue template.

**Comment by Inoguitar** [comment]
Thanks…removed and then reinstalled. Now working fine👍

**Comment by dtisch** [comment]
Thanks for reminding me on this topic. Didn't check since my last comment two months ago. It silently started to work at some point and now displays a battery level. It's weird because battery is still charged at 100% but who knows? Maybe did I discover a source of perpetual energy (or this device is really efficient: it's still summer here, the thermostat isn't really used for now). I'll also try to remove and reinstall the device, maybe it'll flush the data and display somehing more accurate.
