### ISSUE TITLE
TS0203 by _TZ3000_decxrtwa doesn't work at all [BUG] 

### ISSUE THREAD

**Issue by ialexyi** [zigpy/zha-device-handlers#2542]
### Bug description

I have got two doors sensors TS0203
by _TZ3000_decxrtwa. I have added it to the HA.
The configuration process has failed. Even after restarting the Ha the sensor doesn't work at all.

Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

![Screenshot_20230821_173430_Home Assistant](https://github.com/zigpy/zha-device-handlers/assets/7450073/e2cf4308-1bb9-4ec6-970b-fbdb91b3e34f)

### Steps to reproduce

Bind the device TS0203
by _TZ3000_decxrtwa.

![Screenshot_20230821_174055_AliExpress](https://github.com/zigpy/zha-device-handlers/assets/7450073/4629952b-051f-4544-b3dd-2fb1e75635e1)

![Screenshot_20230821_174012_AliExpress](https://github.com/zigpy/zha-device-handlers/assets/7450073/9ca09e8a-1142-49f9-8de5-e87f5cf54457)

### Expected behavior

The door sensor needs to be properly configured. Needs to receive door state. 

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by nocusham** [comment]
can confirm the problem described by ialexyi

**Comment by vladkozlov69** [comment]
I can confirm on HA 9.2 it shows "Configuring" popup but never finish pairing.

**Comment by ialexyi** [comment]
Works now on:

Core
2023.12.0
Supervisor
2023.11.6
Operating System
11.2
Frontend
20231206.0

Many thanks!
