### ISSUE TITLE
[Device Support Request] _TZE200_6rdj8dzm TRV

### ISSUE THREAD

**Issue by sebbelese** [zigpy/zha-device-handlers#2550]
### Problem description

I bought these thermostatic valves:
https://www.tomtop.com/p-c-e0289-1.html

The device pairs well with HA, but without quirks, I see no entity, just LQI and RSSI (see screenshot).

I then tried the following quirks (adding device id in MODELS_INFO when necessary):
[ts0601_trv_me167.py](https://github.com/jacekk015/zha_quirks/blob/main/ts0601_trv_me167.py)
https://github.com/zigpy/zha-device-handlers/files/6633888/thermostat_88teujp.zip
https://github.com/zigpy/zha-device-handlers/blob/dev/zhaquirks/tuya/ts0601_trv_sas.py

Some entities may appear in this case, but they are irrelevant and not functional (device is unusable)

### Solution description

Is there a working quirk, or is it possible to adapt one? 

I have no experience with ZHA quirks (with HA at all), but can try to write something with some guidance.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

![image](https://github.com/zigpy/zha-device-handlers/assets/16559668/9dd2efae-9adb-4610-9c33-d2e7edf4942c)

</details>

### Device signature

<details><summary>Logs</summary>

```python
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0051",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_6rdj8dzm",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.8.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Brussels",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.08.1",
    "host_os": "Home Assistant OS 10.5",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "rpi_gpio": {
      "version": "2022.7.0",
      "requirements": [
        "RPi.GPIO==0.7.1"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "landroid_cloud": {
      "version": "3.0.5",
      "requirements": [
        "pyworxcloud==3.1.14"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "after_dependencies": [
      "onboarding",
      "usb"
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "config_flow": true,
    "dependencies": [
      "file_upload"
    ],
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp"
    ],
    "requirements": [
      "bellows==0.35.9",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.102",
      "zigpy-deconz==0.21.0",
      "zigpy==0.56.4",
      "zigpy-xbee==0.18.1",
      "zigpy-zigate==0.11.0",
      "zigpy-znp==0.11.4"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 39411,
    "manufacturer": "_TZE200_6rdj8dzm",
    "model": "TS0601",
    "name": "_TZE200_6rdj8dzm TS0601",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4417,
    "power_source": "Battery or Unknown",
    "lqi": 112,
    "rssi": -72,
    "last_seen": "2023-08-28T20:46:23",
    "available": true,
    "device_type": "EndDevice",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0051",
          "input_clusters": [
            "0x0000",
            "0x0004",
            "0x0005",
            "0xef00"
          ],
          "output_clusters": [
            "0x000a",
            "0x0019"
          ]
        }
      },
      "manufacturer": "_TZE200_6rdj8dzm",
      "model": "TS0601"
    },
    "active_coordinator": false,
    "entities": [],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "SMART_PLUG"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "f73f4988af4009943ccd9c26aeb9261c",
    "area_id": null,
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "SMART_PLUG",
          "id": 81
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xef00": {
            "endpoint_attribute": null,
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "_TZE200_6rdj8dzm"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "TS0601"
              }
            },
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x000a": {
            "endpoint_attribute": "time",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

**Comment by xxLeoxx93** [comment]
[ts0601_trv_me167.py](https://github.com/jacekk015/zha_quirks/blob/main/ts0601_trv_me167.py)
This file had an issue and is corrected now. Works fine for me!

**Comment by sebbelese** [comment]
I am not sure that the last commit to  ts0601_trv_me167.py ([here](https://github.com/jacekk015/zha_quirks/commit/0a7c52d7d3d6b2a6d076804ccc04571a4aa1417c)) changes anything as the two syntaxes should be equivalent.

Just tried again with the updated quirk, it is is not functioning, I get this:

![image](https://github.com/zigpy/zha-device-handlers/assets/16559668/8bf49124-166a-4eed-878f-7c6f0dd3db9f)

Number Temperature is NaN and cannot be changed. Thermostat card not working (unable to change temperature, and displayed temperature 17°C is not correct).

**Comment by dgrabla** [comment]
@sebbelese @xxLeoxx93 I can see the target temperature and the current temperature. The switch controls the 'child lock' (https://github.com/zigpy/zha-device-handlers/issues/2331#issuecomment-1517328851). The file works fine for me.

![image](https://github.com/zigpy/zha-device-handlers/assets/1942073/e270ebe9-2433-40f0-a979-deafaffed98a)

I tried before with ts0601_trv.py and ts0601_trv_sas.py without success. 
It only worked with this ts0601_trv_my167.py after removing the device and resyncing it

I have two questions:
- @jacekk015 c Why don't we add the ts0601_trv_me167.py file to this repo? 
- @ShogunMan How to use the temperature calibration control?

**Comment by jacekk015** [comment]
@dgrabla Every PR for quirk need to have Python test completed. I don't have time to learn this [11 quirks available] and no one else wanna to do it. There was one big PR for few quirks and died long time ago.
I will not try again.

**Comment by sebbelese** [comment]
I believe that the device id is common to different clones working differently, which is why it works for some and not others.

**Comment by jacekk015** [comment]
@sebbelese If still interested you need to enable debug logging
https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function

Put that quirk ts0601_trv_me167.py in the custom quirks folder
https://github.com/jacekk015/zha_quirks#usage

Remove TRV from HA.
Restart HA
Pair TRV like a brand new.
Wait still 10 minutes
Post here FULL log file from HA. Download logs from HA and drag/drop them into Github post window - it will be added as a file.

**Comment by dgrabla** [comment]
@jacekk015 I would like to have an action to 'set target temperature'. At the moment I can only turn it on and off with the HVAC simulation. When it turns on, it remembers the last temperature set. But I want to be able to change that target temperature as well. The homeassistant UI can do it, and I can do it as well setting the state on the entity by hand. But I don't know where to add actions.

At the moment these are the actions available with this quirk file:
![image](https://github.com/zigpy/zha-device-handlers/assets/1942073/3556eef6-dd39-4918-94fc-85c72d50040b)

Is this something we can do on the quirk file?

UPDATE: I don't know if we can add it on the quick file somehow but we can do this. Please notice I'm a homeassistant noob and I don't know if this is the 'correct' way. 

![image](https://github.com/zigpy/zha-device-handlers/assets/1942073/606be6ae-ea1d-4ce9-a173-19b7f1aad8ce)

**Comment by sebbelese** [comment]
> @sebbelese If still interested you need to enable debug logging https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function
> 
> Put that quirk ts0601_trv_me167.py in the custom quirks folder https://github.com/jacekk015/zha_quirks#usage
> 
> Remove TRV from HA. Restart HA Pair TRV like a brand new. Wait still 10 minutes Post here FULL log file from HA. Download logs from HA and drag/drop them into Github post window - it will be added as a file.

When trying that on the latest quirk, my device is correctly recognized now and the thermostat works

![2023-11-17 13_48_47-Report](https://github.com/zigpy/zha-device-handlers/assets/16559668/25e68eb5-f096-4f0e-9948-fc7f601ab700)

**Comment by jacekk015** [comment]
@dgrabla It's the only way to do this.
