### ISSUE TITLE
[Device Support Request] Tuya - ts0601-TZE200_1vxgqfba

### ISSUE THREAD

**Issue by rutj87** [zigpy/zha-device-handlers#2560]
### Problem description

Please add support for new Tuya Zigbee Smart Blind - TZE200_1vxgqfba

### Solution description

Please add support for new Tuya Zigbee Smart Blind - TZE200_1vxgqfba

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by MattWestb** [comment]
Pleas put in some more technical information like the diagnostic and paring logs of the device or close this issue, then its not possible getting any support without some information for the device `TZE200_1vxgqfba`.

**Comment by kdober** [comment]
Hi
Hi I just installed a zemismart roller motor that matches this signature. I would love to help out solving this one. Shall I open a new issue to paste all the info or can we open this one (to avoid duplications)?
Thanks

> Pleas put in some more technical information like the diagnostic and paring logs of the device or close this issue, then its not possible getting any support without some information for the device `TZE200_1vxgqfba`.

**Comment by kdober** [comment]
I created a custom quirk based on the existent tuya covers.  I was able to make it work.
I did pull request with the update 
https://github.com/zigpy/zha-device-handlers/pull/3277

In the mean time, this ZHA custom quirk can be used:

`
from zigpy.profiles import zha
from zigpy.zcl.clusters.general import Basic, Groups, Identify, OnOff, Ota, Scenes, Time

from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)
from zhaquirks.tuya import (
    TuyaManufacturerWindowCover,
    TuyaManufCluster,
    TuyaWindowCover,
    TuyaWindowCoverControl,
)

class TuyaMoesCoverCristian0601(TuyaWindowCover):
    signature = {
        MODELS_INFO: [
            ("_TZE200_1vxgqfba", "TS0601"),
        ],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.SMART_PLUG,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaManufCluster.cluster_id,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
            }
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                DEVICE_TYPE: zha.DeviceType.WINDOW_COVERING_DEVICE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaManufacturerWindowCover,
                    TuyaWindowCoverControl,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
            }
        }
    }`
