### ISSUE TITLE
[Device Support Request] Tuya contact sensor

### ISSUE THREAD

**Issue by blair287** [zigpy/zha-device-handlers#2566]
### Problem description

Tuya contact sensor this one:

https://a.aliexpress.com/_EJ9Pw9d

Will pair with some pain but doesn't update the sensors after the initial value also shows 2 contact sensors.

### Solution description

Would like the sensor work properly.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

![Screenshot_20230904_202707_Home Assistant](https://github.com/zigpy/zha-device-handlers/assets/44187409/19d9cb54-071d-4ed0-86ac-e8a9a99ac8e7)

### Device signature

<details><summary>Device signature</summary>

```json
[
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0402",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0500"
      ],
      "output_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x000a",
        "0x0019",
        "0x1000"
      ]
    }
  },
  "manufacturer": "_TZ3000_26fmupbb",
  "model": "TS0203",
  "class": "zigpy.device.Device"
}

```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by airampg** [comment]
Dear all,
I just wanted to say that I am experiencing exactly the same behaviour. If there is anything I can do to help add support please let me know.
