### ISSUE TITLE
[Device Support Request] TS0601 - _TZE200_p3dbf6qs - smart radiator thermostat (maybe me168?)

### ISSUE THREAD

**Issue by GeBaLeBa** [zigpy/zha-device-handlers#2569]
### Problem description

Tested with actual zha in home assistant. Creating own quirk based on ts0601_sas.py with _TZE200_p3dbf6qs. No success. 

Log says:
[0x875F:1:0xef00] Unknown cluster command 2 b’\x001 \x00\x00\x19\x05\x06\x00\x00\xd2\x08\x00\x00\xa0\x0c\x00\x00\xd2\x0e\x00\x00\xa0\x12\x00\x00\xd2\x16\x00\x00\xa0’
[0x875F:1:0xef00] Unknown cluster command 2 b’\x002!\x00\x00\x19\x06\x06\x00\x00\xd2\x08\x00\x00\xa0\x0c\x00\x00\xd2\x0e\x00\x00\xa0\x12\x00\x00\xd2\x16\x00\x00\xa0’
[0x875F:1:0xef00] Unknown cluster command 2 b’\x003"\x00\x00\x19\x07\x06\x00\x00\xd2\x08\x00\x00\xa0\x0c\x00\x00\xd2\x0e\x00\x00\xa0\x12\x00\x00\xd2\x16\x00\x00\xa0’
[0x875F:1:0xef00] Unknown cluster command 2 b’\x004#\x05\x00\x01\x00’
[0x875F:1:0xef00] Unknown cluster command 2 b’\x009\x05\x02\x00\x04\x00\x00\x00\xe6’

No Attributes, not usable. 

Then tested with custom quirk ts0601_sas.py with _TZE200_p3dbf6qs. Attributes of thermostat visible, but no data. No success.

### Solution description

find a quirk which works

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]
![image](https://github.com/zigpy/zha-device-handlers/assets/96052420/3f9e062b-cb16-48ae-af0f-dd6a0c5bf444)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>
_TZE200_p3dbf6qs
```json
[Paste the diagnostic information here]
```

</details>

### Additional information

-

**Comment by Raukze** [comment]
In the Zigbee2MQTT [issue](https://github.com/Koenkk/zigbee-herdsman-converters/pull/6067) I read that it was kind of similar to _TZE200_bvu2wnxz. Thats why I tried the custom quirk from @jacekk015 named [here](https://github.com/zigpy/zha-device-handlers/issues/1818#issuecomment-1636880270) and added a line with the device signature of _TZE200_p3dbf6qs. After repairing I am now able to control my thermostat.
Maybe @jacekk015 you can add the signature to your repo.

**Comment by jacekk015** [comment]
@Raukze That signature was added by PR
https://github.com/jacekk015/zha_quirks/pull/19
Thanks for testing!

**Comment by dieterpapa** [comment]
@Raukze 

Could you please post the quirk with the included line? I have the similär Problem to add these TRVs to ZHA.....but may not be as sophisticated as you....

Thanks in advance

dieter

**Comment by jacekk015** [comment]
@dieterpapa it's already there in my repo

Use file:
ts0601_trv_me167.py
from
https://github.com/jacekk015/zha_quirks

**Comment by dieterpapa** [comment]
@jacekk015 
I've copied the above mentioned file to folder custom_zha_quirks, restartet HA, deleted the TRV in ZHA and had it reinstalled.
However, this did not work, see attached screenshot.
![image](https://github.com/zigpy/zha-device-handlers/assets/126156742/30b85ed3-3f82-4ec1-bff9-6c18deeac066)

Any ideas?

Dieter

Found my problem.....link in configuration.yaml to custom quirk directory was lost.

**Comment by dieterpapa** [comment]
One more question:

Other TRVs as for example Shelly TRV have additionally to the climate entity a temperature sensor entity. This is not available on these Zigbee TRVs. Is this a matter of the firmware design or could it be implemented in the quirk?

Best regards

Dieter

**Comment by jacekk015** [comment]
Could you show me an example like screenshot or some image?
Climate entity already has a room temp there. You can take it to front-end without problems.

**Comment by dieterpapa** [comment]
![image](https://github.com/zigpy/zha-device-handlers/assets/126156742/26473986-e062-420c-b889-29b70c459ed3)

See attached Screenshot of a Shelly TRV.

To use "Better Thermostat" in Home assistant you need a climate entity to adjust the TRV and a sensor entity to measure the teperature.

Dieter

**Comment by jacekk015** [comment]
@dieterpapa Instead of messing with doubling items isn't just better do create a Helper template sensor??
State template:
`
{{state_attr('climate.tze200_qc4fpmcn_ts0601_b548f1fe_thermostat', 'current_temperature')}}
`

![image](https://github.com/zigpy/zha-device-handlers/assets/14165726/dd0f9d99-c599-4a16-bbf3-a96a06df226d)

**Comment by dieterpapa** [comment]
Thanks Jacek,

I'll try to get it done. To be honest - that's all new for me. I'm more than happy that I got my Alibaba TRVs running...step by step....and using "helpers" is now also something new for me......

Dieter

**Comment by dieterpapa** [comment]
Wow - a Miracle....it is working

![image](https://github.com/zigpy/zha-device-handlers/assets/126156742/1c2e7fd0-a825-4e8c-808e-4785197e12fe)

**Comment by dieterpapa** [comment]
@jacekk015 
have to apologize...all my testing was with the older ones - which were _bvu2wnxz
Have now tried to install for the first time a _p3dbf6qs TRV. Installation is working, but the device becomes  unknown immediately.

![20231023_185105000_iOS](https://github.com/zigpy/zha-device-handlers/assets/126156742/16f54cb0-d75d-4323-9666-74055fa4a11e)

**Comment by jacekk015** [comment]
@dieterpapa Debug logs needed.
https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function
I will not tell you anything just from the picture.

**Comment by dieterpapa** [comment]
@jacekk015 thanks for your support....I'll try to get the logs....is again something new for me :-)

**Comment by dieterpapa** [comment]
Logfile renamed from .log to .txt as couldn't upload a .log:

[home-assistant.txt](https://github.com/zigpy/zha-device-handlers/files/13111949/home-assistant.txt)

Dieter

**Comment by jacekk015** [comment]
Nothing wrong with the quirk - ta least for now and what I see in the logs:
HA found the quirk for TRV and want to use it
```
2023-10-24 09:23:37.664 DEBUG (MainThread) [zigpy.quirks.registry] Checking quirks for _TZE200_p3dbf6qs TS0601 (a4:c1:38:ef:6a:4d:cc:ae)
2023-10-24 09:23:37.664 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'ts0601_trv_me167.ME167'>
2023-10-24 09:23:37.664 DEBUG (MainThread) [zigpy.quirks.registry] Found custom device replacement for a4:c1:38:ef:6a:4d:cc:ae: <class 'ts0601_trv_me167.ME167'>
```

Then HA says there's no connection with TRV - last seen over 12 hours ago
```
2023-10-24 09:23:47.894 DEBUG (MainThread) [homeassistant.components.zha.core.gateway] [0x9AF3](_TZE200_p3dbf6qs TS0601) restored as 'unavailable', last seen: 12:34:17 ago, consider_unavailable_time: 21600 seconds
```

Since TRV doesn't respond HA marks it unavailable
```
2023-10-24 09:27:41.898 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x9AF3](TS0601): last_seen is 45491.379120111465 seconds ago and ping attempts have been exhausted, marking the device unavailable
2023-10-24 09:27:41.898 DEBUG (MainThread) [homeassistant.components.zha.core.device] [0x9AF3](TS0601): Update device availability -  device available: False - new availability: False - changed: False
```

Look like TRV doesn't have a Zigbee range to coordindator or something like that.
It doesn't talk at all with HA
Even with no quirk there should be communication between HA and TRV.
Here's nothing.

**Comment by dieterpapa** [comment]
That is curious...

it gets identified and binded. I can attach it to a group and rename it (as you can see at the screenshot: TRV_Tim) - but then it is loosing connection again.

**Comment by jacekk015** [comment]
It's not loosing connection. There's always a delay when the HA marks it unavailable.
It try few times before marking.
Like you see form the logs. Device last seen 12 hours ago.

Bring it closer to coordinator antenna and check again. Or remove it and pair like a new.
Maybe TRV didn't bind to HA properly.
For now there's no Zigbee connection between HA and TRV. They don't talk.
Maybe you need an Zigbee amplifier or any power-sourced Zigbee device to be a router.

**Comment by MattWestb** [comment]
@dieterpapa Update you coordinator firmware to latest release then both TI and EZSP have some bugs with direct children. 
Also make sure having one good router around the TRVs then its sleeping end devices (not deep sleeper but is offline most of the time) and if its parent is not OK its going permanent offline then it have lost the contact with its parent.

**Comment by dieterpapa** [comment]
See attached photos, the device paired correctly 
![20231024_092727999_iOS](https://github.com/zigpy/zha-device-handlers/assets/126156742/32f88e6b-535d-4c70-b4c1-7ebc8fddaae2)
![20231024_093213690_iOS](https://github.com/zigpy/zha-device-handlers/assets/126156742/7bd01c51-3d87-45ee-b9c6-18881bdea750)
![20231024_092707384_iOS](https://github.com/zigpy/zha-device-handlers/assets/126156742/e7edad2b-0282-443a-87a7-42135af67754)

I am about 3m away from the ZHA antenna and there are plenty of router-devices installed.

However, I'll check my coordinator firmware - I have a Sonoff stick. 

Dieter

**Comment by jacekk015** [comment]
I would like to get HA logs from that pairing process.
So:
Remove TRV from HA.
Restart HA - to get a smaller log file.
Pair like new
Wait 10 minutes
Post HA full logs.

**Comment by dieterpapa** [comment]
I'm now afraid a little bit....
I've had now serious problems with my heating system at all - all TRVs grouped via climate group gone crazy (3 Shelly TRV, one _bvu2wnxz). TRVs couldn't been adjusted, did change temperatures themselves....crazy behaviour. Had it yesterday and thought it may be HA 10.4 or 10.5 - did restore 10.3 then.
Today the same problem after playing around with the TRVs p3dbf6qs....went back to a backup made yesterday without one of those TRVs in the system - it is running again.
I'll watch my heating system first for a few days and once I have a stable system again I'll come back. 

Dieter

**Comment by tomastyl** [comment]
Dear Jacek, thx for saving my money with your qurk file....is there any chance to get control over % of valve opening (e.g 0-100%)...I am looking fo this control: 
![image](https://github.com/zigpy/zha-device-handlers/assets/147306982/2477f5ea-9469-4e0e-a941-33334abd7bdd)

currently I have these 
![image](https://github.com/zigpy/zha-device-handlers/assets/147306982/16e8d595-7ddf-45fe-a4c1-c8322132c97b)

I am refering to _TZE200_p3dbf6qs
Thanks 
Tom

**Comment by jacekk015** [comment]
@tomastyl Nope - that TRV device don't even have valve % open attribute.
It doesn't support that.

Z2M also don't have it so that doesn't exist.
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/tuya.ts#L2801

Switch is a ChildLock and Numer is a TemperatureCalibration +/-10 degrees

**Comment by tomastyl** [comment]
ok, thanks anyway, so any tips on TRV tested in ZHA with that feature?

**Comment by jacekk015** [comment]
@tomastyl From the quirks code I see that Moes an Rtitek have that attribute.
Can't give you 100% for that since those quirks are old and tested long ago.
I don't remember every TRV id functionality.

Question is what you wanna to achieve?
Even if you send 10% opening I'm still not sure if the TRV wan't change it in the next 5 minutes.

**Comment by tomastyl** [comment]
I want to control % of valve opening based on other sensors (temperature, windows) etc. Basicaly TRV would be just motors - no need for their own termostats....

**Comment by jacekk015** [comment]
Probably not possible. Are you sure that TRV won't override this after few minutes? Even in the manual mode.
If I remember correctly there were some guys that wanted to do this, but there was probably like only one TRV that could be really steered.

Remember that most of that devices have PID implemented.
LIDL TRV's I have aren't stupid devices like full open/close. They just move the engine a bit.
I can check valve open percentage, but only on TRV - they don't send it by Zigbee.

**Comment by tomastyl** [comment]
ok, so it might be bad idea from the beggining :-) 
I am a bit new in this :
in automation I can see trigger HVAC changed to "HEAT" but in history of device I see status "HEATING"  - those two do not match - could it be cause my next steps aren't triggering?

**Comment by jacekk015** [comment]
HVAC mode is probably a system_mode - I'm guessing what you see now.
We emulate TRV as a HVAC.
Real HVAC is an air conditioner. It can heat/cool/fan/dehydrate etc...
TRV can only HEAT or sometimes get OFF system mode. For sure it won't Cool.

Next is State: Heating or Idle.
Those two aren't the same.

Think of it like - I've turned AC to Heat system_mode, but if the temp is over degrees set, the AC goes from Heat state to Idle state and waits for the temperature to drop below temperature set.
But still AC got Heat system_mode - even if current State is Idle

**Comment by tomastyl** [comment]
ok, thanks.... 👍

**Comment by TomcatPi** [comment]
Thanks for the customs quirks
it works but i've got a question

What are the signification of the 2 switchs on the TRV ?
I found that the 1st is the child lock, but I was unable to undestand what is the second one ?

Also i've got another parameter in °C that is at 0°C and can move frome -10°C to +10°C, what is for ?

![image](https://github.com/zigpy/zha-device-handlers/assets/130712179/8ad76762-e758-4a89-abd8-78cb0afc1992)

**Comment by jacekk015** [comment]
Switches are ChildLock and FrostProtection
Next one is a Temperature Calibration slider.

**Comment by TomcatPi** [comment]
> Switches are ChildLock and FrostProtection Next one is a Temperature Calibration slider.

Thanks for the reply
I'm not sure to understand what the temperature calibration slider do exactly ?
could you explain to me ?

**Comment by jacekk015** [comment]
Same as TRV manual says.
Calibrates room temp reading.

**Comment by nicGoSan** [comment]
I have also issues with newly bought device ( AVATTO Tuya ZigBee3.0, tze200_p3dbf6qs_ts0601). Connection works with the quirk. I added an issue to your @jacekk015 github: [https://github.com/jacekk015/zha_quirks]. I have many other devices in ZHA and don't want to switch to Zigbee2MQTT .Your effort is much appreciated.

**Comment by nicGoSan** [comment]
> I have also issues with newly bought device ( AVATTO Tuya ZigBee3.0, tze200_p3dbf6qs_ts0601). Connection works with the quirk. I added an issue to your @jacekk015 github: [https://github.com/jacekk015/zha_quirks]. I have many other devices in ZHA and don't want to switch to Zigbee2MQTT .Your effort is much appreciated.

My Sonoff Zigbee 3.0 usb dongle E firmware was too old. I used a 6.x version.  Updated my firmware to 7.x: [https://darkxst.github.io/sl-test/](url) @jacekk015 , I will close the issue

**Comment by dredkin** [comment]
Hello @jacekk015 !
I just bought 6 TRVs with this identifier and I installed your quirk into the HA 2023.7.3.
It is working fine, so fist of all, thank you very much!

But the additional switches (like child lock and temperature calibration) were imported with gibberish names so now I have to manually rename all of them. It's so much pain.
Is there any way I can edit this quirk so these switches get their names and icons automatically?

**Comment by jacekk015** [comment]
@dredkin That's unfortunately limitation of ZHA

**Comment by dredkin** [comment]
I see. Such a pity. But thanks again anyway for your priceless work!

**Comment by dolorosus** [comment]
I have noticed the attribute ME167_TEMP_CALIBRATION_ATTR is assumed to have the unit _decigree_:
```ME167_TEMP_CALIBRATION_ATTR = 0x022F  # (decidegree)```

However, as far as I can determine, the unit of this attribute is _degree_.  As soon as you try advanced thermostat controls (e.g. better thermostat, ...), the entire temperature control gets confused due to incorrect calibration values.  

Can someone take a look at this and correct it if necessary?

**Comment by michalw2-alt** [comment]
I've noticed that whenever I try to change: "Min heat setpoint limit" or "Max heat setpoint limit" I get error: 
"Failed to perform the action number/set_value. 'NoneType' object is not iterable"
![Screenshot 2024-10-06 at 23 36 29](https://github.com/user-attachments/assets/81857bd6-62ac-4461-8110-7ab2791913ae)

I'm wondering if this is known issue?

**Comment by maciak** [comment]
Hi,
How do I know if I did used the quirk properly? I downloaded the file and dropped it I correct directory, updated configuration.xml with hopefully correct data, restarted HA, re-paired my _TZE200_p3dbf6qs and I see absolutely no change.
Any help would be greatly appreciated.

![Image](https://github.com/user-attachments/assets/dba3de95-d0af-411a-879a-3a22e1b7689d)

**Comment by jneuhauser** [comment]
You do not need to use this custom quirk anymore.... Update to recent HA with ZHA and it should work.

Official support was added with https://github.com/zigpy/zha-device-handlers/commit/e61ecbb4f64291c663fd19d23f95f7db5d33e1f0
