### ISSUE TITLE
[Device Support Request] MCCGQ12LM

### ISSUE THREAD

**Issue by Infrecon** [zigpy/zha-device-handlers#2572]
### Problem description

I want to connect my aqara MCCGQ12LM with a sky connect and zha

### Solution description

connection established

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by MattWestb** [comment]
Perhaps one Device signature and little Diagnostic information can helping more then only "I want" . . . .

Logs can also helping !!

**Comment by Hedda** [comment]
@Infrecon You will also need to provide "Device signature" AND "Diagnostic information"

You can find the device signature by going to the device page, clicking the three dots, clicking on "Manage Zigbee device", and then selecting the "Signature" tab at the top.

You can find the diagnostic information of the device by going to the device page, clicking the three dots, and then by clicking on "Download diagnostics".

If applicable, you can upload relevant logs.

In some cases, it's helpful to enable debug logging, reproducing the issue again, and then uploading the logs.

Note: To enable debug logging, see [this section](https://www.home-assistant.io/integrations/zha/#debug-logging), then restart Home Assistant, reproduce the issue again, and paste the relevant logs in between the lines with the backticks below.

You can also enable debug logs at runtime by going to the integrations page in settings, clicking the three dots next to your ZHA integration, and selecting "Enable debug logging".
Reproduce the issue again, click on those three dots again, and select "Disable debug logging".
Then, copy the relevant log parts from the downloaded file and paste them in between the lines with the backticks below.

https://www.home-assistant.io/integrations/zha#how-to-add-support-for-new-and-unsupported-devices

https://github.com/zigpy/zha-device-handlers/blob/dev/README.md#signature

**Comment by TheJulianJES** [comment]
So you have issues connecting the sensor at all? Hold the reset button for longer while allowing joins in ZHA ("Add Device" button).
