### ISSUE TITLE
[Device Support Request] DoubleSocket50AU by Aurora no backlight level

### ISSUE THREAD

**Issue by Davej817** [zigpy/zha-device-handlers#2574]
### Problem description

DoubleSocket50AU Zigbee smart socket. Exposes the switching and power but no access to the backlight brightness function.
It exists as I can set it in "Manage Zigbee Device" as in the picture.

### Solution description

Include the brightness function to 'controls' with the switches.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]
<img width="408" alt="manage zigbee" src="https://github.com/zigpy/zha-device-handlers/assets/2206975/a9e00eb4-5798-491e-aed8-b572977e5b31">

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4636, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=0, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0009",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0b04"
      ],
      "output_clusters": [
        "0x0019"
      ]
    },
    "2": {
      "profile_id": "0x0104",
      "device_type": "0x0009",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0b04"
      ],
      "output_clusters": []
    }
  },
  "manufacturer": "Aurora",
  "model": "DoubleSocket50AU",
  "class": "zigpy.device.Device"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

### Additional information

Diagnostic information for all my Zigbee devices work except this sockets diagnostics returns a blank page.

**Comment by TheJulianJES** [comment]
Well, that's a very weird implementation and would require some work to expose this as an entity in HA.

A workaround could be to change the device type for endpoint 1 in the `replacement` section of the stub quirk below from `MAIN_POWER_OUTLET` to `DIMMABLE_LIGHT`. It would show up as a light entity then.

A different solution would be to match and create an entity just for that device in ZHA / HA Core.

<details>
<summary>Stub quirk (doesn't do anything yet except applying)</summary>

```python
"""Quirk for Aurora DoubleSocket50AU."""

from zigpy.profiles import zha 
from zigpy.quirks import CustomDevice
from zigpy.zcl.clusters.general import (
    Basic,
    Groups,
    Identify,
    LevelControl,
    OnOff,
    Ota,
    Scenes,
)
from zigpy.zcl.clusters.homeautomation import (
    ElectricalMeasurement,
)
from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)


class AuroraDoublesocket50Au(CustomDevice):
    """Aurora DoubleSocket50AU custom device implementation."""

    signature = {
        MODELS_INFO: [("Aurora", "DoubleSocket50AU")],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.MAIN_POWER_OUTLET,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    LevelControl.cluster_id,
                    ElectricalMeasurement.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id,
                ],
            },
            2: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.MAIN_POWER_OUTLET,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    ElectricalMeasurement.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                ],
            },
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.MAIN_POWER_OUTLET,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    LevelControl.cluster_id,
                    ElectricalMeasurement.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id,
                ],
            },
            2: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.MAIN_POWER_OUTLET,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    ElectricalMeasurement.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                ],
            },
        },
    }

```

</details>

> Diagnostic information for all my Zigbee devices work except this sockets diagnostics returns a blank page.

There should be an exception in the logs when trying to download those. Can you post it here?

**Comment by Davej817** [comment]
Hi,
Thanks for the answer, it may take me a bit to understand your answer but below is the error in the log when requesting diagnostics.


`Logger: aiohttp.server
Source: components/zha/diagnostics.py:156
First occurred: 15:04:35 (3 occurrences)
Last logged: 15:05:32

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 268, in get
    data = await info.device_diagnostics(hass, config_entry, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/diagnostics.py", line 104, in async_get_device_diagnostics
    device_info[CLUSTER_DETAILS] = get_endpoint_cluster_attr_data(zha_device)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/diagnostics.py", line 126, in get_endpoint_cluster_attr_data
    ATTR_IN_CLUSTERS: {
                      ^
  File "/usr/src/homeassistant/homeassistant/components/zha/diagnostics.py", line 129, in <dictcomp>
    **get_cluster_attr_data(cluster),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/diagnostics.py", line 155, in get_cluster_attr_data
    UNSUPPORTED_ATTRIBUTES: {
                            ^
  File "/usr/src/homeassistant/homeassistant/components/zha/diagnostics.py", line 156, in <dictcomp>
    f"0x{cluster.find_attribute(u_attr).id:04x}": {
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/zcl/__init__.py", line 233, in find_attribute
    return self.attributes[name_or_id]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 900
`

**Comment by Blackduke77** [comment]
Is there anything I can do to help get this looked at? I am looking to achieve the same thing

**Comment by TheJulianJES** [comment]
The "not being able to download diagnostics" is a ZHA bug that needs to be fixed.

Can you try this custom quirk? Endpoint 1 should appear as a light entity (on/off for switch) and brightness level for backlight brightness. It's a workaround for now, but it's also stupidly implemented in the plug.

Otherwise, you should be able to change the brightness (without using a custom quirk) from the "Manage Zigbee device" section -> "Clusters" -> select "LevelControl" and under the "commands" tab, send a command with the wanted brightness level.

<details>
<summary>Custom quirk replacing endpoint 1 with "dimmable light" type</summary>

```python
"""Quirk for Aurora DoubleSocket50AU (changed endpoint 1 type to dimmable light)."""

from zigpy.profiles import zha 
from zigpy.quirks import CustomDevice
from zigpy.zcl.clusters.general import (
    Basic,
    Groups,
    Identify,
    LevelControl,
    OnOff,
    Ota,
    Scenes,
)
from zigpy.zcl.clusters.homeautomation import (
    ElectricalMeasurement,
)
from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)


class AuroraDoublesocket50Au(CustomDevice):
    """Aurora DoubleSocket50AU custom device implementation."""

    signature = {
        MODELS_INFO: [("Aurora", "DoubleSocket50AU")],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.MAIN_POWER_OUTLET,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    LevelControl.cluster_id,
                    ElectricalMeasurement.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id,
                ],
            },
            2: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.MAIN_POWER_OUTLET,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    ElectricalMeasurement.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                ],
            },
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.DIMMABLE_LIGHT,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    LevelControl.cluster_id,
                    ElectricalMeasurement.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                    Ota.cluster_id,
                ],
            },
            2: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.MAIN_POWER_OUTLET,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    OnOff.cluster_id,
                    ElectricalMeasurement.cluster_id,
                ],
                OUTPUT_CLUSTERS: [
                ],
            },
        },
    }

```

</details>

**Comment by Blackduke77** [comment]
So, I couldn't work out what to do with the cluster command, but I did install the quirk. I now have a light control for switch 1, and it is either (Blue or Red). Also the Switch control for Switch 1 is now disabled. So cannot operate switch 1. 

I think you expected that.

Does that's help?

I found out there is a green as well when you press Identify)

**Comment by Davej817** [comment]
First time I have used quirks and I too get the same result. Control of the backlight is now possible and socket 1 is switched on and off with the light switch. 
Thanks for the workaround.

**Comment by Blackduke77** [comment]
> First time I have used quirks and I too get the same result. Control of the backlight is now possible and socket 1 is switched on and off with the light switch. Thanks for the workaround.

How are you controlling the light, mine has just moved the switch operation for switch 1 to a new entity called light, and my original switch no longer operates

**Comment by Davej817** [comment]
The switch marked light controls socket 1 and the one marked switch operates the second socket.
![image](https://github.com/zigpy/zha-device-handlers/assets/2206975/05da2797-e97d-418f-8a44-2755b1c4d52c)
Clicking on the icon/word light gives brightness control. 
![image](https://github.com/zigpy/zha-device-handlers/assets/2206975/8b92024c-c151-4412-8b9a-f2bb1f651708)
The second switch does not do anything.

**Comment by Blackduke77** [comment]
oh look your right... @TheJulianJES is this the end result, or just testing for a perm fix?

**Comment by Blackduke77** [comment]
I upgraded to 23.10, removed the quirk, removed the device, and re-added it. I am back to where we were in the beginning. was this fix meant to be in this release or the next

**Comment by Blackduke77** [comment]
@TheJulianJES here is the diagnostics, does this help

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.10.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.10.0",
    "host_os": "Home Assistant OS 10.5",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "octopus_energy": {
      "version": "8.3.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "after_dependencies": [
      "onboarding",
      "usb"
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "config_flow": true,
    "dependencies": [
      "file_upload"
    ],
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp",
      "universal_silabs_flasher"
    ],
    "requirements": [
      "bellows==0.36.5",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.104",
      "zigpy-deconz==0.21.1",
      "zigpy==0.57.2",
      "zigpy-xbee==0.18.3",
      "zigpy-zigate==0.11.0",
      "zigpy-znp==0.11.5",
      "universal-silabs-flasher==0.0.14",
      "pyserial-asyncio-fast==0.11"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_uzg-01._tcp.local.",
        "name": "uzg-01*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 49975,
    "manufacturer": "Aurora",
    "model": "DoubleSocket50AU",
    "name": "Aurora DoubleSocket50AU",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "manufacturer_code": 4636,
    "power_source": "Mains",
    "lqi": 192,
    "rssi": -52,
    "last_seen": "2023-10-09T23:59:11",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4636, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=0, maximum_outgoing_transfer_size=100, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0009",
          "input_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x0b04"
          ],
          "output_clusters": [
            "0x0019"
          ]
        },
        "2": {
          "profile_id": "0x0104",
          "device_type": "0x0009",
          "input_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0b04"
          ],
          "output_clusters": []
        }
      },
      "manufacturer": "Aurora",
      "model": "DoubleSocket50AU"
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "button.aurora_doublesocket50au_identify",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_apparent_power",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_rms_current",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_rms_voltage",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_ac_frequency",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_power_factor",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_active_power",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_apparent_power_2",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_rms_current_2",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_rms_voltage_2",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_ac_frequency_2",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_power_factor_2",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "sensor.aurora_doublesocket50au_active_power_2",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "switch.aurora_doublesocket50au_switch",
        "name": "Aurora DoubleSocket50AU"
      },
      {
        "entity_id": "switch.aurora_doublesocket50au_switch_2",
        "name": "Aurora DoubleSocket50AU"
      }
    ],
    "neighbors": [
      {
        "device_type": "Coordinator",
        "rx_on_when_idle": "On",
        "relationship": "Parent",
        "extended_pan_id": "**REDACTED**",
        "ieee": "**REDACTED**",
        "nwk": "0x0000",
        "permit_joining": "Unknown",
        "depth": "0",
        "lqi": "76"
      }
    ],
    "routes": [
      {
        "dest_nwk": "0x0000",
        "route_status": "Active",
        "memory_constrained": false,
        "many_to_one": false,
        "route_record_required": false,
        "next_hop": "0x0000"
      },
      {
        "dest_nwk": "0xFB70",
        "route_status": "Discovery_Underway",
        "memory_constrained": false,
        "many_to_one": false,
        "route_record_required": false,
        "next_hop": "0xFFFE"
      }
    ],
    "endpoint_names": [
      {
        "name": "MAIN_POWER_OUTLET"
      },
      {
        "name": "MAIN_POWER_OUTLET"
      }
    ],
    "user_given_name": null,
    "device_reg_id": "5b39e53fd8a15b32669530e00903398b",
    "area_id": "office",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "MAIN_POWER_OUTLET",
          "id": 9
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 1
              }
            },
            "unsupported_attributes": {
              "0x4003": {
                "attribute_name": "start_up_on_off"
              }
            }
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "Aurora"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "DoubleSocket50AU"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0b04": {
            "endpoint_attribute": "electrical_measurement",
            "attributes": {
              "0x0300": {
                "attribute_name": "ac_frequency",
                "value": 50
              },
              "0x050b": {
                "attribute_name": "active_power",
                "value": 0
              },
              "0x050f": {
                "attribute_name": "apparent_power",
                "value": 65535
              },
              "0x0000": {
                "attribute_name": "measurement_type",
                "value": 1
              },
              "0x0508": {
                "attribute_name": "rms_current",
                "value": 6
              },
              "0x0505": {
                "attribute_name": "rms_voltage",
                "value": 246
              }
            },
            "unsupported_attributes": {
              "0x0600": {
                "attribute_name": "ac_voltage_multiplier"
              },
              "0x0601": {
                "attribute_name": "ac_voltage_divisor"
              },
              "0x0602": {
                "attribute_name": "ac_current_multiplier"
              },
              "0x0603": {
                "attribute_name": "ac_current_divisor"
              },
              "0x0604": {
                "attribute_name": "ac_power_multiplier"
              },
              "0x0605": {
                "attribute_name": "ac_power_divisor"
              },
              "0x0401": {
                "attribute_name": "ac_frequency_divisor"
              },
              "0x0400": {
                "attribute_name": "ac_frequency_multiplier"
              },
              "0x0403": {
                "attribute_name": "power_divisor"
              },
              "0x0402": {
                "attribute_name": "power_multiplier"
              },
              "0x050a": {
                "attribute_name": "rms_current_max"
              },
              "0x0507": {
                "attribute_name": "rms_voltage_max"
              },
              "0x050d": {
                "attribute_name": "active_power_max"
              },
              "0x0302": {
                "attribute_name": "ac_frequency_max"
              }
            }
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_level",
                "value": 254
              }
            },
            "unsupported_attributes": {
              "0x4000": {
                "attribute_name": "start_up_current_level"
              },
              "0x0011": {
                "attribute_name": "on_level"
              },
              "0x0010": {
                "attribute_name": "on_off_transition_time"
              },
              "0x0014": {
                "attribute_name": "default_move_rate"
              },
              "0x0012": {
                "attribute_name": "on_transition_time"
              },
              "0x0013": {
                "attribute_name": "off_transition_time"
              }
            }
          }
        },
        "out_clusters": {
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "2": {
        "device_type": {
          "name": "MAIN_POWER_OUTLET",
          "id": 9
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 1
              }
            },
            "unsupported_attributes": {
              "0x4003": {
                "attribute_name": "start_up_on_off"
              }
            }
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0b04": {
            "endpoint_attribute": "electrical_measurement",
            "attributes": {
              "0x0300": {
                "attribute_name": "ac_frequency",
                "value": 50
              },
              "0x050b": {
                "attribute_name": "active_power",
                "value": 0
              },
              "0x050f": {
                "attribute_name": "apparent_power",
                "value": 65535
              },
              "0x0000": {
                "attribute_name": "measurement_type",
                "value": 1
              },
              "0x0508": {
                "attribute_name": "rms_current",
                "value": 3
              },
              "0x0505": {
                "attribute_name": "rms_voltage",
                "value": 246
              }
            },
            "unsupported_attributes": {
              "0x0600": {
                "attribute_name": "ac_voltage_multiplier"
              },
              "0x0601": {
                "attribute_name": "ac_voltage_divisor"
              },
              "0x0602": {
                "attribute_name": "ac_current_multiplier"
              },
              "0x0603": {
                "attribute_name": "ac_current_divisor"
              },
              "0x0384": {},
              "0x0605": {
                "attribute_name": "ac_power_divisor"
              },
              "0x0604": {
                "attribute_name": "ac_power_multiplier"
              },
              "0x0401": {
                "attribute_name": "ac_frequency_divisor"
              },
              "0x0400": {
                "attribute_name": "ac_frequency_multiplier"
              },
              "0x0403": {
                "attribute_name": "power_divisor"
              },
              "0x0402": {
                "attribute_name": "power_multiplier"
              },
              "0x050a": {
                "attribute_name": "rms_current_max"
              },
              "0x0507": {
                "attribute_name": "rms_voltage_max"
              },
              "0x050d": {
                "attribute_name": "active_power_max"
              },
              "0x0302": {
                "attribute_name": "ac_frequency_max"
              }
            }
          }
        },
        "out_clusters": {}
      }
    }
  }
}

**Comment by TheJulianJES** [comment]
> I upgraded to 23.10, removed the quirk, removed the device, and re-added it. I am back to where we were in the beginning. was this fix meant to be in this release or the next

No, as it's a workaround and creates a new entity (whilst deleting the old one), it won't be pushed into a stable release for now until a proper solution is made. You can keep using the custom quirk for now though.

**Comment by Blackduke77** [comment]
Thanks for the clarification, let me know if I can help in anyway

**Comment by Hedda** [comment]
@davejarrard @Blackduke77 While it will likely not help with this issue now, suggest that you also always try contacting the manufacturer for support to request a firmware update for this product or at least other future products to make it/them comply with standard Zigbee specifications so there will be no need to apply ZHA Device Handlers (quirks) as workarounds. Referring to:

https://www.home-assistant.io/integrations/zha#knowing-which-devices-are-supported

https://www.home-assistant.io/integrations/zha#how-to-add-support-for-new-and-unsupported-devices

https://github.com/zigpy/zha-device-handlers/blob/dev/README.md

That is also why all devices in Blakadder's Zigbee Device Compatibility Repository also have this directly related comment:

"**_If the device is following Zigbee standards it is possible it will work with other gateway solutions, it is just not confirmed as working yet!_**"

https://zigbee.blakadder.com/Aurora_AU-A1ZBDSS.html

**Comment by philipmather** [comment]
Appologies if you'd prefer this as a seperate thread?
Within the app and hub combo provided by this manufacturer for these sockets there exists the option to lock the sockets off as well. Has anyone worked out what option this would be under manage device?
Happy to write a quirk myself but is there abyway to determine what option it is?

**Comment by Davej817** [comment]
@philipmather I don't see anything in the diagnostics that mentions the locking function. I suppose if you detect the switch event activating you could immediately switch it off but it is not a perfect solution.

After looking further there is an enable in 'manage zigbee device' but setting from 1 to 0 only disables the first socket.
![image](https://github.com/zigpy/zha-device-handlers/assets/2206975/23d348e3-090c-4332-8483-65ba4fe07d6c)

**Comment by Blackduke77** [comment]
I see it in both device one and device two

![image](https://github.com/zigpy/zha-device-handlers/assets/8461433/135d853b-f8de-4bb0-ba5d-be9a6cd39f68)

**Comment by Blackduke77** [comment]
I have been testing these switches with ZHA and Smartthings to try and get to a good setup, this quirk was nearly there for me. It is missing for me the lock, and default on-off as below ( I think that's the one) I wouldn't want to put this on my HA or Freezer without it defaulting to on.

In my testing, I have automated things, which is great, but for some reason, HA is not picking up local on/off actions on the second / child switch. But it is fine on Switch 1 / Master. I have re-paired a few times. I was going to test on another switch. 

The smartthings integration is ok for basic operation, but it has a power meter issue on switch 2, but at least you can restore power state after the powerless


![image](https://github.com/zigpy/zha-device-handlers/assets/8461433/e204928f-596b-4dce-b21e-90006f464592)

**Comment by Blackduke77** [comment]
Could this be the lock

![image](https://github.com/zigpy/zha-device-handlers/assets/8461433/9d278907-14a5-46db-afad-ea65607ab005)

**Comment by appsfinder2** [comment]
quirk  need help missing a socket 

![Settings_–_Home_Assistant](https://github.com/zigpy/zha-device-handlers/assets/31155587/dfd3195b-2f97-4f9f-b55a-5f86aed6396e)


zha:
  database_path: /config/zigbee.db 
  enable_quirks: true
  custom_quirks_path: /config/zhaquirks

Enable quirks with the yaml above in your configuration.yaml file
Remove all devices that are supposed to use new quirks
Restart Home Assistant
Pair the devices again

then create a file in zhaquirks e.g. sockets.py put your code in that file.

restarted home assistant remove sockets and re added

but now only have one light and one switch not two switches and a light what did I do wrong?

**Comment by Davej817** [comment]
The quirk changes one of the switches to a light that we can get to the indicator properties. This was a dirty workaround and doesnt solve the problem for everyone.
