### ISSUE TITLE
[Device Support Request] Tuya Thermostat (_TZE200_viy9ihs7)

### ISSUE THREAD

**Issue by Lesterpig** [zigpy/zha-device-handlers#2601]
### Problem description

Using this device: https://www.amazon.fr/gp/product/B0CCXRC7VK/

Pairing OK but no attribute available.

### Solution description

Expecting the following controls:

- Get room temperature
- Get/Set setpoint temperature
- Get/Set global on/off status
- Get heating status
- Get/Set mode (manual/schedule)
- Get/Set schedule

### Device signature

<details><summary>Device signature</summary>

```json
"signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0051",
          "input_clusters": [
            "0x0000",
            "0x0004",
            "0x0005",
            "0xef00"
          ],
          "output_clusters": [
            "0x000a",
            "0x0019"
          ]
        }
      },
      "manufacturer": "_TZE200_viy9ihs7",
      "model": "TS0601"
    },
```

</details>

### Additional information

I found the following work on this device, and I am currently trying to develop a quirk.

https://github.com/Koenkk/zigbee2mqtt/issues/18589

https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/tuya.ts#L3821C5-L3888C7

**Comment by Lesterpig** [comment]
I have started some work, inspired by https://github.com/jacekk015/zha_quirks/blob/main/ts0601_thermostat_avatto.py

I found the following attributes for this device:

- 0x0101: [0] if powered-off, [1] if powered-on
- 0x0202: [0, 0, 0, 210] target temperature
- 0x0203: [0, 0, 0, 215] room temperature
- 0x0404: [0] if mode is "schedule", [1] if mode is "manual"
- 0x0465: [0] if not heating, [1] if heating

**Comment by jacekk015** [comment]
@Lesterpig Test from https://github.com/jacekk015/zha_quirks
quirk file:
ts0601_thermostat_zwt198.py

**Comment by ranko-ha** [comment]
Hi @jacekk015,

received my ZWT198 last week and couldn't find a quirk, so I constructed one using attributes @Lesterpig published here.
I based it on your code (ts0601_thermostat_Avvato.py) and ended up with something very similar to the quirk you published on Saturday :)

I can confirm that basic thermostat functionality works fine!

However, CHILD_LOCK and TEMP_CALIBRATION don't seem to do anything.
(I used the attribute values from your Avvato quirk, tried also with the new ones you used for ZWT198.)

Not sure if these attribute values are correct… How do you figure these values out anyway?
(I have zero experience with ZHA clusters etc) 

Would be nice if we could somehow figure out the values for other functions too (like frost_protection or battery_percentage_remaining)

I found a Z2M description in zigbee-herdsman-converters with info on additional ZWT198 "Datapoints" but don't know how to use/interpret this info.
[https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/tuya.ts#L3916C1-L3984C1](https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/tuya.ts#L3916C1-L3984C1)

**Comment by jacekk015** [comment]
@ranko-ha Without official doc's you can only guess or, someone with the Thermostat need to enable debug logging and do test's, mark test time, and the post the logs.
From the logs, using time, you can guess what attribute was modified. What was sent to HA.
That's only 100% method.

> However, CHILD_LOCK and TEMP_CALIBRATION don't seem to do anything.
I don't know - I don't have that Thermostat. Need to see DEBUG logs.

battery_percentage_remaining - I don't see any code in Z2M for that.
Switching to old batteries could be an option.
When pairing device still reports data slowly for next 5-10 minutes - specially battery operated.
Some devices doesn't report battery level, and some only 0/1 state like: ok/low

frost_protection
Got 5 TRV's. That function only worked when I've put TRV in the freezer.
Other people tested that also with same results.
We can add it but functionality is close to zero.

**Comment by ranko-ha** [comment]
Hi @jacekk015,                  
Standard out-of-the-box functionality was zero entities for ZWT198 in HA, so great to have a quirk.
Thanks a lot for your work! I learned a lot and now have a much better understanding of ZHA.

Don't really care so much about the extra stuff, it is just that I saw that Z2M-Docu so thought it could somehow be usable for us in ZHA too. :)

BTW:
I based my code on your avatto quirk so noticed a difference in how you defined ENDPOINT 2.
Does the zwt version use the proper class in OUTPUT_CLUSTERS (Endpoint references just the class name)?
Avatto version uses a different name so there is no doubt there...


**ts0601_thermostat_zwt198.py:


class ZWT198UserInterface(TuyaUserInterfaceCluster):
...

class ZWT198UserInterface(CustomTuyaOnOff):
...


            2: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.ON_OFF_SWITCH,
                INPUT_CLUSTERS: [ZWT198UserInterface],
                OUTPUT_CLUSTERS: [],
            },


**ts0601_thermostat_avvato.py:


class AvattoUserInterface(TuyaUserInterfaceCluster):
...

class AvattoChildLock(CustomTuyaOnOff):
...

            2: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.ON_OFF_SWITCH,
                INPUT_CLUSTERS: [AvattoChildLock],
                OUTPUT_CLUSTERS: [],
            },

**Comment by jacekk015** [comment]
Child Lock: There was a bug in two places. Corrected.
That's why I need debug logs for checking internal communication.

**Comment by pascalwhoop** [comment]
Just wanted to chime in that there has been some progress on this device by zigbee2mqtt community
https://github.com/Koenkk/zigbee-herdsman-converters/pull/6155

some more discussion happening here

https://github.com/Koenkk/zigbee2mqtt/issues/19351

any chance we can take those insights and bring them in to HA directly? 


I just threw this at GPT because honestly I'm still just wrapping my head around the ecosystem overall and didn't want to solve the hardest problem right away. If it is of any help, the result is the below

```python
"""TuYa ZWT198 Avatto Wall Thermostat."""

from zigpy.profiles import zha
from zigpy.quirks import CustomDevice
from zigpy.zcl.clusters.general import (
    Basic,
    Identify,
    Time,
    Ota,
)
from zigpy.zcl.clusters.hvac import Thermostat, UserInterface
from zigpy.zcl.clusters.security import IasZone

from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINT_ID,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MANUFACTURER,
    MODEL,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)
from zhaquirks.tuya import (
    TuyaManufClusterAttributes,
    TuyaPowerConfigurationCluster,
    TuyaThermostatCluster,
    TuyaUserInterfaceCluster,
)


class TuyaZWT198Thermostat(CustomDevice):
    """Custom device representing tuya ZWT198 thermostats."""

    signature = {
        # <SimpleDescriptor endpoint=1 profile=260 device_type=769
        # device_version=0
        # input_clusters=[0, 4, 5, 61184, 513]
        # output_clusters=[25, 10]>
        MODELS_INFO: [("_TZE200_viy9ihs7", "TS0601")],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.THERMOSTAT,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    Thermostat.cluster_id,
                    TuyaManufClusterAttributes.cluster_id,
                    TuyaPowerConfigurationCluster.cluster_id,
                ],
                OUTPUT_CLUSTERS: [Ota.cluster_id, Time.cluster_id],
            },
        },
    }

    replacement = {
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.THERMOSTAT,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Identify.cluster_id,
                    TuyaThermostatCluster,
                    TuyaUserInterfaceCluster,
                    TuyaPowerConfigurationCluster,
                ],
                OUTPUT_CLUSTERS: [Ota.cluster_id, Time.cluster_id],
            },
        },
    }

```

**Comment by jacekk015** [comment]
https://github.com/jacekk015/zha_quirks
File: ts0601_thermostat_zwt198.py
```
        MODELS_INFO: [
            ("_TZE200_viy9ihs7", "TS0601"),
        ],
```
