### ISSUE TITLE
Why lqi value in device info  is different from it in topology?

### ISSUE THREAD

**Issue by strawberryhcy** [zigpy/zha-device-handlers#2606]
![1c37bcac78ade5cc8aca227f109b0fcf](https://github.com/zigpy/zha-device-handlers/assets/123892221/3d01fb9d-0294-4828-bc88-68e6afec763c)
![aecce818e0e0a4450a16bb6c3d63f9ff](https://github.com/zigpy/zha-device-handlers/assets/123892221/b02fc1ee-f7b0-417b-9e4e-9ac5f54580bd)

I know what these two lqi values represent in the topology.But i want to know it in the device info.Why two device (coordinater and router)have 3 lqi value?

**Comment by MattWestb** [comment]
The topology is done with requesting all routers neighbors and the links to them.
The device cars is made from the LQI that the coordinator is getting with the package revived from the network and its depends of the rout its taken and if end devices is direct connected to the coordinator with  EZSP you is very likely getting 255 in most firmware versions (best is blocking the coordinator having direct children for getting more stable network).

**Comment by strawberryhcy** [comment]
> The topology is done with requesting all routers neighbors and the links to them. The device cars is made from the LQI that the coordinator is getting with the package revived from the network and its depends of the rout its taken and if end devices is direct connected to the coordinator with EZSP you is very likely getting 255 in most firmware versions (best is blocking the coordinator having direct children for getting more stable network).
I want to know why the values on the page are different from those in the topology diagram. As far as I know, the value of lqi comes from two places, but it has three values that are different from each other.

**Comment by strawberryhcy** [comment]
I want to know why the values on the page are different from those in the topology diagram. As far as I know, the value of lqi comes from two places, but it has three values that are different from each other.

**Comment by Shulyaka** [comment]
As @MattWestb already described, they come from 3 different sources. For the topology, the two LQI between the routers are requested from those routers. For the device info, the LQI is provided by the coordinator firmware and, depending on the firmware, could actually be the LQI of the last hop (i.e. between the coordinator and the nearest router)

**Comment by strawberryhcy** [comment]
> As @MattWestb already described, they come from 3 different sources. For the topology, the two LQI between the routers are requested from those routers. For the device info, the LQI is provided by the coordinator firmware and, depending on the firmware, could actually be the LQI of the last hop (i.e. between the coordinator and the nearest router)

Thank you for your answer. But in the connection between the router and coordinator, the neighbor table only has one value, and to my knowledge, the other value is the connection quality of the last message determined by the coordinator firmware 
   https://github.com/dmulcahey/zha-network-visualization-card/issues/46        So, I still feel puzzled about this.

**Comment by Shulyaka** [comment]
Every value in the topology graph comes from the neighbor tables. It could be the neighbor table of the coordinator itself if the coordinator supports loopback ZDO frames. Two devices would give two values for the link between them. See https://github.com/zigpy/zigpy/blob/50bb2171341bd44239898cfd3dd77b22ac49a03e/zigpy/appdb.py#L332

And the device info (and the zha network card) comes from the coordinator firmware with the last received packet, see
https://github.com/zigpy/zigpy/blob/50bb2171341bd44239898cfd3dd77b22ac49a03e/zigpy/application.py#L1008

I would not rely on the value in the device info because it is only for the last hop (and you would probably be more interested in the first hop).

**Comment by MattWestb** [comment]
@Shulyaka What is the LQI / RSSI coming for the https://github.com/dmulcahey/zha-network-card ?
I think its its from the nigbur scan from all routers in the network then i have seen it being updated then clicking update and sniffing the network.

**Comment by Shulyaka** [comment]
It comes from the device attributes (i.e. from the coordinator firmware), not the neighbor scan.

**Comment by dmulcahey** [comment]
https://github.com/home-assistant/frontend/blob/f43171f91c51a354fb0d7f8d7f152ab95e8fc16a/src/panels/config/integrations/integration-panels/zha/zha-network-visualization-page.ts#L248

The topology in HA uses the neighbor tables.

**Comment by MattWestb** [comment]
@dmulcahey is your https://github.com/dmulcahey/zha-network-card#zha-network-card using neighbor scans or the last hope to the coordinator ?

**Comment by dmulcahey** [comment]
The table is last hop set by zigpy on a per message basis. Neighbors are not used to build the table.
