### ISSUE TITLE
LEDVANCE Gardenpole Multicolor

### ISSUE THREAD

**Issue by CarstenZ1975** [zigpy/zha-device-handlers#2610]
### Problem description

The Gardenpoles used can be controlled via ZHA, but do not switch off completely. As long as the lamps are not coupled with ZHA, the LEDs are off, after coupling and first control it is as if the LEDs still have 10% luminosity in the switched off state. Is there any support from ZHA in the near future?

### Solution description

Integration in the supported devices

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by TheJulianJES** [comment]
You did not fill out the issue template. Device signature / diagnostic information are missing.
