### ISSUE TITLE
[Device Support Request] for Aqara T1 door and window sensor

### ISSUE THREAD

**Issue by sebimt301** [zigpy/zha-device-handlers#2631]
hey, I got 2  Aqara T1 door and window sensor( new version that had been launched in the past month, and it seems it is not supported either. neither the status or the battery. Any thoughts on how to fix this?

Device is initialized <Device model='lumi.magnet.agl02' manuf='LUMI' nwk=0x91F1 ieee=54:ef:44:10:00:92:52:06 is_initialized=True>
Checking quirks for LUMI lumi.magnet.agl02 (54:ef:44:10:00:92:52:06)
Considering <class 'zhaquirks.xiaomi.aqara.opple_switch.XiaomiOpple2ButtonSwitchFace2'>
Fail because endpoint list mismatch: {1, 2, 242} {1}
Considering <class 'zhaquirks.xiaomi.aqara.opple_switch.XiaomiOpple2ButtonSwitchFace1'>
Fail because endpoint list mismatch: {1, 2, 41, 42, 242, 51, 21, 31} {1}
Considering <class 'zhaquirks.xbee.xbee_io.XBeeSensor'>
Fail because endpoint list mismatch: {232, 230} {1}
Considering <class 'zhaquirks.xbee.xbee3_io.XBee3Sensor'>
Fail because endpoint list mismatch: {232, 230} {1}
Considering <class 'zhaquirks.tuya.ts0201.MoesTemperatureHumidtySensorWithScreen'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.smartthings.tag_v4.SmartThingsTagV4'>
Fail because device_type mismatch on at least one endpoint
Considering <class 'zhaquirks.smartthings.multi.SmartthingsMultiPurposeSensor'>
Fail because input cluster mismatch on at least one endpoint
Considering <class 'zhaquirks.netvox.z308e3ed.Z308E3ED'>
Fail because input cluster mismatch on at least one endpoint
Considering <class 'zhaquirks.gledopto.soposhgu10.SoposhGU10'>
Fail because endpoint list mismatch: {11, 13} {1}

this is the spec page i found digging around 
https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:magnet-sensor:0000A016:lumi-agl02:1:0000C80D

_Originally posted by @vistvanv in https://github.com/zigpy/zha-device-handlers/issues/2582#issuecomment-1733241147_

**Comment by TheJulianJES** [comment]
See https://github.com/home-assistant/core/issues/100805 for the HA issue and https://github.com/zigpy/zha-device-handlers/pull/2625 for the PR/fix/quirk.
