### ISSUE TITLE
[Device Support Request] Tuya TRV `_TZE200_b6wax7g0`

### ISSUE THREAD

**Issue by tomg1970** [zigpy/zha-device-handlers#2653]
### Problem description

Hello I have problems with zha to get the correct attributes for my (Tuya) TRV TS0601
from _TZE200_b6wax7g0 to get.
Is there already a zha_quirks for this thermostat?

Many many Thanks

### Solution description

I have researched for hours on the Internet, in forums and have not yet found a solution

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by MattWestb** [comment]
**If** posting some more information like Device diagnostic and signature, it **can** being someone is taking one look on the issue.

**Comment by tomg1970** [comment]
Thanks a lot for fast reply. Please just let me know if you need anything else.
With zha no battery level is displayed, the temperature target input is only possible in 1 degree steps and only the "Heat" mode is selectable and no necessary "Auto" mode to execute a temperature directed control.

[zha-693a8333a9f1baac757f5e139e719931-_TZE200_b6wax7g0 TS0601-9f9b1ccf6516f8efb274ce362629da37.json.txt](https://github.com/zigpy/zha-device-handlers/files/12927483/zha-693a8333a9f1baac757f5e139e719931-_TZE200_b6wax7g0.TS0601-9f9b1ccf6516f8efb274ce362629da37.json.txt)
[attribute.txt](https://github.com/zigpy/zha-device-handlers/files/12927484/attribute.txt)

**Comment by jacekk015** [comment]
https://github.com/jacekk015/zha_quirks
ts0601_trv_beca.py

**Comment by tomg1970** [comment]
Hi thanks for reply.
What is the fastest way to find out if the zha_quirks is also fully functional.
This my attributes now

```
hvac_modes:
  - heat
min_temp: 7
max_temp: 30
preset_modes:
  - none
  - away
  - Schedule
  - eco
  - boost
  - Temporary manual
current_temperature: 19
temperature: 20
hvac_action: heating
preset_mode: none
system_mode: '[<SystemMode.Heat: 4>]/heat'
occupied_heating_setpoint: 2000
friendly_name: ANNE HT
supported_features: 17
```
This a the entities i have now

```

      - entity: number.heizung_anne_number_boost_countdown
        name: Number Boost Countdown
      - entity: number.heizung_anne_number_boost_time
        name: Number Boost Time
      - entity: number.heizung_anne_number_eco_temperature
        name: Number Eco Temperature
      - entity: number.heizung_anne_number_max_temperature
        name: Number Max Temperature
      - entity: number.heizung_anne_number_min_temperature
        name: Number Min Temperature
      - entity: number.heizung_anne_number_temperature_calibration
        name: Number Temperature Calibration
      - entity: number.heizung_anne_number_valve_state
        name: Number Valve State
      - entity: switch.heizung_anne_switch
        name: Switch
      - entity: switch.heizung_anne_switch_2
        name: Switch
      - switch.anne
      - entity: binary_sensor.heizung_anne_binary_input
      name: Binary input
      - sensor.tze200_b6wax7g0_ts0601_lqi_2
      - sensor.tze200_b6wax7g0_ts0601_rssi_2
      - entity: sensor.heizung_anne_battery
        name: Battery
      - entity: climate.anne_ht
```

**Comment by jacekk015** [comment]
I don't understand the question. You have the TRV - just play with it.

**Comment by tomg1970** [comment]
Yes i do that. I just wanted to test if everything works.
I cannot find an `auto` mode, only a `heat` mode, is that correct?

Under `valve` I understand in normal case, how far the thermostat
opens and closes automatically and the value from 0-100%.
Why can I change this value manually? Or what does this device tell me:

entity: number.heizung_anne_number_valve_state
        name: Number Valve State

**Comment by jacekk015** [comment]
Valve state is an opening percentage.
preset_modes: Schedule is an Auto mode.
hvac_modes and system_mode is a function to HVAC panel. TRV can only heat, so Cool or Fan aren't proper here.

**Comment by tomg1970** [comment]
Hi, I already know the valve_state so far. But what is the background, why this should be manually changeable? 
I know that so, the TRV changes the valve_state from 0-100% depending on the need, how far the thermostat must be open or closed.

Here are the preset_modes - no auto or schedule mode

 
![image](https://github.com/zigpy/zha-device-handlers/assets/26352194/1760112a-8670-4203-8654-4525a77f7334)

The two "switch" also have no function? At least I haven't noticed anything. What are they supposed to do?

![image](https://github.com/zigpy/zha-device-handlers/assets/26352194/35999d19-221d-47ab-861c-3d357cd0f20e)

**Comment by jacekk015** [comment]
> Hi, I already know the valve_state so far. But what is the background, why this should be manually changeable?

Don't ask me. I don't own all of those TRV's models. Some people were trying to steer the valve directly.
If it works, and if that specific TRV allows that - I don't know.


>Here are the preset_modes - no auto or schedule mode

To presets to work there need to be code in the quirk and in the HA ZHA.
For Beca all is there.
In quirk you have:
https://github.com/jacekk015/zha_quirks/blob/main/ts0601_trv_beca.py#L352-L364
and
https://github.com/jacekk015/zha_quirks/blob/main/ts0601_trv_beca.py#L429-L462

On the HA ZHA side you have:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/climate.py#L664-L734

So the question is do you have an updated HA version??


>The two "switch" also have no function?

No one will write 100 lines of code just for fun.
According to quirk code they are: BecaChildLock, BecaWindowDetection_A2
If you read the manual you will know what they do.

**Comment by tomg1970** [comment]
Thanks jacekk for your great and detailed feedback.
So I can understand it a little better. Which manual
do you think I should read to find out about ChildLock and WindowD?
can figure out? 
To make sure I do everything right: I only need to create a 'ts0601_trv_beca.py' in the folder 'custom_zha_en.py'.
in the folder 'custom_zha_quirks'?

**Comment by jacekk015** [comment]
https://github.com/jacekk015/zha_quirks#usage

ChildLock is a bit self-explaining but if you know, without manual, what does WindowDetection_A2 do that's not a problem for me.

**Comment by tomg1970** [comment]
Sorry for my bad English. Of course I know what Childlock and WindowDetection does. I just meant, how do you find out that switch.1 (Childlock) and switch2 (WindowDetection) have this function? 
With the valve control I have now understood that some users have tried to change the temperature control via the valve level. This does not work for me either. But I can now manage with a few automations. Thanks for your great help.
I have one question at the end. I would like to try to get along without BetterThermostat or änliches, in order to have everything in the hand.
How would you combine two TRVs in one room?
The HACS climate_group is unfortunately EOL. Can I somehow realize this in the groups.yaml?

**Comment by jacekk015** [comment]
> I just meant, how do you find out that switch.1 (Childlock) and switch2 (WindowDetection) have this function?

From the quirk Python code.
WindowDetection_A2 switch is probably do enable Window Open Detection. Not an Open Window indicator. That's why you should look into manual for that A2 name.

>With the valve control I have now understood that some users have tried to change the temperature control via the valve level.

They've wanna to have it to try if that works.

>I have one question at the end. I would like to try to get along without BetterThermostat or änliches, in order to have everything in the hand.
>How would you combine two TRVs in one room?

I don't know - I treat them separately in my house. I don't use BetterThermostat either.
Mostly that device have self-control. They have Schedule, PID inside. I'm not trying to me smarter than Chinese engineer that created a firmware inside the TRV. One thing I only use HA is to make them globally Off when I'm ventilating a top or bottom floor. And maybe sometimes Temp Calibration - since the are on the radiator who produces heat. They will lie a bit because of that.

**Comment by tomg1970** [comment]
Once again, thank you very much for your comments. That helps me very much.
But you can't access the internal scheduler of the TRV directly?
I have just for this still a scheduler in HA running, which tells me at which
which temperature should be and I have integrated an external room-temperature-sensor.
integrated. In addition, a window sensor, which lowers the TRV to 5 degrees, since this has no OFF mode.

**Comment by armellarcier** [comment]
Hi! I'd need this too so I'm digging this out
