### ISSUE TITLE
WXKG01LM - Xiaomi Long Press

### ISSUE THREAD

**Issue by bryantlee** [zigpy/zha-device-handlers#266]
Hi team!

Looking to see if it was possible to support long press options for the button.  It appears the button does not send explicit long press events, but perhaps Aquara hubs actually just calculate the difference between button press and release.

Zigbee2Mqtt appears to also do this as well.
https://www.zigbee2mqtt.io/devices/WXKG01LM.html

Any way to support this within Quirks?

**Comment by Adminiuga** [comment]
>## How to use device type specific configuration
>__long_timeout__: The WXKG01LM only reports a button press and release. By default, Zigbee2mqtt publishes a long click when there is at least 1000 ms between both events. It could be that due to delays in the network the release message is received late. This causes a single click to be identified as a long click. If you are experiencing this you can try experimenting with this option (e.g. long_timeout: 2000).

**Comment by bryantlee** [comment]
@Adminiuga - just making sure your response wasnt to me.  Do you think this is desirable functionality since it exists in zigbee2mqtt?

**Comment by Adminiuga** [comment]
Just confirming that it is not explicit button/zigbee functionality.

**Comment by peregrinus** [comment]
Hi @Adminiuga apologies for the ignorance but how do I utilise the 'long_timeout' option in home assistant. I don't see this in the ZHA config options for that device. Thanks

**Comment by dmulcahey** [comment]
He was referencing z2m docs that explain that they implemented a software trick to support this.

**Comment by peregrinus** [comment]
thanks for the quick reply David. ZHA is excellent and I appreciate the effort to date. hoping this becomes the standard as it's very stable with my purely Xiaomi environment post decommissioning my Xiaomi hubs.  triple click replaced my long click but would be nice to see ZHA offer the same down the track if possible.
