### ISSUE TITLE
[BUG] Hold device trigger duplicated for Aqara H1 switch

### ISSUE THREAD

**Issue by ChristianEvc** [zigpy/zha-device-handlers#2685]
### Bug description

The HOLD feature seems to be the same for both buttons of the two gang Aqara H1 switch. I.e. it isn't possible to set a different action based on long pressing the left and right buttons. They always have to be mapped to the same. 

In the "zhaquirks.xiaomi.aqara.opple_switch.XiaomiOpple2ButtonSwitchFace2" quirk file, it seems that there is an entry for long pressing of the second button, but its commented out. Any reason for this?

It would be great to be able to do a different long press per button, for example making long press left increase brightness, and vice versa.

### Steps to reproduce

When adding an action to the Aqara H1 button, the long press must apply to both buttons.

### Expected behavior

I expect to be able to assign a long press per button separetly

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by garyfoohw** [comment]
I have the same problem. regardless of left or right hold, I see the following (same) event triggered.
If I hold both, I get the event triggered twice.

```event_type: zha_event
data:
  device_ieee: <edited out>
  unique_id: <edited out>
  device_id: <edited out>
  endpoint_id: 1
  cluster_id: 64704
  command: 1_hold
  args:
    button: 1
    press_type: hold
    attr_id: 252
    value: 0
  params: {}
origin: LOCAL
time_fired: "2024-01-10T14:53:38.539251+00:00"
context:
  id: 01HKSXTNVBG5W97XTWWG1MF1M3
  parent_id: null
  user_id: null```
