### ISSUE TITLE
[BUG] _TZ3000_0zfrhq4i RMS current is wrong

### ISSUE THREAD

**Issue by tribela** [zigpy/zha-device-handlers#2699]
### Bug description

TS011F by _TZ3000_0zfrhq4i (Tuya smart plug) has a problem with RMS current status.
It reports 220V, 200A, 37W which is completely wrong.
I replaced to Another similar tuya plug, they reported 0.2A. So it is _mA_ not _A_

### Steps to reproduce

1. Setup Tuya smart plug (TS011F by _TZ3000_0zfrhq4i)
2. Use it and watch the reporting value

### Expected behavior

Reported value should be mA unit

### Screenshots/Video

<details><summary>Screenshot of history</summary>

![image](https://github.com/zigpy/zha-device-handlers/assets/5047683/bdd163de-3c6c-4b95-899f-6e4772cc3ddf)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4107, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0051",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x000a",
        "0x0702",
        "0x0b04",
        "0x1000",
        "0x1888",
        "0xe000"
      ],
      "output_clusters": [
        "0x0019"
      ]
    },
    "242": {
      "profile_id": "0xa1e0",
      "device_type": "0x0061",
      "input_clusters": [],
      "output_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZ3000_0zfrhq4i",
  "model": "TS011F",
  "class": "zigpy.device.Device"
}
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by jeroenvanpelt** [comment]
Experiencing a similar issue with the exact same type plug. Current seems to be in A not in mA. Not sure if related, but mine also does not report energy. It stays null.
