### ISSUE TITLE
[BUG] TRADFRI bulb GU10 WW 345lm8

### ISSUE THREAD

**Issue by Ichhabekeinenase** [zigpy/zha-device-handlers#2763]
### Bug description

I cant Dimm this Light via the Dashboard. When i do it over the OTA Cluster it works. If i do the Turn on Brightness i can dimm it to a lower Brightness but not Higher.

### Steps to reproduce

1. Go to the Light.
2. Try to Dimm the light.
3. Light doesnt Dimm.
4. Try to Dimm over the Turn on Slider. Dimms lower but doesnt go Higher.

### Expected behavior

Dimm the Bulb!

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature
LED2104R3
TRADFRI bulb GU10 WW 345lm8
<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.11.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.11.3",
    "host_os": "Home Assistant OS 11.1",
    "docker_version": "24.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "switch_manager": {
      "version": "1.3.1",
      "requirements": []
    },
    "dreame_vacuum": {
      "version": "v2.0.0b6",
      "requirements": [
        "pillow",
        "numpy",
        "pybase64",
        "requests",
        "pycryptodome",
        "python-miio",
        "py-mini-racer",
        "tzlocal"
      ]
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "zha_toolkit": {
      "version": "v1.1.6",
      "requirements": [
        "pytz"
      ]
    },
    "smartir": {
      "version": "1.17.8",
      "requirements": [
        "aiofiles>=0.6.0"
      ]
    },
    "nodered": {
      "version": "3.1.1",
      "requirements": []
    },
    "better_thermostat": {
      "version": "1.4.0",
      "requirements": []
    },
    "mass": {
      "version": "2023.6.0b2",
      "requirements": [
        "music-assistant==2.0.0b59"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "after_dependencies": [
      "onboarding",
      "usb"
    ],
    "codeowners": [
      "@dmulcahey",
      "@adminiuga",
      "@puddly"
    ],
    "config_flow": true,
    "dependencies": [
      "file_upload"
    ],
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp",
      "universal_silabs_flasher"
    ],
    "requirements": [
      "bellows==0.36.8",
      "pyserial==3.5",
      "pyserial-asyncio==0.6",
      "zha-quirks==0.0.106",
      "zigpy-deconz==0.21.1",
      "zigpy==0.59.0",
      "zigpy-xbee==0.19.0",
      "zigpy-zigate==0.11.0",
      "zigpy-znp==0.11.6",
      "universal-silabs-flasher==0.0.14",
      "pyserial-asyncio-fast==0.11"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_uzg-01._tcp.local.",
        "name": "uzg-01*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      }
    ],
    "is_built_in": true
  },
  "data": {
    "ieee": "**REDACTED**",
    "nwk": 372,
    "manufacturer": "IKEA of Sweden",
    "model": "\u001aTRADFRI bulb GU10 WW 345lm8",
    "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "quirk_id": null,
    "manufacturer_code": 4476,
    "power_source": "Mains",
    "lqi": 116,
    "rssi": -71,
    "last_seen": "2023-11-21T17:47:37",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0101",
          "input_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x1000",
            "0xfc7c"
          ],
          "output_clusters": [
            "0x0019"
          ]
        },
        "242": {
          "profile_id": "0xa1e0",
          "device_type": "0x0061",
          "input_clusters": [
            "0x0021"
          ],
          "output_clusters": [
            "0x0021"
          ]
        }
      },
      "manufacturer": "IKEA of Sweden",
      "model": "\u001aTRADFRI bulb GU10 WW 345lm8"
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "button.leuchte_test_identifizieren",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "light.leuchte_test_licht",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "number.leuchte_test_ein_aus_ubergangszeit",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "number.leuchte_test_auf_dem_niveau",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "number.leuchte_test_einschaltstrompegel",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "select.leuchte_test_startverhalten",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "DIMMABLE_LIGHT"
      },
      {
        "name": "PROXY_BASIC"
      }
    ],
    "user_given_name": "Leuchte Test",
    "device_reg_id": "8df9981317dfd9e634244a705f81e645",
    "area_id": "test",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "DIMMABLE_LIGHT",
          "id": 257
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "IKEA of Sweden"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "\u001aTRADFRI bulb GU10 WW 345lm8"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 1
              },
              "0x4003": {
                "attribute_name": "start_up_on_off",
                "value": 1
              }
            },
            "unsupported_attributes": {}
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_level",
                "value": 1
              },
              "0x0011": {
                "attribute_name": "on_level",
                "value": 0
              },
              "0x0010": {
                "attribute_name": "on_off_transition_time",
                "value": 5
              },
              "0x4000": {
                "attribute_name": "start_up_current_level",
                "value": 255
              }
            },
            "unsupported_attributes": {
              "0x0013": {
                "attribute_name": "off_transition_time"
              },
              "0x0014": {
                "attribute_name": "default_move_rate"
              },
              "0x0012": {
                "attribute_name": "on_transition_time"
              }
            }
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xfc7c": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "242": {
        "device_type": {
          "name": "PROXY_BASIC",
          "id": 97
        },
        "profile_id": 41440,
        "in_clusters": {
          "0x0021": {
            "endpoint_attribute": "green_power",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0021": {
            "endpoint_attribute": "green_power",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by MattWestb** [comment]
Its working very well on HA 2023.11.0 (after getting the right one then some one was putting in one no TF bulb in the package so one more run to Wbh).

**Comment by Ichhabekeinenase** [comment]
Is it that new one? Because I cant dimm it over the Dashboard. Mine is just the WW one without Color or Cold White.

**Comment by MattWestb** [comment]
Yes was baying it yesterday and its still working after firmware upgrade.
The "old" version is 400lm and is having the old IKEA Zigbee module and the new have the Silabs module.

**Comment by MattWestb** [comment]
LED2104R3

**Comment by MattWestb** [comment]
![20231121_122814](https://github.com/zigpy/zha-device-handlers/assets/49618193/cd977868-22fb-4804-9de3-99a41c5ed6cb)

**Comment by Ichhabekeinenase** [comment]
Which Dongle are you using? Because like i said I cant dimm them over the Sliders just over the Cluster Commands. On All 6 of them. Im on Home Assistant 2023.11.2.

**Comment by MattWestb** [comment]
HA 2023.11.0 and one "IKEA Billy EZSP" (the old IKEA module with latest EZSP 6.10.7).

**Comment by Ichhabekeinenase** [comment]
Ok thats weird! Im using an Sonoff ZB-Dongle E with the efr32mg21. I can try 11.0 in an Docker Image with a Bulb. Maybe that Fixes the Issue? Thats the only difference!

**Comment by TheJulianJES** [comment]
Try to remove the device from ZHA and then re-pair it. Perhaps the interview didn't complete properly.

**Comment by TheJulianJES** [comment]
But before you do that, please download the diagnostic information from HA for that bulb.
It's missing in the issue post.

It can be found on the device page for the bulb. Click the three dots on the left -> download device diagnostics.

**Comment by MattWestb** [comment]
Also after deleting it wait one minute or restart HA so the device is deleted OK in the database or its coming back with the "old" clusters that we dont like then new added is the only way getting all OK.

**Comment by Ichhabekeinenase** [comment]
Trying that Right now. Added the Diagnostic Information! If i change the Turn On Brightness and the Normal Brightness and then turn the Light On and Off it dimms over the Sliders. Im hoping this is not the Default Behavior for HA/Ikea Lights.

**Comment by Ichhabekeinenase** [comment]
Now my Test Light Dimms over the Normal Dimmer but only if i turn it off and on again in Home Assistant?
Heres the now Diagnostic Information!


 "data": {
    "ieee": "**REDACTED**",
    "nwk": 34862,
    "manufacturer": "IKEA of Sweden",
    "model": "\u001aTRADFRI bulb GU10 WW 345lm8",
    "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8",
    "quirk_applied": false,
    "quirk_class": "zigpy.device.Device",
    "quirk_id": null,
    "manufacturer_code": 4476,
    "power_source": "Mains",
    "lqi": 124,
    "rssi": -69,
    "last_seen": "2023-11-21T17:56:33",
    "available": true,
    "device_type": "Router",
    "signature": {
      "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
      "endpoints": {
        "1": {
          "profile_id": "0x0104",
          "device_type": "0x0101",
          "input_clusters": [
            "0x0000",
            "0x0003",
            "0x0004",
            "0x0005",
            "0x0006",
            "0x0008",
            "0x1000",
            "0xfc7c"
          ],
          "output_clusters": [
            "0x0019"
          ]
        },
        "242": {
          "profile_id": "0xa1e0",
          "device_type": "0x0061",
          "input_clusters": [
            "0x0021"
          ],
          "output_clusters": [
            "0x0021"
          ]
        }
      },
      "manufacturer": "IKEA of Sweden",
      "model": "\u001aTRADFRI bulb GU10 WW 345lm8"
    },
    "active_coordinator": false,
    "entities": [
      {
        "entity_id": "number.test_auf_dem_niveau",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "number.test_ein_aus_ubergangszeit",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "number.test_einschaltstrompegel",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "button.test_identifizieren",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "light.test_licht",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      },
      {
        "entity_id": "select.test_startverhalten",
        "name": "IKEA of Sweden \u001aTRADFRI bulb GU10 WW 345lm8"
      }
    ],
    "neighbors": [],
    "routes": [],
    "endpoint_names": [
      {
        "name": "DIMMABLE_LIGHT"
      },
      {
        "name": "PROXY_BASIC"
      }
    ],
    "user_given_name": "Test",
    "device_reg_id": "8df9981317dfd9e634244a705f81e645",
    "area_id": "test",
    "cluster_details": {
      "1": {
        "device_type": {
          "name": "DIMMABLE_LIGHT",
          "id": 257
        },
        "profile_id": 260,
        "in_clusters": {
          "0x0000": {
            "endpoint_attribute": "basic",
            "attributes": {
              "0x0004": {
                "attribute_name": "manufacturer",
                "value": "IKEA of Sweden"
              },
              "0x0005": {
                "attribute_name": "model",
                "value": "\u001aTRADFRI bulb GU10 WW 345lm8"
              }
            },
            "unsupported_attributes": {}
          },
          "0x0003": {
            "endpoint_attribute": "identify",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0004": {
            "endpoint_attribute": "groups",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0005": {
            "endpoint_attribute": "scenes",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0x0006": {
            "endpoint_attribute": "on_off",
            "attributes": {
              "0x0000": {
                "attribute_name": "on_off",
                "value": 1
              },
              "0x4003": {
                "attribute_name": "start_up_on_off",
                "value": 1
              }
            },
            "unsupported_attributes": {}
          },
          "0x0008": {
            "endpoint_attribute": "level",
            "attributes": {
              "0x0000": {
                "attribute_name": "current_level",
                "value": 129
              },
              "0x0011": {
                "attribute_name": "on_level",
                "value": 129
              },
              "0x0010": {
                "attribute_name": "on_off_transition_time",
                "value": 5
              },
              "0x4000": {
                "attribute_name": "start_up_current_level",
                "value": 255
              }
            },
            "unsupported_attributes": {
              "0x0012": {
                "attribute_name": "on_transition_time"
              },
              "0x0014": {
                "attribute_name": "default_move_rate"
              },
              "0x0013": {
                "attribute_name": "off_transition_time"
              }
            }
          },
          "0x1000": {
            "endpoint_attribute": "lightlink",
            "attributes": {},
            "unsupported_attributes": {}
          },
          "0xfc7c": {
            "endpoint_attribute": "manufacturer_specific",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0019": {
            "endpoint_attribute": "ota",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      },
      "242": {
        "device_type": {
          "name": "PROXY_BASIC",
          "id": 97
        },
        "profile_id": 41440,
        "in_clusters": {
          "0x0021": {
            "endpoint_attribute": "green_power",
            "attributes": {},
            "unsupported_attributes": {}
          }
        },
        "out_clusters": {
          "0x0021": {
            "endpoint_attribute": "green_power",
            "attributes": {},
            "unsupported_attributes": {}
          }
        }
      }
    }
  }
}

**Comment by Ichhabekeinenase** [comment]
The Light works Perfectly in Z2M. But i have everything in ZHA. Would like to get to the Bottom of this Issue!

**Comment by TheJulianJES** [comment]
Can you click on the light entity icon or entity title in HA to open the "more info" dialog and send a screenshot of how it looks?

**Comment by MattWestb** [comment]
My light is the same batch the its have the same bad data setting of the model string : `"value": "\u001aTRADFRI bulb GU10 WW 345lm8"` and i thing the last 8 is also one miss but its not the first time the factory have making bad data setting for IKEA devices but it shall behavior the same as my.
