### ISSUE TITLE
[Device Support Request] tuya curtain motor _TZE200_xu4a5rhj

### ISSUE THREAD

**Issue by ricfelten** [zigpy/zha-device-handlers#2766]
### Problem description

Related issue #1945 

ts0601_cover.py needs a new quirk added to support this device properly.
Currently, it pairs with no entities attached.

When using the below quirk i get error `Referenced entities cover.tze200_xu4a5rhj_ts0601_cover are missing or not currently available`

It seems the device is handled in this https://github.com/Koenkk/zigbee2mqtt/issues/17506.

### Solution description

Describe the solution you'd like
Be able to pair the device and control my curtains through HA.

### Device signature

<details><summary>Device signature</summary>

```json
{
"node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
"endpoints": {
"1": {
"profile_id": "0x0104",
"device_type": "0x0202",
"input_clusters": [
"0x0000",
"0x0004",
"0x0005",
"0x0102",
"0xef00"
],
"output_clusters": [
"0x0019"
]
},
"242": {
"profile_id": "0xa1e0",
"device_type": "0x0061",
"input_clusters": [],
"output_clusters": [
"0x0021"
]
}
},
"manufacturer": "_TZE200_xu4a5rhj",
"model": "TS0601",
"class": "ts0601_cover_2.TuyaCover"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

[home-assistant_zha_2023-11-21T15-03-25.249Z.log](https://github.com/zigpy/zha-device-handlers/files/13427934/home-assistant_zha_2023-11-21T15-03-25.249Z.log)

</details>

### Logs

<details><summary>Logs</summary>

[home-assistant_zha_2023-11-21T15-03-25.249Z.log](https://github.com/zigpy/zha-device-handlers/files/13428237/home-assistant_zha_2023-11-21T15-03-25.249Z.log)

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
"""Tuya based cover and blinds."""
from zigpy.profiles import zha
from zigpy.zcl.clusters.general import Basic, GreenPowerProxy, Groups, Ota, Scenes, Time

from zhaquirks.const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
)
from zhaquirks.tuya import (
    TuyaManufacturerWindowCover,
    TuyaManufCluster,
    TuyaWindowCover,
    TuyaWindowCoverControl,
)


class TuyaCover(TuyaWindowCover):
    """Tuya blind cover motor."""

    signature = {
        MODELS_INFO: [
            ("_TZE200_xu4a5rhj", "TS0601"),
        ],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.SMART_PLUG,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaManufCluster.cluster_id,
                ],
                OUTPUT_CLUSTERS: [Time.cluster_id, Ota.cluster_id],
            },
            242: {
                PROFILE_ID: 41440,
                DEVICE_TYPE: 97,
                INPUT_CLUSTERS: [],
                OUTPUT_CLUSTERS: [GreenPowerProxy.cluster_id],
            },
        },
    }
    replacement = {
        ENDPOINTS: {
            1: {
                DEVICE_TYPE: zha.DeviceType.WINDOW_COVERING_DEVICE,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                    TuyaManufacturerWindowCover,
                    TuyaWindowCoverControl,
                ],
                OUTPUT_CLUSTERS: [Ota.cluster_id],
            },
            242: {
                PROFILE_ID: 41440,
                DEVICE_TYPE: 97,
                INPUT_CLUSTERS: [],
                OUTPUT_CLUSTERS: [GreenPowerProxy.cluster_id],
            },
        },
    }
```

</details>

**Comment by AlterSu24** [comment]
Same model and same issue.
[https://github.com/zigpy/zha-device-handlers/issues/2483#issue-1813225750](https://github.com/zigpy/zha-device-handlers/issues/url)

I replyed my debug log and waited for a few months until now.
No further tips or instructions.

I tried with zigbee2mqtt, it works perfectly.
But I change back to ZHA because my ohter devices works more stable with ZHA.

Hope someone can help this out.

**Comment by ricfelten** [comment]
I also switched to zigbee2mqtt. In my limited use it works with this device great like you said and generally seems better for my other devices so far. Would certainly be nice to get it working for ZHA. I would be willing to try it out again.
