### ISSUE TITLE
[BUG] ""TS0601 _TZE200_locansqn"" temp sensor is recognized as a thermostat

### ISSUE THREAD

**Issue by darknessblade** [zigpy/zha-device-handlers#2785]
### Bug description

Temp sensor: _TZE200_locansqn TS0601, is seen as a thermostat instead of a Temp sensor

Link to the product:
https://www.aliexpress.com/item/1005005872890664.html?

### Steps to reproduce

1 connect the device
2 go to device page
3 entities are in correct

### Expected behavior

Only humidity and Temperature being displayed as entities

### Screenshots/Video

![temp sensor 2](https://github.com/zigpy/zha-device-handlers/assets/16239104/157eaef4-6961-404b-a271-874e1d3f2371)

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by javicalle** [comment]
I don't know if that sensor is supported, but yours is loading a local quirk from your HA installation.

**Comment by darknessblade** [comment]
It looks to be similar to this one:
https://smarthomescene.com/reviews/zigbee-temperature-humidity-sensor-with-a-screen-sz-t04-review/

Will try to see what happens if I remove it from the custom quirks file

Removing it does not resolve it It only hides the entities

**Comment by darknessblade** [comment]
I did find this, and It looks like I am not the only one who might have issues with the sensor

https://github.com/zigpy/zha-device-handlers/issues/1286


I also tried the custom quirks from:
https://smarthomescene.com/reviews/zigbee-temperature-humidity-sensor-with-a-screen-sz-t04-review/
But they did not work either. and only showed battery Info
