### ISSUE TITLE
New version of presence sensor

### ISSUE THREAD

**Issue by npa-homeassistant** [zigpy/zha-device-handlers#2814]
### Problem description

I have a zigbee presence sensor which has been working successfully for several months. So, I bought a second one for another room. On installing it, I can see that it's a slightly different version and ZHA doesn't create the entities for it. Both are TS0601 devices. The working one has manufacturer ID of _TZE204_ztc6ggyl, whereas the new (non-working) one is _TZE204_ijxvkhd0.

They are (or should be) functionally identical. I think that it just needs that new ID adding to the system?

### Solution description

Add the new ID of the device alongside the existing one so that both are recognised. 

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

### Additional information

You very helpfully did a very similar change for me a little while ago when I hit the exact same problem with a soil moisture sensor. I bought a second of these and, in the same way, the later one had a slightly different ID, despite being functionally identical.

**Comment by npa-homeassistant** [comment]
Subsequent to this, I then ordered another one from the original supplier, expecting it to be the original model and, instead, it was yet another different one. This new one is

_TZE204_qasjif9e

As before, this should have the same functionality as the original with both presence and illuminance.

**Comment by npa-homeassistant** [comment]
> Subsequent to this, I then ordered another one from the original supplier, expecting it to be the original model and, instead, it was yet another different one. This new one is
> 
> _TZE204_qasjif9e
> 
> As before, this should have the same functionality as the original with both presence and illuminance.

Belay that! I have just installed 2023.12.2 and the latter one, at least, seems now to be working. I will check the first one ASAP.

Thank you to whomever fixed this!

**Comment by mbhforum** [comment]
I am also having issues with TS0601 by _TZE204_ijxvkhd0.  I loaded the .py quirk below and it doesn't even attach to the device.  No errors in logs.

![image](https://github.com/zigpy/zha-device-handlers/assets/11696289/7c3075ce-2629-4d63-809a-809d7666e2e8)

class MmwRadarMotion(CustomDevice):
    """Millimeter wave occupancy sensor."""

    signature = {
        #  endpoint=1, profile=260, device_type=81, device_version=1,
        #  input_clusters=[0, 4, 5, 61184], output_clusters=[25, 10]
        MODELS_INFO: [
            ("_TZE204_sxm7l9xa", "TS0601"),
            ("_TZE204_ijxvkhd0", "TS0601"),
            ("_TZE200_ar0slwnd", "TS0601"),
            ("_TZE200_sfiy5tfs", "TS0601"),
            ("_TZE200_mrf6vtua", "TS0601"),
            ("_TZE200_ztc6ggyl", "TS0601"),
            ("_TZE204_ztc6ggyl", "TS0601"),
            ("_TZE204_ztc6ggyl", "TS0601"),
            ("_TZE204_sxm7l9xa", "TS0601"),
            ("_TZE200_wukb7rhc", "TS0601"),
            ("_TZE200_hl0ss9oa", "TS0601"),
            ],
