### ISSUE TITLE
[Device Support Request] for contact sensor _TZ3000_7d8yme6f 

### ISSUE THREAD

**Issue by rahulpdev** [zigpy/zha-device-handlers#2845]
### Problem description

The product is a door window contact sensor. The product manual describes an anti-tamper button on the back of the device and when I push in and release the button the LED on the device blinks once in response. 
I'm guessing that the second binary sensor showing in ZHA is related to this button but ZHA does not register any change in state when I push and release the button. The sensor always shows as Closed.

### Solution description

I haven't come across Zigbee contact sensors that have an anti-tamper feature (Aqara and Sonoff don't have it) and I think this is a useful feature for home security use cases so it would be a great feature addition to ZHA on this device if possible? 

The solution is for the second binary sensor to change state based on the position of the anti-tamper button

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

I've been able to add the device to ZHA and can see the following sensors:
![image](https://github.com/zigpy/zha-device-handlers/assets/30356979/251d5147-514a-44d5-871a-b2c7263fa40b)

![image](https://github.com/zigpy/zha-device-handlers/assets/30356979/b6c54586-b6e4-4c76-80e3-42bcf82bc2b1)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0402",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0500"
      ],
      "output_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x000a",
        "0x0019",
        "0x1000"
      ]
    }
  },
  "manufacturer": "_TZ3000_7d8yme6f",
  "model": "TS0203",
  "class": "zigpy.device.Device"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by robbionline** [comment]
Do you have any more issues with the device? I can't get it to work at all. I can add it with ZHA, but it doesn't change any of the status.

**Comment by rahulpdev** [comment]
> Do you have any more issues with the device? I can't get it to work at all. I can add it with ZHA, but it doesn't change any of the status.

The device is otherwise working fine with ZHA, the base contact sensor is reporting correctly and the battery also seems to reporting fine.

**Comment by Aldekein** [comment]
TS0203 by _TZ3000_7d8yme6f door sensor imports 2 sensors into HA.
First is magnet-activated and works well.
Second is tamper activated. I see the red LED in sensor blinking when I toggle it. But HA always presents it as off/closed.
