### ISSUE TITLE
Popular Zigbee blind controller motor not supported.

### ISSUE THREAD

**Issue by lrgfries** [zigpy/zha-device-handlers#2906]
### Problem description

Seeking the addition for the attached blind control motor to be supported for easy integration. 
Is one of the most popular motors on AliExpress.

### Solution description

AA

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]
![IMG_0266](https://github.com/zigpy/zha-device-handlers/assets/142952957/98a7522b-5365-421d-8046-56b2483df295)

</details>

### Device signature

<details><summary> IEEE: a4:9e:69:ff:fe:48:26:60
Nwk: 0x4eea
Device Type: EndDevice
LQI: 58
RSSI: Unknown
Last seen: 2024-01-14T17:47:40
Power source: Battery or Unknown </summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by TheJulianJES** [comment]
You need to provide the device signature and/or diagnostics information for that device. It can be found on the device page.
