### ISSUE TITLE
Zemismart Curtain Motor

### ISSUE THREAD

**Issue by Archibald255** [zigpy/zha-device-handlers#2910]
### Problem description

I have a Zemismart curtain motor (and track), with the model number " _TZE200_xaabybja" that works seamlessly. I've got some updated motors that have a different model and no longer work as intended. The new model number is "_TZE200_rmymn92d". It also doesn't seem to come up with any configurable device items (as listed in the ts0601_cover.py file).

### Solution description

Please add support to the new model number like the two that exist in the ts0601_cover.py file or copy the configuration of the original model (can provide on request).

### Screenshots/Video

![image](https://github.com/zigpy/zha-device-handlers/assets/129177954/ca7e8c88-a6eb-4d25-9d56-a29752170c80)
<First screenshot is the old/existing motor>

![image](https://github.com/zigpy/zha-device-handlers/assets/129177954/e66ad524-3a77-4199-a9cb-d3670bd5a04d)
<Second screenshot is the new motor>

### Device signature

<Old motor>
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0202",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0102",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_xaabybja",
  "model": "TS0601",
  "class": "ts0601_cover.TuyaMoesCover0601_inv_position"
}

<New motor>
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0051",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": "0xa1e0",
      "device_type": "0x0061",
      "input_clusters": [],
      "output_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZE200_rmymn92d",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>
[New motor - zha-3ee7318d58fb5c032c974117d96a82b4-_TZE200_rmymn92d TS0601-47b56814112599992cb498d0e006c073.json.txt](https://github.com/zigpy/zha-device-handlers/files/13933158/New.motor.-.zha-3ee7318d58fb5c032c974117d96a82b4-_TZE200_rmymn92d.TS0601-47b56814112599992cb498d0e006c073.json.txt)
[Old motor - zha-3ee7318d58fb5c032c974117d96a82b4-_TZE200_xaabybja TS0601-c486f4ef6465b0227e61bbf52b356a03.json.txt](https://github.com/zigpy/zha-device-handlers/files/13933159/Old.motor.-.zha-3ee7318d58fb5c032c974117d96a82b4-_TZE200_xaabybja.TS0601-c486f4ef6465b0227e61bbf52b356a03.json.txt)

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by dirkpitt35** [comment]
There is already a quirk for this, if you're still having issues update the issue and I'll share the steps.

Matt
