### ISSUE TITLE
[Device Support Request] TS0601 _TZE200_icka1clh  {MOES AM43}

### ISSUE THREAD

**Issue by darknessblade** [zigpy/zha-device-handlers#2926]
### Problem description

device is reconized as a Temperature sensor instead of a "Cover/blinds controller"

Link to order page:
https://www.aliexpress.com/item/1005005447997612.html?

According to ZHA it uses the following Quirk:"Quirk: ts0601_temperature2.TuyaNousE6TempHumiditySensor"
I have checked my custom quirks and it is not part of my custom quirks,

### Solution description

Custom quirk, or adding the device ID/manufactuer information to the correct ZHA entity.

MAIN Features needed:
-Cover [up, Pauze, down]
-Battery status

Optional:
-Motor direction
-Top endstop
-down endstop

### Screenshots/Video

![moes](https://github.com/zigpy/zha-device-handlers/assets/16239104/fddbce71-475f-4ebb-9907-f1191edf47c3)

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by darknessblade** [comment]
Checking the quirks, using it trough a custom quirk the following one looks to match
"class TuyaMoesCover0601(TuyaWindowCover):"

Only thing it doesn't transmit is Battery information.

**Comment by Berenhappinda** [comment]
Problem seems to be the same as: https://github.com/zigpy/zha-device-handlers/issues/2936

**Comment by nikolaynikolov681** [comment]
Hey, I have same issue :(
