### ISSUE TITLE
[Device Support Request] ikea Vallhorn motion sensor

### ISSUE THREAD

**Issue by pascal2313** [zigpy/zha-device-handlers#2935]
### Problem description

it is not working with zha it wont pair or if it does it stays stuck in Configuring

### Solution description

add the ikea vallhorn motion sensor

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0850",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0x0b05",
        "0x1000",
        "0xfc7c",
        "0xfc81"
      ],
      "output_clusters": [
        "0x0003",
        "0x0004",
        "0x0006",
        "0x0019",
        "0x1000"
      ]
    },
    "2": {
      "profile_id": "0x0104",
      "device_type": "0x0107",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0406"
      ],
      "output_clusters": [
        "0x0003"
      ]
    },
    "3": {
      "profile_id": "0x0104",
      "device_type": "0x0106",
      "input_clusters": [
        "0x0000",
        "0x0003",
        "0x0400"
      ],
      "output_clusters": [
        "0x0003"
      ]
    }
  },
  "manufacturer": "IKEA of Sweden",
  "model": "VALLHORN Wireless Motion Sensor",
  "class": "zigpy.device.Device"
}
```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```
[zha-d218b4ae4d185a36316a077f7a5c77c5-IKEA of Sweden VALLHORN Wireless Motion Sensor-8789c9768a3ee60d8311e29db3638ad4.json.txt](https://github.com/zigpy/zha-device-handlers/files/14039957/zha-d218b4ae4d185a36316a077f7a5c77c5-IKEA.of.Sweden.VALLHORN.Wireless.Motion.Sensor-8789c9768a3ee60d8311e29db3638ad4.json.txt)

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by MattWestb** [comment]
What coordinator is you using and the firmware is it ruing ?
Also trying adding it to one good router instead of the coordinator.

**Comment by pascal2313** [comment]
i am using an SONOFF ZigBee 3.0 USB Dongle Plus, TI CC2652P Coordinator. and i cant find the firmware version (is it worth trying to update it is working for all my other zigbee devices).
i have tested the device with an IKEA hub and then it is working. and people say it is working with z2m but i don't want to convert any devices.

**Comment by MattWestb** [comment]
TI coordinator firmware was having nearly all Zigbee 3 end device handling disabled from the beginning and is added in the 2023 firmware and if running older its not working with real Zigbee 3 end devices (but with Xiaomi / aqara not Zigbee 3 devices).
EZSP and de(f)conz is not having this problems.

**Comment by pascal2313** [comment]
i tryed updating the firmware to the latest firmware now it is connected but the info does not update i cant use the identify button it is saying failed to call button press 
![image](https://github.com/zigpy/zha-device-handlers/assets/69986711/7215b5c4-754c-475c-a6a5-d290fb4302b8)
![image](https://github.com/zigpy/zha-device-handlers/assets/69986711/0cd8c762-4da3-40d0-bd62-da741eea6c1a)

**Comment by MattWestb** [comment]
Delete the device and wait one minute before adding it new so the old settings is deleted in the database.
If have problem doing reconfigure take out the battery and putting it back then reconfigure and its not going to sleep before have getting the new config.

**Comment by pascal2313** [comment]
umm it just randomly started working i changed nothing

**Comment by MattWestb** [comment]
IKEAs 3 gen controllers can being tricky getting in pairing mode and also getting the configuration OK (if not they is not listening to nothing = looks dead) but is rock solid then is up and running.
This sensor is kinky on batteries being used and alkaline can triggering false detection and rechargeable looks working OK (have 4 of then and one in production).

**Comment by MattWestb** [comment]
Dirigera feed:
```
IKEA VALLHORN Wireless Motion Sensor Firmware
Installing (82%)
Installed version 0x01000057
Latest version 0x01000064

```
But not in TF so ZHA is getting it but not Z2M if i being right.
