### ISSUE TITLE
[BUG] Philips HUE Dimmer RWL021 (and RWL020, RWL022?) events missing from HA Core 2024.1.3 or 2024.1.4 and onwards

### ISSUE THREAD

**Issue by SkywiperSolutions** [zigpy/zha-device-handlers#2938]
### Bug description

Philips HUE Dimmer RWL021 (and RWL020, RWL022?) events missing from HA Core 2024.1.3 or 2024.1.4 and onwards.
Only very few events are left with amputated or no args.
Restoring HA Core 2024.1.2 re-establishes correct behavior.

### Steps to reproduce

Subscribe to zha_event and press all button combinations on Philips HUE wall dimmer remote.

### Expected behavior

Same behavior as in HA Core 2024.1.2.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

![20240122_103807](https://github.com/zigpy/zha-device-handlers/assets/71917588/09ebe49a-6a67-41d8-a688-fc2b765d495a)

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

**Comment by TheJulianJES** [comment]
You did not fill-out the issue template. Device signature and/or device diagnostics are needed.
Please download the device diagnostics from both releases and attach them here.
