### ISSUE TITLE
conbe II

### ISSUE THREAD

**Issue by lidans5** [zigpy/zha-device-handlers#2981]
### Problem description

is there a way to pair the device with conbee ii (deconz)

### Solution description

an update for pairing

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by Hedda** [comment]
Need details as there are no mind readers here. What device exactly and what are you doing?

Are you using your ConBee as a Zigbee Coordinator for the ZHA integration inside Home Assistant (and not deCONZ)? See -> https://www.home-assistant.io/integrations/zha/

If so then how do you do what and what are the problem symtoms?

Have you read and followed all tips in the troubleshooting sections in the ZHA integration documentation? Read -> https://www.home-assistant.io/integrations/zha/
