### ISSUE TITLE
[Device Support Request] for TS0601 TZE204_5cuocqty (avatto 1 ch zigbee dimmer)

### ISSUE THREAD

**Issue by vrtsman** [zigpy/zha-device-handlers#2999]
### Problem description

device entities not shown / discoverd, just the firmware version

### Solution description

please add this device (also the 2 way dimmer device( to the quirks or full ZHA supported devices

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0051",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": "0xa1e0",
      "device_type": "0x0061",
      "input_clusters": [],
      "output_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZE204_5cuocqty",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by 5bomen** [comment]
+1
`{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.FullFunctionDevice|MainsPowered|RxOnWhenIdle|AllocateAddress: 142>, manufacturer_code=4417, maximum_buffer_size=66, maximum_incoming_transfer_size=66, server_mask=10752, maximum_outgoing_transfer_size=66, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0051",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": "0xa1e0",
      "device_type": "0x0061",
      "input_clusters": [],
      "output_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZE204_5cuocqty",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}`

**Comment by Suxsem** [comment]
datapoints found until now:

            [1, 'state', 
            [2, 'brightness', 
            [???, 'min_brightness', 
            [4, 'switch_type',
            [???, 'max_brightness',
            [6, 'countdown',
            [14, 'power_on_behavior',
            [???, 'light_type',

cannot find min_brightness, max_brightness and light_type

**Comment by simoesp** [comment]
+1 Diagnostic Upload
[zha-1b1c0fd13410c1aebdc6ad142bff5c39-_TZE204_5cuocqty TS0601-22d02299e374c3016a255dd60f89b131.json](https://github.com/zigpy/zha-device-handlers/files/15096369/zha-1b1c0fd13410c1aebdc6ad142bff5c39-_TZE204_5cuocqty.TS0601-22d02299e374c3016a255dd60f89b131.json)

**Comment by stavragi** [comment]
I was watching this thread for updates since i have the same device so i thought i should inform everyone here.
It seems someone managed to get it working:
https://github.com/zigpy/zha-device-handlers/issues/3141

It doesn't seem to have been pulled to the main branch yet, but I tested the suggested changes and it worked for me.
