### ISSUE TITLE
Konke Multi Function Button - Battery unknown - No zha_events generated

### ISSUE THREAD

**Issue by walthowd** [zigpy/zha-device-handlers#300]
This is the Konke Multi function button: https://zigbee.blakadder.com/Konke_KPKEY.html

![Screenshot 2020-03-13 16 12 27](https://user-images.githubusercontent.com/864569/76659879-8d89f980-6545-11ea-8b8b-be3060dda460.png)

![Screenshot 2020-03-13 16 17 20](https://user-images.githubusercontent.com/864569/76660116-2ae52d80-6546-11ea-96ab-721edfb2fd11.png)
![Screenshot 2020-03-13 16 17 30](https://user-images.githubusercontent.com/864569/76660125-2de01e00-6546-11ea-9842-a5381be66a44.png)

Here is the zigpy debug log when joining the device:

https://paste.ubuntu.com/p/PFvQZyVHdd/

It appears the button presses are sent as with hex 80 (quick press), 81 (long press), 82 (double click). 

Those generate the following error:

```
[0xbcb8:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=122 command_id=Command.Report_Attributes>
Failed to parse message (b'087a0a00001080') on cluster 6, because 128 is not a valid Bool
```

Packet captures from:
http://faire-ca-soi-meme.fr/domotique/2019/07/16/test-du-kit-zigbee-konke-smart-home/

Single click:
![image](https://user-images.githubusercontent.com/864569/76660199-55cf8180-6546-11ea-8853-7375c7798ed3.png)

Long click:
![image](https://user-images.githubusercontent.com/864569/76660225-6253da00-6546-11ea-9f25-cdc19b27460c.png)

Double click:
![image](https://user-images.githubusercontent.com/864569/76660253-697ae800-6546-11ea-8fd3-dfcfd69cad46.png)

**Comment by walthowd** [comment]
Battery is a CR2450 3V

**Comment by Adminiuga** [comment]
If it sends standard attributes with wrong data type, then it would need a quirk like xiaomi device with custom deserialization handler

**Comment by walthowd** [comment]
This thread has a lot of relevant info, but I couldn't quite decipher it all:

https://github.com/Koenkk/zigbee2mqtt/issues/1689

**Comment by walthowd** [comment]
Support for Konke button has been merged into dev. Thanks @tube0013 !
