### ISSUE TITLE
[Device Support Request] TS0601_TZE200_r731zlxk

### ISSUE THREAD

**Issue by lth1436** [zigpy/zha-device-handlers#3014]
### Problem description

Not working with ZHA 
It is 6 gang switch 

![IMG_3984](https://github.com/zigpy/zha-device-handlers/assets/33173569/f1643682-9f6f-4152-9dcf-a7b3cfdf2aa8)

### Solution description

.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by javicalle** [comment]
Depending on the device signature it can be a `TuyaSextupleSwitchTO` or the `TuyaSextupleSwitchTO_GP` one:
* https://github.com/zigpy/zha-device-handlers/blob/e4d0663aa4fb2f4bd0b41825f1942e3d29893375/zhaquirks/tuya/ts0601_switch.py#L648
* https://github.com/zigpy/zha-device-handlers/blob/e4d0663aa4fb2f4bd0b41825f1942e3d29893375/zhaquirks/tuya/ts0601_switch.py#L732
