### ISSUE TITLE
[Device Support Request]  TY-ZG-Z-XF-ZJ

### ISSUE THREAD

**Issue by GreatBizarro** [zigpy/zha-device-handlers#3057]
### Problem description

Please provide a quirk for the model ZG-205Z human presence detector  Senzhen Wave Speed Technology Co. I can detect it and get a motion detection indication but that is it. I would like to be able to adjust it.
Thanks

### Solution description

quirk

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

  "manufacturer": "_TZE200_2aaelwxk",
  "model": "TS0225",
  "class": "zigpy.device.Device"

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by javicalle** [comment]
Duplicate of #2551
