### ISSUE TITLE
MiBoxer PIR1-ZB Motion Detektor TS0202

### ISSUE THREAD

**Issue by SkyDroVV** [zigpy/zha-device-handlers#3083]
### Problem description

![Screenshot_20240401_144101_Home Assistant](https://github.com/zigpy/zha-device-handlers/assets/162966965/6032ea69-57bb-44b5-8816-94a5d187cd78)

### Solution description

Generally support.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
[Paste the device signature here]
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by SkyDroVV** [comment]
I sent the motion detector back because of the poor connection and the long response time.

**Comment by jekader** [comment]
I have this device and it works just fine for me. It shows extra controls which are not in use but otherwise all good.

This seems to be a duplicate of #2357
