### ISSUE TITLE
[BUG] Refactor readme supported device

### ISSUE THREAD

**Issue by HydrelioxGitHub** [zigpy/zha-device-handlers#311]
I think that zigbee2mqtt supported devices page is very useful. ( [Link here](https://www.zigbee2mqtt.io/information/supported_devices.html) ). Can we copy the layout (image, model, supported features, etc... ) ? 
I can try to do PR for this if needed.

**Comment by dmulcahey** [comment]
@Adminiuga thoughts?

**Comment by Adminiuga** [comment]
Fine by me, but on the other side: maybe just join efforts with Blackadder?

**Comment by dmulcahey** [comment]
> Fine by me, but on the other side: maybe just join efforts with Blackadder?

I agree

**Comment by HydrelioxGitHub** [comment]
Blackadder ?

**Comment by dmulcahey** [comment]
https://zigbee.blakadder.com

**Comment by dmulcahey** [comment]
and you can find blakadder in the zigbee discord channel in the HA discord server

**Comment by HydrelioxGitHub** [comment]
Wow I was not aware about this website. There is much more devices supported than on the readme ...

**Comment by HydrelioxGitHub** [comment]
> https://zigbee.blakadder.com

This website is very well build. Why not just a link to the part with the HA filter ? It seems better to maintain only one place with updated info than two.

**Comment by Adminiuga** [comment]
Totally agree. 
@dmulcahey  I still have a wish we could have a button in ZHA config panel, where user could submit their device signature with all clusters and low-level info, like software version and maybe device scan results.

**Comment by dmulcahey** [comment]
@Adminiuga sure. Question is where do we send it?

**Comment by Adminiuga** [comment]
open a window with template filled for user to send via email?  
Or should we run a lambda function in AWS?

**Comment by dmulcahey** [comment]
@Adminiuga we have the button now to get the sig. What else do we wanna do here?
