### ISSUE TITLE
How to tell if quirk exist and used

### ISSUE THREAD

**Issue by Fredrik81** [zigpy/zha-device-handlers#3116]
Hello
Is there a good way to tell if quirk exist for device and if so is it used and I just need to re-pair?

**Comment by MattWestb** [comment]
Easiest way is looking on the device card and expanding the device information.
If having the last line "Quirk:" the system have loaded one quirk and if no like its not have loading one quirk (good devices do need quirk then being Zigbee certified ones).
If looks like in the screen shut its from HA and if loading local its giving the path to the quirk.
![QuirkLoaded](https://github.com/zigpy/zha-device-handlers/assets/49618193/004344d4-6101-4a9b-a3d1-02997ed44140)

**Comment by Fredrik81** [comment]
> Easiest way is looking on the device card and expanding the device information.
> 
> If having the last line "Quirk:" the system have loaded one quirk and if no like its not have loading one quirk (good devices do need quirk then being Zigbee certified ones).
> 
> If looks like in the screen shut its from HA and if loading local its giving the path to the quirk.
> 
> ![QuirkLoaded](https://github.com/zigpy/zha-device-handlers/assets/49618193/004344d4-6101-4a9b-a3d1-02997ed44140)
> 
> 
> 
> 
> 
> 

Followup 😄 
I heared that if quirk is added then re-pair is needed. Is that true?

And if yes is there a good way to tell if there quirk is added or updated and repair needed?
