### ISSUE TITLE
[Device Support Request] Schneider Electric 230V CCT599501

### ISSUE THREAD

**Issue by nnae06** [zigpy/zha-device-handlers#3170]
### Problem description

ZHA think is the version only powered by battery and is reported as EndDevice.

![Skärmbild från 2024-05-26 20-13-17](https://github.com/zigpy/zha-device-handlers/assets/13471084/57a5e265-931d-46a6-a07a-d3b160fa46e2)

### Solution description

The Schneider Electric 230V CCT599501 may be used as a Router as well.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4190, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "20": {
      "profile_id": "0x0104",
      "device_type": "0x0402",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0x0402",
        "0x0500",
        "0x0b05",
        "0xfc04"
      ],
      "output_clusters": [
        "0x0003",
        "0x0019"
      ]
    }
  },
  "manufacturer": "Schneider Electric",
  "model": "W599501",
  "class": "zigpy.device.Device"
}

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by meremortals70** [comment]
2nd vote for this. These are good smoke detectors and certified in Australia. Please add

**Comment by uvNikita** [comment]
General support for this smoke detector has been added here: https://github.com/zigpy/zha-device-handlers/pull/3897
The PR added possibility to configure some manufacturer specific settings as well as manually trigger the siren (test mode).

But due to the nature of this device being battery powered in addition to 230V, it don't think it can act as a router.
