### ISSUE TITLE
Tuya T&H devices give in ZHA only half of the battery percentage 

### ISSUE THREAD

**Issue by WilbertWilbers** [zigpy/zha-device-handlers#3185]
### Problem description

The Temperature and Humidity devices give in ZHA only half of the battery percentage that was presented in the Tuya Integration before and also  in the Zigbee device configuration. The real value is 100%! (so it is 100% end ZHA reports 50%)

![image](https://github.com/zigpy/zha-device-handlers/assets/159058432/7e71f8f4-0a04-4dc6-adf9-e7f88430c1fe)

![image](https://github.com/zigpy/zha-device-handlers/assets/159058432/4da3687f-a08a-4f4a-914d-79740612db38)

### Solution description

Solve the issue if that is possible?

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

![image](https://github.com/zigpy/zha-device-handlers/assets/159058432/7e71f8f4-0a04-4dc6-adf9-e7f88430c1fe)

![image](https://github.com/zigpy/zha-device-handlers/assets/159058432/4da3687f-a08a-4f4a-914d-79740612db38)

</details>

### Device signature

<details><summary>**Device name TS0601 by _TZE200_yjjdcqsq**

![image](https://github.com/zigpy/zha-device-handlers/assets/159058432/9e6504b1-2bd5-4c61-b317-445bcba94b9e)

</summary>

```json
[Paste the device signature here]
```
**Device name TS0601 by _TZE200_yjjdcqsq**
</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

### Additional information

This is my first comment that I posted on github. Please tell me if I haven't put the good fields in this request/error. Thank you.

**Comment by HelgeGitHub** [comment]
Same issue for _TZE204_yjjdcqsq TS0601 (sensor for temperature and huminity, using ts0601_sensor.py) : From the beginning of usage always battery 50%

**Comment by WilbertWilbers** [comment]
It was corrected! Thank you!
