### ISSUE TITLE
[Device Support Request] OSRAM Switch-LIGHTIFY

### ISSUE THREAD

**Issue by docgalaxyblock** [zigpy/zha-device-handlers#324]
**Is your feature request related to a problem? Please describe.**
This switch version is not yet supportet

**Describe the solution you'd like**
Complete device support
Primary buttons and secondary the battery (seems to report the voltage but HA says unknown)

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
https://pastebin.com/ZTE1nkrr

**Additional context**
zha_event log pressing all buttons
https://pastebin.com/Lm7W210A

**Comment by dmulcahey** [comment]
The device wasn’t removed. You need to press the remove device button on the device card in the ZHA config panel then press a button on the remote to wake it up. Wait about a minute then re-pair the device

**Comment by docgalaxyblock** [comment]
I've waited 5min between removing and adding it again...
Will setup a VM and pair it there...then it should be ok

**Comment by dmulcahey** [comment]
Did you wake the remote up when removing it? It’s a battery powered device. You have to ensure it isn’t sleeping or it won’t remove

**Comment by docgalaxyblock** [comment]
ehm nope but I have reset the remote

**Comment by dmulcahey** [comment]
Yeah that’s not gonna remove the data from zigpy. Pair it, remove it while waking it up to make sure that it’s removed for real. Then pair it.

**Comment by docgalaxyblock** [comment]
After I successfully destroyed my ZHA I think I got it right

**Comment by dmulcahey** [comment]
Yep paste looks good. I’ll take a look in a bit.

**Comment by docgalaxyblock** [comment]
@dmulcahey Do you know when this will be avaible in homeassistant?

**Comment by dmulcahey** [comment]
109

**Comment by docgalaxyblock** [comment]
@dmulcahey
I updated top 109 today, still No quirk.
(Removed it completely)

**Comment by dmulcahey** [comment]
Yeah I didn’t push an update into 109. Sorry about that.

**Comment by docgalaxyblock** [comment]
Can you bush it to next beta?

**Comment by dmulcahey** [comment]
Won’t be any betas until 110

**Comment by docgalaxyblock** [comment]
I mean the 110b1

**Comment by docgalaxyblock** [comment]
@dmulcahey Hi I got some problems regarding this device
I have three bitron video power metering plugs that turn off if I press the down left button (button 2 )
What I have done:

- New HA VW with different CC2531 stick

- Added the integration and definied the stick

- Added the smart plug and the osram switch

- Waited until the adding process finishes

- Then stayed at the connection dialog (made no manuall changes anythere at HA)

- Press the second button at the switch (down left one) and the plug turned off

Should I activate the ZHA debug logger and send you the logs?

https://bvsite.smabit.eu/index.php/produkte/smart-home-produkte/smart-plug-mit-verbrauchsdatenerfassung/

**Comment by dmulcahey** [comment]
Did you directly bind them at any point?

**Comment by docgalaxyblock** [comment]
No I never touched the binding because I could not find any documentatin about it

but in my opinion they are binded because I removed the coordinator ram my main and my testinh HA and the switch turns them off.
I could not understand why the switch turns all off. it should only act to the binded one right?

**Comment by docgalaxyblock** [comment]
So I today got an conbee2 to play with and tested the Osram Switch again.
The Switch talks directly to all devices, I connected a hue lamp to my ZHA and the unconfigured switch controlls the hole lamp (on/off, brightness, hue and color temp)
So it is a switch bug, I will take a look to purchased an OSRAM Gateway to update the firmware. Zigbe2mqtt is not able to update this device more specifically the switch is not supported by Z2M

**Comment by docgalaxyblock** [comment]
Update: The device has some problems...

#https://github.com/Koenkk/zigbee2mqtt/issues/962
#https://github.com/Koenkk/zigbee-herdsman-converters/pull/1112
#https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2917

**Comment by unromeo** [comment]
Any updates on this issue ? The OSRAM switch mini is working without issues in zigbee2mqtt, they somehow managed to solve the problems they had with it. Only in ZHA, the broadcasting is still present. I migrated everything from zigbee2mqtt but this is the only device I am not able to use inside ZHA.

**Comment by floriandotorg** [comment]
Is there any update on this? I just bought the switch and have this problem. @gnaggi, @unromeo could you find a solution? Thanks!

**Comment by TheJulianJES** [comment]
@floriandotorg Please create a new issue and fill-out the issue template.
