### ISSUE TITLE
[BUG] Samsung Motionv4 works, but v5 does not load the quirk

### ISSUE THREAD

**Issue by zaneclaes** [zigpy/zha-device-handlers#325]
**Describe the bug**
I have two Samsung SmartThings motion devices. One is v4, one is v5. 

The v4 correctly loads the quirk (screenshot 1).  The v5 does not (screenshot 2). As a result, the battery sensor does not work (battery icon in screenshot 2).

AFAICT, this should be supported ([source code](https://github.com/zigpy/zha-device-handlers/blob/1f8659ac6210ab83ae431676db4ba9dbfb70be83/zhaquirks/smartthings/motion.py#L21-L46)).

**To Reproduce**
Just add a v5 motion device.

**Expected behavior**
SmartThings Motion v5 should also load the appropriate quirk.

**Screenshots**
<img width="712" alt="Screen Shot 2020-04-07 at 9 23 53 AM" src="https://user-images.githubusercontent.com/2084821/78687826-cfdaf800-78b1-11ea-91ac-ddf9e7e9d418.png">

<img width="681" alt="Screen Shot 2020-04-07 at 9 24 02 AM" src="https://user-images.githubusercontent.com/2084821/78687756-bfc31880-78b1-11ea-8344-2a3bc15d5fd8.png">

**Comment by dmulcahey** [comment]
Are you on the beta of HA?

**Comment by zaneclaes** [comment]
@dmulcahey nope; `0.107.7` running in Docker. Should I be?
Thanks for the fast response btw.

**Comment by dmulcahey** [comment]
Will be in 108

**Comment by zaneclaes** [comment]
Just upgraded to `0.108.0b5` (via `homeassistant/home-assistant:rc`). The quirk is now loaded, but the battery still shows as "unknown":
<img width="708" alt="Screen Shot 2020-04-07 at 10 48 40 AM" src="https://user-images.githubusercontent.com/2084821/78697056-7973b680-78bd-11ea-830b-f7767374309d.png">
<img width="425" alt="Screen Shot 2020-04-07 at 10 49 46 AM" src="https://user-images.githubusercontent.com/2084821/78697087-8395b500-78bd-11ea-9de6-a4976e48244d.png">

**Comment by dmulcahey** [comment]
It will take time to report, you can force it by selecting the powerconfiguration cluster and selecting the battery_voltage attribute in the zha config panel. Then click read attribute and trip the device so that it wakes up.

David F. Mulcahey

**Comment by zaneclaes** [comment]
It seems a manual reset and re-pairing of the motion sensor was the only thing that fixed it.

What I tried first:
* Wait a half hour; confirm the RSSI was present
* `Reconfigure Device`
* Restart Home Assistant

Thanks for the fix though!
