### ISSUE TITLE
[REQUEST] Add same PyPa workflow as the other zigpy projects

### ISSUE THREAD

**Issue by Hedda** [zigpy/zha-device-handlers#332]
PyPa has a GitHub Action for publishing pre-built distribution packages to PyPI.

- https://github.com/pypa/gh-action-pypi-publish

Consider adding PyPa workflow in the same unified way as other zigpy libraries, see:
 
- https://github.com/zigpy/zigpy-deconz/pull/98

and

- https://github.com/zigpy/zigpy/pull/336
  - https://github.com/zigpy/zigpy/pull/338

Also, consider adding a long description to PyPi index by pointing to the README.md

- https://github.com/zigpy/zigpy/pull/371

Keeping this and other methods the same in all zigpy libraries can help unify them.

IMHO keep code for same functions/features the same to help the finding of issues.

This, in turn, could help existing and developers to which on all libraries for zigpy.

PS: Others features/functions which code could be reused and kept the same include:
- New zigpy initialization
- Support for radio lib configuration schemas
- Implement radio probe / API probe method
- USB reconnect (reconnect serial port on disconnects)

**Comment by dmulcahey** [comment]
Actions are already used to push this
