### ISSUE TITLE
[Device Support Request] TZE204_chbyv06x TS0601

### ISSUE THREAD

**Issue by josecarre** [zigpy/zha-device-handlers#3389]
### Problem description

Device appears in HA, but with no sensors.
Its a gas sensor:
```
    "manufacturer": "_TZE204_chbyv06x",
    "model": "TS0601",
    "name": "_TZE204_chbyv06x TS0601",
``` 

### Solution description

Add support for the device in ZHA.

### Screenshots/Video

<details><summary>Screenshots/Video</summary>

[Paste/upload your media here]

</details>

### Device signature

<details><summary>Device signature</summary>

```json
{
  "node_descriptor": {
    "logical_type": 1,
    "complex_descriptor_available": 0,
    "user_descriptor_available": 0,
    "reserved": 0,
    "aps_flags": 0,
    "frequency_band": 8,
    "mac_capability_flags": 142,
    "manufacturer_code": 4417,
    "maximum_buffer_size": 66,
    "maximum_incoming_transfer_size": 66,
    "server_mask": 10752,
    "maximum_outgoing_transfer_size": 66,
    "descriptor_capability_field": 0
  },
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0051",
      "input_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0xef00"
      ],
      "output_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": "0xa1e0",
      "device_type": "0x0061",
      "input_clusters": [],
      "output_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZE204_chbyv06x",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}
```

</details>

### Diagnostic information

<details><summary>Diagnostic information</summary>

```json
[Paste the diagnostic information here]
```

</details>

### Logs

<details><summary>Logs</summary>

```python
[Paste the logs here]
```

</details>

### Custom quirk

<details><summary>Custom quirk</summary>

```python
[Paste your custom quirk here]
```

</details>

**Comment by jacadcaps** [comment]
https://github.com/zigpy/zha-device-handlers/issues/2748 has a working quirk

**Comment by josecarre** [comment]
Hey, many thanks @jacadcaps , i've loaded it and it works perfect :)
![image](https://github.com/user-attachments/assets/bd83eb32-12f0-4b91-8a9b-e266278678ac)
