### ISSUE TITLE
[BUG] Aqara vibration sensor no zha_event just state_change

### ISSUE THREAD

**Issue by GH2user** [zigpy/zha-device-handlers#347]
**Describe the bug**
related to #124 I guess.
The Aqara vibration sensor is not reporting any zha_events but the binary_sensor does get updated with just 'vibration' instead of the tilt (incl angle), drop as available in the zha_event.

**To Reproduce**

**Expected behavior**
I would expect to see a zha_event  but it's a state-change I guess, not allowed to listen for these.

**Screenshots**
device details
![zha_device_details](https://user-images.githubusercontent.com/59734822/80865546-7c7a8080-8c8a-11ea-8968-486812de15ce.jpg)

binary events log
![zha_binary_events](https://user-images.githubusercontent.com/59734822/80865554-9025e700-8c8a-11ea-8beb-be31e7458406.jpg)

zha_event log same time period, nothing received after first two events (wakeup and motion)
![zha_zha_events](https://user-images.githubusercontent.com/59734822/80865863-31fa0380-8c8c-11ea-817f-53416814bbde.jpg)

zigbee.db attributes table for this device
![zigbee-db_attributes](https://user-images.githubusercontent.com/59734822/80865840-1989e900-8c8c-11ea-9478-187d95163ea5.jpg)

**Comment by dmulcahey** [comment]
How are you testing this?

**Comment by Adminiuga** [comment]
Aqara vibration sensor is an entity, not a remote so it doesn't do zha_events?

**Comment by dmulcahey** [comment]
It does events for tilt entity for vibration

**Comment by GH2user** [comment]
I'm listening for zha_events in HA - developer tools - listening for events.
Thinking there would always be a zha_event to get to the sensor_state....
But not receiving those at all, just the state change which is only 'vibration'

**Comment by dmulcahey** [comment]
`<Event zha_event[L]: device_ieee=00:15:8d:00:02:af:97:27, unique_id=00:15:8d:00:02:af:97:27:1:0x0500, endpoint_id=1, cluster_id=1280, command=Tilt, args=({'degrees': 79},)>` I get these... which is what is expected.
