### ISSUE TITLE
[BUG] Ikea blind not working with google home

### ISSUE THREAD

**Issue by blair287** [zigpy/zha-device-handlers#352]
Not sure when this issue starts but this is whats happening.

1) if i control the ikea blind via HA UI up or down it works fine.

2) if i ask google to open or close (linked through nabu casa) it will start moving then stop after about 10cm this happens every time.

3) if i unlink the blind from google and relink it works for first go then back to the 10cm and stop.

4) if i ask say open to 10% and its closed for example it will open or close normally issue only seems to occur when opening or closing commands used.

this comes up sometimes with a different number everytime i ask google to open or close the blind.

Log Details (WARNING)
Logger: zigpy_deconz.zigbee.application
Source: components/zha/core/helpers.py:32
First occurred: 8:53:38 PM (2 occurrences)
Last logged: 8:53:48 PM

Error while sending 250 req id frame: 0xd0
Error while sending 18 req id frame: 0xd0

**Comment by Adminiuga** [comment]
https://www.home-assistant.io/integrations/zha/#reporting-issues

However, if controlling from UI works fine, I fail to see how this would be ZHA's fault? 🤷‍♂️  Google integration should issue same  commands as UI You may want to  enable google integration (nabu casasa?) debug logging too

**Comment by blair287** [comment]
> https://www.home-assistant.io/integrations/zha/#reporting-issues
> 
> However, if controlling from UI works fine, I fail to see how this would be ZHA's fault?  Google integration should issue same commands as UI You may want to enable google integration (nabu casasa?) debug logging too

I have arrived at this conclusion too powering off the nuc running HA and turning it on again solved the issue for few hours.

How do I turn on debugging for both ZHA and Nabu Casa. There must be another command like stop or maybe it's sending open or close twice causing the blind to pause.

**Comment by Adminiuga** [comment]
https://www.home-assistant.io/integrations/zha/#reporting-issues how to turn on debug logging. Add `homeassistant.components.cloud` and I have no ideas which one is for google integration.

**Comment by blair287** [comment]
Probably not zigbees fault.
