### ISSUE TITLE
Move zhaquirks/schneider to zhaquirks/schneiderelectric

### ISSUE THREAD

**Issue by atsju** [zigpy/zha-device-handlers#3577]
It looks like Schneider folder is relatively new (only 5 month old and is a duplicate od schneiderelectric.
https://github.com/zigpy/zha-device-handlers/blob/97413e3ec2e5fdbcd17239b810d573cec4d3964d/zhaquirks/schneider/outlet.py#L1

It has side effect of creating 2 different manufacturers here : 
https://www.zigbee2mqtt.io/supported-devices/#v=Schneider

Should be a n easy fix and I would do it but I have no experience in this repo and have no idea of the potential side effects.

**Comment by TheJulianJES** [comment]
> It has side effect of creating 2 different manufacturers here : 
https://www.zigbee2mqtt.io/supported-devices/#v=Schneider

ZHA and Z2M are two different things. I think that's an issue on their side.
Still, we should merge both of them.
