### ISSUE TITLE
[Device Support Request] EigenStone Thermostat S2 (KTWKQ03ES)

### ISSUE THREAD

**Issue by slydiman** [zigpy/zha-device-handlers#364]
Could you add support for Aqara / EigenStone Thermostat S2 (KTWKQ03ES), please?
Id is lumi.airrtc.tcpecn02
http://docs.opencloud.aqara.com/en/guideline/product-discription/#thermostat

**Comment by Adminiuga** [comment]
where did you get it?

**Comment by slydiman** [comment]
https://www.aliexpress.com/item/32992549710.html

**Comment by slydiman** [comment]
Note also 
https://homekitnews.com/2020/05/27/aqara-hub-firmware-update-adds-homekit-functionality-for-more-devices/

**Comment by slydiman** [comment]
According to Chinese manual it can be connected to a remote temperature/humidity sensor, but I have no idea how. I have extended the internal thermal sensor using a coaxial cable.
This device has 5 relays (each 2A max) to control heater, cooler and fan (3 speeds). It can be used to control valves. I'm using additionally 2ch 16A Aqara relay to control an electric floor heater and monitor power consumption.

Look at this thread
https://github.com/Koenkk/zigbee2mqtt/issues/3306

**Comment by Adminiuga** [comment]
Try HA dev version. It supports generic Zigbee thermostat, so question is how closely xiaomi bis following Zigbee specs (rhetorical question)

**Comment by slydiman** [comment]
I'm using hass.io in docker on Raspberry PI4. 
What is the easiest way to try HA dev version? 
I have joined to beta channel in supervisor, but I don't see any updates.

**Comment by Adminiuga** [comment]
See on docker hub tag for the latest dev build, then in hassio cli something like `ha core update --version home-assistant.dev20200530` or whatever tag was on docker hub

**Comment by Adminiuga** [comment]
Or wait till Wednesday, I think beta is cut to on Wednesday
