### ISSUE TITLE
Support for lumi.lock.v1

### ISSUE THREAD

**Issue by Nemesis24** [zigpy/zha-device-handlers#39]
It will be very fine to support Xiaomi lumi.lock.v1.
`<SimpleDescriptor endpoint=1 profile=260 device_type=10 device_version=2 input_clusters=[0, 3, 1, 2, 25, 10] output_clusters=[25, 10]>`
I can help if you explain me !
Thank you.

**Comment by dmulcahey** [comment]
We don't have support for the lock domain yet in HA.

**Comment by Nemesis24** [comment]
This lock is a zigbee "sensor" and not serve as lock.

**Comment by dmulcahey** [comment]
I’m confused... what type of device are we actually talking about? If it is really a door lock we’ll wait to support it correctly rather than hack it as a sensor.

**Comment by Nemesis24** [comment]
This device is a simple lock like you've got on all the doors...
But it can detect what key is inserted and it's got 5 keys.
It can detect too if a wrong key or disbled key was inserted.

**Comment by dmulcahey** [comment]
Have a link to the product?

**Comment by Nemesis24** [comment]
https://www.youtube.com/watch?v=0pGiTnyLpU4

**Comment by Nemesis24** [comment]
Perhaps some good news https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1977#issuecomment-698438985

**Comment by pwet45** [comment]
Hello everyone, let me revive the subject. can you integrate lumi.lock.v1 in ZHA? Please
Tell me what you need.
thank you in advance

**Comment by pwet45** [comment]
Could you integrate this lock please?

A link that can help you, in any case I hope

https://easydomoticz.com/forum/viewtopic.php?f=28&t=10587

**Comment by Fenix999** [comment]
> We don't have support for the lock domain yet in HA.

According to the integrations page Locks are supported
https://www.home-assistant.io/integrations/zha/

I don't know if I can do anything to help, but if I can...

**Comment by ec-blaster** [comment]
I'm also interested in this integration.
As a matter of fact, this is the only device I'm missing to get to ZHA from Zigbee2Mqtt.
I can contribute if you guide me.
Thanks!

**Comment by adi90x** [comment]
Hello, 

Any news on this ? 

Regards

**Comment by Nemesis24** [comment]
I hope it could be integrate because this is the only device i can't connect on my Home assistant
If i can help say me something.
Thanks for all.

**Comment by adi90x** [comment]
> I'm also interested in this integration. As a matter of fact, this is the only device I'm missing to get to ZHA from Zigbee2Mqtt. I can contribute if you guide me. Thanks!

Is it working fine on zigbee2mqtt ?

**Comment by Nemesis24** [comment]
https://zigbee.blakadder.com/Xiaomi_Vima_A6121.html
This link says it's working.

**Comment by adi90x** [comment]
Any news on that ? Any chance to have it working in zha ?

**Comment by Nemesis24** [comment]
I would have this integrated in my home assistant, what can i do for helping ? Thanks for your answer.

**Comment by Nemesis24** [comment]
Hi, any news about that, how can i help ?

**Comment by Drun555** [comment]
Zigbee2MQTT has support for this lock for ages - so I'll stick to that for a time.

https://www.zigbee2mqtt.io/devices/A6121.html
