### ISSUE TITLE
[Device Support Request] Legrand Home/Away switch

### ISSUE THREAD

**Issue by Crocmagnon** [zigpy/zha-device-handlers#413]
**Is your feature request related to a problem? Please describe.**
Support Legrand wireless wall switch (with Netatmo) : https://www.legrand.fr/catalogue/interrupteur/interrupteur-sans-fil-supplementaire-pour-installation-connectee-celiane-with-netatmo-avec-plaque-laque-blanc

**Describe the solution you'd like**
This device should be able to control scenes (Arrival at home/Departure from home).

**Additionnal context**
I first started a thread on home-assistant core (https://github.com/home-assistant/core/issues/37436) because I couldn't discover the switches using ZHA. Now I can see them but the pairing isn't complete.

The device gets "discovered" multiple times and appears multiple times in the pairing interface. Only one device seems created though.

**Logs**

Debug logs: https://gist.github.com/Crocmagnon/32a46a435435c0cf52a4d3efe6144de9
Pairing logs: https://gist.github.com/Crocmagnon/79cfeaa49beeb40ebf47b77786de83a0

The device keeps blinking green even after I stopped the discovery in HA.

```json
{
  "node_descriptor": "<Optional byte1=18 byte2=64 mac_capability_flags=128 manufacturer_code=4129 maximum_buffer_size=89 maximum_incoming_transfer_size=63 server_mask=10752 maximum_outgoing_transfer_size=63 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0006",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0xfc01"
      ],
      "out_clusters": [
        "0x0000",
        "0x0003",
        "0x0005",
        "0x0019",
        "0xfc01"
      ]
    }
  },
  "manufacturer": " Legrand",
  "model": " Master remote SW Home / Away",
  "class": "zigpy.device.Device"
}
```

**Comment by dmulcahey** [comment]
Same as #411 look for zha_event
