### ISSUE TITLE
[FEATURE] Better Xiaomi battery percentage calculation

### ISSUE THREAD

**Issue by puddly** [zigpy/zha-device-handlers#415]
Interpreting the battery percentage as the voltage linearly decreasing between 3.0V and 2.8V results in most devices having 100% charge until they're already starting to act strangely or are effectively dead.

Here's what the heartbeat voltages for my devices look like:

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/32534428/87828066-2d37fb00-c84a-11ea-93a7-b3fcf2083b4c.png">

Some information about the data:

 - Most of my devices came with batteries that were already at the steady voltage of ~3.05V. Only brand new batteries caused spikes up to ~3.3V.
 - Two devices are kept outside (the only two that drop below 2.9V) while the rest stay indoors. Indoor temperatures fluctuate by about 15 degrees C, which is why the voltages aren't strictly decreasing as well.
 - Some devices (like the red one) never even get close to 3.0V.

I unfortunately did not save the entire heartbeat message so I do not have any of the SoC temperatures to correlate with this data for anything but temperature sensors. It seems like we could calculate a "true" battery percentage based on the temperature of the reported temperature of the battery and the battery voltage.

Here's what the two plotted together look like for a temperature sensor kept outside (only data source I have, sorry for the discontinuities):

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/32534428/87834034-5f038e80-c857-11ea-9d28-f2bec06f37bd.png">

I think anything is better than the current method so even a simple linear compensation might work. Some ideas:

 - Change the zero level to 2.9V and the fully charged level to 3.1V
 - Compute the percentage based on a temperature-compensated voltage. It appears that the voltage drops 50mV when the temperature drops 20C for me, so basing the computation on `v' = v - (t - 20) * 0.050` instead of `v` might work.

If anyone has more short-term sensor data with rapid temperature changes, you can pull all of this data from your Home Assistant log files if you have debug logging enabled for zigpy. It will be useful to calculate better constants.

**Comment by Adminiuga** [comment]
another problem I'm noticing with xiaomi, is the variation in the reported battery level vs actual battery level., eg battery is 3.2v, but xiaomi report 3.0v. That 200mV is quite a lot in % of battery life for xiaomi

**Comment by puddly** [comment]
Are you measuring the battery voltage without a load? I believe the relatively long duration between radio activity allows the battery's voltage to recover quite a bit.

**Comment by Adminiuga** [comment]
yes, but that was a fresh battery, so it shouldn't matter that much. Cause on the dead battery, radio activity would sag it even more. Per specs they should measure the battery voltage during transmissions, but since it is xiaomi...

**Comment by puddly** [comment]
Hmm, that's a tough one. Their favored microcontroller has an internal voltage reference and a 10 bit ADC so it seems like this should be reliable (unless they have their own reference voltage?). Is it one specific model?

**Comment by stast1** [comment]
zhaquirks.xiaomi.aqara.weather.Weather
![image](https://user-images.githubusercontent.com/48147949/91410203-3a83d480-e84f-11ea-8fc8-009d44860426.png)

**Comment by puddly** [comment]
@stast1: 2% to -2%? That means your battery voltage had a low of `2.798V` and a high of `2.802V`. Interesting. Both are lower than the lowest voltage I've ever observed.

What do the observed outdoor temperatures look like for the same range?

**Comment by stast1** [comment]
> What do the observed outdoor temperatures look like for the same range?

![image](https://user-images.githubusercontent.com/48147949/91526089-86944f00-e90b-11ea-85d5-5fd3ec127f9f.png)
![image](https://user-images.githubusercontent.com/48147949/91526135-9dd33c80-e90b-11ea-8cee-abc9e56f204e.png)

**Comment by stast1** [comment]
The sensor works without any problems.

**Comment by puddly** [comment]
That is interesting, mine become unstable by the time their voltage drops this low. Is the physical distance or the path taken by the packets to your coordinator somehow compensating for impact of the low voltage? Would you happen to still be using the battery that came with the sensor?

**Comment by stast1** [comment]
Distance is about 7 meters. I will use it until it stops working. This sensor is not critical for me.

**Comment by stast1** [comment]
![image](https://user-images.githubusercontent.com/48147949/93231260-375e7300-f781-11ea-95ed-f8702ba437be.png)

**Comment by stast1** [comment]
![image](https://user-images.githubusercontent.com/48147949/93624243-bdc8be00-f9e8-11ea-9a13-599b197486c0.png)

**Comment by stast1** [comment]
![image](https://user-images.githubusercontent.com/48147949/96337993-c79b1b00-1093-11eb-86c5-22a22d1fe546.png)
Interestingly, it will come to -100? :-)

**Comment by stast1** [comment]
![image](https://user-images.githubusercontent.com/48147949/97780889-2c746c00-1b90-11eb-8363-eb4bf0c167fb.png)

**Comment by puddly** [comment]
2.786V? The JN5169 advertises "*2.0 V to 3.6 V battery operation*". Let's see if yours can get down to -800%.

Following Energizer's chart for CR2032 batteries, your battery is either at about 12% or 25% charge level (not sure if the sensor's discharge is closer to "continuous" or "pulse").

Maybe your sensor is very close to a Zigbee router or the coordinator itself so its reducing range due to the dropping voltage may not be causing it to drop off the network?

**Comment by stast1** [comment]
> Maybe your sensor is very close to a Zigbee router or the coordinator itself so its reducing range due to the dropping voltage may not be causing it to drop off the network?

This is the farthest sensor on my network. About 5 meters through the wall. There is also a second sensor inside the refrigerator.:
![image](https://user-images.githubusercontent.com/48147949/97798945-621e6100-1c33-11eb-825f-535f09a9d1fa.png)

**Comment by stast1** [comment]
![image](https://user-images.githubusercontent.com/48147949/99898114-cf0f9e80-2ca7-11eb-8923-8dd20932d017.png)

**Comment by MattWestb** [comment]
I have not looking on Xiaomi sensors schematics but IKEAs have one resistor in serial from the battery and the chip and some extra capacitors for killing spikes then the radio is transmitting.
Its making the measurement not being the real battery more the chip working voltage that is good and bad then calculating the % of the battery power left.
My experience of both is that they can working well with low battery level if having god radio connection but if trying repairing them its not working at all if the battery is little low (the LED blinking for reset and little then start pairing and then stopping blinking and pairing).

**Comment by stast1** [comment]
Everything does not work.
![image](https://user-images.githubusercontent.com/48147949/100495837-fc50c680-3157-11eb-8d9a-1164a71655c2.png)

**Comment by SHxKM** [comment]
I've also experienced this today upon upgrading from HA 2021.1.X to 2021.6.4. Sensor (WSDCGQ11LM) reports temp/humidity just fine:

<img width="395" alt="Screen Shot 2021-06-12 at 19 16 49" src="https://user-images.githubusercontent.com/6573474/121782583-e914be00-cbb2-11eb-8f42-eac19d4e9261.png">

**Comment by MattWestb** [comment]
The interesting is wot voltage the sensor was reporting under the same time period (and also little before).

**Comment by SHxKM** [comment]
> The interesting is wot voltage the sensor was reporting under the same time period (and also little before).

Is this something I should have access to or can see?

**Comment by MattWestb** [comment]
I think its not being save in the database.
I was looking in my influxDB but its not being saved only the calculated % is there :-((

I was looking on my Lumi weathers (5) and all over 75% is stable and under is jumping 3-4 % up or down little now and then.

**Comment by SHxKM** [comment]
> I think its not being save in the database.
> I was looking in my influxDB but its not being saved only the calculated % is there :-((
> 
> I was looking on my Lumi weathers (5) and all over 75% is stable and under is jumping 3-4 % up or down little now and then.

Maybe I can ping the cluster attribute and see what's being reported there? I don't really know what it is though.

**Comment by MattWestb** [comment]
You  is having the attribute under the graph 2.8 V

**Comment by SHxKM** [comment]
OK. So I guess there's nothing to be done here?

**Comment by MattWestb** [comment]
I think you was running ZHA without the last patch for Xiaomi battery calculation #720 so the before update is the old way and after is the new but the voltage is the same only how its being made.
Before its was 100% more or less until it was dead.

**Comment by SHxKM** [comment]
I remember the value being 70% before upgrading HA (you can see in screenshot). 

Also, I ran pip install upgrade zha quirks and zigpy. I’m on the latest release of both.

**Comment by MattWestb** [comment]
I think the old calculation of 70% is in the new nearly zero = OK.

How "old" is the battery ? Lumi weather is running pity long on one.

**Comment by SHxKM** [comment]
I received this device in December 2020/January 2021. Is the battery life supposed to be so bad?
Also as said values seem to be reporting fine.

**Comment by MattWestb** [comment]
I think the sensor is 100% only the batty is little week.
My oldest is have getting one new but not the newest from November is still very OK.
I think you have getting one with old batter so only putting one new in and looking in some month how is running.

They is easy running over one yer is having one good router in the near.

**Comment by SHxKM** [comment]
> I think the sensor is 100% only the batty is little week.
> My oldest is have getting one new but not the newest from November is still very OK.
> I think you have getting one with old batter so only putting one new in and looking in some month how is running.
> 
> They is easy running over one yer is having one good router in the near.

Sorry I'm not following. My Zigbee router is Very close to this sensor. Are you suggesting I switch the battery? or just wait until this one dies?

**Comment by MattWestb** [comment]
As long its reporting its OK and then its stooping you can putting on new in.

**Comment by SHxKM** [comment]
Well what do you know, my Xiaomi device just died. So I guess reporting is pretty darn accurate...(?)

**Comment by MattWestb** [comment]
If they is have low battery and working its not possible resetting them and getting them pairing then its blinking on time but have not enough power for doing the pairing.

Hope you is having some new CR-2032 so you is getting it up and running !!

**Comment by SHxKM** [comment]
> If they is have low battery and working its not possible resetting them and getting them pairing then its blinking on time but have not enough power for doing the pairing.
> 
> Hope you is having some new CR-2032 so you is getting it up and running !!

Nope. The device simply died because the battery died. Put in a new battery and it's reporting a nice 94%.

**Comment by SHxKM** [comment]
Update: The new battery only last a few hours before going back to report at %0:

<img width="389" alt="Screen Shot 2021-06-14 at 08 59 40" src="https://user-images.githubusercontent.com/6573474/121846051-0cdd1e80-ccef-11eb-8177-02db3ebed160.png">

**Comment by MattWestb** [comment]
Looks like ZHA is doing all thing OK then you is getting relevant voltage but the sensor is very hungry on batteries or is the sensor defect.

Let it  running as long as possible on the "new" battery and then putting  in one new and see what happens.

I have baying my first 2 set of them from china but the last i have baying in EU so i have 3 years reclamation right if its going broken (they have printing the serial number on the bill so cant shagging the EU and Chinese devices).
