### ISSUE TITLE
[Documentation] Documentation to help get devices added

### ISSUE THREAD

**Issue by jlongman** [zigpy/zha-device-handlers#426]
Hey there, thanks in advance for what you do.

While trying to do #94 I had a hard time with two things:

- how to do a new device
- how to test the new files once added

The second is maybe simplest, the docs talk about using pypi as a source, (I've never done this but) do I push my code to pypi to validate whether what I'm doing works?  How would I do this?  (If it matters I'm in a hassio environment).

For the first, well I was trying to write this custom handling for the orvibo motion detector that works in zigbee2mqtt. I took an aqara device that had the same requirement to reset the state on a timer and copied a bunch off of it.  But it wasn't clear whether the MOTION AND IAS_ZONE was a choice/a feature to make integration or merely reflecting the devices zigbee reporting.

Additionally the aqara had a signature and a replacement which was referencing `cluster_id`s and `Clusters` _with_ `cluster_id`s so it was confusing. e.g.

```
    signature = {
# skip the SimpleDescriptor
        MODELS_INFO: [(LUMI, "lumi.sensor_motion.aq2")],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.OCCUPANCY_SENSOR,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    XIAOMI_CLUSTER_ID,
                    OccupancySensing.cluster_id, 
# etc
    }

    replacement = {
        SKIP_CONFIGURATION: True,
        ENDPOINTS: {
            1: {
                INPUT_CLUSTERS: [
                    BasicCluster,
                    PowerConfigurationCluster,
                    Identify.cluster_id,
# etc
```

(Is that the point?  the first is used for matching the device and the second is what we present?)

Anyways, I think I made my point is that how to build one isn't clear.  Maybe there's some mandatory fields.  And I get that this probably isn't trivial and even harder to explain, but are there resources somewhere I'm missing maybe?

**Comment by jlongman** [comment]
These are what I came up for what it's worth.  (The illuminance appears to be something I'm not sure is supported in the orvibo but maybe is in the aqara).

# orvibo/__init__.py
```
import asyncio
import logging
import math

from zigpy.quirks import CustomCluster, CustomDevice
from zigpy.zcl.clusters.measurement import (
    IlluminanceMeasurement,
)
from zigpy.zcl.clusters.security import IasZone

from .. import Bus, LocalDataCluster
from ..const import (
    CLUSTER_COMMAND,
    OFF,
    ON,
    ZONE_STATE,
)

_LOGGER = logging.getLogger(__name__)

ORVIBO = "ORVIBO"
BATTERY_SIZE = "battery_size"
ZONE_TYPE = 0x0001
MOTION_TYPE = 0x000D

class OrviboCustomDevice(CustomDevice):
    """Custom device representing orvibo devices."""

    def __init__(self, *args, **kwargs):
        """Init."""
        self.battery_bus = Bus()
        if not hasattr(self, BATTERY_SIZE):
            self.battery_size = 10
        super().__init__(*args, **kwargs)


class MotionCluster(LocalDataCluster, IasZone):
    """Motion cluster."""

    cluster_id = IasZone.cluster_id

    def __init__(self, *args, **kwargs):
        """Init."""
        super().__init__(*args, **kwargs)
        self._timer_handle = None
        self.endpoint.device.motion_bus.add_listener(self)
        super()._update_attribute(ZONE_TYPE, MOTION_TYPE)

    def motion_event(self):
        """Motion event."""
        super().listener_event(CLUSTER_COMMAND, None, ZONE_STATE, [ON])

        _LOGGER.debug("%s - Received motion event message", self.endpoint.device.ieee)

        if self._timer_handle:
            self._timer_handle.cancel()

        loop = asyncio.get_event_loop()
        self._timer_handle = loop.call_later(120, self._turn_off)

    def _turn_off(self):
        _LOGGER.debug("%s - Resetting motion sensor", self.endpoint.device.ieee)
        self._timer_handle = None
        super().listener_event(CLUSTER_COMMAND, None, ZONE_STATE, [OFF])


class IlluminanceMeasurementCluster(CustomCluster, IlluminanceMeasurement):
    """Multistate input cluster."""

    cluster_id = IlluminanceMeasurement.cluster_id
    ATTR_ID = 0

    def __init__(self, *args, **kwargs):
        """Init."""
        super().__init__(*args, **kwargs)
        self.endpoint.device.illuminance_bus.add_listener(self)

    def _update_attribute(self, attrid, value):
        if attrid == self.ATTR_ID and value > 0:
            value = 10000 * math.log10(value) + 1
        super()._update_attribute(attrid, value)

    def illuminance_reported(self, value):
        """Illuminance reported."""
        self._update_attribute(self.ATTR_ID, value)
```
# sn10zw-1cO.py
```
"""Orvibo motion sensor."""
import math

from zigpy.profiles import zha
from zigpy.quirks import CustomCluster
from zigpy.zcl.clusters.general import Basic, Identify, PowerConfiguration, Scenes, Groups
from zigpy.zcl.clusters.measurement import IlluminanceMeasurement
from zigpy.zcl.clusters.security import IasZone

from zhaquirks.xiaomi import BasicCluster
from . import (
    ORVIBO,
    OrviboCustomDevice,
)
from .. import Bus, PowerConfigurationCluster
from ..const import (
    DEVICE_TYPE,
    ENDPOINTS,
    INPUT_CLUSTERS,
    MODELS_INFO,
    OUTPUT_CLUSTERS,
    PROFILE_ID,
    SKIP_CONFIGURATION,
)

ORVIBO_CLUSTER_ID = 0xFFFF
#  Discovered endpoint information:
#   <Optional endpoint=1 profile=260 device_type=1026 device_version=1
#       input_clusters=[0, 3, 1280, 65535, 1]
#       output_clusters=[0, 4, 3, 5, 1]
#       >
#  {
#   "node_descriptor": "<NodeDescriptor
#       byte1=2
#       byte2=64
#       mac_capability_flags=128
#       manufacturer_code=4151
#       maximum_buffer_size=127
#       maximum_incoming_transfer_size=100
#       server_mask=0
#       maximum_outgoing_transfer_size=100
#       descriptor_capability_field=0
#       >",
#   "endpoints": {
#     "1": {
#       "profile_id": 260,
#       "device_type": "0x0402",
#       "in_clusters": [
#         "0x0000",
#         "0x0001",
#         "0x0003",
#         "0x0500",
#         "0xffff"
#       ],
#       "out_clusters": [
#         "0x0000",
#         "0x0001",
#         "0x0003",
#         "0x0004",
#         "0x0005"
#       ]
#     }
#   },
#   "manufacturer": "ORVIBO",
#   "model": "895a2d80097f4ae2b2d40500d5e03dcc",
#   "class": "zigpy.device.Device"
# }
class MotionOrvibo(OrviboCustomDevice):
    """Custom device representing aqara body sensors."""

    def __init__(self, *args, **kwargs):
        """Init."""
        self.battery_size = 9
        self.motion_bus = Bus()
        self.illuminance_bus = Bus()
        super().__init__(*args, **kwargs)

    signature = {
        MODELS_INFO: [(ORVIBO, "895a2d80097f4ae2b2d40500d5e03dcc")],
        ENDPOINTS: {
            1: {
                PROFILE_ID: zha.PROFILE_ID,
                DEVICE_TYPE: zha.DeviceType.OCCUPANCY_SENSOR,
                INPUT_CLUSTERS: [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    IasZone.cluster_id,
                    ORVIBO_CLUSTER_ID,
                ],
                OUTPUT_CLUSTERS: [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                ],
            }
        },
    }

    replacement = {
        SKIP_CONFIGURATION: True,
        ENDPOINTS: {
            1: {
                INPUT_CLUSTERS: [
                    BasicCluster,
                    PowerConfigurationCluster,
                    Identify.cluster_id,
                    IasZone.cluster_id,
                    ORVIBO_CLUSTER_ID,
                ],
                OUTPUT_CLUSTERS: [
                    Basic.cluster_id,
                    PowerConfiguration.cluster_id,
                    Identify.cluster_id,
                    Groups.cluster_id,
                    Scenes.cluster_id,
                ],
            }
        },
    }


class IlluminanceMeasurementCluster(CustomCluster, IlluminanceMeasurement):
    """Multistate input cluster."""

    cluster_id = IlluminanceMeasurement.cluster_id
    ATTR_ID = 0

    def __init__(self, *args, **kwargs):
        """Init."""
        super().__init__(*args, **kwargs)
        self.endpoint.device.illuminance_bus.add_listener(self)

    def _update_attribute(self, attrid, value):
        if attrid == self.ATTR_ID and value > 0:
            value = 10000 * math.log10(value) + 1
        super()._update_attribute(attrid, value)

    def illuminance_reported(self, value):
        """Illuminance reported."""
        self._update_attribute(self.ATTR_ID, value)
```

**Comment by timmo001** [comment]
My biggest concern is how do I test what I have added works locally before committing the changes to a PR. This may be less for those who have already contributed, but not for newbies to zha.

I have tried to point the pip add-on to my specific git repository but that doesn't seem to work

**Comment by liorm0505** [comment]
Hi, 
If i want to test this code, should i put it in custom component folder?

**Comment by dmulcahey** [comment]
@timmo001 are you using a venv for HA?

**Comment by tube0013** [comment]
to test new/updated quirks with a supervised or hassos install:

You need to get access to the home-assistant docker container. I do this with the portainer add-on, you can get command line access in your browser within any container. 

<img width="798" alt="Screen Shot 2020-07-28 at 4 39 33 PM" src="https://user-images.githubusercontent.com/11084412/88719260-fdfa7700-d0f0-11ea-8791-88ed3e26915d.png">
 
I stage the updated/new quirk file(s) in a folder in my config directory. Open a console via portainer.

browse to the quirks install folder:  /usr/local/lib/python3.7/site-packages/zhaquirks/ or /usr/local/lib/python3.8/site-packages/zhaquirks/

go into directory of the manufacturer or create a new one, then copy the quirk files from /config/ to the location. , delete the __pycache__ folder, then close out the terminal and restart HA.

![image](https://user-images.githubusercontent.com/11084412/88719725-bde7c400-d0f1-11ea-913a-fc5d4ed03b9b.png)

**Comment by jlongman** [comment]
Trying this now, looks like I have more to do:
```
2020-07-28 20:56:54 DEBUG (MainThread) [zigpy.quirks.registry] Checking quirks for ORVIBO 895a2d80097f4ae2b2d40500d5e03dcc (00:15:8d:00:01:bf:a5:c3)
2020-07-28 20:56:54 DEBUG (MainThread) [zigpy.quirks.registry] Considering <class 'zhaquirks.orvibo.sn10zw-1c0.MotionOrvibo'>
2020-07-28 20:56:54 DEBUG (MainThread) [zigpy.quirks.registry] Fail because device_type mismatch on at least one endpoint
```
fixed that (I'll fix the above) and look at this some more.  It still seems to detecting motion constantly so it looks like more work to do.  IIRC the original groovy document had 15 seconds and the aqara example has 120.  Anyways, the device issue is separate, I'll maybe open another issue.

The addition of docker instructions is excellent, _thank you_.

But for example I don't know whether the `signature` and `replacement` structures should be different or why.  I also assume the difference between a cluster and device is some zigbee implied terminology.  Maybe a better question is, is there value in describing these?  Are there devices that can serve as models that explain this?

And once again, sorry if it's repetitive, but thanks for ZHA and the work, to all involved.

**Comment by dmulcahey** [comment]
I’m gonna write a guide soon that breaks down a full existing quirk with explanations. I started mapping out what I want to cover today. Have you read what’s in the contributing section? It goes into light detail. In the simplest terms: `signature` is what the device is OOTB... `replacement` is what you want it to be.

**Comment by dmulcahey** [comment]
@tube0013 any chance you wanna or that into the readme?

**Comment by tube0013** [comment]
> @tube0013 any chance you wanna or that into the readme? 

Sure will work on it in the coming days

**Comment by liorm0505** [comment]
> to test new/updated quirks with a supervised or hassos install:
> 
> You need to get access to the home-assistant docker container. I do this with the portainer add-on, you can get command line access in your browser within any container.
> 
> <img alt="Screen Shot 2020-07-28 at 4 39 33 PM" width="798" src="https://user-images.githubusercontent.com/11084412/88719260-fdfa7700-d0f0-11ea-8791-88ed3e26915d.png">
> 
> I stage the updated/new quirk file(s) in a folder in my config directory. Open a console via portainer.
> 
> browse to the quirks install folder: /usr/local/lib/python3.7/site-packages/zhaquirks/ or /usr/local/lib/python3.8/site-packages/zhaquirks/
> 
> go into directory of the manufacturer or create a new one, then copy the quirk files from /config/ to the location. , delete the **pycache** folder, then close out the terminal and restart HA.
> 
> ![image](https://user-images.githubusercontent.com/11084412/88719725-bde7c400-d0f1-11ea-913a-fc5d4ed03b9b.png)

Thank you for the detailed explanation.
I will give it a try today.

**Comment by liorm0505** [comment]
Hi @jlongman ,
Is there a way to get your latest code for testing as well ?

Thanks,

**Comment by jlongman** [comment]
@liorm0505 I'm assuming your interest is the actual device support, so if you don't mind, I'll move that discussion to #94.  (If your point is more about taking that as an example for instructional purposes, then this would have been the correct place.)

I see @dmulcahey has started to [add to the contributing guide](https://github.com/zigpy/zha-device-handlers/commit/74d7845a0d5268caff0f482aa18da8f3ebf4a428) and already the replacement notes are helpful.

**Comment by dmulcahey** [comment]
#431 is the first swing at a guide. LMK what you think.
