### ISSUE TITLE
[Device Support Request] Embertec 4-channel Power Monitor

### ISSUE THREAD

**Issue by meremortals70** [zigpy/zha-device-handlers#455]
Would support for this device be available. Added it to my network today and it created ten entities but all showing as unavailable.

Has 4-channels which have CT’s attached for monitoring circuits.

1
{
2
  "node_descriptor": "<Optional byte1=2 byte2=64 mac_capability_flags=140 manufacturer_code=4370 maximum_buffer_size=82 maximum_incoming_transfer_size=512 server_mask=10752 maximum_outgoing_transfer_size=512 descriptor_capability_field=0>",
3
  "endpoints": {
4
    "1": {
5
      "profile_id": 260,
6
      "device_type": "0x0053",
7
      "in_clusters": [
8
        "0x0702",
9
        "0x0b04"
10
      ],
11
      "out_clusters": []
12
    },
13
    "2": {
14
      "profile_id": 260,
15
      "device_type": "0x0053",
16
      "in_clusters": [
17
        "0x0702",
18
        "0x0b04"
19
      ],
20
      "out_clusters": []
21
    },
22
    "3": {
23
      "profile_id": 260,
24
      "device_type": "0x0053",
25
      "in_clusters": [
26
        "0x0702",
27
        "0x0b04"
28
      ],
29
      "out_clusters": []
30
    },
31
    "4": {
32
      "profile_id": 260,
33
      "device_type": "0x0053",
34
      "in_clusters": [
35
        "0x0702",
36
        "0x0b04"
37
      ],
38
      "out_clusters": []
39
    },
40
    "5": {
41
      "profile_id": 260,
42
      "device_type": "0x0053",
43
      "in_clusters": [
44
        "0x0000",
45
        "0x0003",
46
        "0x0702",
47
        "0x0b04",
48
        "0xfd00",
49
        "0xfd01"
50
      ],
51
      "out_clusters": [
52
        "0x0003",
53
        "0x000a",
54
        "0x0019"
55
      ]
56
    }
57
  },
58
  "manufacturer": "Embertec",
59
  "model": "EMAU-ZN04-HA-01",
60
  "class": "zigpy.device.Device"
61
}

**Comment by Hedda** [comment]
FYI, it looks like support for more Zigbee clusters attributes is now being worked on for [ZHA integration](https://www.home-assistant.io/integrations/zha) in Home Assistant core, see:

https://github.com/home-assistant/core/pull/56909

and

https://github.com/home-assistant/core/pull/56666

Also, note the last comment from Adminiuga in PR for ZHA in Home Assistant core -> https://github.com/home-assistant/core/pull/56909

"**_Support for other attributes could be extended later, as I couldn't find too many devices other than Sinopé RM3250ZB Electrical Load Controller – 50A – Zigbee https://www.amazon.com/dp/B07CGJ6XH2/ reporting anything interesting on the electrical measurement cluster._**"

So maybe now you could try to get this working with the latest Home Assistant beta or wait for the next upcoming release:

https://www.home-assistant.io/faq/release/

PS: There is much more discussion about ZHA energy cluster and attributes for smart energy metering here -> https://github.com/zigpy/zha-device-handlers/issues/605 and https://github.com/zigpy/zha-device-handlers/issues/1045
