### ISSUE TITLE
Osram SMART+

### ISSUE THREAD

**Issue by egelmex** [zigpy/zha-device-handlers#458]
Osram+ bulb in pairing but not controllable.
![image](https://user-images.githubusercontent.com/474014/90925005-700c6600-e3e8-11ea-8213-3aee22abfb9a.png)

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
```
{
  "node_descriptor": "<Optional byte1=1 byte2=64 mac_capability_flags=142 manufacturer_code=48042 maximum_buffer_size=64 maximum_incoming_transfer_size=0 server_mask=0 maximum_outgoing_transfer_size=0 descriptor_capability_field=3>",
  "endpoints": {
    "3": {
      "profile_id": 49246,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x1000",
        "0xfc0f"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "unk_manufacturer",
  "model": "unk_model",
  "class": "zigpy.device.Device"
}
```

**Comment by dmulcahey** [comment]
A fix was pushed in .116 of HA that should prevent unk model / manufacturer errors like this. Please upgrade to .116 of HA. You will have to remove the device from HA and then pair it again after updating.
