### ISSUE TITLE
[Device Support Request] Xiaomi Motion Sensor RTCQ11LM (auto reset)

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zha-device-handlers#469]
The Xiaomi motion sensor ( zhaquirks.xiaomi.aqara.motion_aq2.MotionAQ2 ) is only sending a Occupancy bitmap8.1 when a motion is detected. However it never send bitmap8.0 .

Would it be possible that the quirk is making a bitmap8.0 after 15s ?

**Comment by dmulcahey** [comment]
Quirks do handle this already

**Comment by pipiche38** [comment]
Great. I'm new in the zigpy worlkd, trying to develop a plugin for Domoticz.
Do I have to do something to enable it ? Do I have to use a specific version ?

**Comment by Adminiuga** [comment]
https://github.com/zigpy/zha-device-handlers/blob/dev/CONTRIBUTING.md

`import zhaquirks` before you start the radio.

**Comment by dmulcahey** [comment]
Just import it before starting up. Look at the ZHA code in HA

**Comment by Adminiuga** [comment]
1st one

**Comment by dmulcahey** [comment]
Damn, Alexi beat me again 😂

**Comment by pipiche38** [comment]
So did I, otherwise it wouldn't have been identified as  zhaquirks.xiaomi.aqara.motion_aq2.MotionAQ2

**Comment by Adminiuga** [comment]
it should send the command to IAS cluster subscribers then

**Comment by pipiche38** [comment]
As said, I received:

Received an attribute update 0=bitmap8.1 on cluster <zigpy.zcl.clusters.measurement.OccupancySensing object at 0xaae5c9a0> from device <zigpy.device.Device object at 0xaae5c628>/00:15:8d:00:03:02:1

but nothing else . Of course I received correctly the Lux on Cluster 0x0400

**Comment by Adminiuga** [comment]
quirks is not going to generate Zigbee messages. you need to add your "listeneres" to the cluster. quirks will send commands to those listeners.

**Comment by Adminiuga** [comment]
https://github.com/zigpy/zha-device-handlers/blob/1235e8434a68db70590cdb9ee77dbd0477f8e819/zhaquirks/xiaomi/__init__.py#L312-L334

**Comment by pipiche38** [comment]
For each new device I'm doing the following, is that not enough ?

```
            for cluster in endpoint.in_clusters.values():
                # The context listener passes its own object as the first argument
                # to the callback
                cluster.add_context_listener(self)
```

Do you mean that I have to set the timer myself ?

**Comment by Adminiuga** [comment]
the `self` instance, need's to have `attribute_updated()` method to receive notification about attribute change. For IAS clusters it needs to have `cluster_command()` method. 
Again, look how ZHA does it in zha/core/channels/*

**Comment by Adminiuga** [comment]
I can't answer your question, because I don't know what `self` is in your case

**Comment by Adminiuga** [comment]
you may look at HA versions about 0.80.0, a bit easier to understand

**Comment by pipiche38** [comment]
not solved, just gave up

**Comment by Hedda** [comment]
https://github.com/pipiche38/Domoticz-Zigpy#to-be-addressed

> This is using the "quirk" part (from ZHA Device Handlers), and I do not fully understand how it works (especially in regards to that issue https://github.com/zigpy/zha-device-handlers/issues/469 - I do not understand what Cluster IAS should do here!)

@pipiche38 By the way, noticed that Adminiuga comment at the bottom of this other discussion which might be relevant here:

https://github.com/zigpy/zha-device-handlers/discussions/625

"**_ZHA really doesn't care if there's a single basic cluster on one of the endpoints or if there are multiple basic clusters. It always would use the 1st basic cluster it founds when processing all of the endpoints._**"
