### ISSUE TITLE
[BUG] Aqara Battery not reporting for some devices

### ISSUE THREAD

**Issue by NobleWolf** [zigpy/zha-device-handlers#480]
**Describe the bug**
Of the 7 Aqara devices I have only 2 are reporting battery level. One that is reporting is a contact sensor, but the other 2 are not reporting. The other that is reporting is a water sensor. They are each connected to a different zigbee repeater. Other non-reporting devices are connected to the same repeaters (Centralite plug) and directly to the coordinator (Conbee 2).

**To Reproduce**
1. Connect devices via ZHA
2. Allow devices to complete setup.
3. View Device listings

**Expected behavior**
Battery levels are expected to report.

**Screenshots**

_New Screenshot Sep 11, 2020 09:52 Central time_
A new 3rd battery is now reporting
![image](https://user-images.githubusercontent.com/5035544/92940197-6b9a0280-f414-11ea-8f53-c609f85483b4.png)

_Old screenshot Sep 11, 2020 09:28 Central time_
![image](https://user-images.githubusercontent.com/5035544/92937359-dd704d00-f410-11ea-93fc-24b605ef2a1f.png)

**Additional context**
I have attempted to reinstall ZHA. After deleting, but before reinstalling I deleted the entities and devices from the core.entity_registry and core.device_registry files. I have restarted multiple times. I have waited 12+hours to allow time for something to happen, but no change.

**System Health**
arch	x86_64
chassis	vm
dev	false
docker	true
docker_version	19.03.11
hassio	true
host_os	HassOS 4.13
installation_type	Home Assistant OS
os_name	Linux
os_version	5.4.63
python_version	3.8.3
supervisor	242
timezone	America/Chicago
version	0.114.4
virtualenv false

**Radio**
Conbee 2

**Device Signatures**
Provided in order on the screenshot
_Basement Door_
Zigbee info
IEEE: 00:15:8d:00:05:22:43:46
Nwk: 0x4650
Device Type: EndDevice
LQI: Unknown
RSSI: Unknown
Last Seen: 2020-09-11T09:01:54
Power Source: Battery or Unknown
Quirk: zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2
```
{
  "node_descriptor": "<NodeDescriptor byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x5f01",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0xffff"
      ],
      "out_clusters": [
        "0x0000",
        "0x0004",
        "0x0006",
        "0xffff"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.sensor_magnet.aq2",
  "class": "zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2"
}
```

_Basement Drain Water Sensor_
Zigbee info
IEEE: 00:15:8d:00:04:77:6c:4e
Nwk: 0x79ea
Device Type: EndDevice
LQI: Unknown
RSSI: Unknown
Last Seen: 2020-09-11T08:09:03
Power Source: Battery or Unknown
Quirk: zhaquirks.xiaomi.aqara.wleak_aq1.LeakAQ1
```
{
  "node_descriptor": "<NodeDescriptor byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0402",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0500"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.sensor_wleak.aq1",
  "class": "zhaquirks.xiaomi.aqara.wleak_aq1.LeakAQ1"
}
```

_Basement Outlet_
Zigbee info
IEEE: 08:6b:d7:ff:fe:6e:47:3a
Nwk: 0xd38f
Device Type: Router
LQI: 95
RSSI: -82
Last Seen: 2020-09-11T09:46:14
Power Source: Mains
```
{
  "node_descriptor": "<NodeDescriptor byte1=1 byte2=64 mac_capability_flags=142 manufacturer_code=4174 maximum_buffer_size=82 maximum_incoming_transfer_size=82 server_mask=11264 maximum_outgoing_transfer_size=82 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0b05"
      ],
      "out_clusters": [
        "0x0003",
        "0x0006",
        "0x0019"
      ]
    }
  },
  "manufacturer": "Centralite Systems",
  "model": "4200-C",
  "class": "zigpy.device.Device"
}
```

_Corner Lamp_
Zigbee info
IEEE: 08:6b:d7:ff:fe:6e:6d:5e
Nwk: 0xdf8f
Device Type: Router
LQI: 255
RSSI: -47
Last Seen: 2020-09-11T09:48:10
Power Source: Mains
```
{
  "node_descriptor": "<NodeDescriptor byte1=1 byte2=64 mac_capability_flags=142 manufacturer_code=4174 maximum_buffer_size=82 maximum_incoming_transfer_size=82 server_mask=11264 maximum_outgoing_transfer_size=82 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0b05"
      ],
      "out_clusters": [
        "0x0003",
        "0x0006",
        "0x0019"
      ]
    }
  },
  "manufacturer": "Centralite Systems",
  "model": "4200-C",
  "class": "zigpy.device.Device"
}
```

_Front Door_
Zigbee info
IEEE: 00:15:8d:00:05:42:27:18
Nwk: 0x5cbd
Device Type: EndDevice
LQI: 255
RSSI: -45
Last Seen: 2020-09-11T09:29:18
Power Source: Battery or Unknown
Quirk: zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2
```
{
  "node_descriptor": "<NodeDescriptor byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x5f01",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0xffff"
      ],
      "out_clusters": [
        "0x0000",
        "0x0004",
        "0x0006",
        "0xffff"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.sensor_magnet.aq2",
  "class": "zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2"
}
```

_Kitchen Motion_
Zigbee info
IEEE: 00:15:8d:00:05:2b:3d:76
Nwk: 0x0e99
Device Type: EndDevice
LQI: 255
RSSI: -46
Last Seen: 2020-09-11T09:17:49
Power Source: Battery or Unknown
Quirk: zhaquirks.xiaomi.aqara.motion_aq2.MotionAQ2
```
{
  "node_descriptor": "<NodeDescriptor byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0107",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0400",
        "0x0406",
        "0x0500",
        "0xffff"
      ],
      "out_clusters": [
        "0x0000",
        "0x0019"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.sensor_motion.aq2",
  "class": "zhaquirks.xiaomi.aqara.motion_aq2.MotionAQ2"
}
```

_Living Room Motion_
Zigbee info
IEEE: 00:15:8d:00:05:72:a0:7f
Nwk: 0x5bd3
Device Type: EndDevice
LQI: 255
RSSI: -50
Last Seen: 2020-09-11T09:17:58
Power Source: Battery or Unknown
Quirk: zhaquirks.xiaomi.aqara.motion_aq2.MotionAQ2
```
{
  "node_descriptor": "<NodeDescriptor byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0107",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0400",
        "0x0406",
        "0x0500",
        "0xffff"
      ],
      "out_clusters": [
        "0x0000",
        "0x0019"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.sensor_motion.aq2",
  "class": "zhaquirks.xiaomi.aqara.motion_aq2.MotionAQ2"
}
```

_Magic Cube 2_
Zigbee info
IEEE: 00:15:8d:00:04:2d:6e:1b
Nwk: 0x3536
Device Type: EndDevice
LQI: 255
RSSI: -52
Last Seen: 2020-09-11T09:39:27
Power Source: Battery or Unknown
Quirk: zhaquirks.xiaomi.aqara.cube.Cube
```
{
  "node_descriptor": "<Optional byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x6f01",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0019"
      ],
      "out_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0012",
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x6f02",
      "in_clusters": [
        "0x0003",
        "0x0012"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0012"
      ]
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x6f03",
      "in_clusters": [
        "0x0003",
        "0x000c"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0005",
        "0x000c"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.sensor_cube",
  "class": "zhaquirks.xiaomi.aqara.cube.Cube"
}
```

_Stairwell Door_
Zigbee info
IEEE: 00:15:8d:00:05:22:43:2c
Nwk: 0xb8d8
Device Type: EndDevice
LQI: 239
RSSI: -64
Last Seen: 2020-09-11T09:25:11
Power Source: Battery or Unknown
Quirk: zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2
```
{
  "node_descriptor": "<NodeDescriptor byte1=2 byte2=64 mac_capability_flags=128 manufacturer_code=4151 maximum_buffer_size=127 maximum_incoming_transfer_size=100 server_mask=0 maximum_outgoing_transfer_size=100 descriptor_capability_field=0>",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x5f01",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0xffff"
      ],
      "out_clusters": [
        "0x0000",
        "0x0004",
        "0x0006",
        "0xffff"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.sensor_magnet.aq2",
  "class": "zhaquirks.xiaomi.aqara.magnet_aq2.MagnetAQ2"
}
```

_Zigbee Coordinator_
Zigbee info
IEEE: 00:21:2e:ff:ff:05:ee:40
Nwk: 0x0000
Device Type: Coordinator
LQI: 6
RSSI: 3
Last Seen: 2020-09-11T09:20:38
Power Source: Mains

**Comment by Adminiuga** [comment]
do you get sensor entities for battery created?

![image](https://user-images.githubusercontent.com/5826160/92942007-10214200-f41f-11ea-8e88-04237cc96854.png)
![image](https://user-images.githubusercontent.com/5826160/92942175-4232a400-f41f-11ea-9f42-18fefb44f190.png)

BTW, I'm not sure Centralite plugs are good routers for xiaomi. Didn't have luck with mine, as it was always falling off those. 
Do you get device readings when you trigger the devices?

**Comment by Adminiuga** [comment]
Confirm the devices are online and are sending the updates. They should report battery about every hour, but if they fall off the network, then you won't get the battery.
Confirm you get the sensor entities representing the battery

**Comment by Adminiuga** [comment]
@dmulcahey should we add all entities associated with the device in the signature?

**Comment by NobleWolf** [comment]
They are sensor battery types.
![image](https://user-images.githubusercontent.com/5035544/92945008-50ca8c80-f41a-11ea-9988-9f94d87e2685.png)

A couple more are reporting now. Maybe it is just because I have restarted several times?
![image](https://user-images.githubusercontent.com/5035544/92944767-047f4c80-f41a-11ea-958b-f8f8ff86b144.png)

I'm just now learning that Aqara devices don't play well with all repeaters. Hopefully they don't fall off. I've read that sometimes you can put the Aqara devices in pair mode and they'll reconnect without other actions.
I'll replace the Centralite plugs with Tradfri when they get back in stock. I found them on this list: https://community.hubitat.com/t/xiaomi-aqara-devices-pairing-keeping-them-connected/623/5

**Comment by Adminiuga** [comment]
after a restart it may take till next battery report (about an hour) for it to update and pop up in the device list.

**Comment by dmulcahey** [comment]
> @dmulcahey should we add all entities associated with the device in the signature?

We could... up to you. Doesn’t matter to me
