### ISSUE TITLE
ZHA broke after trying to test new release 

### ISSUE THREAD

**Issue by bednim** [zigpy/zha-device-handlers#483]
Sorry if this will sound chaotic!

I'm running home assistant inside proxmox. 

I'm on version 0.104 and supervisor is 4.13

Ive decides to test new zha by using python add on. 

This rendered whole zha unusable. Zbbridge became unresponsive. 

I decided to remove everything connected to new zha version (folders inside home assistant/config) 

This did bring zha back to life but my zigbee devices were unresponsive.

So I thought I will remove devices from the zha list, and after doing so I can't add them back on, as the message I get from logs says:"skipping configuration for device already added/paired". 

I have removed all files that are related to zha including zigbee.db, hard restart home assistant and still can't add devices. 

What else can I try? 

I'm using sonoff zbbridge with tasmota.

**Comment by Adminiuga** [comment]
Sonoff bridge is supported only in latest beta version
