### ISSUE TITLE
[BUG] Osram switch mini

### ISSUE THREAD

**Issue by basnagel** [zigpy/zha-device-handlers#499]
**Describe the bug**
Adding a OSRAM Lightify Switch Mini to my network is not working out after quirk was added some time ago.

Before quirk: I picked up zha_events.

After quirk: The remote switches everything(switched bulbs cover) in my network on and off.

 

**To Reproduce**
Removed remote, deletes entries from zha.storage and other HA files I could find the remote.

Device signature:
{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4364, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=0, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
  "endpoints": {},
  "manufacturer": "OSRAM",
  "model": "Lightify Switch Mini",
  "class": "zhaquirks.osram.switchmini.OsramSwitchMini"
}

Manage cluster is empty.
![osrammini](https://user-images.githubusercontent.com/11892538/94000737-deea2f80-fd97-11ea-88a2-83301b6584a0.png)

**Expected behavior**
A remote that switches the stuff I want, not everything(via zha_event for my usage)

**Screenshots**

**Additional context**
[osramminiadd.txt](https://github.com/zigpy/zha-device-handlers/files/5267371/osramminiadd.txt)

**Comment by basnagel** [comment]
I tried further and after removing the quirks file for the switch I got a working remote again catching the zha_events.

![switch mini no quirks](https://user-images.githubusercontent.com/11892538/94408360-f9941e00-0174-11eb-9dd2-137d1279cf1f.png)

Is there a setting to choose not to use a quirks, besides removing the file from the site-packages?

I have added the debug log from this join

[osramswitchmini.txt](https://github.com/zigpy/zha-device-handlers/files/5290934/osramswitchmini.txt)

**Comment by Adminiuga** [comment]
@dmulcahey that Quirk indeed doesn't have any `replacement` https://github.com/zigpy/zha-device-handlers/blob/1f0bd91c746afe3d1576954ceefd74ee2e37fc63/zhaquirks/osram/switchmini.py#L45 which would cause the new endpoints to be empty.

**Comment by Adminiuga** [comment]
@basnagel can you copy this file into your environment and confirm if it is working as expected?

**Comment by Adminiuga** [comment]
https://github.com/Adminiuga/zha-device-handlers/blob/fixes/osram-mini/zhaquirks/osram/switchmini.py

**Comment by basnagel** [comment]
After a reboot and a reconfigure the switchmini is working as intended.

I can select device-> shortpress etc as triggers, clusters are present and most import, not everything in my network is switching on and off.

Log from the reconfigure.

[osramswitchminifixed.txt](https://github.com/zigpy/zha-device-handlers/files/5294325/osramswitchminifixed.txt)
