### ISSUE TITLE
[Device Support Request]

### ISSUE THREAD

**Issue by mikosoft83** [zigpy/zha-device-handlers#509]
**Is your feature request related to a problem? Please describe.**
I've seen these TRVs made by Tuya apparently but they don't stick to ZHA.

**Describe the solution you'd like**
Adding a quirk would be nice

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be**
I don't own them yet but here's a link to deconz thread:
[](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3110)

**Additional context**

**Comment by dmulcahey** [comment]
Please fill out all of the required information

**Comment by mikosoft83** [comment]
Here's a missing [link to deconz thread](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3110), is this enough to work with?

**Comment by thumDer** [comment]
I would very like to have this as well!

**Comment by MattWestb** [comment]
Some devs have starting doing the ground for the tuya comand decoding and some for the TRVs https://github.com/zigpy/zha-device-handlers/pull/538#issue-509500699.

Device support request is posted for them https://github.com/zigpy/zha-device-handlers/issues/581#issue-740866517.

If making one working then its only adding the model id and its working and if little different its only applying different options from the tuya palette of functions (look at Z2M how they is adding new ones its similar as for Zigpy).

![TRV02](https://user-images.githubusercontent.com/49618193/99306564-a6297c80-2855-11eb-8007-d33694a94257.PNG)
I have some twins (different model number) and its being supported in the dev branch today in deCONZ ;-))

HA dont have support for all functions but more is in the pipe.
