### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by taxinvoice** [zigpy/zha-device-handlers#512]
I have ZHA installed in Hassio using xbee module.  Trying to pair with aqara motion sensor...it appears i need a device handler for these sensors..but how do i add these handlers to hassio.   I dont see any instructins on this?

**Comment by dmulcahey** [comment]
They are installed with ZHA automatically. There is nothing you need to do. If there is an issue related to a particular device open a new issue and fill out the entire template please.
