### ISSUE TITLE
[Device Support Request] [Enhancement] Sercomm SZ-ESW01-AU Plug

### ISSUE THREAD

**Issue by meremortals70** [zigpy/zha-device-handlers#526]
Would it be possible to please add this to the list of switches instead of identifying simply as lights?

Would it also be possible for daily consumption, voltage, current and power factor are also very handy (available on Deconz)

```
{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=4401, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=0, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0702",
        "0x0b04",
        "0x0b05"
      ],
      "out_clusters": [
        "0x0003",
        "0x000a",
        "0x0019",
        "0x0b05"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0103",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003"
      ],
      "out_clusters": [
        "0x0003",
        "0x0006"
      ]
    }
  },
  "manufacturer": "Sercomm Corp.",
  "model": "SZ-ESW01-AU",
  "class": "zigpy.device.Device"
}
```

Please let me know if you need any additional information.

**Comment by Adminiuga** [comment]
You can override entity type via zha configuration. Look for example on the forum, it was posted there a while back

**Comment by meremortals70** [comment]
Thanks, which forum I searched the HA forum and the issues here before adding the request?

**Comment by Adminiuga** [comment]
https://community.home-assistant.io/t/zha-zigbee-tested-devices-please-add-your-device-results/17718/384?u=adminiuga

The device section. Usually it is the ieee address + endpoint id, so in your case it should end in `-1`

**Comment by meremortals70** [comment]
That's awesome, can we get that added to documentation please?

**Comment by meremortals70** [comment]
Hi folks

Are we able to add the additional clusters for this device please?
