### ISSUE TITLE
[Device Support Request] CentraLite 3323-G

### ISSUE THREAD

**Issue by ryantiger658** [zigpy/zha-device-handlers#572]
**Is your feature request related to a problem? Please describe.**
I purchased a new [CentraLite multisensor from Amazon ](https://www.amazon.com/gp/product/B071YQCWQM/)that supposedly has a [humidity sensor](https://www.centralite.com/downloads/DataSheet-3SeriesDoorSensor.pdf), however, the quark that Home Assistant uses doesn't seem to pull through the humidity data. 

**Describe the solution you'd like**
It would be great if someone could add the Humidity cluster to the CentraLite quark, or to help me understand how to work with the device signatures so I can put in my own PR for it.

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**

```
{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4174, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=0, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0402",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0020",
        "0x0402",
        "0x0500",
        "0x0b05"
      ],
      "out_clusters": [
        "0x0019"
      ]
    },
    "2": {
      "profile_id": 49887,
      "device_type": "0x000c",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0b05"
      ],
      "out_clusters": [
        "0x0003"
      ]
    }
  },
  "manufacturer": "CentraLite",
  "model": "3323-G",
  "class": "zhaquirks.centralite.3300S.CentraLite3300S"
}
```

**Additional context**
Thanks in advance for your help!

**Comment by Adminiuga** [comment]
Is this a door sensor? Does not have humidity, only temp.

**Comment by dmulcahey** [comment]
are you referring to this:

![image](https://user-images.githubusercontent.com/1335687/98543627-c3ac8400-2260-11eb-93ad-f43f43d2cfbe.png)


If so, that isn't capabilities for the device. That is tolerance for shipping / storage of the device.

**Comment by ryantiger658** [comment]
@Adminiuga, Ya the door sensor, I snagged the outlet too for another purpose though.

Ultimately, looking through the documentation I don't see anything from the manufacturer, but I was looking at some of the comments. 

![comment 1](https://user-images.githubusercontent.com/11201272/98555066-771c7500-226f-11eb-8e16-8729a662647f.PNG)

![comment 2](https://user-images.githubusercontent.com/11201272/98555074-7a176580-226f-11eb-8c28-f7cf75d05f83.PNG)

![comments](https://user-images.githubusercontent.com/11201272/98555908-7a643080-2270-11eb-886b-245871afe3f9.PNG)

Perhaps since they are from 2018 the sensor has changed. I have been looking for a reliable (and cheep) humidity sensor for a while now and have struggled to find one. 

Thanks for looking into this for me!

**Comment by Adminiuga** [comment]
Konke temp & humidity sensor.

**Comment by ryantiger658** [comment]
I have a couple [Aqara climate sensors](https://www.amazon.com/Aqara-WSDCGQ11LM-Temperature-Humidity-Sensor/dp/B07D37FKGY/ref=sr_1_12?dchild=1&keywords=Konke+humidity+zigbee&qid=1604937798&sr=8-12), but I have a problem where they loose connection and stop functioning about 24 hours after I set them up. There are zigbee repeaters in the same room that work fine so there shouldn't be range issues.

**Comment by Adminiuga** [comment]
and that's why the recommendation was for Konke and not Xiaomi.

**Comment by Adminiuga** [comment]
Won't fix. Working as designed.

**Comment by Adminiuga** [comment]
Check pinned messages of #Zigbee channel on HA discord server to see the answer to
>so there shouldn't be range issues.

**Comment by ryantiger658** [comment]
Thanks again!
