### ISSUE TITLE
[SUGGESTION] Add "Autosquash" GitHub Action make squashing and merging pull requests more user-friendly

### ISSUE THREAD

**Issue by Hedda** [zigpy/zha-device-handlers#577]
Please consider adding "Autosquash" GitHub Action make rebasing and squashing pull requests more user-friendly via UI.

https://github.com/marketplace/actions/autosquash

If it is possible to squash a pull request with conflicts then GitHub can merge it without having to rebase first.

FYI, that "Autosquash" GitHub Action replaces this "Autorebase" GitHub Action from the same developers:

https://github.com/tibdex/autorebase

Autorebase GitHub Action was replaced with "Autosquash" because GitHub is merge oriented rather than rebase oriented.

PS: I found out about these in https://github.com/isaacs/github/issues/88 when looking for a GitHub web UI for rebasing a pull request.

**Comment by dmulcahey** [comment]
GitHub just rolled out autosquash / merge once checks are met. I’ll look at that when there is time. We need to add more checks to guarantee approval and I’d like to script a validator of some sort as well. Closing this as it is different from what will be done (eventually)
