### ISSUE TITLE
[BUG] Xiaomi Mija sensor switch reports a single click in addition to long press events

### ISSUE THREAD

**Issue by samueltardieu** [zigpy/zha-device-handlers#597]
**Describe the bug**

When long pressing a Mija sensor switch, it reports a single click before reporting the long press and the end of long press. This does not happen with the phoscon integration, where long press and end of long press are independent events.

**To Reproduce**

Press the Mija sensor switch. and keep it pressed for one second.

**Expected behavior**

I expect **only** two events to be generated:

- one to indicate that the button has been pressed (not clicked)
- one to indicate that the button has been released one second later

Right now, three events are generated, the first one being bogus:

- one to indicate a single click  *<= this one should not be generated*
- one to indicate that the button has been pressed (not clicked)
- one to indicate that the button has been released one second later

Note that the phoscon plugin to HomeAssistant generates only two events, as expected.

**Additional context**

## Other plugins

Before switching to ZHA, I was using the Phoscon/deconz plugin with the same hardware (same dongle, same Mija switch). Phoscon generates only two events when the button is long pressed (press + release), as expected.

## Traces

Here is an event log for a long press, we can see three events instead of two. The first event should not have been generated as there was no single click, only a long press:

```
Événement 0 déclenché 21:30:  ## NOTE: this one should not happen

{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:15:8d:00:04:18:59:aa",
        "unique_id": "00:15:8d:00:04:18:59:aa:1:0x0006",
        "device_id": "0b7324457bbc259b3e1085d9a072acd3",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "click",
        "args": {
            "click_type": "single"
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-11-24T20:30:17.349971+00:00",
    "context": {
        "id": "43d523129578c85dfa216fb8d25b2519",
        "parent_id": null,
        "user_id": null
    }
}

Événement 1 déclenché 21:30:

{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:15:8d:00:04:18:59:aa",
        "unique_id": "00:15:8d:00:04:18:59:aa:1:0x0006",
        "device_id": "0b7324457bbc259b3e1085d9a072acd3",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "attribute_updated",
        "args": {
            "attribute_id": 0,
            "attribute_name": "on_off",
            "value": true
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-11-24T20:30:17.352194+00:00",
    "context": {
        "id": "6ddc789fc0a179e6fd28f8f9f458b67d",
        "parent_id": null,
        "user_id": null
    }
}

 Événement 2 déclenché 21:30:

{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "00:15:8d:00:04:18:59:aa",
        "unique_id": "00:15:8d:00:04:18:59:aa:1:0x0006",
        "device_id": "0b7324457bbc259b3e1085d9a072acd3",
        "endpoint_id": 1,
        "cluster_id": 6,
        "command": "attribute_updated",
        "args": {
            "attribute_id": 0,
            "attribute_name": "on_off",
            "value": false
        }
    },
    "origin": "LOCAL",
    "time_fired": "2020-11-24T20:30:19.559430+00:00",
    "context": {
        "id": "728f8ec3ab9480a2abcd7d3d84b1c8f0",
        "parent_id": null,
        "user_id": null
    }
}
```

**Comment by Adminiuga** [comment]
- You do need to fill in the template
- There're no long presses with this button -- but you can implement those using automations
- it supports only "short-press", double/triple/quadruple/quintuple presses
- the other two events are by design and totally expected

**Comment by samueltardieu** [comment]
>     * You do need to fill in the template

Done
 
>     * There're no long presses with this button -- but you can implement those using automations

So what are those two events, which trigger when I start pressing the button and when I release it? If you don't like the term "long press", replace it with "press and hold".

>     * it supports only "short-press", double/triple/quadruple/quintuple presses

The Phoscon plugin supports those in addition to press and hold detection, and does not send a single click event first. The setup I had was (and that I'd like to reproduce with ZHA, same hardware):

- single click toggles the light
- press event starts changing the intensity up then down then up then down…
- until release event stops the automation

Right now, with ZHA, the extra single click makes it more complex to implement those kind of automation in HomeAssistant than with Phoscon.

>     * the other two events are by design and totally expected

My problem is not with the "other two events" which indeed are what I want to keep (start pressing, and release). It is with the extra "single click" event.

**Comment by Adminiuga** [comment]
> So what are those two events, which trigger when I start pressing the button and when I release it? If you don't like the term "long press", replace it with "press and hold".

Those two events are from presses, will be present for long or for short presses.
