### ISSUE TITLE
[Device Support Request] LIVARNO LUX/LIDL Led Panel 60x60 (Tuya TS0502A)

### ISSUE THREAD

**Issue by docgalaxyblock** [zigpy/zha-device-handlers#618]
[LIDL Service website](https://www.lidl-service.com/cps/rde/xchg/SID-3771F4F2-8A18D468/lsp/hs.xsl/product.html?id=5027306530&title=Smart+LED+Light+Panel&count=1)

**Describe the solution you'd like**
- [x] power control
- [x] brightness control
- [x] CCT control
- [ ] remove color control

![grafik](https://user-images.githubusercontent.com/21227087/101215714-9778fd00-367e-11eb-957c-a1f86d50946e.png)

Maybee because the board is also color capable
![IMG_20201204_123040](https://user-images.githubusercontent.com/21227087/101216036-1e2dda00-367f-11eb-9663-c2623fec6553.jpg)

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
[Device signature and pairing log at my dev VM](https://pastebin.com/ifAkAXaF)

**Additional context**
https://zigbee.blakadder.com/Tuya_TS0502A.html
Touchlink resetable

**Comment by docgalaxyblock** [comment]
Signature
```
{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x010c",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0300",
        "0x1000"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZ3000_9evm3otq",
  "model": "TS0502A",
  "class": "zigpy.device.Device"
}

**Comment by MattWestb** [comment]
I like the PCB but someone have stolen the IR receiver and was not having time putting the drivers for RGB in place but the TC looks OK :-))

I was thinking buying one of then but they was not delivered to my store :-(

**Comment by docgalaxyblock** [comment]
@MattWestb You are the guy who has made a teardown of the tradfri bulbs right?

**Comment by MattWestb** [comment]
I have not making one large teardown of bulbs that's one netherland guy that have doing that. I have more "extracting" the Zigbee module for using it as one coordinator i ZHA and Tasmota.
What i have seen is the first gen bulbs potted with some heat transmitting mass and the newer one without only more metal inside and all components blues on the PCB. 
Normally its the coils that is not firm done that is making vibrations and then not being god glused its can making much sounds / vibrations.

Was reading that new Philips HUE Zigbee / BL bulbs was trying changing the PWM frequency to getting the noise away but its not easy if the components is not good done / fixed.

**Comment by gijsje** [comment]
The round ceiling light is also shown als color lights but only has cold/warm white
`{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x010c",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0300",
        "0x1000"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TZ3000_rylaozuc",
  "model": "TS0502A",
  "class": "zigpy.device.Device"
}`

**Comment by TheJulianJES** [comment]
This seems like the same issue as https://github.com/zigpy/zha-device-handlers/issues/643.
Created a PR here: https://github.com/zigpy/zha-device-handlers/pull/680 (Please test it if you can and report back)
