### ISSUE TITLE
[FUTURE / FUNKTION REQUEST] Calibrating and Offset for sensors.

### ISSUE THREAD

**Issue by MattWestb** [zigpy/zha-device-handlers#622]
**Describe the bug**

I think its belong here or / and i Zigpy.

Many sensors is not so precise or is depending on environment for how the measurement is being done.

**To Reproduce**

Example I have 4 first gen Aqara weather sensors and 2 second gen. Between the sensors in the same gen its minimal difference but between the gens its being little more and dont look nice.
And with pressure is always calibrating to the sea level so before it was no problem then I was living around sea level but now i need adding some metater (nearly 200) for getting it being true.

Edit: For My its around 28 hPa that is missing for getting the real true sea level reading.

![Sensor01](https://user-images.githubusercontent.com/49618193/101355669-2fe9ca00-3897-11eb-83c3-bd9a343e0388.PNG)

I have 2 Philips HUE motion sensors in My living room that is little "off sync".
In deCONZ i was putting offset and they was getting then nice synced to all other temperature sensors.
![Sensor02](https://user-images.githubusercontent.com/49618193/101355944-a38bd700-3897-11eb-9d2e-78f1f30d5380.PNG)
BM= Philips HUE ones on etch side or the window / balcony door. The red line is one Aqara that is in the middle of the living room / kitchen.

The Aqara / Xiaomi looks being pretty good but still some degree can being between them.  If being possible I putting all together for some time and then calculating the offset and applying and letting them reporting for some more time for seeing that its looks nice and putting  them back there belong.

**Expected behavior**

I dont knowing the policy in AH and ZHA but my feeling is that the corrections should being as near the source as possible. Its possible making templates in HA but then you is getting one "new" sensor and one old one and all is saved in the DB (or in InfluxDB for My) = double data and half its waist.

**Screenshots**

![Sensor03](https://user-images.githubusercontent.com/49618193/101357324-9374f700-3899-11eb-8da1-08f4f449b2dc.PNG)

One day with little more moving.

**Additional context**

Then offset / calibration is per sensor it must being saved (in the DB ?) and being reused after HA restarts. If doing it only for ZHA i think the zigbee.db is one good place but i can also being in HAs domain (HA policy ?).

I can seeing adding the calibration / offset from the cluster menu for all sensors belonging to the device ala "zigbee design" as one virtual cluster that is saving it in the database and is used for all sensors that have it implanted in the quirks. But also ZHA and Zigpy is need being adopted for making it working all the way.

For My personal thing its temperature and pressure interesting but normally not humidity then the sensors is very inaccurate. But i think the best is implementing somthing that is more general for all sensor and not only some types and doing the selection in the quirks config like other cluster. Zigbee Temp In > Offset > Zigbee Temp Out (or whatever the name / function is).

PS: deCONZ can calibrating sensors but not all types like pressure is not possible that is pretty bad if like using the historical evaluation of them.

This is one future that have pretty low priority but is definitely somthing that is being needed for ZHA in the long run for making it better for our user in the future (and My).

**Comment by MattWestb** [comment]
I have upgrading and looking on Zigbee.db and its one table with last known attributes from all cluster.
So i cumming back to my request:

All sensors is having attribute up to 0x200 and above is "free":
One example from ZCL V7
```
Index Application Usage
0x0000 Arm Disarm Command BO
0x0001 Occupancy Control BO
0x0002 Enable Control BO
0x0003 Access Control BO
0x0200 to 0xFFFE Vendor defined
0xFFFF Other
```
So making one cluster attribute 0xeeee  and  linking it to one sensor cluster (and attribute) and saving it Zigbee.db for all sensors adding the cluster thru quirk.
Then in ZHA the user can "setting" attribute 0xeeee (offset) on the sensor cluster and the value is saved in the DB linked to the sensor.

Then the quirk or Zigpy can reading the offers for the attribute in the DB and applying it then sending the attribute red / reported from the sensor.

GUI is OK and the function is working OK then the possibility is added in the device quirk so its under devs control.

How the applying the offset i think some devs is knowing better then i butt shall being possible.

**Comment by MattWestb** [comment]
One more useful thing with attribute in the Zigbee.db is adding on virtual attribute for the OTA  cluster with number 0xeeef the same way as above and storing "forces version" for the  device then doing OTA up/downgrading.

If not sett then the system is using the default = if finding one newer file then upgrading.
If attribute is sett in db for the OTA cluster attribute 0xeef of the device then up/downgrading if is not equal.
If the user is putting wrong or the system cant finding the file online or local its no match = no updating.

God user control in GUI and no large changing in the system but using resources that  the system is having.


@puddly  Do you understanding my thinking ??
Is it very bad for the system ?
I think its pity easy doing and working good and easy for user to understanding.

**Comment by MattWestb** [comment]
ZHA need one patch for understanding that 0xeeee is one offset attribute on sensor clusters with the datatype from the cluster type.

OTA is easy the 0xeeef shall being one uint32 as the attribute 0x0002 on one OTA cluster.

So adding them like one "extension  / universal" manufacture cluster attribute to the ZCL.

**Comment by MattWestb** [comment]
I have making one discussion with more updated "thinking" https://github.com/zigpy/zha-device-handlers/discussions/1179.

I think its easy doing  but no input from the devs how they like have it implemented then now all attribute is saved in Zigbee.DB so only need reading the sett attribute offset and using it then the device is reporting new valiues.

**Comment by MattWestb** [comment]
Still interesting future for ZHA that is needed.

**Comment by csstup** [comment]
Still needed.

**Comment by TheJulianJES** [comment]
@csstup You'll need to create a template sensor entity using the HA frontend instead, where you can just enter the fixed offset, and then attach that to the device entry IIRC.

Home Assistant Core doesn't want integration-provided offset entities if the device doesn't expose them natively (e.g. for cases where it also has a display that needs the offset applied, where it's fine to have config offset entities then).
