### ISSUE TITLE
Xiaomi Sensor actual first timeout is 90sec

### ISSUE THREAD

**Issue by tyjtyj** [zigpy/zha-device-handlers#646]
https://github.com/zigpy/zha-device-handlers/blob/288913ecb1604c7f20c161d526fea9dc481fcfdc/zhaquirks/xiaomi/__init__.py#L343

I understand migateway setting is 120sec for returning from on to off is 120sec but xiaomi motion sensor actual timeout is 90. 
After first motion, the next motion detection is set every 30s. Below is example of the timeline

```
0s motion detected
60s motion redetect activated
60-89s any motion here will extend the motion to 120s
if no motion 
90s motion switch to off if no motion detected. 
if motion
90s motion remain on till 120s, redetection start at 90s again.
We can see this behaving correctly in z2m setting motion off to 90s.
```

Edit to explain further the behavior

if motion is at detect at 80s
eg.
0s motion detected
60s motion detection reactivated:
80s motion detected
110s motion redetect activated
if no motion for 30s, sensor should be off at 140s 
if motion here, sensor remain on
120s motion detected
if no motion for 30s, sensor should be off at 180s

**Comment by dmulcahey** [comment]
the Z2M code looks like a straight 90 second timeout...


I also found this: https://community.smartthings.com/t/xiaomi-motion-sensor-aqara-how-to-test/170752/11

I'll change this to 65 seconds and do some testing in a few hrs when my sensor that I had to re-pair is no longer in test mode.
