### ISSUE TITLE
Xiaomi WXKG02LM 2016     lumi.sensor_86sw2 

### ISSUE THREAD

**Issue by orsgah** [zigpy/zha-device-handlers#650]
ZHA and Xiaomi WXKG02LM 2016

Aqara wxkg02lm two buttons wireless switch
lumi.sensor_86sw2
Bottons connected successfully, but automations do not work, zha didn’t trigger buttons, but in log buttons is clicked.
I try it with two items.

Cc2531

log

0xe70b:1:0x0006] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=GLOBAL_COMMAND manufacturer_specific=False is_reply=True disable_default_response=True> manufacturer=None tsn=164 command_id=Command.Report_Attributes>
[0xe70b:1:0x0006] ZCL request 0x000a: [[Attribute(attrid=0, value=<TypeValue type=Bool, value=Bool.true>), Attribute(attrid=0, value=<TypeValue type=Bool, value=Bool.false>)]]
[0xe70b:1:0x0006] Attribute report received: on_off=1, on_off=0

**Comment by Adminiuga** [comment]
what zigpy lib are you using?

**Comment by orsgah** [comment]
> what zigpy lib are you using?

I am using last update of home assistant 2020.12 fresh installed(hass os) and znp cc2531 usb

**Comment by catatonico2** [comment]
I have the same problem, have you been able to solve it?

**Comment by Adminiuga** [comment]
Switch to using zigpy_znp

**Comment by catatonico2** [comment]
My coordinator is a Conbee 2. I have consulted and it seems not made for this.

**Comment by Adminiuga** [comment]
Well, then you problem.is completely unrelated.

**Comment by Adminiuga** [comment]
You button probably just dropped off the network, cause xiaomis tend to do that

**Comment by orsgah** [comment]
> You button probably just dropped off the network, cause xiaomis tend to do that

But on zigbee to mqtt work fine. And in logs i see that button work

**Comment by catatonico2** [comment]
in the end using zha_event has worked for me

**Comment by Kitser** [comment]
I have got the same problem. Using the zha_event work as a workaround. But I only have events for button 1, button 2, and both.
No separate event for double click and hold. Hopefully, this will be fixed in a later update.
