### ISSUE TITLE
[BUG] Cannot turn off Eurotronic Spirit Zigbee thermostat

### ISSUE THREAD

**Issue by malfroid** [zigpy/zha-device-handlers#711]
**Describe the bug**
Turning off the heating does not work.
Changing the heating setpoint temperature does work.

**To Reproduce**
1. Go to the thermostat entity screen
2. Change 'Operation' from 'Heat' to 'Off'
3. Refresh entity screen
4. 'Operation' is stuck on 'Heat'

**Expected behavior**
Operation moves to 'Off'

**Screenshots**

https://user-images.githubusercontent.com/3715399/104122458-66f34580-5345-11eb-811f-74ee527dce70.mp4

**Additional context**
Running Home Assistant 2021.1.1 and ZHA on Raspberry Pi 4 with Conbee II zigbee stick.
Problem occurs as well with 3 other Eurotronic Spirit Zigbee thermostats.
Many other connected Zigbee devices work without problems.

**Device info**
SPZB0001
by Eurotronic
Zigbee Coordinator
Zigbee info
IEEE: 00:15:8d:00:05:3d:2d:21
Nwk: 0x076a
Device Type: EndDevice
LQI: 255
RSSI: -61
Last Seen: 2021-01-10T13:00:41
Power Source: Battery or Unknown
Quirk: zhaquirks.eurotronic.spzb0001.SPZB0001

**Device signature**

``` json
{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4151, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0301",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x000a",
        "0x0019",
        "0x0201"
      ],
      "out_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0004",
        "0x000a",
        "0x0019",
        "0x0201"
      ]
    }
  },
  "manufacturer": "Eurotronic",
  "model": "SPZB0001",
  "class": "zhaquirks.eurotronic.spzb0001.SPZB0001"
}
```

**Full debug logs**:
[home-assistant.log](https://github.com/zigpy/zha-device-handlers/files/5792577/home-assistant.log)

(relevant entity ID: `climate.thermostat_office_thermostat` )

**Comment by FHellmann** [comment]
The issue still remains with this version:
```
Home Assistant 2023.6.3
Supervisor 2023.06.4
Operating System 10.3
Frontend 20230608.0 - latest
```
