### ISSUE TITLE
[BUG] Centralite 3200 switch identified as light.

### ISSUE THREAD

**Issue by adolfomendes** [zigpy/zha-device-handlers#718]
**Describe the bug**
The Centralite 3200 (4257050-RZHAC) switch is identified as On/Off Light ("device_type": "0x0100")

**To Reproduce**
Display the device.

**Expected behavior**
The device type should be Mains Power Outlet ("device_type": "0x0009")

**Screenshots**
![image](https://user-images.githubusercontent.com/29480988/104308269-26afd680-54af-11eb-822b-4c1a76cb0056.png)
![image](https://user-images.githubusercontent.com/29480988/104308336-40e9b480-54af-11eb-8960-23042de5cd00.png)
![image](https://user-images.githubusercontent.com/29480988/104308445-72fb1680-54af-11eb-86e4-c8a3a60240fd.png)

**Comment by TheJulianJES** [comment]
See https://github.com/zigpy/zha-device-handlers/issues/654#issuecomment-749165413

**Comment by adolfomendes** [comment]
This is a work around, I would like a correction.

**Comment by dmulcahey** [comment]
> This is a work around, I would like a correction.

There is a work around for this. If you would like a permanent change feel free to open a PR. There is an extensive guide in the readme.
