### ISSUE TITLE
[BUG] IKEA lights report incorrect values for current_level during move_to transitions

### ISSUE THREAD

**Issue by PremiumUsername** [zigpy/zha-device-handlers#760]
**Describe the bug**
During the transition after a `move_to_level` command IKEA light responds incorrectly then you try to get `current_level`. It responds with the starting value instead. The related `remaining_time` attribute is reported correctly.  When you update the entity in HA, it also fails to update, which I suppose is related.

in contrast Philip lights do update their value when you update an entity 

**To Reproduce**

1. Use the Cluster command move_to_level with a long transition period
2. During the transition use the HA service to update the entity, or get the current_level attribute from the integration page

**Expected behavior**
The value is update to the real value

**Screenshots**

**Additional context**

**Comment by Adminiuga** [comment]
Yeah, you probably should open the bug with Ikea instead.
