### ISSUE TITLE
[Device Support Request] Heating Order Legrand Cable Outlet

### ISSUE THREAD

**Issue by Oxydiums** [zigpy/zha-device-handlers#789]
Hi i recently add a cable outlet with heating order to my Home assistant.
this is the model :
https://www.legrand.fr/pro/catalogue/43076-sortie-de-cable/sortie-de-cable-connectee-pour-installation-with-netatmo-compatible-fil-pilote-3000w-on-off-et-mesure-conso-blanc

With this device i could have on/off command, Power consumption and Heating order.
After succesfully paired i can only have on/off and power consumption.
So after some research here is some informations that could be great for implementing heating order :
here is the cluster and the attribute for the order :
https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Legrand-Netatmo-corner.md#cluster-0xfc40

and the full list from the manufacturer :
https://developer.legrand.com/documentation/product-cluster-list/

I hope you could implement it with those informations,
Thanks for your work !

**Comment by mycanaletto** [comment]
+1

**Comment by nerthazrim** [comment]
Hi,

+1

Is there any way to get this issue reopened?

**Comment by lboue** [comment]
Here is the new [products cluster list](https://developer.legrand.com/local-interoperability/#Products%20cluster%20list) and [NLP – Connected outlet cluster-list.xlsx](https://static.developer.legrand.com/files/2023/03/NLP-cluster-list.xlsx)
