### ISSUE TITLE
[Device Support Request] Updated Zemismart Zigby blind motors

### ISSUE THREAD

**Issue by davek00997744** [zigpy/zha-device-handlers#791]
The new updated Zemismart zigbee blind motors will pair with Zigby Home Assistant but no entities are created so control is not possible

**Describe the solution you'd like**
An update to the interface to allow control of Open, Close, Midway and Stop

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**

**Additional context**

**Comment by Daniel-Sanche** [comment]
Is [this the one?](https://zigbee.blakadder.com/Moes_AM43-0_45_40-ES-EB.html)

If so, there's an [open issue](https://github.com/zigpy/zha-device-handlers/issues/744). I'm also watching it as I have the same problem

**Comment by davek00997744** [comment]
Mine is the M515EGBZTN from Zemismart/Benexmart, it has the zigbee adaptor built in.

**Comment by blauret** [comment]
[This](https://github.com/zigpy/zha-device-handlers/pull/801) should be a good starting point
