### ISSUE TITLE
[Device Support Request] Philips Hue Dimmer RWL022

### ISSUE THREAD

**Issue by tvnoppen** [zigpy/zha-device-handlers#821]
**Describe the solution you'd like**
This dimmer is apparently a successor on RWL021. Labels on buttons are a bit different, but otherwise seems to be the same as RWL021. See also https://zigbee.blakadder.com/Philips_RWL022.html

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
`{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4107, maximum_buffer_size=82, maximum_incoming_transfer_size=128, server_mask=11264, maximum_outgoing_transfer_size=128, descriptor_capability_field=0)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0830",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x1000",
        "0xfc00"
      ],
      "out_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0008",
        "0x0019",
        "0x1000"
      ]
    }
  },
  "manufacturer": "Signify Netherlands B.V.",
  "model": "RWL022",
  "class": "zhaquirks.philips.rom001.PhilipsROM001"
}`

**Comment by TheJulianJES** [comment]
See https://github.com/zigpy/zha-device-handlers/pull/815
