### ISSUE TITLE
[Device Support Request] Tuya Zigbee 3.0 Home Smart Switch 16A Relay

### ISSUE THREAD

**Issue by samuelmcconnell** [zigpy/zha-device-handlers#873]
**Is your feature request related to a problem? Please describe.**
This device is discovered and added in ZHA, but adds as an open/closed binary sensor and a light, instead of as a switch as I would assume the default behavior should be.

**Describe the solution you'd like**
This should be recognized as a single switch entity.
 
**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**

`{
  "node_descriptor": "NodeDescriptor(byte1=1, byte2=64, mac_capability_flags=142, manufacturer_code=0, maximum_buffer_size=80, maximum_incoming_transfer_size=160, server_mask=10752, maximum_outgoing_transfer_size=160, descriptor_capability_field=0, *allocate_address=True, *complex_descriptor_available=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False, *is_valid=True, *logical_type=<LogicalType.Router: 1>, *user_descriptor_available=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0100",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0006"
      ],
      "out_clusters": [
        "0x0003",
        "0x0004",
        "0x0006"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "_TYZB01_phjeraqq",
  "model": "TS0001",
  "class": "zigpy.device.Device"
}`

**Additional context**
The device can be purchased here: https://www.aliexpress.com/item/1005002095170500.html

**Comment by Adminiuga** [comment]
The binary_sensor  is because the device reports a client one-off cluster, like some open/close sensor do. Just disable that entity. The device reports itself as a on_off light, that's why it is a light, you can overuse it as a switch if you'd like, check zha docs
