### ISSUE TITLE
[BUG] 2nd button not working on Xiaomi Aqara Opple 6 button remote v5

### ISSUE THREAD

**Issue by krue81** [zigpy/zha-device-handlers#907]
**Describe the bug**
I cannot make the second button register anything on a Xiaomi Aqara Opple 6 buttons remote. My remote pairs with Home Assistant OK and I can read the single button, double button and hold button inputs as zha_events, but when I press the button #2, even with the remote blinking the blue led light, Home Assistant doesn't register anything.

**To Reproduce**
1. Pair the remote with Home Assistant ZHA integration using a HUSBZB-1 connected to my Raspberry Pi 4b
2. Subscribe to zha_events on Developer page
3. Press the button #2 (upper right)
4. Nothing appears on the log...

**Expected behavior**
A 2_single, 2_double or 2_longpress command should report when pressing one or two times or holding the button.

**Screenshots**

**Additional context**
Device signature:

  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=128, manufacturer_code=4447, maximum_buffer_size=127, maximum_incoming_transfer_size=100, server_mask=11264, maximum_outgoing_transfer_size=100, descriptor_capability_field=0, *allocate_address=True, *complex_descriptor_available=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False, *is_valid=True, *logical_type=<LogicalType.EndDevice: 2>, *user_descriptor_available=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0105",
      "in_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0012",
        "0xfcc0"
      ],
      "out_clusters": [
        "0x0003",
        "0x0006",
        "0x0008",
        "0x0300"
      ]
    },
    "2": {
      "profile_id": 260,
      "device_type": "0x0103",
      "in_clusters": [
        "0x0003"
      ],
      "out_clusters": [
        "0x0003",
        "0x0006"
      ]
    },
    "3": {
      "profile_id": 260,
      "device_type": "0x0103",
      "in_clusters": [
        "0x0003",
        "0x0012"
      ],
      "out_clusters": [
        "0x0006"
      ]
    },
    "4": {
      "profile_id": 260,
      "device_type": "0x0103",
      "in_clusters": [
        "0x0003",
        "0x0012"
      ],
      "out_clusters": [
        "0x0006"
      ]
    },
    "5": {
      "profile_id": 260,
      "device_type": "0x0103",
      "in_clusters": [
        "0x0003",
        "0x0012"
      ],
      "out_clusters": [
        "0x0006"
      ]
    },
    "6": {
      "profile_id": 260,
      "device_type": "0x0103",
      "in_clusters": [
        "0x0003",
        "0x0012"
      ],
      "out_clusters": [
        "0x0006"
      ]
    }
  },
  "manufacturer": "LUMI",
  "model": "lumi.remote.b686opcn01",
  "class": "zhaquirks.xiaomi.aqara.opple_remote.RemoteB686OPCN01V5"
}

**Comment by walnuss0815** [comment]
I think this can be closed, because it is already fixed in dev branch. See #920 for more details.
