### ISSUE TITLE
[BUG] lumi.sensor_motion.aq2 miss temperature entity

### ISSUE THREAD

**Issue by FrancYescO** [zigpy/zha-device-handlers#908]
**Describe the bug**
lumi.sensor_motion.aq2 sensor does not have the temperature entity i was able to read it with Z2M https://www.zigbee2mqtt.io/devices/RTCGQ11LM.html

**Screenshots**
<img width="313" alt="image" src="https://user-images.githubusercontent.com/4574593/120490136-75a3cd00-c3b8-11eb-882f-49cf680e8376.png">

**Comment by Adminiuga** [comment]
yeah, it was removed on purpose because it really is does not provide useful data. in other words it shows moons temperature.
