### ISSUE TITLE
[Device Support Request]BYUN Smoke sensor

### ISSUE THREAD

**Issue by syzylj** [zigpy/zha-device-handlers#916]
The smoke sensor is correctly identified and used in ZigBee2mqtt, and the display model is m415-6c, ZigBee model: Windows switch.
But it is shown as a switch in ZHA, Byun windows switch, which cannot be used normally.
Request support for this device, thank you!

{
  "node_descriptor": "NodeDescriptor(byte1=2, byte2=64, mac_capability_flags=0, manufacturer_code=0, maximum_buffer_size=80, maximum_incoming_transfer_size=160, server_mask=0, maximum_outgoing_transfer_size=160, descriptor_capability_field=0, *allocate_address=False, *complex_descriptor_available=False, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False, *is_valid=True, *logical_type=<LogicalType.EndDevice: 2>, *user_descriptor_available=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0402",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0006"
      ],
      "out_clusters": [
        "0x0000",
        "0x0500"
      ]
    }
  },
  "manufacturer": "BYUN            ",
  "model": "Windows switch  ",
  "class": "zigpy.device.Device"
}

**Comment by syzylj** [comment]
So far, the problem has not been solved

**Comment by KodieM** [comment]
I would love for this to be fixed. I bought two sensors and can't use them with ZHA

**Comment by ViktuK359** [comment]
Again...So far, the problem has not been solved.
