### ISSUE TITLE
[BUG] zha visualization missing after 2021.7.3

### ISSUE THREAD

**Issue by lishan89uc** [zigpy/zha-device-handlers#968]
**Describe the bug**
zha visualization missing after 2021.7.3

**To Reproduce**
Install 2021.7.3 
go to integration
go to zha and press configure
click on the visualization tab on top

**Expected behavior**
see something when you go there

**Screenshots**
![chrome_rb9qUqrKI3](https://user-images.githubusercontent.com/24217695/126056321-428e08bd-f555-4b92-82c5-39e6e6a04406.png)

**Additional context**
Add any other context about the problem here. Please include full debug logs as well as the device signature.

**Comment by almico** [comment]
It works for me:
![image](https://user-images.githubusercontent.com/15247405/126124263-f7fb6495-fdd8-4331-a0bb-a3f9c4e73731.png)

**Comment by lishan89uc** [comment]
Sorry I didn't know what the issue was and posted in both zigpy and HA core. https://github.com/home-assistant/core/issues/53132
