### ISSUE TITLE
[Device Support Request] IKEA TRADFRI W2045 - Solved!

### ISSUE THREAD

**Issue by WeterPeter** [zigpy/zha-device-handlers#975]
Hi,

I have purchased a IKEA light bulb switch bombo, the bulb is supported (LED194G9) but the switch (type W2045 19972) apparently not. 

https://www.ikea.com/nl/nl/p/tradfri-set-met-afstandsbediening-kleur-en-wit-spectrum-60462432/

I could not find any other requests on the type numbers.
I am fairly new to this stuff, is this the right way to ask for a device addition to ZHA? 

Regards,
Peter

**Comment by MattWestb** [comment]
IKEA Styrbar alias E2001 and E2002 is working out of the box if using it for sending commands to bounded light groups (as it intend to do).

Device automatons is also working but the quirk is not merged then need fixing the command  spamming from the device. 
You can install the quirk from this pull and adding the last changes that is in the comments for getting it working OK (but it still spamming the automation) #867.

The W2045 is not type number its the production year and week so pleas us the real product number that is E2001 and E2002.

**Comment by WeterPeter** [comment]
Thank you! 

Regards,
Peter
