### ISSUE TITLE
[Device Support Request] _TZE200_thbr5z34 (AWOW MS-C-4 TRV)

### ISSUE THREAD

**Issue by lst8** [zigpy/zha-device-handlers#978]
**Is your feature request related to a problem? Please describe.**
Bought a thermostat AWOW MS-C-4 TRV on Amazon. It does pair, but does not expose any controls or status.

**Describe the solution you'd like**
I would like to be able to control the target temperature, and read current temperature and battery level

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**

`{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.EndDevice: 2>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress: 128>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.0: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=True, *is_full_function_device=False, *is_mains_powered=False, *is_receiver_on_when_idle=False, *is_router=False, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0051",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x000a",
        "0xef00"
      ],
      "out_clusters": [
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZE200_thbr5z34",
  "model": "TS0601",
  "class": "zigpy.device.Device"
}`

**Additional context**
I'm using ZHA via a Tasmotized Sonoff ZBBridge

**Comment by MattWestb** [comment]
Link  with picture if the TRV pleas.

I cant finding any thing on google with "AWOW MS-C-4 TRV"

**Comment by lst8** [comment]
Sorry, Sure here is a Link to amazon : https://www.amazon.de/dp/B08M3R3FVW/ref=cm_sw_r_cp_api_glt_i_HRTNR1KWZHZDBZTCRX3B

**Comment by MattWestb** [comment]
Its one version of [Moeshous ZW-HUB-SH4-1](https://www.moeshouse.com/products/zigbee-smart-thermostatic-radiator-valve-controller-trv-thermostat-tuya-temperature-voice-control-works-with-alexa-google-home) that no one have making one quirk for but perhaps one of the Moes can working partly for it.

One matrix with tuya TRV that  is supported in ZHA https://github.com/zigpy/zigpy/discussions/653#discussioncomment-314395

**Comment by daniel100097** [comment]
Is there any progress, on the support of _TZE200_thbr5z34 ? :D

**Comment by MattWestb** [comment]
I have found 4 of this model that is called "Alt Moes" in Z2M but no one have making one working quirk for it so for the moment i cant do anything until its being made.

| Brand | Model | Manufacturer Name | Model ID | ZHA Quirk | Request |
|--------|---------|-----------------------|-----------|-------------|----------|
| Moes | ZW-HUB-SH4-1 | _TZE200_fhn3negr | TS0601 | ⭕ Moes Alt | [ 938 ](https://github.com/zigpy/zha-device-handlers/issues/938) |
| Tuya |  | _TZE200_qc4fpmcn | TS0601 | ⭕ |  |
| Moes | ZW-HUB-SH4-1 | _TZE200_zion52ef | TS0601 | ⭕ Moes Alt | [ 938 ](https://github.com/zigpy/zha-device-handlers/issues/938) |
| Essentials | 120144 | _TZE200_i48qyn9s | TS0601 | ⭕ Moes Alt | [ 677 ](https://github.com/zigpy/zha-device-handlers/issues/677) |
| AWOW | MS-C-4 | _TZE200_thbr5z34| TS0601 | ⭕ Moes Alt | [978](https://github.com/zigpy/zha-device-handlers/issues/978) |

⭕ = Not implanted: look in the last section "Adding support for not supported device"  
  
Hopefully some dev is bying one and making one quirk and then its only adding the model / manufacture in the quirk for getting it working.

**Comment by tklein23** [comment]
Made my AWOW MS-C-4 (aka _TZE200_thbr5z34) work - including a patch for correctly setting the time:
* https://codeberg.org/tklein23/zigbee2mqtt/src/branch/main/data/moes_radiator_alt.js

**Comment by jacekk015** [comment]
@MattWestb 
I'm working on quirk for _TZE200_qc4fpmcn - I own two of them.
valve.py contains attributes numbers like
```
# info from https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/lib/tuya.js
# and https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/converters/fromZigbee.js#L2777
MOES_TARGET_TEMP_ATTR = 0x0202  # target room temp (decidegree)
MOES_TEMPERATURE_ATTR = 0x0203  # current room temp (decidegree)
MOES_MODE_ATTR = 0x0404  # [0] away [1] scheduled [2] manual [3] comfort [4] eco [5] boost [6] complex
MOES_CHILD_LOCK_ATTR = 0x0107  # [0] unlocked [1] child-locked
MOES_VALVE_DETECT_ATTR = 0x0114  # [0] do not report [1] report
MOES_TEMP_CALIBRATION_ATTR = 0x022C  # temperature calibration (decidegree)
MOES_MIN_TEMPERATURE_ATTR = 0x0266  # minimum limit of temperature setting (decidegree)
MOES_MAX_TEMPERATURE_ATTR = 0x0267  # maximum limit of temperature setting (decidegree)
MOES_WINDOW_DETECT_ATTR = 0x0068  # [0,35,5] on/off, temperature, operating time (min)
MOES_BOOST_TIME_ATTR = 0x0269  # BOOST mode operating time in (sec)
MOES_FORCE_VALVE_ATTR = 0x046A  # [0] normal [1] open [2] close
MOES_COMFORT_TEMP_ATTR = 0x026B  # comfort mode temperaure (decidegree)
MOES_ECO_TEMP_ATTR = 0x026C  # eco mode temperature (decidegree)
MOES_VALVE_STATE_ATTR = 0x026D  # opening percentage
MOES_BATTERY_LOW_ATTR = 0x016E  # battery low warning
MOES_WEEK_FORMAT_ATTR = 0x046F  # [0] 5 days [1] 6 days, [2] 7 days
MOES_AWAY_TEMP_ATTR = 0x0272  # away mode temperature (decidegree)
MOES_AUTO_LOCK_ATTR = 0x0174  # [0] auto [1] manual
MOES_AWAY_DAYS_ATTR = 0x0275  # away mode duration (days)
```

Z2M works on the DP points and commands - I've got all of them from my device.
For example in AUTO mode temperature setting is DP:105
```
DEBUG: Received Zigbee message from '0x5c0272fffedb023e', type 'commandSetDataResponse', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,44],"type":"Buffer"},"datatype":2,"dp":105,"fn":0,"status":0,"transid":105}' from endpoint 1 with groupID 0
```

How to translate DP's to attribute numbers??
tuya.js neither fromZigbee.js doesn't show any connection possibility.
zhaquirks/tuya/__init__.py, zhaquirks/tuya/valve.py or zigpy/zcl/clusters/hvac.py also doesn't show how to translate it.

Who did translate those
```
MOES_TARGET_TEMP_ATTR = 0x0202  # target room temp (decidegree)
```
to
```
moesHeatingSetpoint: 16,
```

**Comment by MattWestb** [comment]
I dont knowing exact how its working but the most DP things is made in the `zhaquirks/tuya/init.py` and then the `valve.py` is making 2 clusters (or more if needed) one that converting and sending things to the TRV and the other is converting things from the TRV and making Zigbee cluster commands / attribute for ZHA.

I think your TRV is called "Moes Alt" type in Z2M and is many users in ZHA that having them but no one have making one working quirk for it so its great if you is getting it working but i think some of the devs that have making the other TRV can helping if you can getting in contact with them.

Some of the DP commands is converted to short from so you can find the exact number of them only the short form that is linked to the Zigbee cluster command / attribute.
I think the ground can being Moes TRV and making some changes for making it working OK and dont need writing on complete new quirk only new cluster with the changed function and then adding the device in one new section in the valve.py.

The running state shall being made in `MOES_MODE_ATTR = 0x0404  # [0] away [1] scheduled [2] manual [3] comfort [4] eco [5] boost [6] complex` but its more logic behind it that you need to catching. 

Sorry for i can not helping you with the coding then im no code warier ;-((

**Comment by jacekk015** [comment]
Do you know who did that MOES integrations for other TZ200?? Maybe he could help to clarify this?

**Comment by MattWestb** [comment]
All commits is https://github.com/zigpy/zha-device-handlers/commits/dev/zhaquirks/tuya/valve.py and i have only adding devices and no code changes.

**Comment by jacekk015** [comment]
@xonestonex 
Hi. How did you map all those DP’s from Z2M to proper attributes? I have code for _TZE200_qc4fpmcn that works in Z2M but I would like to port it to ZHA

**Comment by jacekk015** [comment]
@MattWestb 
Good info: I've got from DEBUG a connections between ZHA attributes and Z2M DP's
```
2021-09-23 20:19:44 DEBUG (MainThread) [zigpy.zcl] [0xddeb:1:0xef00] ZCL deserialize: <ZCLHeader frame_control=<FrameControl frame_type=CLUSTER_COMMAND manufacturer_specific=False is_reply=True disable_default_response=False> manufacturer=None tsn=17 command_id=2>
2021-09-23 20:19:44 DEBUG (MainThread) [zigpy.zcl] [0xddeb:1:0xef00] ZCL request 0x0002: [Command(status=0, tsn=101, command_id=613, function=0, data=[4, 0, 0, 0, 42])]
2021-09-23 20:19:44 DEBUG (MainThread) [zhaquirks.tuya] [0xddeb:1:0xef00] Received value [0, 0, 0, 42] for attribute 0x0265 (command 0x0002)
```
I'ts in the "tsn" parameter that valve sends.
For example tsn=101 is the "dp":101 - which is a comfort temperature settings on the valve.

Bad news:
Almost all code need to be rewritten or many if's are needed for that valve series.
For example simplest thing: temperature in present Moes code need to be divided by 10 or 100 - depends which temperature
```
 "occupied_heating_setpoint": (
            MOES_TARGET_TEMP_ATTR,
            lambda value: round(value / 10),
        ),
```
_TZE200_qc4fpmcn and maybe some others need to be divided by 2
```
2021-09-23 20:19:44 DEBUG (MainThread) [zhaquirks.tuya] [0xddeb:1:0xef00] Received value [0, 0, 0, 42] for attribute 0x0265 (command 0x0002)
```
Valve returns 42, and divided by 2 its 21 degrees for comfort temperature.
This is how it looks in Z2M code:
```
case tuyaLocal.dataPoints.moesAltComfortTemp: // 101
          return { comfort_temp_preset: (value / 2).toFixed(1) }
```

Attribute codes and even clusters are different from Type1 or Type2 - so there is a much difference between them.
```
    signature = {
        #  endpoint=1 profile=260 device_type=81 device_version=0 input_clusters=[0, 4, 5, 10, 61184]
        #  output_clusters=[25]>
        MODELS_INFO: [
            ("_TZE200_qc4fpmcn", "TS0601"),
        ],
```

**Comment by MattWestb** [comment]
Great that you have getting the debugging working and you can see what is happening !!

The `tsn` is transaction numbers used by Zigbee network for getting control of messages sent in the network. If one message is not being acked by receiving device and it not coming back to the sender the sending device shall reseeding the same command with the same `tsn`.
Its for unicast and all Zigbee Cluster Liability (ZCL) commands is automatic dont off the stack but the tuya DP is not ZCL so the quirk must do that handling. Also all broadcast (group commands) is not using it then its "spamming the network" and dont need it.

In ZHA need triggering the quirk loading on the devise is configurated on the zigbee clusters and endpoints. Tuya is using the same tuya MCU with 2 different Zigbee modules with diferent cluster configurations so most TRVs have one for each Zigbee module but is using the same "quirk" then the devices have the same tuya MCU therefor its Type1  and Type2 in the quirks for all TRVs.

One thing with the original Moes TRVs quirk is having some extra functions implanted in ZHA that need being added in ZHA for getting all functions to working all the way in HA GUI.

**Comment by jacekk015** [comment]
One step closer.
It looks that only attribute numbers are different, and some doesn't exist.
Work in progress.
![Zrzut ekranu z 2021-09-24 16-17-09](https://user-images.githubusercontent.com/14165726/134689763-dd0b0e54-d4b4-4168-8726-2d8548621ef4.png)

**Comment by MattWestb** [comment]
Great !!

I think then you is taking the battery out for some minute and putting them back the TRVs MCU is sending all attribute / commands (DPs) it having / can using. I was working for my Sitew and some devs have saying its shall working so.

**Comment by jacekk015** [comment]
So basically I can now steer the TRV temperature and all TRV temps are synced with HomeAssistant. Min/Max needs to be statically given in the code since the TRV doesn't have such attributes.
I need to work some time on the modes like: Auto, Manual, etc.
Child lock and Window detection will have a switch. Child lock switch took me few days to achieve, because I need to put it on the second endpoint in the replacements. All that python code takes much time to understand for the first time - many classes of other classes and so on.
Child lock working GIF below
![Obraz](https://user-images.githubusercontent.com/14165726/135773261-7b1538a5-7313-4137-ad91-52a93cf72d68.gif)

**Comment by jacekk015** [comment]
BTW Someone confirmed to work very similar TRV
https://zigbee.blakadder.com/Moes_SH4-ZB.html
probably it's a clone of mine.
I doesn't see any code for that _TZE200_zion52ef ID

**Comment by multigcs** [comment]
``

const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;
const tuya = require("zigbee-herdsman-converters/lib/tuya");


const fz2 = {
    awow_thermostat: {
        cluster: 'manuSpecificTuya',
        type: ['commandGetData', 'commandSetDataResponse'],
        convert: (model, msg, publish, options, meta) => {
            const dp = msg.data.dp;
            const value = tuya.getDataValue(msg.data.datatype, msg.data.data);

            switch (dp) {
            case 105:
                return {current_heating_setpoint_auto: (value / 2).toFixed(1)};
            case 16:
                return {current_heating_setpoint: (value / 2).toFixed(1)};
            case 2:
                const modes = {0: 'auto', 1: 'manual', 2: 'away'};
                var away_mode = 'OFF';
                if (value == 2) {
                    away_mode = 'ON';
                }
                return {mode: modes[value], away_mode: away_mode};

            case 24:
                return {local_temperature: (value / 10).toFixed(1)};

            case 34:
                return {battery_voltage: (value / 0.05).toFixed(1), battery: ((value / 0.05) - 2100) / 10};

            case 118:
                return {boost_time: value};

            case 30:
                return {child_lock: value ? 'LOCK' : 'UNLOCK'};

            case 106:
                return {timer: value};


            case 116:
                return {windowDetectionTemp: value / 2};
            case 117:
                return {windowDetectionTime: value};


            case 109: // mon
            case 114: // week
            case 115: // sun
                const days = {0: '???', 1: 'Monday', 2: 'Tuesday', 3: 'Wednesday', 4: 'Thursday', 5: 'Friday', 6: 'Saturday', 7: 'Sunday'};

                //  SUN 20  6:00 21  9:00 22  10:00 23  23:00 17  24:00

                // [7,  40, 24,  42, 36,  44, 40,   46, 92,   34, 96,    42,96,34,96,42,96,34]
                   1,   34, 24,  42,36,34,68,42,92,34,96,42,96,34,96,    42,96,34,96,42,96,34

                if (value[0] == 7) {

                    return {
                        program_sunday: {
                            sunday: [
                                '0h:0m ' + value[1] / 2 + '°C',
                                '' + parseInt(value[2] / 4) + 'h:' + (value[2] - parseInt(value[2])) * 15 + 'm ' + value[3] / 2 + '°C',
                                '' + parseInt(value[4] / 4) + 'h:' + (value[4] - parseInt(value[4])) * 15 + 'm ' + value[5] / 2 + '°C',
                                '' + parseInt(value[6] / 4) + 'h:' + (value[6] - parseInt(value[6])) * 15 + 'm ' + value[7] / 2 + '°C',
                                '' + parseInt(value[8] / 4) + 'h:' + (value[8] - parseInt(value[8])) * 15 + 'm ' + value[9] / 2 + '°C',
                                '' + parseInt(value[10] / 4) + 'h:' + (value[10] - parseInt(value[10])) * 15 + 'm ' + value[11] / 2 + '°C',
                            ]
                        },
                    }
                }

            default:
                meta.logger.warn(`zigbee-herdsman-converters:AwowThermostat: NOT RECOGNIZED DP #${
                    dp} with data ${JSON.stringify(msg.data)}`); // This will cause zigbee2mqtt to print similar data to what is dumped in tuya.dump.txt
            }
        },
    },
}

const tz2 = {
    awow_thermostat_lock: {
        key: ['lock'],
        convertSet: async (entity, key, value, meta) => {
            var lock = 0;
            if (value == 'ON') {
                lock = 1;
            }
            await tuya.sendDataPointRaw(entity, 30, [lock]);
        },
    },
    awow_thermostat_current_heating_setpoint_auto: {
        key: ['current_heating_setpoint_auto'],
        convertSet: async (entity, key, value, meta) => {
            const temp = parseInt(value * 2);
            await tuya.sendDataPointRaw(entity, 105, [0, 0 ,0, temp]);
        },
    },
    awow_thermostat_current_heating_setpoint: {
        key: ['current_heating_setpoint'],
        // set manual mode
        convertSet: async (entity, key, value, meta) => {
            const temp = parseInt(value * 2);
            await tuya.sendDataPointRaw(entity, 16, [0, 0 ,0, temp]);
            await tuya.sendDataPointRaw(entity, 2, [1]);
        },
    },
    awow_thermostat_current_mode: {
        key: ['mode'],
        convertSet: async (entity, key, value, meta) => {

            switch (value) {
            case 'auto':
                await tuya.sendDataPointRaw(entity, 2, [0]);
                break;
            case 'manual':
                await tuya.sendDataPointRaw(entity, 2, [1]);
                break;
            case 'away':
                await tuya.sendDataPointRaw(entity, 2, [2]);
                break;
            }

        },
    },
}


const definition = {
    fingerprint: [
        {
            modelID: 'TS0601',
            manufacturerName: '_TZE200_thbr5z34'
        },
    ],
    model: 'MS-SH4-Z',
    vendor: 'AWOW',
    description: 'Thermostatic radiator valve',
    supports: 'thermostat, temperature',
    onEvent: tuya.setTime,
    fromZigbee: [
        fz.ignore_basic_report,
        fz.tuya_data_point_dump,
        fz2.awow_thermostat,
        fz.ignore_tuya_set_time,
    ],
    toZigbee: [
        tz.tuya_data_point_test,
        tz2.awow_thermostat_current_heating_setpoint_auto,
        tz2.awow_thermostat_current_heating_setpoint,
        tz2.awow_thermostat_current_mode,
        tz2.awow_thermostat_lock,
    ],
    configure: async (device, coordinatorEndpoint, logger) => {
        const endpoint = device.getEndpoint(1);
        await reporting.bind(endpoint, coordinatorEndpoint, ['genBasic']);
    },
    exposes: [
        exposes.climate()
            .withSetpoint('current_heating_setpoint', 5, 30, 0.5, ea.STATE_SET)
            .withLocalTemperature(ea.STATE)
            .withAwayMode(),
        e.battery_voltage(), e.battery(),
        e.child_lock(),
    ],
};

module.exports = definition;

``

**Comment by jacekk015** [comment]
That's code for Zigbee2Mqtt, not ZHA

**Comment by jacekk015** [comment]
@lst8 @daniel100097 @multigcs 
If you are interested here's the code to test
https://github.com/zigpy/zha-device-handlers/issues/1061#issuecomment-961433590

@MattWestb I'm almost sure that _TZE200_thbr5z34 is another 100% clone of mine _TZE200_qc4fpmcn
If that Z2M code above works DPs are the same.

**Comment by MattWestb** [comment]
I have adding it in the test file for ZHA presets that i was posing so only adding the device id it the quirk and it shall working if some user like testing it.

**Comment by jacekk015** [comment]
@lst8 Please close that issue if all is OK. Thanks!
