### ISSUE TITLE
[Device Support Request] Tuya Smart Zigbee Curtain Switch Module (_TZ3000_mowcrwsa)

### ISSUE THREAD

**Issue by rmjjanssen1** [zigpy/zha-device-handlers#998]
**Is your feature request related to a problem? Please describe.**
Device can be paired in ZHA but not working properly in HA.
Manufacturer ID _TZ3000_mowcrwsa is not added as MODELS_INFO in ts130f.py

**Describe the solution you'd like**
Add manufacturer ID of the below device signature to class TuyaZemismartTS130F(CustomDevice): of zha-device-handlers/zhaquirks/tuya/ts130f.py

**Device signature - this can be acquired by removing the device from ZHA and pairing it again from the add devices screen. Be sure to add the entire content of the log panel after pairing the device to a code block below this line.**
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4098, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.0: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0202",
      "in_clusters": [
        "0x0000",
        "0x0004",
        "0x0005",
        "0x0006",
        "0x0102"
      ],
      "out_clusters": [
        "0x000a",
        "0x0019"
      ]
    }
  },
  "manufacturer": "_TZ3000_mowcrwsa",
  "model": "TS130F",
  "class": "zigpy.device.Device"
}

**Additional context**

**Comment by MattWestb** [comment]
I have posting one PR that is only using the model TS130F and not model ID for those device https://github.com/zigpy/zha-device-handlers/pull/980 but its not merged of the devs. Then its merged its no need adding devices with ID then all TS130F being added in ZHA.
I putting one comment in the PR with your ID if its not going thru i can making on new PR with the ID added.
